### ISSUE TITLE
Is there an option for reducing the constructor method visibility?

### ISSUE THREAD

**Issue by ChrisTrenkamp** [immutables/immutables#1010]
I have some simple data classes that need some validation in their constructor methods.  I want to reduce the visibility of the constructor method to the package level to stop users from accidentally bypassing the validation:

```java
@Value.Style(defaults = @Value.Immutable(builder = false))
@Value.Immutable
public interface Path {
    @Value.Parameter
    String value();

    static ImmutablePath of(String value) {
        return ImmutablePath.of(sanitize(value));
    }

    static String sanitize(String value) {
        return value.replace('\\', '/');
    }
}

...

Path sanitizedPath = Path.of("foo\\bar"); // Will be converted to foo/bar
Path uhOh = ImmutablePath.of("foo\\bar"); // This shouldn't be exposed
```

I cannot reduce the visibility of the Immutable class itself because I'm using Protostuff to serialize these data structures, and it requires the base class to be non-abstract.

**Comment by elucash** [comment]
I usually just hide generated classes, `@Style(visibility = PACKAGE, overshadowImplementation=true` stuff like that, thx
