### ISSUE TITLE
Annotation processor memory leak inside Eclipse

### ISSUE THREAD

**Issue by trask** [immutables/immutables#105]
Hi,

Eclipse ran OOM on me a couple times recently.  Heap dump points to one instance of `org.immutables.value.internal.$processor$.meta.$Styles` retaining many instances of `org.immutables.value.internal.$processor$.meta.$StyleMirror`.

![image](https://cloud.githubusercontent.com/assets/218610/7218495/a84e825c-e626-11e4-82de-346f97553d08.png)

I uploaded the full heap dump to https://s3-us-west-2.amazonaws.com/trask/eclipse.hprof.zip in case that helps.

I was doing several large operations outside of Eclipse, and then Eclipse workspace would auto refresh/re-build when I went back into Eclipse each time.  After several of these, it got super slow (near OOM death).  I think I can repro if needed.

Thanks,
Trask

**Comment by elucash** [comment]
Hi Trask, thank you for this report, great finding! I've revised interning of Style objects, there's a big chance that this might be solved. Could you evaluate current 2.0.8-SNAPSHOT?

**Comment by trask** [comment]
Did my best to repro using 2.0.8-SNAPSHOT, looks good to me.

**Comment by elucash** [comment]
Thanks! Released in 2.0.9
