### ISSUE TITLE
Mongo repository doesn't save/retrieve objects with embedded maps.

### ISSUE THREAD

**Issue by jkwatson** [immutables/immutables#108]
I'm not 100% sure the description is precisely what the problem is, but this code demonstrates the issue.
The call to findById() blows up when trying to construct the `EmbeddedMap` instance.

What gets saved in the database:
```json
{
    "_id" : ObjectId("55454f250364499fd0ecf36c"),
    "items" : [ 
        {}
    ]
}
```

Code:
```java
public class Tester {
    public static void main(String[] args) throws ExecutionException, InterruptedException {
        List<Double> stuff = Arrays.asList(5.5d, 6.6d);
        ImmutableEmbeddedMap items = ImmutableEmbeddedMap.builder().putValues("key", stuff).build();

        ImmutableJunk testItem = ImmutableJunk.builder()
                .items(singletonList(items))
                .build();
        System.out.println("testItem = " + testItem);

        JunkRepository junkRepository = new JunkRepository(RepositorySetup.forUri("mongodb://localhost/test"));
        junkRepository.insert(testItem);

        Junk retrievedItem = junkRepository.findById(testItem.id()).fetchFirst().get().get();

        System.out.println("saved is equal? " + retrievedItem.equals(testItem));
    }

    @Value.Immutable
    @Mongo.Repository
    public abstract static class Junk {
        @Mongo.Id
        @Value.Default
        public Id id() {
            return Id.generate();
        }

        public abstract List<EmbeddedMap> items();

    }

    @Value.Immutable
    public abstract static class EmbeddedMap {
        abstract Map<String, List<Double>> values();
    }

}
```

**Comment by elucash** [comment]
Hi John, thank you for this report. I've tried to launch the example your provided and it indeed blew up.
The catch is that only Gson-marshalable objects could work properly. In this case Junk itself have Gson type adapter attached (by virtue of having `@Mongo.Repository` annotation). But `EmbeddedMap` don't have type adapter attached. Basically, you can put `@Gson.TypeAdapters` on a top-level class or package which encloses classes that should be mapped.

After adding `@Gson.TypeAdapters` annotation and running it I was able to see
```
testItem = Junk{id=554589de5ca4631ef10ce1b3, items=[EmbeddedMap{values={key=[5.5, 6.6]}}]}
saved is equal? true
```

The details of Gson mapping could be found at [json/gson documentation](http://immutables.github.io/json.html#gson).

I clearly see that documentation of mongodb repositories should be improved.

```java
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import org.immutables.gson.Gson;
import org.immutables.mongo.Mongo;
import org.immutables.mongo.repository.RepositorySetup;
import org.immutables.mongo.types.Id;
import org.immutables.value.Value;

@Gson.TypeAdapters // <--  Annotation added
public class Tester {
  public static void main(String[] args) throws ExecutionException, InterruptedException {
    List<Double> stuff = Arrays.asList(5.5d, 6.6d);
    ImmutableEmbeddedMap items = ImmutableEmbeddedMap.builder().putValues("key", stuff).build();

    ImmutableJunk testItem = ImmutableJunk.builder()
        .addItems(items)
        .build();
    System.out.println("testItem = " + testItem);

    JunkRepository junkRepository = new JunkRepository(RepositorySetup.forUri("mongodb://localhost/test"));
    junkRepository.insert(testItem).getUnchecked();

    Junk retrievedItem = junkRepository.findById(testItem.id()).fetchFirst().get().get();

    System.out.println("saved is equal? " + retrievedItem.equals(testItem));
  }

  @Value.Immutable
  @Mongo.Repository
  public abstract static class Junk {
    @Mongo.Id
    @Value.Default
    public Id id() {
      return Id.generate();
    }

    public abstract List<EmbeddedMap> items();

  }

  @Value.Immutable
  public abstract static class EmbeddedMap {
    abstract Map<String, List<Double>> values();
  }

}
```

Just a minor trick, if you want to make EmbeddedMap a wrapper around map which is invisible in BSON,
you can define it as having no builder and single argument constructor, so it will become pure wrapper.

```java
   // EmbeddedMap will become invisible wrapper around values in JSON
  @Value.Immutable(builder = false)
  public abstract static class EmbeddedMap {
    @Value.Parameter
    abstract Map<String, List<Double>> values();
  }
```

Please, feel free to report any other problems or ask questions

**Comment by jkwatson** [comment]
Ah!  I was thinking there was probably a magic annotation to add that would fix this, but I didn't think to look in the Gson section. Yes, this is probably just a doc bug, then, with the mongodb repository support.  

As to your "minor trick":  yes, that works, but it's really non-obvious to me why it should work that way. Why does removing a builder and having a single-arg constructor make it behave as a pure wrapper to gson?

**Comment by jkwatson** [comment]
Thanks for the info.  Much appreciated. You can close this if you want, or keep it open to track the doc issues; your call.

**Comment by elucash** [comment]
Pushed updated documentation which mention things from this issue + added compile warning when no explicit `Gson.TypeAdapters` annotation specified.
