### ISSUE TITLE
SourceExtractor fails to extract imports for source files, causing imports to be missing

### ISSUE THREAD

**Issue by bgertzfield** [immutables/immutables#109]
Using both immutables.org 1.x and 2.x, `SourceExtractor` fails to extract imports for files, causing imports to be silently dropped for any value types which import another value type from another package.

To reproduce:

1) Download and unzip https://www.dropbox.com/s/2lip4mhri7tis8t/immutables-missing-imports.zip?dl=0
2) `cd immutables-missing-imports`
3) Run `./build.sh`

I added a bunch of debugging to figure this out and pushed it here:

https://github.com/immutables/immutables/commit/6f33f501385218e800af6a0249a670c20237a693

When I run the test case with the above debugging patch, it confirms the issue is when SourceExtractor tries to open the source file:

https://gist.github.com/bgertzfield/de7a855cb9a37245e79f

  warning: Could not collect imports for bar.Bar: java.io.FileNotFoundException: bar/Bar.java

This should probably be an error, but instead `SourceExtractor` silently returns an empty set of imports.

**Comment by elucash** [comment]
For some general case (read — our fixture test suite) javac compilation worked, at least in maven. For this case I've used the same strategy as for Eclipse - by using javac specific classes to obtain source code. Can you, please, check the latest 1.0.11-SNAPSHOT ?

I suspect that you might have other problems with Immutables running from IDEA or Eclipse, which we don't know yet. You should know that at least couple of our users reported (and also I've checked it myself) that 2.0 works fine in Eclipse and IDEA, so it's not fair that you cannot use favorite ides to generate/compile value objects during development. Any ideas how we can peek into those problems?
I will, probably, try to setup Buck codebase in ide, are there any caveats?

**Comment by bgertzfield** [comment]
Thanks for the quick turnaround! I tried building Buck in the IntelliJ IDE with :.org `2.0.11-SNAPSHOT` from commit df4ec69.

I used this patch to the latest Buck Github master and opened the root directory in IntelliJ (you will probably have to manually point it at your Java SDK):

https://github.com/bgertzfield/buck/commit/5c3f79af38f05c817eaaf35eea1b6ba843c1b8c8

This revision now gives me a nice error message as a build warning when running the annotation processor:

  Warning:java: Could not read source files to collect imports for com.facebook.buck.android.AbstractAndroidPackageableCollection: java.io.FileNotFoundException: Resource does not exist : SOURCE_PATH//com/facebook/buck/android/AbstractAndroidPackageableCollection.java

This exception is thrown from IntelliJ's implementation of `StandardJavaFileManager`, `org.jetbrains.jps.javac.JavacFileManager`:

http://grepcode.com/file/repository.grepcode.com/java/ext/com.jetbrains/intellij-idea/13.0.0/org/jetbrains/jps/javac/JavacFileManager.java#112

I think that's coming from this call in `SourceExtraction`:

https://github.com/immutables/immutables/blob/df4ec6908b06d91b09d2559ecbca596a42c43e9e/generator/src/org/immutables/generator/SourceExtraction.java#L92

**Comment by elucash** [comment]
This helped a lot, thanks! Made this work in IDEA. Essentially, fix was to make source extraction work in case when classpath during annotation processing contains both Eclipse and Javac classes. Now I'll try the Buck projects to import in IDEA and Eclipse.

**Comment by elucash** [comment]
compiling Buck codebase in IDEA now seems to work (enable annotation processing, obtain from classpath). Compiling Buck in eclipse revealed couple of additional problems. Stay tuned

**Comment by bgertzfield** [comment]
Very nice. I confirmed commit 6edec01 fixes the Buck build in IntelliJ IDEA! Well done.

**Comment by elucash** [comment]
The changes released in v 1.0.11, you might try it in the Eclipse and IDEA. I was able to compile Facebook Buck codebase in both ides.
