### ISSUE TITLE
Update example in "Hide implementation class" section of the documentation

### ISSUE THREAD

**Issue by ralscha** [immutables/immutables#1117]
The section 
https://immutables.github.io/immutable.html#hide-implementation     
shows this example
```
// Make generated class package private
@Value.Style(visibility = ImplementationVisibility.PACKAGE)
@Value.Immutable
public abstract class Point {
  @Value.Parameter public abstract double x();
  @Value.Parameter public abstract double y();

  public static Point of(double x, double y) {
    return ImmutablePoint.of(x, y);
  }

  public static Builder builder() {
    return ImmutablePoint.builder();
  }
  // Signatures of abstract methods should match to be
  // overridden by implementation builder
  public interface Builder {
    Builder x(double x);
    Builder y(double y);
    Point build();
  }
} 
```

but the [Builder section](https://immutables.github.io/immutable.html#builder) shows a more concise example with `overshadowImplementation` and extending the Builder from the implementation class.

My suggestion is that the example in the *Hide implementation class* section should be replaced with this example which is more concise and I think achieves the exact same goal. 
```
@Value.Style(visibility = ImplementationVisibility.PACKAGE, 
	overshadowImplementation = true)
@Value.Immutable
public abstract class Point {
  @Value.Parameter public abstract double x();
  @Value.Parameter public abstract double y();

  public static Point of(double x, double y) {
    return ImmutablePoint.of(x, y);
  }

  public static Builder builder() {
    return new Builder();
  }

  static final class Builder extends ImmutablePoint.Builder { }
}
```

**Comment by asereda-gs** [comment]
Do you mind creating a PR for [docs repository](https://github.com/immutables/immutables.github.io/pulls) ?

**Comment by elucash** [comment]
Actually, I think that the example is still valid. Extending builder doesn't provide true hiding (it depends if sourcecode or bytecode is taken into account). "True" implementation hiding means that full API is fully manually written and that, If you carefully, you can even [rename]refactor attributes and builder initializers in proper sequence across codebase. The example with extending [yet-to-be-generated] builder is just not the same, albeit similar mechanism

**Comment by asereda-gs** [comment]
Yes that's a good point. Maybe still enhance the documentation explaining the difference between the two ? 

First example doesn't leak API (via super-type), second is easier to write but user still inherits `ImmutablePoint.Builder`.

**Comment by elucash** [comment]
I definitely for expanding documentation and explaining nuances, just don't have time to focus on it at the moment, but any help/PRs are welcome

**Comment by ralscha** [comment]
I see. It's not the exact same thing. Thanks for the explanation.
In my code I wanted the `build()` method to return the interface instead of the generated immutable class. And to solve just this I can choose both approaches. But if I want to completely hide the implementation then the example in the documentation is the only way and correct. 
Thanks.
