### ISSUE TITLE
Possible to ignore properties in a supertype shared between multiple immutable impls?

### ISSUE THREAD

**Issue by henryptung** [immutables/immutables#1118]
Looking to specify a method in a supertype that:

1. Looks like an attribute method (has return type, no parameters)
2. Must be implemented by value subtypes (should fail to compile if not implemented)
3. Must not become a builder-settable or JSON-deserializable property

Not sure how to do this.

**Comment by smorel-plenty** [comment]
+1 to this issue. I want to have a super type (either `interface` or `abstract class`) that leaves some methods as abstract / unimplemented and force the subclasses to implement them (with compiler support for missing implementations). 

The closest I've found is 

```java

interface Supertype {
  String aValidStringAttribute();

  // Abstract "smart" domain method (I don't want a property)
  default myAbstractMethod() { throw new NotImplementedException(); }
}

@Immutable
interface MyThing implements Supertype {

  @Override
  default myAbstractMethod() {
    // real impl goes here
  }
}
```

Basically, I'd like an annotation to put on `Supertype.myAbstractMethod()` that treats it like ["smart data"](https://immutables.github.io/immutable.html#smart-data) but leaves it abstract so the compiler can do its thing.

**Comment by elucash** [comment]
`@Value.NonAttribute`, will be in next release, provably 2.9.0 or smth
