### ISSUE TITLE
Custom immutable annotation

### ISSUE THREAD

**Issue by darichey** [immutables/immutables#1122]
I am trying to create a custom immutable annotation as described in the [docs](https://immutables.github.io/style.html#custom-immutable-annotation), building with Gradle.

I have the following java files:
**CustomImmutable.java**
```java
package test;
import org.immutables.value.Value;
@Value.Style(defaults = @Value.Immutable) // I have other customizations in practice
public @interface CustomImmutable {}
```
**Foo.java**
```java
package test;
@CustomImmutable
public interface Foo {
    String bar();
    int baz();
}
```
a resources file at `/META-INF/annotations/org.immutables.value.immutable`
```
test.CustomImmutable
```
as well as a gradle build script:
```gradle
plugins { id 'java' }
repositories { jcenter() }
dependencies {
    compileOnly 'org.immutables:value:2.8.1'
    annotationProcessor 'org.immutables:value:2.8.1'
}
```
When invoking `./gradlew classes`, no sources are generated. Note that if I directly annotate `Foo` with `@Value.Immutable`, sources *are* generated. What am I doing wrong?

**Comment by elucash** [comment]
Build systems nowadays allow themself to treat compilation in a pretty custom way in the name of optimization and so on, by doing "smart" sandboxing and other stuff many resource discovery mechanisms fall flat, especially with annotation processing involved.
What to try? Perhaps if you put custom annotation in a separate module / jar (make sure it compiles and packages the META-INF resource in that jar). Then try to reference that jar in the module which will use custom annotation on either `compileOnly`, or `annotationProcessor `, or on both scopes. This might work.

**Comment by darichey** [comment]
I tried your suggestion, building a jar with CustomImmutable.java and the META-INF resource, and modified the build.gradle to include this dependency (placed in `./libs`):
```gradle
plugins { id 'java' }
repositories {
    jcenter()
    flatDir { dir 'libs' }
}
dependencies {
    compileOnly 'org.immutables:value:2.8.1'
    annotationProcessor 'org.immutables:value:2.8.1'
    compileOnly name: 'test'
}
```
However, still no sources are generated. Could you check that the [attached jar](https://github.com/immutables/immutables/files/3853657/test.zip) looks correct?

**Comment by elucash** [comment]
tried sample Gradle project, it worked when you put jar on both `compileOnly` _and_ `annotationProcessor`. Probably, technically, it could also work if split in 2 jars `annotationProcessor` would contain `META-INF/**` jar and `compileOnly` with only `test/CustomImmutable.class`, but I haven't tried and more cumbersome than just put singlejar twice on two scopes. It could works easier with Maven and javac command-line compilation, but  ¯\_(ツ)_/¯

**Comment by elucash** [comment]
```gradle
plugins {
    id 'java'
}

repositories {
    jcenter()
    flatDir { dir 'lib' }
}

dependencies {
    compileOnly 'org.immutables:value-annotations:2.8.1'
    annotationProcessor 'org.immutables:value:2.8.1'
    compileOnly name: 'test'
    annotationProcessor name: 'test'
}

```

**Comment by darichey** [comment]
Ah, didn't think of that! Thanks!
