### ISSUE TITLE
Question: Should the Criteria generated Repository::fetch return ImmutableFoo or AbstractFoo?

### ISSUE THREAD

**Issue by Steven-Rowell** [immutables/immutables#1124]
I have a question regarding the expected return type of a Criteria generated Repository. My generated Repositories are returning the Interface instead of the additionally generated Immutable.

1. Is this the expected default behaviour
2. If yes, is there something I can do to get my Repositories to return the Immutable instead of the interfaces? 

**Example**

I have a base class

```java
public interface FooCore {
    String getBar();
}
```

and an immutable implementer

```java
@FooStyle
@Value.Immutable
@Criteria // generate criteria
@Criteria.Repository(name = "FooEntity")
@JsonSerialize(as = FooEntity.class)
@JsonDeserialize(as = FooEntity.class)
public interface FooEntityIF extends FooCore {
    @Criteria.Id
    @JsonProperty("_id")
    @Value.Default
    default ObjectId getId() {
        return new ObjectId();
    }
}
```  

Which generates a `FooRepository` as expected that accepts a `FooEntity` for inserts, upserts, etc. However, all get methods return the `FooEntityIF` interface. I can wrap this in a builder and get back my immutable, but it seems odd. I'm using a custom style, which might be the culprit. I've attached it below.

```
MarketEntityRepository::insert(FooEntity)
MarketEntityRepository::find(FooCriteria) -> FooEntityIF instance
```

```java
@Value.Style(
        get = {"is*", "get*"},
        init = "set*",
        typeAbstract = {"Abstract*", "*IF"},
        typeImmutable = "*",
        )
public @interface FooStyle {
}
```

**Comment by asereda-gs** [comment]
Currently Criteria API allows only single (and same) type (`T`) for both query (`Criterion<T>`) and result (`Publisher<T>`). 

Do you always expect backend to return immutable version of `T` (maybe it uses [flyweight](https://refactoring.guru/design-patterns/flyweight) pattern) ? 

Also not all Criteria models have immutable implementation (see [JavaBeans](https://immutables.github.io/criteria.html#javabeans)).

That being said, you can always decorate [Backend.Session](https://github.com/immutables/immutables/blob/master/criteria/common/src/org/immutables/criteria/backend/Backend.java#L57) or write [custom repository](https://immutables.github.io/criteria.html#custom-repositories) then apply `map()` function.

**Comment by Steven-Rowell** [comment]
For my purposes I think a custom repository would work just fine.

Closing this out now that I have some direction, thank you for your help!
