### ISSUE TITLE
Java built-in deserialization improvements for evolving value objects

### ISSUE THREAD

**Issue by jbergfi** [immutables/immutables#113]
When using java built-in serialization on evolving value objects you may end up with invalid value objects which may contain required non-null attributes as null or optional (guava or Java8) attributes as null instead of Optional.absent.

For example if you add a new required attribute you would expect to get an exception from the deserialization if you deserialize an object which didn't have that attribute. If you add a new optional (guava or Java8) you expect to get an Optional.absent for the attribute when deserializing an old version of the value object.

Suggested fix is to generate a readResolve method in the value implementation where the a new object is created using the builder or contstructor using the attribute values parsed by the java serialization.

**Comment by elucash** [comment]
Thank for the feature request!

In nutshell, the idea is to use readResolve and writeReplace with serialization proxies (Effective Java 2nd, item 78) so that on the wire, field names will be serialized along with values. The important aspect of this is that objects are being deserialized using it's constructors and builders, and not the internal representation, thus all singletons, interning and other invariants will be preserved and data migration made possible (using either optional or nullable attributes).

Currently, there's no definite API in mind. But I expect we could converge on something similar to following examples:

```java
@Value.Serialize

or

@Serialize.Structural(serialVersion=1L) // or just (1L)
```

**Comment by elucash** [comment]
After playing with possible annotation API and trying to match the _"theme"_ of existing API, there are couple of ideas how to name module and annotations.

* `org.immutables:serial` - module and corresponding top level package for the API
* `@Serial.Structural` - annotation to generate structural serialization. No attributes. Could be applied to types, enclosing types, enclosing packages and as meta-annotation.
* `@Serial.Version(1L)` - required value attribute to specify serial version. This annotation will be slightly magical in that it will make covered value types serializable (by structure if `@Serial.Structural` is also specified). Could be applied to types, enclosing types, enclosing packages and as meta-annotation. If no serial version annotation is specified — default will be used — 1L (seems to be a reasonable default) if serialization is implied by other means.

**Comment by augustotravillio** [comment]
I would be strictly against adding this api to the core `value` module. But I find proposed new module `serial` and that `@Structural/@Version` annotations a good fit overall.

**Comment by elucash** [comment]
While experimental in nature, this feature is implemented (courtesy of @augustotravillio ) in version  2.0.12 available on the central.

+ http://immutables.github.io/immutable.html#serialization
+ module `org.immutables:serial`
   - org.immutables.serial.Serial.Version
   - org.immutables.serial.Serial.Structural
