### ISSUE TITLE
[Bug] No buildPartial support found for the generated modifiable class

### ISSUE THREAD

**Issue by ningt** [immutables/immutables#1131]
As mentioned above, I see there is `buildPartial` support for `Modifiable` class in the documentation, however I couldn't find it in the generated code and in this repo. I'm on version `2.7.4`. Is the feature removed from some version?

**Comment by asereda-gs** [comment]
Can you please provide example in documentation where `buildPartial` is supported ? 

On the contrary, [modifiable classes](https://immutables.github.io/immutable.html#modifiable-classes) are trying to avoid it : 
> We believe that modifiable companion class is a better alternative to:
> 
> 1. Polluting builders with attribute query and isSet/isInitialized methods.
> 2. Introducing dangerous buildPartial() methods that produce incomplete immutable instances.

**Comment by ningt** [comment]
@asereda-gs Sorry misread the documentation, thanks for the reply
