### ISSUE TITLE
Default value for type

### ISSUE THREAD

**Issue by darichey** [immutables/immutables#1154]
I have a type, `Foo`, that is very much like `java.util.Optional` which I use extensively throughout my immutable objects. Currently, I must explicitly state the default value for every occurrence which is very verbose:
```java
@Value.Immutable
interface Val {
  @Value.Default default Foo<Bar> bar() {
    return Foo.empty();
  }
  @Value.Default default Foo<Baz> baz() {
    return Foo.empty();
  }
  @Value.Default default Foo<Qux> qux() {
    return Foo.empty();
  }
}
``` 
Is it possible to define a "global" default value for all uses of this type?

**Comment by elucash** [comment]
The only alternative that comes to my mind is using custom encodings https://immutables.github.io/encoding.html

**Comment by elucash** [comment]
here's an example of using encoding for Vavr's optional https://github.com/immutables/immutables-vavr/blob/develop/vavr-encodings/src/main/java/org/immutables/vavr/encodings/VavrOptionEncoding.java
