### ISSUE TITLE
Retain @Immutable annotation at RUNTIME

### ISSUE THREAD

**Issue by AMTerp** [immutables/immutables#1168]
Hey,
I'm currently doing some work where I'd like to reflectively identify if a class is Immutables-generated. Unfortunately, neither @Immutable nor @Generated have RUNTIME retention. Any thoughts on potentially making @Immutable use RetentionPolicy.RUNTIME? 
Thanks,
Alex

**Comment by io7m** [comment]
https://github.com/immutables/immutables/issues/776

**Comment by AMTerp** [comment]
Thanks for the link, @io7m.
