### ISSUE TITLE
Version 2.8.6 Does Not Generate Classes

### ISSUE THREAD

**Issue by canayozel** [immutables/immutables#1171]
Version 2.8.6 Does Not Generate Classes Annotated with Custom Style Annotation

I am investigating and will post the reason here. Is this a known issue or are there any breaking changes ?

**Comment by canayozel** [comment]
Just noticed, that the 2.8.6 jar does not contain META-INF/services package.

**Comment by elucash** [comment]
something strange is happening, snapshot and release build contain jar with services included, but the one built for deploy with signatures etc, happens to not contain `META-INF/services`

**Comment by asereda-gs** [comment]
Yes it affects us as well. Seems something went wrong with [2.8.6 release](https://github.com/immutables/immutables/releases/tag/2.8.6)

**Comment by elucash** [comment]
released 2.8.4 instead, should contain services file (2.8.6 perished, don't ask about numbering though :-) )

**Comment by napstr** [comment]
Maybe it would make sense to jump to 2.8.7? I have tooling that notifies me of new versions, and it did for 2.8.6, however when I came here looking for a changelog or release entry there is none.

**Comment by asereda-gs** [comment]
Probably our next release will be 2.8.7. Sorry for the confusion with version numbers.

**Comment by talios** [comment]
So to clarify, the NEW release is the older version number (2.8.4)? 

Is there an ETA for when 2.8.7 will be released?

**Comment by asereda-gs** [comment]
Unfortunately yes. We'll release 2.8.7 in a couple of weeks.

**Comment by Stephan202** [comment]
Many people use tooling that notifies them of new versions. A sizeable subset of those will upgrade without finding this issue (or only find it one they hit the issue themselves). From that perspective releasing a new 2.8.7 (even if it just contains the last known-good release) seems preferable.

**Comment by elucash** [comment]
@asereda-gs let me just release 2.8.7, just confirming that whatever was wrong was fixed in 2.8.4

**Comment by asereda-gs** [comment]
Yes agree. Keeping bad version as latest is not very user friendly

**Comment by canayozel** [comment]
Closing the issue since it is fixed with 2.8.4.
