### ISSUE TITLE
Problem with @Criteria.Repository on Eclipse

### ISSUE THREAD

**Issue by ralscha** [immutables/immutables#1175]
I'm dabbling a bit with ```@Criteria``` and it does not work with the Eclipse compiler.

I created a demo project to demonstrate the issue:        
https://github.com/ralscha/immutables

The project works fine on the command line and the OpenJDK compiler. But when you import that project into Eclipse it generates an "empty" Repository implementation

```java
@Value.Immutable
@Criteria
@Criteria.Repository
interface Person {
  @Criteria.Id
  String id();
  String fullName();
}
```

"Empty" Repository without any methods
```java
class PersonRepository implements Repository<Person>{
  private final Backend backend;
  public PersonRepository(Backend backend) {
    this.backend = Objects.requireNonNull(backend, "backend");
  }
}
```

As a second test I added the default facets.
```java
@Value.Immutable
@Criteria
@Criteria.Repository(facets = {SyncReadable.class, SyncWritable.class})
interface Person {
  @Criteria.Id
  String id();

  String fullName();
}
```
With this change the Eclipse compiler no longer generates `PersonRepository` and instead throws this error

```
org.immutables.value.internal.$processor$.$Processor threw java.lang.IllegalArgumentException: element public default org.immutables.criteria.backend.WriteResult upsert(T)  is not a member of the containing type org.immutables.criteria.repository.sync.SyncRepository.Writable<ch.rasc.immutables.Person> nor any of its superclasses
	at org.eclipse.jdt.internal.compiler.apt.model.TypesImpl.asMemberOf(TypesImpl.java:190)
	at org.immutables.value.internal.$processor$.meta.$RepositoryModel$FacetConsumer.consume($RepositoryModel.java:165)
	at org.immutables.value.internal.$processor$.meta.$RepositoryModel.facets($RepositoryModel.java:81)
	at 
``` 

Not sure if that is a bug in the Eclipse compiler.

**Comment by elucash** [comment]
It's not the first time we have problems with `Types.asMemberOf` implementation discrepancies between Javac and ECJ, @asereda-gs when you have time, can you take a look. I'm trying to remember how we work around it.... so it was something like this: if this is javac we use `asMemberOf` to resolve type parameters, but for ECJ we use `Elements.getAllMembers` which resolves type variables instead (but not for javac, hence `asMemberOf`)

**Comment by asereda-gs** [comment]
I will take a look. @ralscha what version of Eclipse are you using ?

**Comment by ralscha** [comment]
The latest version Eclipse IDE 2020‑03

**Comment by asereda-gs** [comment]
@ralscha I'm working on Immutables release now (which should happen this week). 
Will take a look at this issue as soon as I am done.

**Comment by realumhelp** [comment]
Any updates on this? I seem to be having a similar issue with Eclipse 2020-09 /w JDK11. Building via Eclipse will generate a Repository with only a constructor as @ralscha shows. However, when I build via command line it seems to properly build the Repository classes.

My current work-around seems to be building via command line and refreshing my Eclipse project to see the properly generated classes. Eclipse picks them up and seems to run with them just fine, but it is very annoying to have to constantly build from command line. Any resolution would be awesome!!

**Comment by elucash** [comment]
Need to take a look, hopefully can dedicate some time this weekend. Sorry for late responses etc, very busy overall...

**Comment by moledzki** [comment]
Any updates on this?

**Comment by asereda-gs** [comment]
This should be fixed in the last commit. Is there a way for you to build your project from immutables `master` ?

**Comment by vagtsi** [comment]
Hi @asereda-gs , I can confirm, this issue is fixed! I successful tested the criteria _Quick Start_ code in Eclipse `2021-12 (4.22.0)` with recent immutables `2.9.0`.
Thank you very much!
