### ISSUE TITLE
Modify argument type of generated Modifiable setter

### ISSUE THREAD

**Issue by kanderson8** [immutables/immutables#1179]
Cross-posted on SE with more details: https://stackoverflow.com/questions/61740183/cannot-load-collection-using-dynamodbmapper-and-immutables

I'm trying to use DynamoDBMapper with types generated by Immutables but I'm running into an issue with collection types. What I've found is that the mapper is unable to identify the setter for my collection because tries to find a setter with an argument that has the same type as that which gets returned by the getter (in this case, a Set) but my class generated by `@Value.Modifiable` has a setter that takes an Iterable as an argument (for mapper source code, see here: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/StandardBeanProperties.java#L143). Is it possible to force the collection setter of my Modifiable class to take a Set instead of an Iterable as an argument so that the Dynamo mapper can resolve it correctly?

**Comment by elucash** [comment]
You can try to use `Style.beanFriendlyModifiables = true`, this makes setters return void and take the same type as parameter  iirc
