### ISSUE TITLE
Annotation for explicit ownership?

### ISSUE THREAD

**Issue by devinrsmith** [immutables/immutables#1183]
I've got a setup where I have some (parameterless) methods that I want to force my implementations to provide. This works as long as all the implementations remember to implement it. If an implementation forgets though, Immutables happily takes over ownership of it. For example:

```java
interface Animal {
  String name(); // I want this to be handled by Immutables
  
  String sound(); // I *don't* want this to be handled by Immutables
}

@Immutable
abstract class Cat {
  public final String sound() {
    return "meow";
  }
}

@Immutable
abstract class Dog {
  // This impl forgot to implement sound()!
  // I'd like to get a compiler error (helpful for initial development).
}
```

Is there a way to annotate the original interface to tell Immutables to ignore the `sound()` method?

```java
@Excluded
String sound();
```

**Comment by smorel-plenty** [comment]
dupe of #1118

**Comment by devinrsmith** [comment]
Good catch! I didn't search hard enough before I filed an issue. Thanks!
