### ISSUE TITLE
BoM dependency Management

### ISSUE THREAD

**Issue by joke** [immutables/immutables#1187]
Hi,

it would really be great to provide a BoM artifact with a dependency management bundling all the versions of the different artifacts. It would simplify including multiple artifacts.

Something like: [spring-boot-dependencies](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.3.0.RELEASE/spring-boot-dependencies-2.3.0.RELEASE.pom) or [jackson-bom](https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-bom/2.11.0/jackson-bom-2.11.0.pom).

If you are interested I could put something together and make a pull request.

Regards
Joke

**Comment by elucash** [comment]
Can you briefly explain the motivation? We try to avoid using dependencies for the generated code as well as for the generator itself. Most of the dependencies for generated code are optional, the idea is that we try not to drag transitive into user code and don't force specific versions (just hoping that backward compatibility is maintained). Overall we don't mind such contribution, just need to understand for what kind of code it makes sense and that we will not force unnecessary dependencies or being strict with versions to the users of the annotation processor.

**Comment by joke** [comment]
Sure.

Let's say a project is relying heavily on different artifacts:
````
<dependencies>
    <dependency>
        <groupId>org.immutables</groupId>
        <artifactId>value</artifactId>
        <version>2.8.8</version>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.immutables</groupId>
        <artifactId>serial</artifactId>
        <version>2.8.8</version>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.immutables</groupId>
        <artifactId>annotate</artifactId>
        <version>2.8.8</version>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.immutables</groupId>
        <artifactId>mongo</artifactId>
        <version>2.8.8</version>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.immutables</groupId>
        <artifactId>criteria-mongo</artifactId>
        <version>2.8.8</version>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.immutables</groupId>
        <artifactId>criteria-elasticsearch</artifactId>
        <version>2.8.8</version>
        <scope>provided</scope>
    </dependency>
</dependencies>
````
As you can see the project needs to specify the version of `2.8.8` for each artifact. If the project get's updated someone might miss updating the version of the `criteria-elasticsearch` artifact. Maybe the pom.xml got cluttered and individual imports were not lined up as a consecutive blog.
One way to avoid this is to use properties. Something like
```
<properties>
    <immutables.version>2.8.8</immutables.version>
</properties>

<dependencies>
    <dependency>
        <groupId>org.immutables</groupId>
        <artifactId>value</artifactId>
        <version>${immutables.version}</version>
        <scope>provided</scope>
    </dependency>
```
That's better but still later on someone might add a new immutables dependency and not use the properties simply because he did not know or he used an IDE feature.

Projects with multiple artifacts like spring or jackson and many others publish a dependency management artifact (BOM) so the project can import the correct dependencies that way.

Let's assume there was a dependency management dependency from the immutables project. That way the project might import the dependency management and use the dependencies without specifying the exact version of every artifact:

```
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.immutables</groupId>
            <artifactId>bom</artifactId>
            <version>2.8.8</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>
    <dependency>
        <groupId>org.immutables</groupId>
        <artifactId>value</artifactId>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.immutables</groupId>
        <artifactId>serial</artifactId>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.immutables</groupId>
        <artifactId>annotate</artifactId>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.immutables</groupId>
        <artifactId>mongo</artifactId>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.immutables</groupId>
        <artifactId>criteria-mongo</artifactId>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.immutables</groupId>
        <artifactId>criteria-elasticsearch</artifactId>
        <scope>provided</scope>
    </dependency>
</dependencies>
```

To be clear: The dependency management artifact (BoM) should only include the artifacts of the immutables project itself. This way no transitive dependencies will be dragged into the importing project like you fear. You might take a look at the [spock-bom](https://repo1.maven.org/maven2/org/spockframework/spock-bom/2.0-M3-groovy-3.0/spock-bom-2.0-M3-groovy-3.0.pom). It's a rather good and short example.

Regards
Joke
