### ISSUE TITLE
optimize criteria  call of exists()  to extract just ID rather then entire document 

### ISSUE THREAD

**Issue by stardv** [immutables/immutables#1188]
Unless a projection is specifically added, this currently returns the entire document  by default when all it needs is the ID field. 

See org.immutables.criteria.repository.reactive.ReactiveFetcherDelegate:

@Override
public Publisher<Boolean> exists() {
  Query query = this.query.withLimit(1); // check if at least one exists
  Publisher<List<T>> asList = Publishers.toList(session.execute(StandardOperations.Select.of(query)).publisher());
  return Publishers.map(asList, list -> !list.isEmpty());
}

**Comment by asereda-gs** [comment]
As workaround (for now) can you explicitly use a projection ? 
```java
boolean exists = repository.find(...)
.select(person.id)
.exists()
```
?

**Comment by stardv** [comment]
Agreed , that is is the plan for now, but i keyed a ticket to make it a little more user friendly.

**Comment by asereda-gs** [comment]
Do you think something like `.withLimit(1).withCount(true)` would work ? 
IE is Geode smart enough to optimize:
```sql
 select count(*) from (select * from /foo where ... LIMIT 1)
```

**Comment by asereda-gs** [comment]
@stardv can you pls confirm there is no performance penalty with the following OQL:

```sql
select count(*) from (select * from /foo where ... LIMIT 1)
```

Result should be `0` or `1`

**Comment by stardv** [comment]
I will need to see if I can run it with execution plan and get back
