### ISSUE TITLE
Javax.validation API with Immutables 

### ISSUE THREAD

**Issue by Nikolaob96** [immutables/immutables#1197]
First of all im sorry if this is repeated question, i couldn't find any answers regarding this so i decided to post here..

I wanted to know if there is a way to combine javax.validation API and Immutables. I was trying to validate my DTO object using the @Validated annotation and i couldn't as annotations such as @NotNull weren't passed down to immutable deserialized object. 

My class looks like this: 
```java
@Value.Immutable
@JsonSerialize(as = ImmutableTestClass.class)
@JsonDeserialize(as = ImmutableTestClass.class)
public interface TestClass {
    @JsonProperty("code")
    @NotNull
    String test();
}

This would produce the following getter for ImmutableTestClass:
  @JsonProperty("code")
  @Override
  public String test() {
    return test;
  }
```

**Comment by elucash** [comment]
Here's a thread that you might find useful, https://github.com/immutables/immutables/issues/26
it describes couple ways using bean validation with Immutables, including gotchas like non-bean-getter accessors supported by recent versions of Hibernate validator via special configuration. Please, let us know if you will have more questions

**Comment by Nikolaob96** [comment]
Thank you very much.
