### ISSUE TITLE
No Python 3.5 Windows Wheel on pypi

### ISSUE THREAD

**Issue by rongduan-zhu** [immutables/immutables#1200]
There are wheels published for all three platforms (win, mac, linux) for python 3.6 to python 3.8 but for python 3.5, there are only wheels for mac and linux. https://pypi.org/project/immutables/#files

Is it possible to publish Python 3.5 wheel for Windows as well?

**Comment by elucash** [comment]
@rongduan-zhu sorry, but you found wrong project, this is java code generator having nothing to do with python

**Comment by rongduan-zhu** [comment]
Lol this is embarrassing, sorry about this.
