### ISSUE TITLE
When modifiable has modifiable default field, Immutables produces syntactically invalid code.

### ISSUE THREAD

**Issue by SimY4** [immutables/immutables#1215]
When modifiable has modifiable default field, Immutables produces syntactically invalid code.

Same is true for derived and lazy.

There's a PR raised to fix this: https://github.com/immutables/immutables/pull/1212

BEFORE:

```
...
  @Override
  public final ModifiableMod getDefaultMod() {
    return defaultModIsSet()
      ? defaultMod
      : BeanFriendly.super.getDefaultMod(); // doesn't compile because return type of super getDefaultMod is not type of ModifiableMod
  }
...
```

AFTER:

```
...
  @Override
  public final ModifiableMod getDefaultMod() {
    if (defaultModIsSet()) {
      return defaultMod;
    } else {
      BeanFriendly.Mod defaultMod = BeanFriendly.super.getDefaultMod();
      return defaultMod instanceof ModifiableMod
          ? (ModifiableMod) defaultMod
          : new ModifiableMod().from(defaultMod);
    }
  }
...
```

**Comment by SimY4** [comment]
@elucash I humbly ask you to take a look at this issue. It's kind of a blocker for us at the moment.

If you get a chance to review linked PR to fix this, that would be awesome!

**Comment by elucash** [comment]
Sorry for not responding in time. I've merged the PR with the hope it will work and for evaluation purposes. However I don't think it's a good solution, and maybe a candidate to revert before the release. My concerns are about many assumptions in play here about detecting of covariant override to return a type which happens to be a modifiable version of abstract class, it's even hard to imagine how it worked before. So, let's see how it goes.

**Comment by SimY4** [comment]
@elucash thank you for a chance to look at it. 🙏 

I also think that the provided solution can be improved further. I was merely unblocking myself from failing compilation.
