### ISSUE TITLE
Bean friendly modifiable from method return void result

### ISSUE THREAD

**Issue by SimY4** [immutables/immutables#1216]
Modifiable's from method with bean friendly flag turned on returns void in the case where the modifiable class has 1 or more extended interfaces.

This cause two issuers:

it's inconsistent with from method that's generated for Modifiable that doesn't extend any extra interfaces
it causes syntactic errors in Modifiable class in certain scenarios.

There's a PR to address this issue: https://github.com/immutables/immutables/pull/1211

**Comment by SimY4** [comment]
@elucash Can you please have a look at this issue? There's a PR open with a fix. Thank you!

**Comment by elucash** [comment]
Need to take a look, hopefully can dedicate some time this weekend. Sorry for late responses etc, very busy overall...
