### ISSUE TITLE
Using Immutables.Criteria in Java 9+ environment

### ISSUE THREAD

**Issue by realumhelp** [immutables/immutables#1223]
I'm trying to import the Criteria annotations in a JDK11 environment. 

```xml
<dependency>
    <groupId>org.immutables</groupId>
    <artifactId>criteria-inmemory</artifactId>
    <version>2.8.2</version>
</dependency>
```

It seems the module name is not valid because of the dash: `requires org.immutables.criteria-common;`. There are no issues adding the requires statements for Values. Any suggestions would be greatly appreciated!

**Comment by realumhelp** [comment]
So I started looking through some of the code and found the following:

/pom.xml
```xml
              <archive>
                <addMavenDescriptor>false</addMavenDescriptor>
                <manifestEntries>
                  <Automatic-Module-Name>${module.name}</Automatic-Module-Name>
                </manifestEntries>
              </archive>
```
It looks like an automatic module name is created in each jar file. However, if you keep diving down into the criteria modules like **inmemory** or **common**. You'll see that the module.name variable looks to be created from the **project.groupId** and **project.artifactId**. 

/criteria/common/pom.xml
```xml
  <parent>
    <artifactId>criteria</artifactId>
    <groupId>org.immutables</groupId>
    <version>2.8.9-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>criteria-common</artifactId>
  <name>${project.groupId}.${project.artifactId}</name>
```
In the above example you'll end up with **module.name = org.immutables.criteria-common**. This is generating an invalid name. 

I'm reaching a bit past my expertise here with Maven and Modules, but this seems to be the issue.

Just for an example sake if I change the /criteria/inmemory/pom.xml's **artifactId** to something like **criteriainmemory** for example it looks like it starts generating a valid module name:

```
jar --describe-module --file ./immutables-master/criteria/inmemory/target/criteriainmemory-2.8.9-SNAPSHOT.jar
No module descriptor found. Derived automatic module.

org.immutables.criteriainmemory@2.8.9-SNAPSHOT automatic
requires java.base mandated
contains org.immutables.criteria.inmemory
```

versus say a delivered JAR from the Maven Repo

```
jar --describe-module --file criteria-inmemory-2.8.8.jar
Unable to derive module descriptor for: criteria-inmemory-2.8.8.jar
Automatic-Module-Name: org.immutables.criteria-inmemory: Invalid module name: 'criteria-inmemory' is not a Java identifier
```

I don't have any good solutions off the top of my head for this issue because obviously changing the **<artifactId>criteria-common</artifactId>** is not really a good solution. Maybe add a new variable or use some kind of variable manipulation to remove the "-" character. Also this issue looks like it might extend past the Criteria package as well since it looks like other packages use a "-" as well.

If anyone has any comments on the above suggestions I'd appreciate them!

**Comment by realumhelp** [comment]
Just an FYI i looked through all of the pom.xml files for each module and found that a few of them are correctly setting the module-name:

/value-processor/pom.xml
```xml
  <properties>
    <module.name>${project.groupId}.value.processor</module.name>
  </properties>
```

I would recommend following this pattern for each module that contains a "-". 

Specifically:
> android-stub
criteria/common
criteria/elasticsearch
criteria/geode
criteria/inmemory
criteria/mongo
criteria/reactor
criteria/rxjava2
criteria/sql
generator-processor
processor-testlib
value-fixture

I did a quick test and added the appropriate `<properties>` to the above modules and it seems to work for criteria-inmemory at least. `jar --describe-module --file <FILE>` looked good as well.

**Comment by Alex1304** [comment]
Is there at least a temporary workaround for this issue so we can use it in jdk 11+ projects, until #1224 changes are merged and released? I started a project with jdk 11 and found the criteria api very interesting, but i kinda feel screwed that I can't use it.

**Comment by realumhelp** [comment]
It is not pretty but what I've been doing is manually modifying the MANIFEST.MF files inside of the jar files I need.

1) Extract JAR files (there will be a few that need to be corrected like: criteria-common, criteria-mongo for instance depending on your needs. Same process for each JAR.):
  --  jar xvf criteria-mongo-2.8.2.jar

2) Modify META-INF/MANIFEST.MF
  -- vi META-INF/MANIFEST.MF
  -- Correct the **Automatic-Module-Name: org.immutables.criteria.mongo** (notice the dot between criteria and mongo rather than a dash).

3) Update the JAR file with the newly modified MANIFEST.MF
  -- jar --update --file criteria-mongo-2.8.2.jar --manifest=META-INF/MANIFEST.MF

4) Check JAR to make sure it is working:
  -- jar --describe-module --file criteria-mongo-2.8.2.jar

5) Repeat for each JAR that is broken and profit!

Note: If you have any kind of checksums on your dependencies they will obviously be wrong because you're modifying the JARs. So just be cautious about that, and obviously I wouldn't deliver any of the modified JARs... This should get you going temporarily though. You should only need to this once.

**Comment by Alex1304** [comment]
Hmm I figured out the simplest way was to clone your fork of Immutables, checkout your PR branch and build locally with `mvn install`. That way I could use 2.8.9-SNAPSHOT in my project, the dependency resolution wouldn't fail since i installed it in my local maven cache.

**Comment by realumhelp** [comment]
> Hmm I figured out the simplest way was to clone your fork of Immutables, checkout your PR branch and build locally with `mvn install`. That way I could use 2.8.9-SNAPSHOT in my project, the dependency resolution wouldn't fail since i installed it in my local maven cache.

That would be another approach and should work as an unofficial release. I'd be curious to hear if it does work properly, just some extra confirmation that my fix actually works :+1:. However, if you wanted to work with an officially released version you would need to modify the JAR files.

**Comment by Alex1304** [comment]
turns out the `mvn install` fails with a compilation error because it can't find the class `javax.annotation.Generated`. And if I add the javax.annotation dependency manually I get another error saying `Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider org.immutables.generator.processor.Processor not found`

Did you have any issues building the immutables project locally?

**Comment by Alex1304** [comment]
ok so the first error is my fault because I was building using jdk 15, with jdk 8 I don't need the javax.annotation dependency. But I still get the second error about Processor not being found, idk what that means cuz the class is present

**Comment by elucash** [comment]
Can you create minimal repro pom/project and specify version of JDK and Immutables? I have pretty much every JDK installed (albeit micro-version would be different) I can try your case, who know what can come up

**Comment by Alex1304** [comment]
Looks like something broken on realumhelp's fork, now that it's merged I tried with a clone of the main repo, the build was successful

**Comment by elucash** [comment]
good to know, thanks!

**Comment by realumhelp** [comment]
I may not have had the latest of the latest code since I made these changes back in September. If you got everything compiled to check if the auto-module new are good try running:

`jar --describe-module --file criteria-mongo-2.8.2.jar`

If it returns the proper module name then you should be good to go for modules! :D

**Comment by elucash** [comment]
```
$ jar --describe-module --file criteria-mongo-2.8.9-SNAPSHOT.jar
No module descriptor found. Derived automatic module.

org.immutables.criteria.mongo@2.8.9-SNAPSHOT automatic
requires java.base mandated
contains org.immutables.criteria.mongo
contains org.immutables.criteria.mongo.bson4jackson
contains org.immutables.criteria.mongo.codecs
```

**Comment by realumhelp** [comment]
Without the fix you would get something like: 

```
jar --describe-module --file criteria-inmemory-2.8.8.jar

Unable to derive module descriptor for: criteria-inmemory-2.8.8.jar
Automatic-Module-Name: org.immutables.criteria-inmemory: Invalid module name: 'criteria-inmemory' is not a Java identifier```
