### ISSUE TITLE
Criteria to add a readThrough Cache for <Class, memberPath>to avoid class scanning on every query

### ISSUE THREAD

**Issue by kriarani** [immutables/immutables#1241]
Add a readThrough  cache that stores class#memberPath to Member so that subsequent lookup can avoid costly reflective class scanning.

CriteriaContext.appendPath called from Templace  look at this cache.
This will boost > 1ms for every query.

**Comment by kriarani** [comment]
Thanks aserada for fixing it. when are are targetting 2.8.9 ?

**Comment by asereda-gs** [comment]
Yes. It should be in the next release
