### ISSUE TITLE
Upgrade mongo java driver to 4.1.1

### ISSUE THREAD

**Issue by jmoghisi** [immutables/immutables#1242]
Upgrade mongo java driver to 4.1.1 to support MongoDB v4.4 Clusters

See [compatibility matrix](https://docs.mongodb.com/drivers/java#mongodb-compatibility)

**Comment by szjani** [comment]
Hi @jmoghisi 
Is it known when this change will be released? Even an ea release would be fine for me but 2.8.9-ea-1 does not contain it.
