### ISSUE TITLE
Immutable deserialization throws ValueInstantiationException even with Jackson @JsonIgnoreProperties(ignoreUnknown = true)

### ISSUE THREAD

**Issue by sharoha** [immutables/immutables#1243]
I am trying out the deserialization of json object using immutables. Here is the Immutable interface that I have:
```java
@Value.Immutable
@Value.Style(builder = "new")
@JsonSerialize(as = ImmutableTest.class)
@JsonDeserialize(builder = ImmutableTest.Builder.class)
@JsonIgnoreProperties(ignoreUnknown = true)
public interface Test {

    String a();

    Double b();

    Integer c();
}
```

And the following is the Main class that tests the deserialization using the above immutable:
```java
public class TestJacksonMapping {
    public static void main(String[] args) throws JsonProcessingException {
        String json = "{ \"a\": \"123\", \"b\": 2.000}";
        Test deserializedObject = new ObjectMapper().readValue(json, Test.class);
        System.out.println(deserializedObject);
    }
}

```

My current understanding is that with the following annotation set in *Test* immutable, deserialization in my Main class should work even with the field `c` missing in the `JSON String` in the main class.
```java
@Value.Style(builder = "new")
@JsonDeserialize(builder = ImmutableTest.Builder.class)
@JsonIgnoreProperties(ignoreUnknown = true)
```
But running `TestJacksonMapping` throws the following exception:
```
Exception in thread "main" com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `immutables.mapping.ImmutableTest$Builder`, problem: Cannot build Test, some of required attributes are not set [c]
 at [Source: (String)"{ "a": "123", "b": 2.000}"; line: 1, column: 25]
```

Following are the Gradle dependencies that I have in my project:
```
annotationProcessor "org.immutables:value:2.8.2"
compile "org.immutables:value-annotations:2.8.2"
compile "com.fasterxml.jackson.core:jackson-databind:2.10.3"
compile "com.fasterxml.jackson.core:jackson-core:2.10.3"
```
Is there something that I am missing over here?

**Comment by elucash** [comment]
If you define a field, you cannot have it missing, `c` must be provided in JSON. If you want to mark it as optional, i.e. non-mandatory, you should declare it as `@Nullable Integer c()`, `Optional<Integer> c()`, or having a default value `@Value.Default default int c() {return 0;}`. pls see https://immutables.github.io/immutable.html#optional-attributes https://immutables.github.io/immutable.html#default-attributes  https://immutables.github.io/immutable.html#nullable-attributes

**Comment by elucash** [comment]
`ignoreUnknown` works the other way around. it allows you to specify fields in JSON, let's say `h: "unknown"`, and because object do not have `String h()` declared it will just ignore field `"h"` coming from JSON, with no errors.

**Comment by sharoha** [comment]
This makes sense. Thanks for the reply.
