### ISSUE TITLE
2.8.9-ea-1 compilation error on Java 11

### ISSUE THREAD

**Issue by SimY4** [immutables/immutables#1245]
This simplified definition:
```
@Value.Style(jdkOnly = true)
@Value.Immutable(copy = false)
public interface ValidationErrorDetails extends ErrorDetails {
    @Value.Parameter
    List<ValidationErrorMessage> getValidationErrors();
}
```
Raises a compilation error:

```
[ERROR] .../target/generated-sources/annotations/.../errors/ImmutableValidationErrorDetails.java:[37,33] method copyOf in interface java.util.List<E> cannot be applied to given types;
  required: java.util.Collection<? extends E>
  found: java.lang.Iterable<capture#1 of ? extends ...errors.ValidationErrorMessage>
  reason: cannot infer type-variable(s) E
    (argument mismatch; java.lang.Iterable<capture#1 of ? extends ...errors.ValidationErrorMessage> cannot be converted to java.util.Collection<? extends E>)
```

**Comment by asereda-gs** [comment]
Can you pls paste the line(s) where it is failing ?

**Comment by SimY4** [comment]
@asereda-gs it's inside one of copy constructors:

```
@Generated(from = "ValidationErrorDetails", generator = "Immutables")
@SuppressWarnings({"all"})
@SuppressFBWarnings
@ParametersAreNonnullByDefault
@javax.annotation.processing.Generated("org.immutables.processor.ProxyProcessor")
@Immutable
@CheckReturnValue
public final class ImmutableValidationErrorDetails
    implements ValidationErrorDetails {
  private final List<ValidationErrorMessage> validationErrors;

  private ImmutableValidationErrorDetails(
      Iterable<? extends ValidationErrorMessage> validationErrors) {
    this.validationErrors = List.copyOf(validationErrors); // <- here. There's no copyOf(Iterable) method in JDK stdlib
  }
  
  ...
```

**Comment by elucash** [comment]
apparently I fixed copy methods but not copy constructors

**Comment by asereda-gs** [comment]
Hmm it works for me on JDK11 (`11.0.9.1`) with your example.
It generates copy via `createUnmodifiableList()` (not `List.of()`) static method:

```java
  private final List<ValidationErrorMessage> validationErrors;

  private ImmutableValidationErrorDetails(Iterable<? extends ValidationErrorMessage> validationErrors) {
    this.validationErrors = createUnmodifiableList(false, createSafeList(validationErrors, true, false));
  }
```

**Comment by elucash** [comment]
@asereda-gs I would actually expect what @SimY4 got, recent experimental changes to try to use jdk9+ collections if possible. Maybe you have source/target set to jdk8 or something (even if under Jdk11). for the record

```java
//for an attribute
  public boolean isGenerateJdk9() {
    return containingType.isGenerateJdk9()
        && isGenerateJdkOnly()
        && (typeKind.isList() || typeKind.isMap() || typeKind.isSet())
        && nullElements.ban();
  }
//  for a type
  public boolean isGenerateJdk9() {
    return constitution.protoclass().environment().hasJava9Collections();
  }
// hasJava9Collections
    @Value.Lazy
    public boolean hasJava9Collections() {
      for (SourceVersion v9 : SourceVersion.values()) {
        if (v9.name().equals("RELEASE_9")
            && processing().getSourceVersion().compareTo(v9) >= 0) {
          TypeElement element = findElement(List.class.getCanonicalName());
          assert element != null : "always present in modern JREs";
          for (ExecutableElement e : ElementFilter.methodsIn(element.getEnclosedElements())) {
            if (e.getModifiers().contains(Modifier.STATIC) && e.getSimpleName().contentEquals("of")) {
              return true;
            }
          }
        }
      }
      return false;
    }
```

**Comment by elucash** [comment]
btw, one of the problem for templating (to avoid any drastic changes at all cost, including any stop-gap changes akin to ones cause the bug in this issue) is that Jdk9 collection constructors (specifically, `List/Set.copyOf`) take `Collection`, not `Iterable`, like we use everywhere, initially inspired by Guava's immutable collection patterns. If we ignore builder initializers and constructors using builder internally, where we actually iterate over / copy to arraylist, so if we ignore those, then for copy methods and copy constructors it's quite a problem to convert `Iterable` to immutable `List` or `Set` (the ones from jdk9).
The code which seems good enough is smth like

```java
elements instanceof java.util.Collection<?>
      ? java.util.List.copyOf((java.util.Collection<? extends T>) elements)
      : java.util.stream.StreamSupport.stream(elements.spliterator(), false)
          .collect(java.util.stream.Collectors.toUnmodifiableList()
```

But it's really problematic to insert in the current, already chaotic, chain of templates. So I currently thinking if it's just yet another style flag for Java 9 where we for Set and List would just generate `Collection<? extends T>` in constructor/method parameters (instead of iterables). Style flag seems appropriate to justify change in generated signatures, where autodetection  approach would cause spurious change of generated methods Iterable->Collection during upgrade.

Any thoughts or advises?

**Comment by asereda-gs** [comment]
@elucash you're right I didn't change compiler version settings (just JDK)

Do be honest, I'd rather go the template route.

With style we'd have to support different JDK8/JDK9 collection instantiation for quite a while. I don't see anything wrong if new immutables version uses different collection implementation.

In future, maybe user can inject their own collection copy strategy similarly to #1233 (for `toString()`).

**Comment by elucash** [comment]
The dilemma I facing here is not about changing implementation, but also signatures of Iterable->Collection accepting methods, i dunno. As per collection strategies, in general we have encodings fully covering those, but I somehow thought of using List/Map/Set.of/copyOf out of the box

**Comment by dmivankov** [comment]
Is there a known workaround for this? Just tried 2.8.9-ea-1 and got this issue with `List.copyOf` being called for Iterable

**Comment by SimY4** [comment]
@elucash anything I can help with this one being fixed? I *really* need some other fixes included in 2.8.9 to be released. Thank you.

**Comment by elucash** [comment]
It requires some rearrangements to be "fixed" (introduce feature flag to accept `Collection` instead of `Iterable` and change how utils are implemented to use what shown in https://github.com/immutables/immutables/issues/1245#issuecomment-733493160 for the case of iterable)
what we can do now is just make `ValueType.isGenerateJdk9` to return `false` 

```java
public boolean isGenerateJdk9() {
  return false; // constitution.protoclass().environment().hasJava9Collections();
}
```

**Comment by SimY4** [comment]
@elucash @asereda-gs Can some of you please release another ea version?

**Comment by elucash** [comment]
I'll do the release when return from the business trip, Saturday or Sunday, I see there are some PR to review and merge too. Thank you!

**Comment by elucash** [comment]
I'm still on this, after returning from the trip was sucked into the whirlwind of chores, will get to this tomorrow, sorry

**Comment by SimY4** [comment]
@elucash no worries. No rush, we're not blocked by this in any way

**Comment by elucash** [comment]
I've released `2.9.0-beta1` https://repo1.maven.org/maven2/org/immutables/value/2.9.0-beta1/
so far. Probably not ready to pursue rc and the release right now, but given some feedback in 1-2 weeks we can proceed on releases

**Comment by dmivankov** [comment]
Only a quick test, but fwiw compiles in a project with java11 where 2.8.9-ea-1 had issues, no regressions observed in unit tests so far :ballot_box_with_check:

**Comment by SimY4** [comment]
LGTM from our end.
