### ISSUE TITLE
add a @Generated and @Nullable annotations

### ISSUE THREAD

**Issue by xenoterracide** [immutables/immutables#1253]
static analysis tools will now (often) recognize these by name alone, so it would be ideal if Immutables provided them. Example of problems

```
/Users/calebcushing/IdeaProjects/ppm/scaf/build/generated/sources/annotationProcessor/java/main/com/xenoterracide/scaf/ImmutableSkeletonConfiguration.java:135: error: [UnusedVariable] The parameter 'synthetic' is never read.
  private boolean equalTo(int synthetic, ImmutableSkeletonConfiguration another) {
                              ^
    (see https://errorprone.info/bugpattern/UnusedVariable)
  Did you mean '&& equalTo((ImmutableSkeletonConfiguration) another);'?
/Users/calebcushing/IdeaProjects/ppm/scaf/build/generated/sources/annotationProcessor/java/main/com/xenoterracide/scaf/ImmutableSkeletonConfiguration.java:148: error: [Var] Non-constant variable missing @Var annotation
    int h = 5381;
        ^
    (see https://errorprone.info/bugpattern/Var)
  Did you mean '@Var int h = 5381;'?
/Users/calebcushing/IdeaProjects/ppm/scaf/build/generated/sources/annotationProcessor/java/main/com/xenoterracide/scaf/ImmutableSkeletonConfiguration.java:179: error: [NullAway] @NonNull field ImmutableSkeletonConfiguration$Json.templateSourceType not initialized
    Application.SourceType templateSourceType;
                           ^
    (see http://t.uber.com/nullaway )
/Users/calebcushing/IdeaProjects/ppm/scaf/build/generated/sources/annotationProcessor/java/main/com/xenoterracide/scaf/ImmutableSkeletonConfiguration.java:180: error: [NullAway] @NonNull field ImmutableSkeletonConfiguration$Json.source not initialized
    String source;
           ^
    (see http://t.uber.com/nullaway )
/Users/calebcushing/IdeaProjects/ppm/scaf/build/generated/sources/annotationProcessor/java/main/com/xenoterracide/scaf/ImmutableSkeletonConfiguration.java:181: error: [NullAway] @NonNull field ImmutableSkeletonConfiguration$Json.destination not initialized
    String destination;
           ^
    (see http://t.uber.com/nullaway )
/Users/calebcushing/IdeaProjects/ppm/scaf/build/generated/sources/annotationProcessor/java/main/com/xenoterracide/scaf/ImmutableSkeletonConfiguration.java:182: error: [NullAway] @NonNull field ImmutableSkeletonConfiguration$Json.after not initialized
    Pattern after;
            ^
    (see http://t.uber.com/nullaway )
/Users/calebcushing/IdeaProjects/ppm/scaf/build/generated/sources/annotationProcessor/java/main/com/xenoterracide/scaf/ImmutableSkeletonConfiguration.java:285: error: [NullAway] initializer method does not guarantee @NonNull fields templateSourceType (line 280), source (line 281), destination (line 282), after (line 283) are initialized along all control-flow paths (remember to check for exceptions or early returns).
    private Builder() {
            ^
    (see http://t.uber.com/nullaway )
```

and source

```java
  @Value.Immutable
  @JsonSerialize(as = ImmutableSkeletonConfiguration.class)
  @JsonDeserialize(as = ImmutableSkeletonConfiguration.class)
   interface SkeletonConfiguration {
    SourceType getTemplateSourceType();
    String getSource();
    String getDestination();
    Pattern getAfter();
  }
```

I've tried this and subsets of gradle.build.kts (btw, you might want to update the get started documentation with how do do this)

```kts
  annotationProcessor("org.immutables:value:2.+")
  errorprone("org.immutables:value:2.+")
  errorprone("org.immutables:value-annotations:2.+")
  errorprone("com.google.errorprone:error_prone_core:2.4.+")
  errorprone("com.uber.nullaway:nullaway:0.8.+")
  compileOnly("org.immutables:value-annotations:2.+")
```

**Comment by elucash** [comment]
I don't understand the issue here, I mean that there might be an issue(or issues) here, but need some unpacking. We provide `@org.immutables.value.Generated` annotation and also use javax.* Generated. We also use Nullable annotation if it's present in classpath etc.  I know that linters change over time to become (sometimes ridiculously) stricter, but yeah generated files while trying to be reasonable should be generally excluded from overzealous checking. 

Are there more comments or advises, especially from the folks who already submitted issues / PRs to fix errorprone/linter stuff?

**Comment by Stephan202** [comment]
> Are there more comments or advises, especially from the folks who already submitted issues / PRs to fix errorprone/linter stuff?

I'm one of those folks, but have since decided to simply skip Error Prone analysis of generated code. Our Maven build contains the following Error Prone config:
```
-XepDisableWarningsInGeneratedCode
-XepExcludedPaths:${project.build.directory}${file.separator}.*
```

(The first flag disables analysis of all `@Generated` code, even if it's checked in (:see_no_evil:). The second flag disables analysis of all code generated at build time, even if not marked `@Generated`. Additionally, it prevents Error Prone from looking at such code at all, providing a small performance boost.)

For an example see our [open-source parent `pom.xml`](https://github.com/PicnicSupermarket/oss-parent/blob/e82970e916079276773e9d5f23034b0e40a03867/pom.xml#L1061-L1066). Since we enable nearly all Error Prone checks, skipping analysis of generated code seems to be the only pragmatic approach.

**Comment by xenoterracide** [comment]
hmm.... *sigh* I knew this all once... I should have looked up my old plugins... and for some reason last night before filing this, I could swear I opened the generated code and it didn't have `@Generated` on it, so I don't know what I was on there. sorry

    disableWarningsInGeneratedCode.set(true) // did nothing
    excludedPaths.set("$buildDir/generated/sources/.*") // worked

I have created these upstream issues https://github.com/google/error-prone/issues/1984 (good year), https://github.com/tbroyer/gradle-errorprone-plugin/issues/54

**Comment by xenoterracide** [comment]
> We also use Nullable annotation if it's present in classpath

not certain what you mean here? which Nullable annotation? from what jar? certainly nothing was done automagically with checker nullable...

**Comment by xenoterracide** [comment]
related. I have this

```java
@Value.Immutable
@JsonDeserialize(as = ImmutableSkeletonConfiguration.class)
abstract class SkeletonConfiguration {

  @Value.Default
  @NotNull Map<String, String> getContext() {
    return Map.of();
  }

  abstract @Nullable Boolean getOverwrite();

  abstract @Nullable Pattern getAfter();

  abstract @NotNull String getSource();

  abstract @NotNull String getDestination();

  @Override
  public @NotNull String toString() {
    return ToStringBuilder.reflectionToString( this, ToStringStyle.MULTI_LINE_STYLE );
  }
}
```

the `@NotNull` does not show up in the subclass

```java
  /**
   * @return The value of the {@code source} attribute
   */
  @JsonProperty("source")
  @Override
  String getSource() {
    return source;
  }
```

**Comment by xenoterracide** [comment]
appears that the `@NotNull` is probably an issue with the fact that the `annotation` module isn't documented, and doesn't seem to work as advertised.
