### ISSUE TITLE
Generating JSON Schema

### ISSUE THREAD

**Issue by backuitist** [immutables/immutables#1258]
Hello,
Is this supported: https://json-schema.org/ ?
I've seen tickets asking for json-schema -> java, but not the other way around?
Is there any support for custom generators, that is, leveraging immutable's annotation parsing logic?
Thanks

**Comment by asereda-gs** [comment]
You can use [JSON Schema module](https://github.com/FasterXML/jackson-module-jsonSchema) of Jackson.

See [immutables jackson](http://immutables.github.io/json.html) integration for more details.

**Comment by backuitist** [comment]
Would that work with composition?
Maybe I'm getting this wrong but if you have something like that:
```
class A { abstract String field1(); }
class B { abstract A a(); }
```
Then we'll end-up with:
```
class ImmutableB { A a() { ... } }
```
Trying to produce a schema from `ImmutableB` is not going to give you `A.field1`?

**Comment by asereda-gs** [comment]
It should, as long as both A and B are immutable (there is individual JSON schema).

**Comment by backuitist** [comment]
Ok, nvm, I managed to produce it with https://github.com/victools/jsonschema-generator
Thanks for the answer :)

**Comment by nickstolwijk** [comment]
@backuitist How did you manage that? We are trying to do the same, but until now without succes.

```
SchemaGeneratorConfigBuilder configBuilder =
            new SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2019_09, OptionPreset.PLAIN_JSON)
                    .with(Option.DEFINITIONS_FOR_ALL_OBJECTS)
    SchemaGeneratorConfig config = configBuilder.build();
    SchemaGenerator generator = new SchemaGenerator(config);
    JsonNode jsonSchema = generator.generateSchema(ImmutableSwodIntakeMessage.class);

    System.out.println(jsonSchema.toString());
```
But this doesn't show the properties of fields which are itself immutables
