### ISSUE TITLE
AspectJ does not compile when Immutables are used

### ISSUE THREAD

**Issue by temirov** [immutables/immutables#1267]
I was unable to use Immutables and AspectJ's aspectj-maven-plugin in a single module.

I have created a repo to demonstrate the issue: https://github.com/temirov/aspectj-immutables

```
[WARNING] The version of the Immutables annotation on the classpath has incompatible differences from the Immutables annotation processor used. Various problems might occur, like this one: java.lang.NullPointerException
        <unknown source file>:<no line information>

[ERROR] org.immutables.value.internal.$processor$.$Processor threw java.lang.NullPointerException
```

I have opened [the same issue](https://github.com/eclipse/org.aspectj/issues/30) in the ApsectJ repo as it might be in their court but I wanted to post it here for the sake of completeness.

**Comment by elucash** [comment]
Have you tried to fix the issue outlined in the warning? I.e. difference in annotation jar and annotation processing jar versions? Maybe it's irrelevant but the report currently is not very useful for aspectj. Running maven with -X (or something like that) might show better error trace.

**Comment by temirov** [comment]
@elucash Thanks for your response! Yes, I have tried all kind of combinations I could come up with: 

1. Using individual artifacts, e.g. value-annotations, value-processor
2. specifying value-annotations, value-processor artifacts in <dependencies> section of aspectj-maven-plugin
3. specifying value-annotations, value-processor artifacts in <weavenDependencies> section of aspectj-maven-plugin

I am getting the same warning and then the error when AJC is invoked.

**Comment by temirov** [comment]
The way to fix it is to exclude immutables sources, see [this PR](https://github.com/temirov/aspectj-immutables/pull/1) for the details
