### ISSUE TITLE
@Nullable List and Set initialized as empty become null after Java serialization/deserialization

### ISSUE THREAD

**Issue by RJoker0** [immutables/immutables#1295]
Good day, 
We are using immutables 2.8.2 and realized that if we have a `@Nullable` Set or List fields which are initialized with an empty collection then after Java serialization/deserialization they become nulls. 
At the same time, `@Nullable` Collection fields remain empty collections what I consider expected behavior.

This happens because the generated code is different by some reason between List/Set and Collection fields in the generated SerialForm nested class:

    if (instance.collection() != null) {
        names.add("collection");
        values.add(instance.collection());
      }

      if (instance.set() == null) {
        names.add("set");
        values.add(null);
      } else if (!instance.set().isEmpty()) {
        names.add("set");
        values.add(instance.set().toArray());
      }

      if (instance.list() == null) {
        names.add("list");
        values.add(null);
      } else if (!instance.list().isEmpty()) {
        names.add("list");
        values.add(instance.list().toArray());
      }

Would it be possible to change Set and List behavior to the same as for Collections.

Thanks in advance!
[immutables-sample.zip](https://github.com/immutables/immutables/files/6399489/immutables-sample.zip)

**Comment by elucash** [comment]
will look into that, thank you. I think that code is not completely wrong for being not the same for regular collections (`Collection` attributes are not recognized as "collections" at all for being too abstract, there's an obscure note about that in collection section in the user guide), but it's definitely not right either, as nullable collection should support `null`. It could be there are hard to "fix" or intentional limitations for nullable collections in general, will see.

**Comment by RJoker0** [comment]
Thank you, Eugene. 

Maybe just a few words about our use-case: we use generated "request objects" to search for some domain entities (ex. devices). "Request objects" contain all the possible criteria, ex. names, types, locations, etc., which are collections. 

We need to distinguish two cases:
- no criterion provided at all (ex. no types) - this means that we should ignore this criterion completely while searching (we use null Set to represent this)
- empty criterion provided (ex. empty collection of types) - this means that by some reason a client has given to us no acceptable values (we use empty Set to represent this). Yes, in this case nothing will be found and returned to the client - client side could programmatically compose those criteria and not even realize that some criteria are empty.

Cheers
Roman

**Comment by elucash** [comment]
Thanks for reminding, seems to found the solution, yet was a bit puzzling to figure out where the logical mistake was. I'm merging to master, will release in beta3 in 1-2 days

**Comment by RJoker0** [comment]
Thank you very much, Eugene!
Roman

**Comment by RJoker0** [comment]
Dear Eugene,
when do you plan to release the fix?
Thanks!
Roman

**Comment by elucash** [comment]
Hi Roman, only now I've managed to return to this, released in `2.9.0-beta3`

**Comment by RJoker0** [comment]
Thank you very much, Eugene!
2.9.0-beta3 works for me.
When do you plan to make it proper 2.9.0 release?
Cheers
Roman

**Comment by asereda-gs** [comment]
We're planning to release 2.9.0 within couple of weeks

**Comment by RJoker0** [comment]
Dear @elucash and @asereda-gs ,
2.9.0 is not yet released, right?
When do you plan to release it?
Thanks!
Roman

**Comment by elucash** [comment]
@RJoker0 I'm very sorry for the seemingly endless delays, we had extremely small amount of time that we could dedicate to that in the light of some hard to troubleshoot issues. I've carved some time for the last ditch effort to address known issues with the goal to release with whatever remains. Wish me good luck tonight :)

**Comment by RJoker0** [comment]
Good luck, Eugene!

**Comment by elucash** [comment]
released in 2.9.0 at last
