### ISSUE TITLE
[Encoding] Annotations on custom method parameters are discarded

### ISSUE THREAD

**Issue by Alex1304** [immutables/immutables#1307]
Given the following encoding class:

```java
@Encoding
public class CustomOptionEncoding<T> {

    @Encoding.Impl
    private CustomOption<T> value = CustomOption.none();

    @Encoding.Naming("with*OrNull")
    @Encoding.Copy
    public CustomOption<T> withNullable(@Nullable T t) {
        return CustomOption.ofNullable(t);
    }
}
```

Calling `immutableObject.withPropertyOrNull(null)` will raise an IDE warning saying the value cannot be null, because the `@Nullable` annotation is not present in the generated implementation.

Might be related to https://github.com/immutables/immutables/issues/1205

**Comment by elucash** [comment]
thank you for reporting this. We have some limitation with regard to annotation handing in encoding. Transferring annotation from parameter might be possible though, but might require some efforts to properly propagate all the way. All I can promise is to take a look at it within 1–2 weeks. Or is someone could be "brave" enough to help with PR, after all we do copy annotations from encoding methods, so adding param annotation handling might be non-trivial, but not far off the beaten path.

**Comment by Alex1304** [comment]
Just for info, this problem doesn't seem to affect custom Builder methods
