### ISSUE TITLE
IllegalAccessError with Jackson Afterburner 

### ISSUE THREAD

**Issue by cemo** [immutables/immutables#1313]
I am using immutables v2.8.2 and jackson v2.12.3 with Afterburner module. However this is causing some issue regarding access modifers. 

I created a sample project with 2 test. One of them is registering AfterBurner and other one is not. The one without afterburner is working properly. However other one is not. 

https://github.com/cemo/immutable-afterburner-issue

Here is the sample error

```
WARNING: Disabling Afterburner serialization for class com.mycompany.app.ImmutableVal (field #0; mutator com.fasterxml.jackson.module.afterburner.ser.IntMethodPropertyWriter), due to access error (type java.lang.IllegalAccessError, message=failed to access class com.mycompany.app.ImmutableVal from class com.mycompany.app.ImmutableVal$Access4JacksonSerializer7db6db1a (com.mycompany.app.ImmutableVal is in unnamed module of loader 'app'; com.mycompany.app.ImmutableVal$Access4JacksonSerializer7db6db1a is in unnamed module of loader com.fasterxml.jackson.module.afterburner.util.MyClassLoader @5c30a9b0))

java.lang.IllegalAccessError: failed to access class com.mycompany.app.ImmutableVal from class com.mycompany.app.ImmutableVal$Access4JacksonSerializer7db6db1a (com.mycompany.app.ImmutableVal is in unnamed module of loader 'app'; com.mycompany.app.ImmutableVal$Access4JacksonSerializer7db6db1a is in unnamed module of loader com.fasterxml.jackson.module.afterburner.util.MyClassLoader @5c30a9b0)
	at com.mycompany.app.ImmutableVal$Access4JacksonSerializer7db6db1a.intGetter(com/mycompany/app/ImmutableVal$Access4JacksonSerializer.java)
	at com.fasterxml.jackson.module.afterburner.ser.IntMethodPropertyWriter.serializeAsField(IntMethodPropertyWriter.java:55)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4487)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3742)
	at com.mycompany.app.AppTest.shouldAnswerWithThisTrueToo(AppTest.java:46)
```

to replicate run `mvn clean test `

**Comment by elucash** [comment]
Thank you for reporting this, unfortunately we don't have time/resources to investigate this problem on our own and we need help with it.
* What Jackson Afterburner is trying to do? (so it gets IllegalAccessError)
* Is it legit what it is doing? (for the Java version used)
* How Immutable generated code is not what it expected if it is
* What would be the fix(es) on the side of Immutables?
* Double check if it's Jackson Afterburner problem or limitation after all?

**Comment by mikebell90** [comment]
Note: Blackbird is the Java 11 successor to AfterBurner. Did you try that?

**Comment by mikebell90** [comment]
See https://github.com/FasterXML/jackson-modules-base/tree/master/blackbird

AfterBurner is really only safe to use with Java 8 and previous

**Comment by cemo** [comment]
Azure SDK is using :) It is not configurable and it is private static final. 

https://github.com/Azure/azure-sdk-for-java/blob/412be1e5ee6778ee21bcdc56e21a7aea48b104b9/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/Utils.java#L68-L87

**Comment by mikebell90** [comment]
Yes that will go down in flames I'm pretty sure in Java 17 now that all such access is restricted without add-opens

**Comment by mikebell90** [comment]
@cemo looks like they released version of azure sdk removing this for JDK16+.... so is your issue "solved"
