### ISSUE TITLE
"Was unable to read source file" warning when extending interface in different module and using sibling concrete generated class

### ISSUE THREAD

**Issue by Tristan971** [immutables/immutables#1323]
Hi, I ran into some odd compiler warning with immutables (2.8.8). The title is... the best way I could manage to put it...

To start off, this warning is produced when running `mvn compile` from a clean workspace:

     [WARNING] Was unable to read source file for moe.tristan.ibv.common.immutables.SomeInterface[com.sun.tools.javac.code.Symbol$ClassSymbol.class]: java.io.FileNotFoundException: moe/tristan/ibv/common/immutables/SomeInterface.java

Doesn't happen on JDK 11, happens on JDK 16. I made what I believe to be the most minimal reproduction case here: https://github.com/Tristan971/immutables-odd-warning-repro

Here's a short explainer. Say you have 2 modules, with the following classes in each:

Module A:
```java
public interface SomeInterface {}
```

Module B (depends on A):
```java
@Immutables
public interface ClassA extends SomeInterface {

  ImmutableClassB getB();

}

@Immutables
public interface ClassB {}
```

Then this warning will be triggered during compilation of module B.

Just in case, this also happens if you remove `ClassB` altogether and set the property type in `ClassA` to `ImmutableClassA`. I just went this route to clarify that it's not due to some handling of the cycle in the type.

From here on out, I'm really not sure exactly how to investigate further... Hopefully the test repo helps

---
Full output: (reproduced on maven 3.8.1 on ubuntu, and with adoptopenjdk 16 in a CI environment)
```
$ mvn --show-version compile 
Apache Maven 3.6.3 (Red Hat 3.6.3-8)
Maven home: /usr/share/maven
Java version: 16.0.2, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-16-openjdk-16.0.2.0.7-1.rolling.fc34.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.19.128-microsoft-standard", arch: "amd64", family: "unix"
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] ibv                                                                [pom]
[INFO] common                                                             [jar]
[INFO] dependency                                                         [jar]
[INFO] 
[INFO] --------------------------< moe.tristan:ibv >---------------------------
[INFO] Building ibv 0.0.1-SNAPSHOT                                        [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] -------------------------< moe.tristan:common >-------------------------
[INFO] Building common 0.0.1-SNAPSHOT                                     [2/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/tristan/perso/immutables-beanvalidation/common/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ common ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/tristan/perso/immutables-beanvalidation/common/target/classes
[INFO] 
[INFO] -----------------------< moe.tristan:dependency >-----------------------
[INFO] Building dependency 0.0.1-SNAPSHOT                                 [3/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ dependency ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/tristan/perso/immutables-beanvalidation/dependency/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ dependency ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/tristan/perso/immutables-beanvalidation/dependency/target/classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] Was unable to read source file for moe.tristan.ibv.common.immutables.SomeInterface[com.sun.tools.javac.code.Symbol$ClassSymbol.class]: java.io.FileNotFoundException: moe/tristan/ibv/common/immutables/SomeInterface.java
[INFO] 1 warning
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] warnings found and -Werror specified
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ibv 0.0.1-SNAPSHOT:
[INFO] 
[INFO] ibv ................................................ SUCCESS [  0.002 s]
[INFO] common ............................................. SUCCESS [  0.560 s]
[INFO] dependency ......................................... FAILURE [  0.315 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.928 s
[INFO] Finished at: 2021-08-03T03:14:18+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project dependency: Compilation failure
[ERROR] warnings found and -Werror specified
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :dependency
```

**Comment by elucash** [comment]
We use mechanism to read some information from source files when compiler provided information is inaccurate or missing, usually to get around any incomplete or "not yet generated" types. Most of the time this should not be an issue, but it may result in some more complex cases not working. In particular, this most affects when not yet generated types are used as attribute types in abstract value types to be generated. Need some digging to understand if Javac completely stopped to provide us with source files, it's unknown if any workarounds will be possible. In any case I would recommend, if possible, to minimize or avoid use of not-yet-generated types in signatures (as return types/parameters), but I understand if those are widely used this may not be easy or a good move.

**Comment by Tristan971** [comment]
Fair, I expected it would be something to that order

Unfortunately it's usually non-trivial to not rely on generated types (if one wants to try and have every object used in the API to use immutables)

**Comment by Magotchi** [comment]
As having that remaining warning above about Serializable causes incremental compilation to be disabled, I've worked around it by creating a completely empty file at "<project-path>/immutables-java-17-bug-workaround/java/io/Serializable.java" and adjusting my build.gradle to have:
```groovy
compileJava {
    options.sourcepath =
        files(
            sourceSets.findByName("main").allJava.srcDirs,
            // This directory contains an empty java/io/Serializable.java file to work around
            // https://github.com/immutables/immutables/issues/1323
            'immutables-java-17-bug-workaround'
        )
}
```

**Comment by Magotchi** [comment]
It turns out that having the "sourcepath" compiler argument in Gradle results in incremental compilation being disabled if any of the files referenced in it change, sadly, so this is less of a workaround than I thought.

**Comment by markpritchard** [comment]
I've run into this problem with a JDK 17 project on Gradle 7.3. Immutables is having trouble finding the source for classes referenced across modules. The challenge might be the source locations may not be provided by Gradle, just the built jar as a dependency on the class path.

Unfortunately, this is emitted as a compiler warning, so we've had to turn off warnings-as-errors which is unfortunate.

I suspect one way to tackle it would be refactoring the project to have all immutables in one module, but that wouldn't be a preferred solution. 

Would another option be to turn off the warning? Perhaps via a command line flag to the annotation processor?

**Comment by elucash** [comment]
thank you for some more info, I hope to address it soon, either by removing it or suppressing when it wouldn't apply

**Comment by elucash** [comment]
removed warning in 2.9.0
