### ISSUE TITLE
upcoming 2.9.0 release

### ISSUE THREAD

**Issue by elucash** [immutables/immutables#1333]
released `2.9.0-rc1`. I don't expect any more changes / fixes, but just in case can include some important hotfixes.

**Comment by elucash** [comment]
https://repo1.maven.org/maven2/org/immutables/immutables/2.9.0-rc1/

**Comment by elucash** [comment]
evaluating rc, also awaiting for possible performance fixes for criteria modules

**Comment by mikebell90** [comment]
Is there changelog?

**Comment by asereda-gs** [comment]
We'll prepare release notes.

Re: Criteria performance fixes were addressed in fef58594

**Comment by jacques-n** [comment]
@asereda-gs, it would be great to get a fix for the multi-module bug for #1262, specifically described in [this comment](https://github.com/immutables/immutables/issues/1262#issuecomment-929742007). Any ways to help facilitate that? It seems like the way that nullable annotations from compiled jars are read/matched differently than when they are in the same compilation module. It's pretty hard to work around this constraint.

**Comment by asereda-gs** [comment]
@jacques-n we'll try to address it before 2.9.0 final

**Comment by jacques-n** [comment]
> @jacques-n we'll try to address it before 2.9.0 final

Awesome, super appreciated!

**Comment by koalalam** [comment]
Any update on rollout plan of v2.9.0?

BTW, when trying the `underrideEquals` feature, we found the new parameter `synthetic` in `equalTo` function is not actually used. There is a comment:

> adding synthetic parameter for macros-hygiene: do not overlap with any customized equalTo method

Not 100% sure what it means and in what scenarios would this new parameter help. Appreciated much if anyone can explain.

https://github.com/immutables/immutables/commit/2d3f104b751226ab6031d7fd1a9c496ee63c8bc8#diff-17df6884bdcc65d11cd9dbc5f815c4d4bee0d466b175a364f5f20c260cac952dR3076

**Comment by elucash** [comment]
we're discussing some last preparation/inclusions into 2.9.0, which should be released promptly: don't want to make promises, but estimate it within a week

**Comment by elucash** [comment]
the `synthetic` parameter is to disambiguate overloads, i.e. if one would define `boolean equalTo(T t)`, the generated private method would not overlap with that manually written method, i.e. their parameter signatures would not clash. See how it used in test fixtures:

```java
@Value.Style(underrideEquals = "equalTo", underrideHashCode = "hash", underrideToString = "stringify")
@Value.Immutable
@Value.Modifiable
public interface UnderrideObjectMethods {
  int a();

  default String stringify() {
    return "%%%";
  }
  default int hash() {
    return -1;
  }
  default boolean equalTo(UnderrideObjectMethods b) {
    return this == b;
  }

  @Value.Style(underrideEquals = "equalTo", underrideHashCode = "hash", underrideToString = "stringify")
  @Value.Immutable
  @Value.Modifiable
  interface StaticUnderride {
    static String stringify(StaticUnderride a) {
      return "!!!";
    }
    static int hash(StaticUnderride a) {
      return -2;
    }
    static boolean equalTo(StaticUnderride a, StaticUnderride b) {
      return a == b;
    }
  }

  @Value.Style(underrideEquals = "equalTo")
  @Value.Immutable(intern = true)
  interface InternUnderride {
    int d();
    static boolean equalTo(InternUnderride a, InternUnderride b) {
      return a == b;
    }
  }
}
```

My expectation is that `@SuppressWarnings("all")` should handle any warning for unused, if case an IDE is too smart to warn about it, just disable the check or ignore it in the generated code. Adding that parameter is harmless as is invisible outside, doesn't make any sense to generate conditional code if signature clash is to be expected or not.

**Comment by koalalam** [comment]
@elucash , thanks for your explanation. To clarify - is the generated private method still generated even if `underrideEquals` is used? In our use case, the private method isn't generated.

Source:
```java
@Value.Immutable
@Value.Style(
    strictBuilder = true,
    builder = "new",
    jdkOnly = true,
    defaultAsDefault = true,
    get = {"get*", "is*"},
    init = "set*",
    underrideEquals = "equalTo",
    underrideHashCode = "hash")
@Serial.Version(1L)
@JsonDeserialize(builder = ImmutableOrderCountByMarket.Builder.class)
public interface OrderCountByMarket extends Serializable {

  @Value.Derived
  @JsonIgnore
  default int hash() {
    return getMarket().hashCode();
  }

  default boolean equalTo(OrderCountByMarket rhs) {
    return getMarket().equals(rhs.getMarket());
  }

  @Value.Parameter
  String getMarket();

  @Value.Parameter
  int getCount();
}
```

Generated:
```java
  /**
   * This instance is equal to all instances of {@code ImmutableOrderCountByMarket} that have equal attribute values or
   * as defined by custom equality check method in supertype.
   * @return {@code true} if {@code this} is equal to {@code another} instance
   */
  @Override
  public boolean equals(Object another) {
    return another instanceof ImmutableOrderCountByMarket
        && OrderCountByMarket.super.equalTo((ImmutableOrderCountByMarket)another);
  }
```

**Comment by koalalam** [comment]
> we're discussing some last preparation/inclusions into 2.9.0, which should be released promptly: don't want to make promises, but estimate it within a week

@elucash, any update on this? Thank you!

**Comment by ppetershagen** [comment]
Hi, just looked at the commits in master and figured out, this change about `beanFriendlyModifiables` is also included: https://github.com/immutables/immutables/commit/89582952ae4229c4893d23834bb1aa96d49ad82c I think it's worth mentioning it, why this might help in some use cases with JPA / entity beans.

**Comment by elucash** [comment]
v2.9.0 landed,  https://repo.maven.apache.org/maven2/org/immutables/value/2.9.0/
we've been trying to incorporate as many fixes as possible, some issues with no straightforward fix are still with a solution or only having partial solution. There will be some release notes, but it will be couple of days before we sort this out
