### ISSUE TITLE
Immutables and Javax Validation without get prefix

### ISSUE THREAD

**Issue by throwawaygit000** [immutables/immutables#1336]
If I set an immutable without get prefix validations are not triggered.

```
@Value.Immutable
public interface Entity {
    @Min(19)
    int age();

     @NotBlank
    @Size(min = 10)
    String name();

}
```

**Comment by elucash** [comment]
this is not per validation specification, per specification you must use `get*` prefix, but Hibernate Validator 5+ have a feature to enable accessors without prefixes and AFAIK this is a matter of configuration
