### ISSUE TITLE
java.lang.IllegalStateException: endPosTable already set on repeated  mvn compile

### ISSUE THREAD

**Issue by apara** [immutables/immutables#134]
Using latest released version of Immutables.

I am seeing an issue where repeated mvn compile causes java.lang.IllegalStateException: endPosTable already set error to be returned from compiler.  It is similar to the issue seen for a different code generation framework which is described here:

https://github.com/mkarneim/pojobuilder/issues/71

In essence repeated mvn compile cause the above mentioned compiler error.  Command mvn clean compile (doing a clean before compile which deletes the target directories) always fixes the issue and everything works fine.  I am sure it's a javac error, however, I am not quite sure how to apply the configuration fix they did in the pojobuilder library to the Immutables library.

Thanks.
-AP_

**Comment by elucash** [comment]
Hi Alex, thank you for reporting this! I, for example, usually just use `mvn clean install` so did not have a chance to catch this, however when I use `mvn compile` repeatedly there still no sign of the bug. Anyway, judging from the issue/discussion thread you provided, there are no real solution on the annotation processing side. The workaround is to split annotation processing and compilation in different steps/using different plugins. I've included link to the PojoBuilder wiki page to the documentation. The page describes how to configure maven build in the project which uses annotation processor.

**Comment by trask** [comment]
@elucash in case you want to see a repro, it occurs consistently with the [glowroot](https://github.com/glowroot/glowroot) build (at least using Java 1.8.0_45 on Windows).

**Comment by elucash** [comment]
yep, was able to repro it, thanks @trask!
I'll poke around it, but have very little hope.

**Comment by elucash** [comment]
BTW I found a better solution for Maven which works for me, there's `useIncrementalCompilation` option in compiler plugin configuration.

```xml
    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.3</version>
        <configuration>
          <compilerVersion>1.8</compilerVersion>
          <source>1.8</source>
          <target>1.8</target>
          <useIncrementalCompilation>true</useIncrementalCompilation>
          <compilerArgs>
            <arg>-Xlint:deprecation</arg>
            <arg>-Xlint:unchecked</arg>
          </compilerArgs>
        </configuration>
      </plugin>
```

**Comment by trask** [comment]
Looks like a good find. Did you mean set it to false?

**Comment by elucash** [comment]
sure
EDIT: `<useIncrementalCompilation>false</useIncrementalCompilation>`

**Comment by apara** [comment]
Nice, looks like its working...

**Comment by mjball** [comment]
The root cause of this bug is now fixed: https://issues.apache.org/jira/browse/MCOMPILER-236

**Comment by elucash** [comment]
I hope so, thanks for the info!

**Comment by yarieldis** [comment]
It solves the problem for me, thank you.

**Comment by spulluru** [comment]
I got this error 
java.lang.IllegalStateException: endPosTable already     with     JDK 1.8, Maven 3.5 

Adding this line    
<useIncrementalCompilation>false</useIncrementalCompilation>  works great

**Comment by Ramblurr** [comment]
Is there a similar workaround for gradle?

**Comment by elucash** [comment]
I dunno, maybe something like below, but not sure if (or how) it will work

```
compileJava {
    options.incremental = false
}
```

**Comment by Ramblurr** [comment]
That doesn't work, I've also tried:

```
allprojects {
    tasks.withType(JavaCompile) {
        options.incremental = false
    }
}
```

I suspect the issue might not be related to gradle' incremental compilation.

But crikey it is so annoying having to clean generated classes every build.

**Comment by tbcs** [comment]
With Gradle v4.5 and APT plugin v0.13 running on JDK 1.8.0_151, disabling incremental compilation as suggested above did not solve the issue for me.  I ended up adding this to my build file:
```
def generatedSrcRoot = file("${buildDir}/generated/source/apt/main")

task deleteGeneratedSources(type: Delete) {
  delete generatedSrcRoot
}

tasks.withType(JavaCompile) { it.dependsOn('deleteGeneratedSources') }
```

**Comment by BVijayKrishna** [comment]
what is the workaround for gradle 3.4 with Java 1.8

**Comment by mykhailo-edcast** [comment]
> what is the workaround for gradle 3.4 with Java 1.8

Have you found?
