### ISSUE TITLE
Compilation error when all fields are nullable  (deepImmutablesDetection + allParameters)

### ISSUE THREAD

**Issue by Nick-VdP** [immutables/immutables#1344]
A compilation error occurs when all fields are nullable and you use deepImmutablesDetection in combination with allParameters.

Example:

```
@Value.Immutable
@Value.Style(deepImmutablesDetection = true, allParameters = true)
public interface Test {

    @Nullable
    TestChild getChild();
}

@Value.Immutable
public interface TestChild {}
```

\target\generated-sources\annotations\test\ImmutableTest.java:88:30
java: incompatible types: @org.jetbrains.annotations.Nullable test.TestChild cannot be converted to @org.jetbrains.annotations.Nullable test.ImmutableTestChild

**Comment by elucash** [comment]
this particular case is fixed in 2.9.0
