### ISSUE TITLE
Option to include class as part of hashCode

### ISSUE THREAD

**Issue by devinrsmith** [immutables/immutables#1349]
I've got a lot of structures that have the same fields, but are otherwise distinguished by their class / type. It would be nice to be able to try and spread their hash codes out so they don't end up colliding in a map when they have the same values. I might imagine the implementation could look like:

```java
  @Override
  public int hashCode() {
    int h = 5381;
    h += (h << 5) + ImmutableX.class.hashCode();
    ...
```

Of course, I *could* implement all my own hash codes, but that defeats some of the ease-of-use for using Immutables :).

In the case where there are no fields (a common occurrence I find in meta / type-ing code), it would be nice to also not return 0, and just return the class hashCode:

```java
    @Override
    public int hashCode() {
        return ImmutableX.class.hashCode();
    }
```

I *am* able to handle this latter case with relative ease in my own code by having common abstract code that implements hashCode w/ `getClass().hashCode()`, but I think it would be a nice-to-have feature as well.

Is there any sort of functionality that exists to add the class type into the hash code?

**Comment by elucash** [comment]
`Style.includeHashCode` in v2.9.0

```java
    /**
     * If {@code includeHashCode} is not empty it will be used as part of generated `hashCode`. This will be a verbatim
     * line of code used with the tag-placeholder {@code [[type]]} will be replaced with the simple
     * (or relative to top level) name of the abstract value type.
     * It's the responsibility of the user to put well-formed code to be put in context, including parenthesis, etc,
     * use try-see-fix approach here. Other fields will be included as usual, coming after this custom value.
     * <p>Examples might give you better ideas how to use it:
     * <pre>
     *   includeHashCode = "this.baseHashCode()"
     *   includeHashCode = "super.hashCode()"
     *   includeHashCode = "getClass().hashCode()"
     *   includeHashCode = "[[type]].class.hashCode()"
     *   includeHashCode = "(\"[[type]]\".length() + 1)"
     * </pre>
     * <p><em>Note: this will be ignored if `hashCode` will be manually written in the abstract value class or {@link #underrideHashCode()} will be used for the same purpose</em>
     * @return interpolated code snippet, by default empty and have no effect
     */
    String includeHashCode() default "";
```
