### ISSUE TITLE
Add static builder() to Builder.Constructor

### ISSUE THREAD

**Issue by HariNairJHUAPL** [immutables/immutables#1352]
For consistency with the static ImmutableXXX builder() method which returns a new ImmutableXXX.Builder(), please add a similar method to Factory builders.  

i.e. using the example in the documentation
```
class Sum {
  final int result;
  @Builder.Constructor
  Sum(int a, int b) {
    this.result = a + b;
  }
}
... // use generated builder
Sum sum = new SumBuilder()
    .a(111)
    .b(222)
    .build();
```

You should also be able to do 
```
... // use generated builder
Sum sum = SumBuilder.builder()
    .a(111)
    .b(222)
    .build();
```

**Comment by elucash** [comment]
Hi, thank you for suggestion! But I think this is already implemented using styles `@Value.Style(newBuilder = "builder")` With this style attribute you can customize builder name (`newBuilder` applies to external builders), the default is `"new"` which result in plain constructor. With any non-default value you will get factory method generated with the name you specify. The style annotation can be added to the class, package or as meta annotation for custom "style annotation". See about how to apply styles here https://immutables.github.io/style.html
