### ISSUE TITLE
All-argument constructor for builder-method Immutable classes

### ISSUE THREAD

**Issue by ChrisTrenkamp** [immutables/immutables#1357]
I'm using Protostuff for serializing and deserializing our generated Immutable classes.  Protostuff heavily relies on reflection in order for it to work.  With the latest Java releases, we have to add explicit `--opens` parameters to the JVM in order for Protostuff to work.

After exploring a bunch of different options, the only proper fix for this problem is to create our own annotation processor for generating efficient serialization/deserialization code for our Immutable classes.

We use this style for our Immutable's:

```
@Value.Style(
    visibility = Value.Style.ImplementationVisibility.PACKAGE, // Reduce the visibility to package so the public API isn't polluted
    privateNoargConstructor = true, // This is here so Protostuff can instantiate the Immutable class.
    implementationNestedInBuilder = true // Keep the internal API as clean as possible; we don't need to see the implementation class
)
```

This generates a builder that looks something like this:
```
public final class FooBuilder {
    private final String someField;
    ...
    static final class ImmutableFoo {
        private final String someField;
        private ImmutableFoo() { ... }
        private ImmutableFoo(FooBuilder builder) {
            this.someField = builder.someField;
            ...
        }
        ...
    }
    ...
}
```

Is it possible to tweak the style so the `ImmutableFoo` class has a package-level all-argument constructor?  e.g. `ImmutableFoo(String someField) {...}`.  This way, the annotation processor can generate code that directly instantiate the `ImmutableFoo` class without using any reflection or wasting CPU cycles using the `FooBuilder` to construct it.  We do have instances where we're using Immutable's [Constructor method](https://immutables.github.io/immutable.html#constructor-method), but those are rarely used due to its fragility.

I believe this also, at least indirectly, relates to adding support for Records (https://github.com/immutables/immutables/issues/1285).  If Record support were to be added to Immutables, the Builder classes would need to call the constructor for the Record that contains all the arguments.

**Comment by elucash** [comment]
I think there should be some styles you might be interested in
* `of="new"` to switch from the factory method to public constructor
* `allParameters` or `allMandatoryParameters` to include all attributes or all mandatory attributes in constructor
* `optionalAcceptNullable` to tweak some optional / nullable discrepancies.
maybe not precisely what is needed, but it may get you very close

**Comment by ChrisTrenkamp** [comment]
A combination of `of="new"` and `allParameters=true` did get pretty close to what I was looking for.  However, there were two issues:

* I got this error message, `Interning, singleton and validation will not work correctly with 'new' constructor configured in style`.  I certainly don't want to turn off validation.
* The public constructors are calling `createSafeList`, which creates another copy of array/map fields.  That certainly is desirable; you don't want to pass in a list and suddenly your immutable is different when you change it afterwards.  However, for the use-case of serializing and deserializing streams of data, creating a copy of the list is unnecessary and inefficient.

I think what I'll do is keep the current style we're currently using, but the annotation processor will use reflection to set the Immutable's fields.  It looks like there are reflection options [that perform very well](https://stackoverflow.com/a/22337726).

**Comment by elucash** [comment]
I see, by creating the class in the same package (using an annotation processor), the reflection would originate from it, not from some other library, and then, faster reflection is just nice thing to have and good enough.  Good solution!
