### ISSUE TITLE
Make @Value.Style inherited

### ISSUE THREAD

**Issue by creckord** [immutables/immutables#1370]
Would it be possible to add `@Inherited` to the `@Value.Style` annotation?

I'm coming from issue #26 and using a mixin interface with `@Value.Check` to implement my custom validation. This works great, but requires subtypes to not just extend my mixin but also to declare `@Value.Style(validationMethod = Value.Style.ValidationMethod.NONE)`. Otherwise my custom validation is superceded by the default simple builder validation, that still happens first in the `build()` method.

Here's a simplified example that currently doesn't work, because the style is not picked up in ImmutableMyBean.Builder:

```
@Value.Style(validationMethod = Value.Style.ValidationMethod.NONE)
public interface Validated {

    Validator DEFAULT_VALIDATOR = Validation.buildDefaultValidatorFactory().getValidator();

    @Value.Check
    default void validate() throws ValidationException {
        Set<ConstraintViolation<?>> constraintViolations = DEFAULT_VALIDATOR.validate(this);
        if (!constraintViolations.isEmpty()) {
            throw new ConstraintViolationException(constraintViolations);
        }
    }
}

@Value.Immutable
public interface MyBean extends Validated {
    @Size(min = 1, max = 10)
    @Pattern(regexp = "[a-zA-Z0-9]{1,10}")
    @NotNull
    String getSomeProperty();
}
```
(In reality, my validator is doing a bit more. Also, setting the style on the package would be possible, but I'd have to separate out my beans based on their validation needs, and I'd rather not do that...)

**Comment by creckord** [comment]
Forgot to mention: I also tried to use @Value.Style as a meta annotation on an annotation that had @Inherited, but that didn't work either :(

**Comment by elucash** [comment]
I kinda understand your need, but I'm not sure yet we need to add this specific case. Maybe you can just put style annotation on a package or a parent package? This will work with either style annotation or meta-style annotation. If all of your objects would share the same settings, then there's no reason to complicate it, just define your style and apply it once. If you need a distinct flavors, then define couple of meta-style annotations and apply them directly to the abstract value type or to the sub-package containing a group of data types. I understand that the style should correlate with the inherited interface to work properly, which is inconvenience and potential source of mistakes. But just putting a single annotation to parent package could mitigate that by standardizing all of the immutable objects (or groups of the immutable objects by using meta-annotation styles)

**Comment by creckord** [comment]
I kinda hoped to get it working with inheritance, but package-wide config is an option. It wasn't my first choice, because I'm moving a legacy codebase to Immutables, and have different requirements for classes in the same package. But I guess I'll just bite the bullet and split the package up.
