### ISSUE TITLE
Enhancement Request - Ability to Have BuildStages for Optional parameters in Staged Builder

### ISSUE THREAD

**Issue by David-16** [immutables/immutables#1373]
First of all, I honestly and greatly appreciate this library and your continued support

I use Immutables for the database and middleware layers.  Almost immediately, these two layers diverge and so I have two different (but very similar) Immutables and translate between them

Life is good until someone wants to add something.  In order to remain backward compatible, anything new must be `Optional` or `Nullable`.  I use staged builders for type safety and so these new parameters are obviously not required

The problem is that each time something is added, I have to find each instance of where I translate between the Immutables and make sure to copy this `Optional` or `Nullable` parameter.  This is error prone since it is not caught at compile time

After reading some open issues, I found wildcards make Optional lose their special status:
```
@SuppressWarnings("immutables:untype")
Optional<? extends String> getFoobar();
```

I tried this but then json deserialization breaks in the backward compatibility case because it cannot create the Immutable object since 'foobar' is a required parameter as far as it is concerned because it lost its special default status.  Maybe there is a way to hook into this deserialization process and feed it the default value if missing

It is a bit of an oxymoron, I know.  And it is a bit niche which is strike two.  But, the ask is the ability to make some or all `Optional` or `@Nullable` properties have their own `BuildStage` instead of all going to the `BuildFinal`.  A super-pedantic builder if you will.  This would give type safety when copying from one business object to another when a new property is added.  All other behavior regarding `Optional` or `@Nullable` stays the same

**Comment by elucash** [comment]
Thank you for the request. I'm reading and try to digest. Seems that I got a lot of it, but need to think on this a bit more. In the meantime, I'm thinking if any workarounds available, in particular for the serialization problem. What if making optional a default attribute might help anything.

```java
@Value.Default default Optional<? extends String> getFoobar() {
   return Optional.empty();
}
```

**Comment by David-16** [comment]
`@Default` puts it into the `BuildFinal` of the staged builder with all the other `Optional` and `@Nullable` parameters.  My desire is for it to have its own `BuildStage` like a required parameter such that existing usages of the staged builder will fail at compile time and have to deal with the addition of the new property even though it is not required for deserialization

This could probably be solved strictly from the Jackson perspective by hooking into their deserialization methods (or maybe extending/shadowing the one generated by Immutables?), but I would rather avoid writing custom deserializers for every class

**Comment by dsinghvi** [comment]
+1 That would be great -- it would be great to create a compile break after adding optional fields

**Comment by David-16** [comment]
To clarify, let's say we have a `Person`:
```
@Value.Immutable
@Value.Style(stagedBuilder = true, ....)
interface Person {
  String getFirstName();
  String getLastName();
}
```

Now, someone wants to add a middle name:
```
@Value.Immutable
@Value.Style(stagedBuilder = true, ....)
interface Person {
  String getFirstName();
  @Value.RequiredOptional Optional<String> getMiddleName();
  String getLastName();
}
```


Current behavior is:
```
ImmutablePerson.builder().firstName("foo").lastName("bar").build();
ImmutablePerson.builder().firstName("foo").lastName("bar").middleName("baz").build();
```

More pedantically:
```
FirstNameBuildStage firstNameBuildStage = ImmutablePerson.builder();
LastNameBuildStage lastNameBuildStage = firstNameBuildStage.firstName("foo");
BuildFinal buildFinal = lastNameBuildStage.lastName("bar");
BuildFinal buildFinal2 = buildFinal.middleName("baz");
Person = buildFinal.build();
```

Desired behavior would be:
```
ImmutablePerson.builder().firstName("foo").middleName("baz").lastName("bar").build();
```

More pedantically:
```
FirstNameBuildStage firstNameBuildStage = ImmutablePerson.builder();
MiddleNameBuildStage middleNameBuildStage = firstNameBuildStage.firstName("foo");
LastNameBuildStage lastNameBuildStage = middleNameBuildStage.middleName("baz");
// OR LastNameBuildStage lastNameBuildStage = middleNameBuildStage.middleName(Optional.empty());
BuildFinal buildFinal = lastNameBuildStage.lastName("bar");
Person = buildFinal.build();
```

The idea is to maintain serialize/deserialize API compatibility while requiring consumers to acknowledge the existence of 'middleName' via the Java API when constructing new ones

Again, I understand this seemingly contradicts the purpose of 'Optional', but we have a couple places where we copy Immutables from one container to another where the APIs are basically the same but slightly different.  E.g., one system might have a person that is almost the same but uses `surname` or `family name` or whatever instead.  When one `Person` or the other adds 'middle name' as an Optional (and it generally has to be Optional to maintain serialize/deserialize compatibility), we have to rely on human communication to say 'update your copy constructors or equivalent APIs to potentially include middle name if you also have that field' which is error prone

**Comment by David-16** [comment]
Closing stale issue

**Comment by elucash** [comment]
Sorry, I'm missed to follow up on this. Need to restore context on this. If not for this enhancement, but maybe we can extract some good points / add at least some of the needed functionality.
