### ISSUE TITLE
Question: Why are attributes of type `ImmutableSortedSet` required to build an Immutable?

### ISSUE THREAD

**Issue by ferdinand-swoboda** [immutables/immutables#1378]
With a class like 

```java
@Value.Immutable
public interface Tada {
    ImmutableSortedSet<String> sortedSet();

    ImmutableSet<String> set();
}
```

Following 
> There's no need to use @Value.Default to return empty collections as collection attributes are empty by default if not initialized.

and 

> When building using builders, the contents of collection attributes can be left unspecified.

from the documentation, I expected all these calls to succeed i.e. `set` and `sortedSet` to default to empty sets (with natural comparator for the sorted set):
```java
ImmutableTada.builder().build();
ImmutableTada.builder().sortedSet(ImmutableSortedSet.of()).build();
ImmutableTada.builder().addSet("test").build();
```

This behaviour can be achieved by declaring a default value
```java
    @Value.Default
    default ImmutableSortedSet<String> sortedSet() {
        return ImmutableSortedSet.of();
    }
}
```
or using `@Value.NaturalOrder`/`@Value.ReverseOrder` on `sortedSet`.

Why is this not the default behaviour? Intuitively, I'm assuming that an empty, immutable sorted set's comparator is irrelevant and can thus default to `Comparator.naturalOrder()`

Apologies in advance if I missed the answer in one of the other issues.

Thank you

**Comment by ferdinand-swoboda** [comment]
A caveat and possible answer is that defaulting to `ImmutableSortedSet.of()` would also mean implicitly defaulting the set's comparator to `ImmutableSortedSet.naturalOrder()` which might not be a compatible or intuitive change, especially if the set is part of a nested collection with sibling sets that have `ImmutableSortedSet.reverseOrder()`.

In the context of Jackson the following test case courtesy of @Stephan202 exemplifies this:

```
final class DummyTest {
  @Value.Immutable
  interface DummyInterface {
    @Value.Default
    default ImmutableSortedSet<String> strings() {
      return ImmutableSortedSet.of();
    }
  }

  @Test
  void deserializationRoundTrip() throws JsonProcessingException {
    ObjectMapper objectMapper = new ObjectMapper().registerModule(new GuavaModule());

    Dummy dto = Dummy.of(ImmutableSortedSet.<String>reverseOrder().add("a", "b").build());
    String json = objectMapper.writeValueAsString(dto);
    Dummy newDto = objectMapper.readValue(json, Dummy.class);
    assertThat(newDto.strings()).containsExactlyElementsOf(dto.strings());
  }
}
```

**Comment by elucash** [comment]
Have you tried to use `@Value.NaturalOrder` (or `@Value.ReverseOrder`) on `SortedSet`, this will turn it into what you expect from regular `Set` in terms of building etc. This is because annotation explicitly express ordering, there's some mention here https://immutables.github.io/immutable.html#array-collection-and-map-attributes

**Comment by ferdinand-swoboda** [comment]
> Have you tried to use `@Value.NaturalOrder` (or `@Value.ReverseOrder`) on `SortedSet`?

Indeed, this works as expected & documented. My question resulted from a seemingly inconsistent behaviour when deserializing Immutables with missing sorted sets: `ImmutableSet`s default to an empty set whereas `ImmutableSortedSet`s don't. 
I now understand that defaulting to `ImmutableSorted.of()` would also impact its comparator in subtle ways that makes this not suitable for broader usage.
