### ISSUE TITLE
InjectAnnotation should allow injecting annotation on factory method

### ISSUE THREAD

**Issue by Adrodoc** [immutables/immutables#1388]
`@InjectAnnotation` can be used to place an annotation on the constructor of the immutable type using `target = Where.CONSTRUCTOR`. This is great, but it requires me to use `@Value.Style(of = "new")` which in turn prevents me from using [normalization](https://immutables.github.io/immutable.html#normalization):
>Interning, singleton and validation will not work correctly with 'new' constructor configured in style

It would be great if the Annotation would be placed on the static factory method when no public constructor is generated or if there was something like a `Where.FACTORY_METHOD` that could be used instead of `Where.CONSTRUCTOR` in such a case.

**Comment by elucash** [comment]
sorry for very delayed response. I've just reviewed the templates and it seems that we inject `Where.CONSTRUCTOR` annotations onto factory methods if bare constructor is not used. Trying to implement smth like `Where.FACTORY` I'm anxious to break compatibility if anyone already uses constructor annotations on those factory methods, but it may be that it works differently than I think it is. Can you provide a case where `CONSTRUCTOR` annotation is not applied on the factory method?

**Comment by Adrodoc** [comment]
Interesting, I will try to give you a minimal reproducer next week.

**Comment by Adrodoc** [comment]
I created this reproducer: https://github.com/Adrodoc/immutables-1388

As you can see the generated `ImmutableSomeObject` does not have any annotation on it's `of(String)` method.

**Comment by elucash** [comment]
Thank you for the repro! I've nailed the issue, there were couple of more factory method templates for special cases, so this is fixed by including injected annotations there too. This will go into release later this week or next week.
Btw we have similar functionality to that pojo builder annotation: https://immutables.github.io/factory.html

**Comment by Adrodoc** [comment]
Thank you for the fix :)
I know about your builders (though I didn't know of your Factory builders which look very cool), however we use PojoBuilder for Testdata generation and your builders crucially miss support for the [nested builder pattern](https://github.com/mkarneim/pojobuilder/wiki/Using-builders-within-builders) which is essential for our DSL: https://github.com/mkarneim/pojobuilder/wiki/Domain-specific-language

**Comment by elucash** [comment]
Interesting. We actually have some nested builder functionality, maybe it's a bit obscure feature and can be improved.

```java
@Value.Style(attributeBuilderDetection = true)
public interface Builders {

  @Value.Immutable
  interface Abc {
    int a();
    boolean b();
    String c();
  }

  @Value.Immutable
  interface Xyz {
    Abc one();
    Abc two();
  }

  static void main(String... args) {
    var b = ImmutableXyz.builder()
        .oneBuilder(ImmutableAbc.builder()  // passing builder
          .a(2)
          .b(false)
          .c(""));

    b.twoBuilder()   // using internal builder
        .a(1)
        .b(true);

    b.build();
  }
}
```

**Comment by Adrodoc** [comment]
Interesting, apparently there is no documentation on your site: https://www.google.com/search?q=attributeBuilderDetection+site%3Aimmutables.github.io
The main thing that looks to be missing for your builders is the option to declare a builder interface which is important to supply custom Builders that can build `Abc` objects. Also we need to be able to supply builders for primitives (int, boolean, String, ...). I think those two would be the most important for test data generation, but we use just about every feature that PojoBuilder offers, so it's unlikely for us to switch :)

**Comment by elucash** [comment]
Yep, that feature was experimental and, arguably, not well polished and not documented to not "advertise" it. There were plans to implement more solid support for "nested" builders if there would be more interest/demand. Being locked into features of the library is understandable, we also have a number of unique feature making migrating off Immutables "difficult", the same is about unique features and advantages of PojoBuilder, etc. So here I've actually tried to get some feedback and, probably, received my answers. I'll release the fix over weekend, thank you!

**Comment by Adrodoc** [comment]
You are welcome and thank you for the quick fix. I look forward to removing all the methods that are annotated with `@GeneratePojoBuilder` and simply delegate to the generated of methods :)

**Comment by Adrodoc** [comment]
@elucash Do you know yet when 2.9.3 will be released?

**Comment by elucash** [comment]
I'm still sitting on a slow internet (2 bars mobile) and releasing and checking the release is a bit of a torture. Basically, will be released as soon as I can.

**Comment by Adrodoc** [comment]
Just a small reminder: I still look forward to the release 😉

**Comment by elucash** [comment]
2.9.3 released

**Comment by Adrodoc** [comment]
Thank you very much for the fix. I tried to use this in my project, but there is an unfortunate combination of factors that prevent me from doing so.

The problem I am having is that I have a type with a collection (`ImmutableList`). This causes the generated immutable to have two "of" methods, one with an `ImmutableList` parameter and one with an `Iterable` parameter. The `GeneratePojoBuilder` annotation is injected on both of methods.
This is a problem for me because only one pojobuilder can be generated for the type and as it turns out (at least in the eclipse compiler) it is random which "of" method wins. So somethimes I get a pojobuilder which can take any Iterable and sometimes I get a pojobuilder that can only take an ImmutableList. I always need a pojobuilder which can take any Iterable.

I am wondering: why is an "of" method with parameter type of ImmutableList generated in the first place? Why would I ever call that method?
Could you maybe add an option to suppress generation of this method?

Should I open a new ticket for that?

# Example

```java
import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.RetentionPolicy.SOURCE;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import org.immutables.annotate.InjectAnnotation;
import org.immutables.annotate.InjectAnnotation.Where;
import org.immutables.value.Value;
import net.karneim.pojobuilder.GeneratePojoBuilder;

@Retention(SOURCE)
@Target(TYPE)
@Value.Style(allParameters = true)
@InjectAnnotation(type = GeneratePojoBuilder.class, target = Where.CONSTRUCTOR)
public @interface MyStyle {}
```
```java
import org.immutables.value.Value;
import com.google.common.collect.ImmutableList;

@Value.Immutable
@MyStyle
public interface Order {
  ImmutableList<ImmutableItem> items();
}
```
```java
package de.sanacorp.zar.api.aef.v4;

import org.immutables.value.Value;

@Value.Immutable
@MyStyle
public interface Item {
  String name();
}
```
"of" methods of generated immutable (I'd like to suppress generation of the first one, which seems useless to me anyways):
```java
  /**
   * Construct a new immutable {@code Order} instance.
   * @param items The value for the {@code items} attribute
   * @return An immutable Order instance
   */
  @GeneratePojoBuilder
  public static ImmutableOrder of(ImmutableList<ImmutableItem> items) {
    return of((Iterable<? extends ImmutableItem>) items);
  }

  /**
   * Construct a new immutable {@code Order} instance.
   * @param items The value for the {@code items} attribute
   * @return An immutable Order instance
   */
  @GeneratePojoBuilder
  public static ImmutableOrder of(Iterable<? extends ImmutableItem> items) {
    return new ImmutableOrder(items);
  }
```
