### ISSUE TITLE
Make Style.passAnnotations also handle attribute level annotations

### ISSUE THREAD

**Issue by augustotravillio** [immutables/immutables#139]
It is not fully safe to copy all attribute level annotations are not safe as it is not always safe with type level annotations (as was mentioned in #26). The effect of passAnnotations style will be expanded to also handle whitelist of attribute level annotations. In order to preserve compatibility for major use case, we will copy `com.fasterxml.jackson.annotations.*` by default.

**Comment by elucash** [comment]
went into 2.0.17
