### ISSUE TITLE
where is org.immutables:builder-annotations?

### ISSUE THREAD

**Issue by bmarwell** [immutables/immutables#1396]
Hi,

there is value-annotations, but I cannot find builder-annotations.
This would be useful for maven and gradle builds, as we would not need to import too much classes we do not actually need.

**Comment by elucash** [comment]
`org.immutables.builder` module is annotation only module, you don't need to look for `-annotations`. Additional classes there are only test classes, the implementation resides the codebase of the main processor `org.immutables:value-processor`

**Comment by bmarwell** [comment]
Thanks! Will close then.
