### ISSUE TITLE
com.google.gson.TypeAdapterFactory is missing if incremental compile is active

### ISSUE THREAD

**Issue by cheorges** [immutables/immutables#1399]
Hello together
Maybe I do not understand the behavior correctly, please correct me.

However, I have noticed that from version > 2.7.4 the `com.google.gson.TypeAdapterFactory` is no longer created if the annotation processor argument `immutables.gradle.incremental` is set.
Current version of gradle is 7.4.2.

This means that as soon as incremental compile is activated the `GsonAdapter*` must be loaded manual and it is not possible by using `java.util.ServiceLoader`.

```java
// Does not work with incremental compile, because the META-INF/services/ is no longer generated
for (TypeAdapterFactory factory : ServiceLoader.load(TypeAdapterFactory.class)) {
  gsonBuilder.registerTypeAdapterFactory(factory);
}

// Manual registration is required if incremental compile is active
gsonBuilder.registerTypeAdapterFactory(new GsonAdaptersMyDocument());
```

Best

**Comment by elucash** [comment]
this seems to be a "feature" of incremental compilation. The meta-inf file is generated for the whole module, one file for all type adapters in the module. If only one file is recompiled/one type adapter regenerated, the file cannot be updated, moreover - creating/writing resources are suppressed in incremental mode (as opposed to creating generated source files). To get meta-inf file generated you'll need to disable incremental compilation, and that is what you've probably tried to avoid. The alternative for you can be writing your own auto discovery routines using reflection: scanning classpath,  loading and instantiating classes matching filename mask. At some point we've just decided to left out such functionality, it is an overkill for us to maintain such speculative / custom routines.

**Comment by cheorges** [comment]
Thank you for the detailed response. I agree that this is overkill to implement this functionality, since the adapters can be loaded manually.
