### ISSUE TITLE
tag missing problem

### ISSUE THREAD

**Issue by CChengjie** [immutables/immutables#1400]
I'm doing a research on tags .
We found that versions like **2.8.6**、**2.8.9**、**2.8.6**、**2.9.0** was released in Maven, but there was no corresponding tag in github, Can you help me with this?
1）What is the reason for tag's absence?（Related commit messages are found.）

- a、This version code has problems, such as the loophole, compatibility and interface issues, etc.
- b、This version has functional problems, such as unreasonable function planning, basic function cannot be used
- c、Forgot to tag
- d、Don't care or is too trouble
- e、others，_

2） To solve this problem, we propose a method that can find the true commit of version to help developers quickly locate the problem code and fix the bug. Here are the possible true commits given by our method. Can you confirm whether or not the actual commits are included, and if not, which ones?
**2.8.6**
['e2e11cf2f14f20e8a9e2124e1940323e519ccaf3']
**2.8.9**
['7651b2d0bee1447b42ecb135438f76a454d62e32']
**2.9.0**
['434eba18d1f1747dc2ce8fea661cc3eb430a49e6']

Also, i am not sure the commit id of 2.8.9-ea-1 and 2.8.9-ea-0.

♥ This question is very important to our research. Thank you for your time!

**Comment by elucash** [comment]
hey people, this is open source, it's free under condition of the license. no need to spy with bots
