### ISSUE TITLE
Cyclic inheritance on nested builder when using @Enclosing and overshadowing = true

### ISSUE THREAD

**Issue by cameronprater** [immutables/immutables#1402]
Hi, I've encountered an issue when using `@Enclosing` and `@Immutable(overshadowing = true)` on a top-level class with nested classes who also have nested classes (`Foo.Bar.Baz`). Builders are defined for each class that extend from the generated immutable builders. The builders are generated correctly when the level of nesting doesn't exceed 1 (e.g. `Foo.Bar`), but when the level of nesting reaches 2 (e.g. `Foo.Bar.Baz`), the generated builder extends from the builder I defined and introduces a cyclic dependency. So, I have a builder that extends from the generated builder, but the generated builder also extends from the builder I defined for some reason. 

Let me know if you need any more details.

**Comment by elucash** [comment]
Thank you for reporting this. I've used current snapshot (after 2.9.1 release) with the following code:

```
@Value.Enclosing
@Value.Style(overshadowImplementation = true)
public class EnclosingOvershadow {
  @Value.Immutable
  interface Foo {
    int a();
    class Builder extends ImmutableEnclosingOvershadow.Foo.Builder {}
    @Value.Immutable
    interface Bar {
      int b();
      class Builder extends ImmutableEnclosingOvershadow.Bar.Builder {}
      @Value.Immutable
      interface Baz {
        int c();
        class Builder extends ImmutableEnclosingOvershadow.Baz.Builder {}
      }
    }
  }
}
```

I was unable to reproduce any cyclic inheritance. Can you nail down the exact case or create a minimal repro, maybe check the latest version (2.9.1)?

**Comment by cameronprater** [comment]
Ah, I'm also using a custom annotation annotation which seems to be the missing piece. You can find a reproducible example [here](https://github.com/cameronprater/immutables-bug).

**Comment by cameronprater** [comment]
You can find a reproducible example [here](https://github.com/cameronprater/immutables-bug). I'm using a custom annotation.

**Comment by elucash** [comment]
Thank you for the repro, it seems that I know what the issue is. So when using enclosing generation, all nested classes are generated inside top level class. You will have 

```
Foo -> ImmutableFoo
Foo.Bar -> ImmutableFoo.Bar
Foo.Bar.Baz -> ImmutableFoo.Baz  // but not ImmutableFoo.Bar.Baz
```

In you repro, you need to use `class Builder extends ImmutableFoo.Baz.Builder {` for it to compile. Hope this will solve the issue.

**Comment by cameronprater** [comment]
That fixed my issue. Thanks!
