### ISSUE TITLE
Staged builder breaks jackson deserialization of nullable fields

### ISSUE THREAD

**Issue by SimY4** [immutables/immutables#1407]
Consider an entity definition:

```
@Value.Immutable
@Value.Style(stagedBuilder = true)
@JsonDeserialize(as = ImmutableEntity.class)
public interface Entity {
  @Value.Default
  default String getNullableDefault() {
    return "default";
  }
}
```

and a JSON string: `{"nullableDefault":null}`

This would fail jackson deserialisation with:

```
Can not construct instance of org.immutables.fixture.jackson.ImmutableEntity, problem: nullableDefault
 at [Source: {"nullableDefault":null}; line: 1, column: 40]
	at org.immutables.fixture.jackson.ObjectMappedTest.jsonNullableWithDefault(ObjectMappedTest.java:252)
Caused by: java.lang.NullPointerException: nullableDefault
	at org.immutables.fixture.jackson.ObjectMappedTest.jsonNullableWithDefault(ObjectMappedTest.java:252)
```

If you remove `@Value.Style` serialization works as expected.

**Comment by elucash** [comment]
Thank you for reporting this. It's hard to dig every feature combination, especially with quite complex Jackson mapping. Here I would ask for help, If staged builder is involved then how it exactly affects Jackson so it doesn't work? One can, for example, take the generated code and out it into a source folder, remove `@Value.Immutable` annotation and try to fiddle / debug the code to find out what causes the problem.
