### ISSUE TITLE
Feature request: Generate update(UnaryOperator)-methods along withers (new style flag?)

### ISSUE THREAD

**Issue by ajkettun** [immutables/immutables#1408]
Currently transforming Immutables-generated objects requires to write rather clumsy code.
```
immutableBar.withFoo(doSomeTransformation(immutableBar.getFoo()))
```
And it gets worse with nested objects.

Simple improvement could be if Immutables would generate update-methods along with withers to allow transforming nested objects more cleanly. Basic update-method signature for a `String foo`-property in ImmutableBar -class would be:
```
ImmutableBar updateFoo(UnaryFunction<String> updater);
```
Which would allow to write:
```
immutableBar.updateFoo(foo -> ...)
```
Or if the `foo`-property would be another immutables -generated object instead of String:
```
immutableBar.updateFoo(foo -> foo.updateSomeOtherField(someOtherField -> ... ))
```
Currently updaters can be written by hand to the template class / interface if needed, but I see no reason why they could not be generated.

Also Optional (and Vavr Option etc.) could be taken account and offer an updater method which would transform the value only if it is present but this feature is not a must.

Chaining and doing this for multiple fields is of course inefficient but nothing prevents abusing withers in the same way.

**Comment by ajkettun** [comment]
That was fast! Thank you! 

Hopefully records get withers some day and they creep up to regular immutable classes too:

https://github.com/openjdk/amber-docs/blob/master/eg-drafts/reconstruction-records-and-classes.md

**Comment by elucash** [comment]
yep, all good stuff comes to java only if you don't wait for it ;)
