### ISSUE TITLE
Crash on constant in enum value annotation param

### ISSUE THREAD

**Issue by bjoernhype** [immutables/immutables#1411]
If there exists in the java project an enum with a value with annotation with a parameter which is a constant defined in the enum, the whole immutable generating process doesn't generate anything.

Example:
```
public enum MyEnum {
    @SuppressWarnings(UNCHECKED)
    VAL;

    public static final String UNCHECKED = "unchecked";
}
```
breaks, but
```
public enum MyEnum {
    @SuppressWarnings("unchecked")
    VAL;

    public static final String UNCHECKED = "unchecked";
}
```
works fine.

The plain existence of that enum brings immutables to crash, even it is used nowhere.

Reproduced in 2.8.2 and current 2.9.2

**Comment by elucash** [comment]
Thank you for reporting this. Can you create a minimal repro? When I just added this code – nothing bad happened, everything seems to work fine.

**Comment by bjoernhype** [comment]
Thanks for your response.
I spend some time shrinking my complex scenario to a simple example project, and doing this came to the point that Immutables is not involved here:
I now have a simple project with Java, Gradle & IntelliJ IDEA, with the given example (above), and without Immutables. It is fine without error or warning in IntelliJ IDEA, but throws an "error: illegal forward reference" during gradle compileJava. Strange & inconsistent, but not related to Immutables, which seems to have crashed only because of that.
So I'm closing this ticket.
Thanks for investigating this
