### ISSUE TITLE
Extract Strings as constants in generated class 

### ISSUE THREAD

**Issue by rtatton** [immutables/immutables#1413]
Would it be possible to refactor how the immutable classes are generated such that the Strings that mirror the names of the getters are generated and subsequently used as String constants? This memory optimization would be particularly helpful for objects that are instantiated many times.

It would be even more convenient if the developer could define these themselves as non-private class constants in case they wanted to use them, say, in the method that is annotated with `@Value.Check`. This is similar to how developers can define a Builder interface in the class if they want to hide the generated implementation; all that is needed is for the naming to match what the generated code.

Hopefully this feature request makes sense; but just in case it's not, here is a simple example.

**Current implementation**
```
@Value.Immutable
abstract class Person {

    protected static final NAME = "name"

    String name();

    @Value.Check
    protected void check() {
        if (name().length() < 2) {
            throw new IllegalArgumentException();
        }
    }
}

public final class ImmutablePerson implements Person {

    private final String name;

    private ImmutablePerson(String name) {
        this.name = Objects.requireNonNull(name, "name");
    }
    ...
}
```

**Requested implementation**
```
public final class ImmutablePerson extends Person {
    private final String name;

    private ImmutablePerson(String name) {
        // Reuse non-private String constant in the abstract class
        // or define in this class, if it's not already defined.
        this.name = Objects.requireNonNull(name, NAME);
    }
    ...
}
```

**Comment by elucash** [comment]
Hi, thank you for the request. However, I'm not sure what you're interested in. If it's about optimization, then, I think this is not a problem, as you know, all constant string literals are _interned_ and refer to the same object which instantiated only once (You can check that ` "abc"  ==  "abc"` is always `true`.

But if you need to have constants with names for attributes generated, then there's experimental (and barely documented, sorry) module `data` (`org.immutables:data`) where `@Data` annotation generates a meta-class (`Datatypes_*`) with goodies like constants, reflection-like attributes and builders.

**Comment by rtatton** [comment]
Thank you for the incredibly fast response. Perhaps I do not actually understand Java String interning. So what you're saying is that Java automatically interns String constants? I thought that if I wanted to achieve this inside a class, I needed to store them as static, final fields. Are you saying that if I just use them in-line (like how Immutables uses them in the generated class), then Java will intern them for me?

**Comment by rtatton** [comment]
Wow. Well, I guess I just misread the Javadoc. This is, in fact, the case. Java is smarter than I thought. From the `intern()` JavaDoc ([source](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html)):

> All literal strings and string-valued constant expressions are interned

@elucash Thank you anyway for pointing this out and allowing me to safely make my code less verbose without any loss in performance. As this optimization was my main concern, I'm going to close this issue.

**Comment by elucash** [comment]
@rtatton you're welcome. Just to mention, in a generated code we're less not concerned about making typo as we derive names programmatically and code is quite readable, but in regular code written by programmer, sometimes it makes sense to use constants just to avoid typos (and not for optimization): if you misspell `NAMED` constant as `NAMES`, the compiler will hopefully tell you "symbol not found", but if `"named"` or `"names"` will be mistyped it can lead to bugs somewhere later in runtime.
