### ISSUE TITLE
Nullable optional fields

### ISSUE THREAD

**Issue by cameronprater** [immutables/immutables#1430]
If I wanted to go about maintaining a fork to allow optional fields to be explicitly set to null (for serialization purposes), where in the code should I look to achieve this? Use case is like in #1127 and #1214, I have optional and nullable API fields and only want to serialize an `Optional` field if the `Optional` reference itself is null or if the `Optional` reference is not null and its value is not null.

Basically, I just want to disable the non-null check for optional fields and only generate builder methods that accept an `Optional` rather than generating both the `Optional` and value type setters. Then the serialization of my nullable optional field can be customized with `@JsonInclude(value = Include.ALWAYS, content = Include.NON_NULL)`. Ideally, the `Optional` reference would always be non-null when deserialized even if the field itself is nullable and optional, but not sure how I would achieve this.

Maybe there's a need for a `Style` option to achieve this?

**Comment by elucash** [comment]
It's really hard to understand without JSON and object (either POJO / Immutables) examples.
AFAIK you cannot construct `java.util.Optional` with `null` inside, and I assume you want to use `java.util.Optional`, otherwise you would let us know that.

```java
@Nullable Optional<T> opt();
```
Wouldn't this work? Any difference to public field with an optional  concerning Jackson-bind setup?

JFYI, if I would want some trickery in serializing these kinds of values, I would seriously think of creating special type and have custom serializer for it. I'm thinking of something like `Option {  Null | Empty | Present(value)  }` (in pseudocode) which would have conversion methods from optional/nullable and `toOptional()`

**Comment by cameronprater** [comment]
I believe `@Nullable Optional<T>` would work but the behavior I desired was slightly different than what would be generated by Immutables using this case. You can construct `Optional` with null using `Optional.ofNullable`, but you're right that the custom type approach is what I was looking for. I've just finished creating a `NullableOptional` class and figured out how to serialize the three different cases with Jackson, now I just have to look into encodings to handle it on the Immutables side (I don't want to have `@Nullable NullableOptional<?> foo()` or `Optional<NullableOptional<?>> foo()` because I think that would be redundant

**Comment by elucash** [comment]
Yes, having a default value is something that can be specific to a type encoding. Most custom collection encodings use this to default to an empty collection. Moreover, I suspect that annotation (@Nullable/@Default etc) combinations might don't even work for encoded types)

**Comment by elucash** [comment]
```java
@Encoding
class OptionEncoding<T> {
  @Encoding.Impl
  private Option<T> field = Option.none();   //  <--  ! here, we `=` default value. `Option.none()` expression will
  // be inserted into generated code to initialize value if it's not set

  // if you specify one of the copy methods, the default one is not longer generated
  // so you need to declare both alternative methods
  @Encoding.Copy
  public Option<T> withOption(Option<T> value) {
    return Objects.requireNonNull(value); // insert any checks necessary
  }

  @Encoding.Copy
  public Option<T> with(T value) {
    return Option.some(value); // insert any checks necessary
  }
}
```

**Comment by cameronprater** [comment]
Thanks!
