### ISSUE TITLE
How to build locally?

### ISSUE THREAD

**Issue by cameronprater** [immutables/immutables#1435]
I've added a few `Style` options in my fork (not sure whether I should PR them) and am trying to test that they work correctly, but I can't get the project to build as the generated sources directory is outputting malformed code even on the `master` branch (without my changes). I'm running `mvn clean install` and even tried specifying the options run in CI with `mvn clean install -Pjavac -Dextra=errorprone` and tried skipping tests as well with `-DskipTests`, but my build continues to fail: 
![image](https://user-images.githubusercontent.com/40479627/213982926-0cd38f50-e4c0-46ee-ad36-046a8eded2e5.png)

What am I missing?

**Comment by elucash** [comment]
it builds on CI and locally. Is this Intellij - specific issue?
<img width="353" alt="Screen Shot 2023-01-23 at 11 06 29 AM" src="https://user-images.githubusercontent.com/1692611/214088847-f6892e7f-c02e-4c2b-83cd-8df068fe3b58.png">

**Comment by cameronprater** [comment]
I tried running it without IntelliJ's bundled Maven and the same issue happens

**Comment by cameronprater** [comment]
Since I can't build locally for some reason, I'm just attempting to run tests in CI. I'm having an issue with one of my styles which you can find here: 
https://github.com/cameronprater/immutables/pull/3/files

How would I modify the Immutables generator to achieve this?

**Comment by cameronprater** [comment]
What is the maintainers' approach on `Style` options? The options I've added seem like they are niche and not many users would need or use them, so I'm not sure if it would be a good idea to PR them into the main repository. Then again, if the approach is to support as many different configurations as possible, it might be a good idea to have these in the main repository nonetheless. Either way, I will need to find some way to build locally so I can use them in my own project. 😕

WDYT?

**Comment by elucash** [comment]
_Will try to provide meaningful answer soon, sorry for late responses_

**Comment by cameronprater** [comment]
Closing since I found a workaround, however I strongly suspect there is an issue with compiler compatibility/Maven setup in the build since the project relies heavily on the Eclipse compiler
