### ISSUE TITLE
Default attributes not recalculated when using wither methods

### ISSUE THREAD

**Issue by MGafitescu** [immutables/immutables#1438]
This issue is similar with  #106

Back then, it was acknowledged that this was an issue for both derived and default attributes and that issue was fixes in the  2.0.10 release for derived attributes. For default attributes, at that moment, it was considered ok not to be recalculated and I agree that back then it didn't constitute a problem.

Since then however, support for using other default or derived attributes in the initializer method of a default attribute was introduced. (Quoting from [documentation](https://immutables.github.io/immutable.html#default-attributes): "Since version 2.1, a default attribute initializer method’s body can refer to other default or derived attributes as long as this does not introduce initialization cycles.")

Because of this change of behaviour, I think default attributes not being recalculated when using with* methods is a bug nowadays.

In order to better explain the problem I faced I can provide some code that doesn't work as expected.

```

import org.immutables.value.Value;

@Value.Immutable
public abstract class CandyShop {
    public abstract String getCandyType();

    public abstract int getQuantity();

    @Value.Default
    public String getShopDescription() {
        return "This shop sells " + getQuantity() + " " + getCandyType() + " candies";
    }
}
```

```

public class CandyShopBehaviour {
    public static void main(String[] args) {
        CandyShop candyShop = ImmutableCandyShop.builder()
                .candyType("chocolate")
                .quantity(2)
                .build();

        System.out.println(candyShop.getShopDescription());
        //This prints "This shop sells 2 chocolate candies"

        CandyShop secondaryCandyShop = ImmutableCandyShop.copyOf(candyShop)
                .withCandyType("gummy bear");

        System.out.println(secondaryCandyShop.getShopDescription());
        // This prints "This shop sells 2 chocolate candies" as well
        // I would expect this to print "This shop sells 2 gummy bear candies"
        // I never initialized the shopDescription field for secondayCandyShop object so I would expect the field to return what the initializer method calculates, not have a default value copied from the original candyShop object
    }
}
```

**Comment by elucash** [comment]
It's a difference in how we could understand the semantic of the default value. In my view, current behavior is perfectly valid, we apply default value if one is _not_ provided during construction and store it. In case of `with*` copy the value is there, we should copy it. What can help? A specialized copy routine where you cherry pick what you copy or a change in how you define attributes. For the use case shown, I would use something like this

```java
@Value.Immutable
public abstract class CandyShop {
    public abstract String getCandyType();

    public abstract int getQuantity();

    public Optional<String> getCustomDescription();

    @Value.Derived // could be also regular method, also @Value.Auxiliary might be useful here
    public String getShopDescription() {
        return getCustomDescription()
            .orElseGet(() -> "This shop sells " + getQuantity() + " " + getCandyType() + " candies");
    }
}
```

For me, the above doesn't look like a workaround, but an accurate representation of the idea.

**Comment by MGafitescu** [comment]
Hi!

Thank you for your prompt reply!
Yes, I agree that I understood a bit different the semantic of the default value as I was expecting the default initializer method to be applied anytime the user does not specifically provide a value, but I can see the logic in considering that the original object is the one providing the value used when copying with a with* method.
Thanks for the code example as well, it's helpful and does what I would need in this specific case!
