### ISSUE TITLE
Way to skip creation of unmodifiable maps, collections and list

### ISSUE THREAD

**Issue by ivansenic** [immutables/immutables#1463]
Having a parameter:

```
  @Value.Parameter
  Map<String, String> map();
```

will as part of the built-in support create `createUnmodifiableMap` method which converts the given map to the unmodifiable one. Is there any way to disable the built-in support. I am already creating the unmodifiable map on my own and there is no need to re-create it.

**Comment by elucash** [comment]
Possible workarounds:
* `Value.Style.builtinContainerAttributes = false` will disable all special support for containers.
* Using encodings (https://immutables.github.io/encoding.html) to override how attribute type is handled 
* `Value.Style.immutableCopyOfRoutines = {CustomRoutines.class}` if I remember correctly, this can be used to override `copyOf` routines in generated code, so `CustomRoutines` can contain, in your case no-op static methods with matching signatures.

**Comment by ivansenic** [comment]
@elucash Thanks, will have a look tomorrow and close this.

**Comment by ivansenic** [comment]
Works, thanks.
