### ISSUE TITLE
StagedBuilder cannot be used with "SandwichStyle"

### ISSUE THREAD

**Issue by dylanbaroody** [immutables/immutables#1465]
We are seeing that if we use the sandwich style described here: https://github.com/immutables/immutables#modern-usage-style-aka-sandwich 

`StagedBuilder` does not work. Is there any way to make this work programatically? It seems like the only way to make a staged builder work is by doing:

`Object object = ImmutableObject.builder().setStage1().setStage2().build()`, which requires exposing the `ImmutableObject` implementation.

**Comment by elucash** [comment]
Staged builder is using generated interfaces per stage, and you cannot avoid using generated types in this case. Just to shuffle things a bit, you can hide (sort-of) the builder class usage. (`Style.builderVisibility`, frankly I don't remember how combination with staged will work for generated stage interfaces), then have some code.

```java
@Immutable interface X {
    int first();
    String secord();

   static FirstStage builder() {
      return ImmutableX.builder();
   }
}

**Comment by dylanbaroody** [comment]
Ok, thank you!
