### ISSUE TITLE
Why does @Value.Derived generate a method with @JsonProperty?

### ISSUE THREAD

**Issue by TheKeveloper** [immutables/immutables#1471]
If I annotate a method with`@Value.Derived`, the generated method in the `Immutable` type includes a `@JsonProperty` annotation, but the same is not true if I annotate a method with `@Value.Lazy`. This feels a bit weird since I would expect `@Value.Lazy` and `@Value.Derived` to behave mostly the same with the exception of when the underlying field is initialized. 

In particular, this can result in weird behavior with code of the following form
```
interface Foo {
  @JsonProperty("bar")
  RawBar rawBar();

  @Value.Derived
  default Bar bar() {
    return cleanRawBar(rawBar()); 
  } 
} 
```

which will generate an `ImmutableFoo` class with two methods that both have the `@JsonProperty("bar")` annotation.

I'm not sure if this behavior is intentional, but if it is, I would be curious to know the rationale behind it? 

If it's not intentional, I would be happy to submit a PR, but wanted to make sure it wasn't breaking some intended behavior. Thank you!

**Comment by elucash** [comment]
A derived attribute is part of the immutable state. Derived attributes can be initialized with some external counter or auto-generated value in the mix. And it stays with the object, is part of the equals/hashCode, as well as a part of JSON serialization. What you can do to achieve what you want?
1. Remove `@Derive` annotation, make it regular(or `default`) method, yes, it will compute cleanRawBar on each invocation, a trade-off
2. Make it `@Lazy`, it will be clear that it's just caching the value
3. Use `@JsonIgnore` annotation to suppress the field in JSON
4. Use `@JsonProperty(*)` to customize names and un-clash JSON fields

**Comment by TheKeveloper** [comment]
Ah I see, I didn't think about derived containing some externally generated value that isn't a pure function of the rest of the values. That makes sense to me. I think this answers my question. Thank you!
