### ISSUE TITLE
Constructor method "of" allows null values

### ISSUE THREAD

**Issue by pawel-marchewka** [immutables/immutables#148]
Hi.

I am using one of the example from documentation about [constructor methods](http://immutables.github.io/immutable.html#constructor-method)

	@Value.Immutable
	public abstract class HostWithPort {
	  @Value.Parameter
	  public abstract String hostname();
	  @Value.Parameter
	  public abstract int port();
	}

If I try something like this

    ImmutableHostWithPort.builder().hostname(null).port(8081).build()

I will get NullPointerException which is expected.

But if I use constructor method "of"

    ImmutableHostWithPort.of(null, 8081);

I can build ImmutableHostWithPort object with null value as hostname and I think this is a bug.

When I open generated code I can see that neither constructor nor "of" method checks for null value.

	private ImmutableHostWithPort(String hostname, int port) {
	  this.hostname = hostname;
	  this.port = port;
	}

	...

	public static com.example.immutablestest.ImmutableHostWithPort of(String hostname, int port) {
	  return new ImmutableHostWithPort(hostname, port);
	}

My environment:
* Immutables 2.0.16
* Android Studio 1.3
* JDK 1.8.0 u51
* Apt 1.6
* No Guava
* minSdkVersion of test project set to 16

**Comment by elucash** [comment]
You're right, this is the bug, probably side effect of constructor "optimization" we've put recently. Thank you for the report!

**Comment by elucash** [comment]
Relates to #120  #147

**Comment by elucash** [comment]
Released in 2.0.17 available on central, thank you!
