### ISSUE TITLE
Initialize a builder from existing instance

### ISSUE THREAD

**Issue by chris-dekker** [immutables/immutables#1517]
Any way I can achieve the following?

```
MyType instance = MyType.of(a, b, c, d, ..., x);
MyType updated = MyType.builder()
  .from(instance) // <-- this
  .a(aa)
  .b(bb)
  .c(cc)
  .build();
```

Right now I can only achieve this by doing this
```
MyType instance = MyType.of(a, b, c, d, ..., x);
MyType updated = instance.withA(aa).withB(bb).withC(cc);
```

But this runs `@Value.Check` after each `withX(..)` call. At best this is inefficient, at worst this creates problems when the intermediate state is not valid.

Being able to initialize a builder from an existing instance would make this much cleaner and reduce boilerplate without having to provide all parameters again.

**Comment by elucash** [comment]
This is standard functionality available out of the box. The only way this might not be available is when builder generation is disabled or strict builder disallows `from` method on builder. Please check `Immutable` annotations and `Style` annotations. Look for things like `builder = false` or `strictBuilder = true` or similar custom attributes.

**Comment by chris-dekker** [comment]
Thank! My bad. Looks like we have `strictBuilder = true` configured.
