### ISSUE TITLE
Querying builders

### ISSUE THREAD

**Issue by HariNairJHUAPL** [immutables/immutables#1524]
I sometimes have a need to know what value I've set for one of the components of the builder.  I can call build() and get the value that way, but it would be nice to be able to query the builder directly.

```
@Value.Immutable
public interface MyClass() {
MyObject object();
}
```

If I want the value of object from the builder I would like to do this:

```
MyClass.Builder builder = ImmutableMyClass.builder().object(object);
MyObject object2 = builder.object();  // rather than builder.build().object();
```

Thanks!

**Comment by elucash** [comment]
There's open request for this #432 (and #234). So far there are no plans of addressing it via builder (maybe in next major version, vaguely, via some plugin), but as mentioned, modifiable classes provide this functionality

**Comment by HariNairJHUAPL** [comment]
Thank you for the references!  I will close this issue.
