### ISSUE TITLE
ServiceLoader filename for moshi is incorrect.

### ISSUE THREAD

**Issue by taichi** [immutables/immutables#160]
current name is `META-INF/services/com.squareup.moshi.JsonAdapter.Factory`
but `JsonAdapter.Factory` is inner class, so correct name is `META-INF/services/com.squareup.moshi.JsonAdapter$Factory`

**Comment by elucash** [comment]
Indeed, thank you for reminding this. I guess I'm too used to annotation processing api using canonical names, so never tried this. Released in 2.0.19
_Note this \[Moshi\] functionality is experimental and subject to change or even removal in later version_

**Comment by taichi** [comment]
thanks for your work!!
