### ISSUE TITLE
Separating out Gson generator.

### ISSUE THREAD

**Issue by digitalbuddha** [immutables/immutables#170]
Chiming in from NY Times.  We've been doing a lot of performance analysis related to gson parsing on android and started seeing a lot of slowdown due to gson doing reflection unless we write out type adapters by hand.  Is it possible to separate out the Gson generator from the rest of the project.  Ideally we'd like to be able to annotate any java model with something and then have type adapters created for it.  Cheers and thank you for your hard work making an awesome project.

**Comment by elucash** [comment]
Thank you for the request. So at this point I think there are low chances to have some sort of absolutely separate processor for Gson. However, I don't see any reason why we cannot expand processor to support additional models, such as struct-like objects (all fields public and mutable) or bean-like objects.

BTW On a JVM, the advantage of generated bindings is [quite marginal](https://github.com/immutables/samples). It is very interesting to know what the difference is on android.

**Comment by digitalbuddha** [comment]
Here are some stats from a trace made of our app startup https://www.nimbledroid.com/play/com.nytimes.android?p=2LB8aGC2wlVVPm#Summary  

1200 ms delay from gson getBoundedField calls. This was parsing a 20kb json file on a nexus 7.

**Comment by digitalbuddha** [comment]
Here is the stack trace. https://www.nimbledroid.com/play/com.nytimes.android?p=2LB8aGC2wlVVPm#ReflectiveTypeAdapterFactory.getBoundFields

You'd have free beer everytime you come to NY if we can use the generator with package private fields or getters/setters.

**Comment by elucash** [comment]
I'm closing this as the amount of work to support arbitrary models is quite significant, but alternative solutions already exist such as [bluelinelabs/LoganSquare](https://github.com/bluelinelabs/LoganSquare) or using _Immutables_ objects with Gson or upcoming Moshi generators. Thank you!
