### ISSUE TITLE
Allow customization of exception thrown when checking required attributes

### ISSUE THREAD

**Issue by leourbina** [immutables/immutables#174]
Currently, after calling `build()` and a required field is not set the exception thrown is always an `IllegalStateException`. It would be useful to customize the class of the exception in order to better integrate with other libraries/frameworks (e.g. automatically transform some specific type of exceptions into 4** vs 5** errors)

**Comment by elucash** [comment]
Thank you for the feature request! I'll see what kind of extensibility we could provide for exception type. This can also include #124.

**Comment by ldriscoll** [comment]
@leourbina this is fixed by #176

**Comment by elucash** [comment]
@ldriscoll @mjball @augustotravillio Just landed (18cf7da) naming template `Style.buildOrThrow` which will serve as feature flag at the same time (enable feature by setting a naming template). Will it be ok to release it in such form?

**Comment by ldriscoll** [comment]
I like it!

**Comment by augustotravillio** [comment]
lgtm

**Comment by elucash** [comment]
Released in 2.1.0
