### ISSUE TITLE
Support for buildPartial() and/or copy methods that accept a Builder instance.

### ISSUE THREAD

**Issue by mjball** [immutables/immutables#177]
I have two builders, and I'd like to merge one into the other. Currently the copy methods (`Foo#copyOf(Foo)` and `Foo.Builder.with(Foo)`) only accept built instances. I can't just call `build()` right before merging, because I've no guarantee that either instance is complete yet. I see two possible ways to solve this, not mutually exclusive with each other:

- Add `copyOf(Foo.Builder)` and `with(Foo.Builder)` overloads, and/or
- Add a [protobuf-like `buildPartial()` method][1], which behaves like `build()`, but does not throw an exception if required fields are missing.

I'm not sure if a `buildPartial()` method introduces too much complexity, since users could end up with an instance that they think is complete, but is not. It's also an indirect solution to my problem, so if I had to pick just one, I'd prefer overloading `copyOf(Foo)` and `with(Foo)`.

Thoughts?

[1]: https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Message.Builder#buildPartial()

**Comment by elucash** [comment]
We are developing (or rather resurrecting) the support for modifiable companion class #130 (see also #138)  It could be used as builder on steroids when you need something like not fully initialized object conforming to abstract value type; need to inspect attributes or query if some attributes is initialized or pass an object around while it is not yet constructed etc. Modifiable companion class will allow copying/merging data from instances of abstract value types, and `toImmutable` conversion. We found that builder usage should be streamlined, mostly one way: no query methods, don't need to pass it around and so on.
You're absolutely right about `buildPartial()` — it's basically dangerous, as it allows to pass around not fully constructed value object.

**Comment by elucash** [comment]
See `Value.Modifiable` instead released in 2.1.0
