### ISSUE TITLE
Ammending Builder forces loss of `.builder()` convenience :(

### ISSUE THREAD

**Issue by prior** [immutables/immutables#178]
Your awesome docs point out that you can adjust the Builder like so:
```
@Value.Immutable
public interface ValueIF {
  boolean getSomething();

  class Builder extends Value.Builder {
    Value build() {
      // some code to normalize object
      return super.build();
    }
  }
```

However, doing so removes the `.builder` static convenience method in the generated `Value` class.  I suppose you do this as a precaution in case the constructor has changed from a no-arg constructor, but I would love it if there was a way for me to choose whether to add it or not.  Ideally you could introspect to know if there is still a no-arg constructor and only remove the static method if there is not.  Or even better a static convenience that mirrored the constructor args.  If there is no way to introspect then maybe there could be some annotation that I could add to tell the code generation to still include it?

@elucash /cc @ldriscoll

**Comment by elucash** [comment]
There was an idea and some discussion about still generating builder method in this case. First of all you're right about issue with additional constructor parameters. There are couple of other arguments why this might not be very useful:
* `Builder` and `builder()` will be both visible but coming from different classes (abstract and immutable) adding to confusion
* It's easy to create manual `builder()` in abstract value type
```java
@Value.Immutable
public interface Val {
  boolean getSomething();
  class Builder extends ImmutableVal.Builder {}
  public static Builder builder() {
    return new Builder();
  }
}
```
* Builder is usually extended if you're going to use abstract value type directly. In this way `Immutable` or whatever prefix is no longer used, you use `Val v = new Val.Builder().....build()`. In this case generated builder would be accessed as `Val.builder()` which will be flagged as warning (indirect static access: no static inheritance, suggesting to use `ImmutableVal.builder()` directly). But if you use reverse style where your abstract value type has suffix `ValueIF` and generated class doesn't. e.g. `Value` then you can have unpleasant mixture of types: `ValueIF.Builder b = Value.builder()`.

What we can do in this situation is one of the following:
* Just generate `builder()` for no-arg builder if generated class visibility is not package-private (the case of non-public/hidden generated class)
* Provide facilities to effectively override/intercept build method while generated builder extends manually written builder (the opposite case where there is no extends specified for `Builder`)
* ...leave as it or something else..

Sorry for the late answer. Thank you for the report!
