### ISSUE TITLE
Make generated builder non-final to enable more customisation

### ISSUE THREAD

**Issue by CRogers** [immutables/immutables#179]
I have the following code:

```java
@Value.Immutable
public abstract class Steps {
    @Value.Parameter protected abstract ImmutableList<Step> steps();
    // other parameters
```

I would like the builder to have an extra method, `Builder addOptionalStep(Optional<Step> step)`. Using the method from the docs doesn't work:

```java
    public static abstract class Builder {
        public abstract Builder addSteps(Step step);

        public Builder addOptionalStep(Optional<Step> step) {
            if (step.isPresent()) {
                addSteps(step.get());
            }

            return this;
        }
    }
```

as now `addOptionalStep()` returns a `Steps.Builder` which doesn't have all the methods we want from the generated builder. The way other libraries like FreeBuilder allow you to customise the builders is by extending them. I would like to be able to do:

```java
    public static class Builder extends ImmutableSteps.Builder {
        public Builder addOptionalStep(Optional<Step> step) {
            if (step.isPresent()) {
                addSteps(step.get());
            }

            return this;
        }
    }
```

but `ImmutableSteps.Builder` is final, so I can't :( Would it be possible to remove the `final` annotations from the generated builder classes/methods to enable this customisation?

**Comment by elucash** [comment]
Actually both ways should work for the use case you outlined. When you extend generated builder, generated builder no longer generated as final, also generated builder' methods return down-casted `Builder` just like one would expect.

```java
import com.google.common.collect.ImmutableList;
import com.google.common.base.Optional;
import org.immutables.value.Value;

interface Step {}

@Value.Immutable
interface StepsExtends {

	ImmutableList<Step> steps();

	public class Builder extends ImmutableStepsExtends.Builder {
		public Builder addStep(Optional<Step> step) {
			if (step.isPresent()) {
				addSteps(step.get());
			}
			return this;
		}
	}
}

@Value.Immutable
interface StepsSuper {

	ImmutableList<Step> steps();

	public class Builder {
		public ImmutableStepsSuper.Builder addStep(Optional<Step> step) {
			ImmutableStepsSuper.Builder builder = (ImmutableStepsSuper.Builder) this;
			if (step.isPresent()) {
				builder.addSteps(step.get());
			}
			return builder;
		}
	}
}
```

There are also have some compilation and unit tests for this functionality [see ExtendingInnerBuilderValue.java test for an example](https://github.com/immutables/immutables/blob/master/value-fixture/src/org/immutables/fixture/ExtendingInnerBuilderValue.java).

Let us know if it's not working for you with some details about compiler version etc if possible.

One of the late addition was making most methods final (to be able only to add methods), but it should be probable relaxed anyway for the next release.

Thank you!

**Comment by CRogers** [comment]
Ok, I managed to make it compile. I had to `git clean -df` then rebuild using IDEA. It complained about the `final` issue even after deleting the generated source sets from inside IDEAf. Weird. Thanks for your help.
