### ISSUE TITLE
The builder.from(interface) is not generated when all interface methods are overridden  

### ISSUE THREAD

**Issue by apara** [immutables/immutables#180]
For example, suppose the interface is defined as:

    public interface Foo {
        int getA();
        int getB();
    }

Immutable is defined as:

    @MyImmutableStyle
    @Value.Immutable
    public abstract class FooImpl implements Foo {
        @Override
        public abstract int getA();

        @Override
        public abstract int getB();
}

Then only a single ImmutableFooImpl.builder().from(FooImpl source) will be generated.  However, if I remove one of the @Override from FooImpl then two builder "from" methods will be generated.

I would like both methods to be always generated as I frequently only have an interface and not an actual immutable in my code.

See https://github.com/apara/immutableTest for runnable example.

**Comment by elucash** [comment]
Thank you! It helped to find and fix wrong logic in determining supetypes/attributes. You can try latest snapshot or wait for the release just around the corner.

**Comment by elucash** [comment]
Released in 2.1.0
