### ISSUE TITLE
Warning: "Avoid introduction of fields (except constants) in abstract value types"

### ISSUE THREAD

**Issue by pushbit** [immutables/immutables#182]
I'm getting the above warning ([src][1]) for a lazily instantiated static field that is used by a method implemented in the abstract class.  Is this warning intended to be shown for static fields?  Why is this warning being given?

[1]: https://github.com/immutables/immutables/blob/master/value-processor/src/org/immutables/value/processor/meta/ValueTypeComposer.java#L204

**Comment by elucash** [comment]
Apparently, it is intended. The question is should we relax this warning for static fields?
Mutable static state could be great source of instability. I got that it is lazy initialized static field, but still not sure if we should remove this warning. As about options, it's possible to silence Immutables' warnings
by using `@SuppressWarnings("immutables")`. Also you could use lazy initialization using other class: either external or internal static class (also could use classloading-based lazy init, quick googling: [.../lazy-loading-singletons.html](http://blog.crazybob.org/2007/01/lazy-loading-singletons.html)). If you have useful observations on that, please share.

**Comment by pushbit** [comment]
Would this be instability of an `@Immutable`?  In this case it is a private field in a `@Modifiable`.  Does that make a difference?  I'm not sure what "instability" means here.  Is the idea that we don't want to create `@Immutable` classes that have fields which could be changed/mutated after an instance is built?

**Comment by elucash** [comment]
yes, "instability" is pretty vague term in this case, sorry. Basically, we warn about mutable state in abstract value type. Of course if you use only `@Value.Modifiable` this makes little sense.
It's probably too defensive way of program but it's still making sense to isolating data types from other concerns like lazy initializations. 
An option could be to not warn if there's no `@Value.Immutable`, and abstract value type only used with `@Value.Modifiable`, for example.

**Comment by elucash** [comment]
relaxed warning to `Value.Modifiable` only objects, for objects having `Value.Immutable` warnings are still relevant. Released in 2.1.0
