### ISSUE TITLE
jdkOnly in meta Style has no effect

### ISSUE THREAD

**Issue by pushbit** [immutables/immutables#184]
I created a meta `Style` with `clearBuilder = true, jdkOnly = true`.  When annotating a class with the meta `Style`, only `clearBuilder` has an effect.  If I directly annotate the class with `Style` and these attributes, then both have an effect.

**Comment by elucash** [comment]
I'll try to reproduce, obviously it should work unless it's a bug. Thank you for the report!

**Comment by pushbit** [comment]
This may be an Eclipse build issue.  I found that changes to meta `Style` attributes do not take effect until Eclipse is restarted.  Now `jdkOnly` in the meta `Style` is having the intended effect.

**Comment by elucash** [comment]
Immutables does aggressive caching of meta-annotation information, it doesn't make any functional difference for the full builds. But in incremental builds lifecycle of the cache(annotation processor) is IDE dependent. We might revise caching, once revised we can document remaining effects. Thank you for the insight!

**Comment by elucash** [comment]
For now I think this is impractical do get rid of the caching or rework it significantly. The potential problems was mentioned in "things to be aware of" on the [style doc page](http://immutables.github.io/style.html#apply-style), so I'm closing the issue. Thank you!
