### ISSUE TITLE
Modifiable* class Javadoc contains @see Immutable* (which may not exist)

### ISSUE THREAD

**Issue by pushbit** [immutables/immutables#186]
Create an abstract class with only `@Modifiable`.  The generated `Modifiable*` class Javadoc contains `@see Immutable*`.  I suppose this should be omitted if an `Immutable*` class is not being generated.

**Comment by elucash** [comment]
Definitely should be fixed. Thanks!

**Comment by elucash** [comment]
Released in 2.1.1
