### ISSUE TITLE
final Modifiable*

### ISSUE THREAD

**Issue by pushbit** [immutables/immutables#188]
I understand the need to have `Immutable*` final, but is this necessary for `Modifiable*` as well?  I have a situation where I would like to extend the generated `Modifiable` and override a method implemented in the abstract type.  If `Modifiable*` can be non-final, then I imagine the constructor should also be `protected`.

**Comment by elucash** [comment]
May sound funny, but I could not remember for sure, but it's seems to me that we might have such functionality. Try to use `"new"` as a naming template for `create` method (i.e. `Value.Style(create = "new"...)`). It will use public constructor and might drop `final` as well.

**Comment by pushbit** [comment]
Yes, `final` and the constructor are dropped, so it would have an implicit public constructor.  Though personally I would prefer to use the default `create()` style.  What do you think about removing `final` and changing the constructor to `protected` for added flexibility in the default case?

**Comment by elucash** [comment]
Wow, indeed, I've checked the template and we do have this working. I have a feeling that having extendable modifiable class not always make sense with `create()` method:
If you extend a modifiable class, then almost always you will want to instantiate the subclass, not the original one, and so having `create` method to create non-extended equivalent would be not much of a help. In other words, if you create subclass you will have to have a separate static factory method for it if you need one.

```java
public class MyExt extends ModifiableExt {
 protected MyExt() {}
 public static MyExt create() {
  return new MyExt();
 }
}
```

**Comment by pushbit** [comment]
In my case I will most often be instantiating the generated class and only the subclass when needing its alternative behaviour.  Regardless, I'm not fully convinced for my previous suggestion.  Maybe there is value in having a `final Modifiable*` with `create()` vs. a non-`final` with public constructor.  I'll give it a go as-is for now.
