### ISSUE TITLE
@Nullable array properties

### ISSUE THREAD

**Issue by pushbit** [immutables/immutables#191]
When an array property is required we get the client friendly `foo(Type... elements)` signature.  But when it's `@Nullable`, then the setter reverts to `foo(Type[] foo)` and clients have to do something like `foo(new Type[] { foo, bar, baz })` instead of just `foo(foo, bar, baz)`.

Was it designed this way because sending `null` to `foo(Type... elements)` is ambiguous and generates a compiler warning?  The workaround to this, as I'm sure you're aware, is just sending `(Type[]) null`.  In my experience, calling these types of methods with non-null values is significantly more common than the exception of calling them with `null`.  Because of this, I think it would be a net benefit to also generate `@Nullable` array property setters with varargs instead of requiring an explicit array.

Am I missing any reasons that this could cause problems or might we be able to head in this direction?

**Comment by elucash** [comment]
In current implementation, making non-primitive attribute `@Nullable` will just make it "regular", i.e. nothing special is generated about it except it will allow `null`. In this case special varargs initializers are not generated for arrays. Another difference is that arrays are cloned on write and read (to be thread safe), while nullable arrays are largely unsafe. We can "fix" by special casing nullable arrays (but I could not imaging doing it for every other nullable collection, though).

**Comment by pushbit** [comment]
Sounds good.  In the meantime I've found a temporary (hack) solution.  Instead of `@Nullable` I am using `@Default` and returning `null`.  Doesn't make much sense logically, but it works.

A related thought: required `Collection` properties are initialised with an empty instance.  Perhaps required array properties should also be initialised with a (global static, something like [ArrayUtils][1]) empty instance?  Then we can call the getter (and get the empty instance) without having to call the setter.

[1]: https://commons.apache.org/proper/commons-lang/javadocs/api-release/org/apache/commons/lang3/ArrayUtils.html

**Comment by elucash** [comment]
Released in 2.1.1. Thank you!

**Comment by pushbit** [comment]
I changed an array property to `@Nullable` and it now generates a setter with varargs.  But `toString` tries to call `*IsSet`, which no longer exists, resulting in a compile error.

**Comment by elucash** [comment]
Is it standard generated implementation of `toString`?. I have a tests for this and don't see such errors, could you attach example, i.e. source and generate code snippets

**Comment by pushbit** [comment]
Yes, standard `toString`.  It seems to be an issue with `@Modifiable` and not `@Immutable`.

```java
	@Modifiable
	static abstract class Foo {
		@Nullable
		abstract String[] bar();
	}
```

generates `toString`:

```java
    return MoreObjects.toStringHelper("ModifiableFoo")
        .add("bar", barIsSet() ? Arrays.toString(bar) : "?")
        .toString();
```

with compile error:

> The method barIsSet() is undefined for the type ModifiableFoo

**Comment by elucash** [comment]
Oh yeah, didn't looked at Modifables. got it!

**Comment by elucash** [comment]
Can you check 2.1.2

**Comment by pushbit** [comment]
The compile error is fixed, but it looks like the `toString` logic is backwards.

```java
bar == null ? Arrays.toString(bar) : "?"
```

I assume it should be `bar != null`.

**Comment by elucash** [comment]
Fixed, could be check in snapshot
