### ISSUE TITLE
Ability to skip a field in toString by specifing an annotation

### ISSUE THREAD

**Issue by arteam** [immutables/immutables#192]
Hi, Immutables team. Thanks for a great library, it's a joy to use it. 

I have a feature request. It would be great to have the ability to skip a field in the `toString` method implementation by specifing an annotation on the field. Something like this:

````java
@Value.Immutable
@JsonDeserialize(as = ImmutableUser.class)
public interface User {

    String username();

    @NotExpose
    String password();
}
````

Of course one could provide own `toString` implementation, but it requires a switch to an abstract
class and writing this implementation by hand, which could be error-prone.

**Comment by elucash** [comment]
Thank you for the request! Please, consider some of the functionality that we already have as it might solve similar needs.
http://immutables.github.io/immutable.html#opaque-containers
http://immutables.github.io/immutable.html#auxiliary
If other options will not fit the bill we can then try to define missing functionality.

**Comment by arteam** [comment]
Auxiliary attributes suit for my use case, thanks for the pointers. I definitely need to spend more time on reading documentation. I guess you can close this issue.

**Comment by elucash** [comment]
Feel free to discuss functionality of file bugs. Thank you!
