### ISSUE TITLE
Support optional arrays: Optional<T[]>

### ISSUE THREAD

**Issue by bcalmac** [immutables/immutables#193]
In one of my value classes I have an optional image:

    Optional<byte[]> getBackground();

`equals()` does not work as expected though. The generated code delegates to `Optional.equals()` which further delegates to `Objects.equals()`. This does not have special handling for arrays and compares them by identity.

If the array had not been optional, the generated code would have generated `Arrays.equals(background, another.background)`, which is what you'd normally expect.

**Comment by elucash** [comment]
We would be glad to give an ability for users to somehow define how to handle arbitrary combination of types, and we really expect that some next major version would make it possible. Currently we specifically support optionals, and also support arrays, but unfortunately those are not compose together automatically. And it would be quite difficult to support such combinations i.e. have them first class, bug-free and with sound semantics.

Here I'll try to list some workarounds, or more precisely, what would I do if I need to handle it

1) Use regular array attribute. Empty array will essentially mean "absent" value. If absolutely necessary to disambiguate empty array from absent value, you can use separate flag field and even try to maintain consistency using `@Value.Check`
```java
@Value.Immutable
abstract class Obj {
  abstract boolean hasBackground();
  abstract byte[] getBackground();
  @Value.Check
  void validate() {
    Preconditions.checkState(hasBackground() || getBackground().length == 0)
  }
}
... 
```
2) Beware that in _Immutables_, arrays attributes are cloned on every read. So I would recommend to have separate wrapper container around `byte[]` with some methods which would allow to use it safely without excessive copying. Such small abstractions are proven to be useful, especially as you can fold some of dreaded `WhateverUtil` stuff in such containers.

```java
Background getBackground();
...
// where Background has methods like
class Background {
  static Background empty(); // empty factory, may use singleton to represent empty instance
  static Background of(byte[] array);
  boolean isEmpty(); // our optional-like flag
  byte[] read(); // clone on read? this instead of get 
  int size(); // get the size without cloning, just as an example
  ...
}
```

**Comment by bcalmac** [comment]
Right, solution 2) makes sense. I think I would have needed to created the byte[] wrapper anyway.
