### ISSUE TITLE
JsonInclude.Include.NON_EMPTY causes NullPointerException

### ISSUE THREAD

**Issue by alexwen** [immutables/immutables#198]
Testing with the latest version, 2.1.0, I am running into an NPE when attempting to use `JsonInclude.Include.NON_EMPTY`:

```
    @Value.Parameter
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public abstract Optional<OrgRelationships> getRelationships();
```

Jackson, when deserializing initializes the value of the relationships on the Json object to null, even though it is an Optional. This causes the constructor to throw a NullPointerException:
```
    this.relationships = Objects.requireNonNull(relationships);
```
Changing `optionalAcceptNullable` doesn't appear to have an affect.

Let me know if I can provide any other information!

**Comment by elucash** [comment]
This has to be fixed. Thank you for the bug report!

**Comment by elucash** [comment]
Fixed and released in 2.1.1

**Comment by alexwen** [comment]
Hey @elucash I finally got around to testing this on 2.1.4 and it is still triggering a NPE during serialization when the property is null:
```
Caused by: java.lang.NullPointerException: relationships
	at java.util.Objects.requireNonNull(Objects.java:228) ~[na:1.8.0_31]
	at us.nuve.app.rest.org.ImmutableOrgData.<init>(ImmutableOrgData.java:41) ~[classes/:na]
	at us.nuve.app.rest.org.ImmutableOrgData.of(ImmutableOrgData.java:280) ~[classes/:na]
	at us.nuve.app.rest.org.ImmutableOrgData.fromJson(ImmutableOrgData.java:267) ~[classes/:na]
```

Let me know if I can supply any more details.

**Comment by elucash** [comment]
Yes, full value definition and corresponding JSON to be deserialized (or reduced to minimal repro case). We have a test for this, so your error is not covered, and additional info would be helpful. Thank you!

**Comment by alexwen** [comment]
Yeah, I tracked down the discrepancy in your test from what I was doing and was able to reproduce, starting from  [OptionIncludeNonEmpty](https://github.com/immutables/immutables/blob/a594d4d706208e6d3c14d4f61de48d047ace211f/value-fixture/src/org/immutables/fixture/jackson/OptionIncludeNonEmpty.java):

I additionally, disabled the builder on the class I was having trouble with:
```
@Value.Immutable(builder = false)
@JsonDeserialize(as = ImmutableOptionIncludeNonEmpty.class)
public abstract class OptionIncludeNonEmpty {

    @Value.Parameter
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public abstract Optional<String> getRelationships();

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public abstract Map<String, Number> getMap();

    // used to test abstract method generation in Json class
    public abstract OptionIncludeNonEmpty withMap(Map<String, ? extends Number> number);
```

The following test then triggers the condition:

```
package com.test.optionalnpe;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import com.google.common.collect.ImmutableMap;

import java.io.IOException;
import java.util.Optional;

/**
 *
 */
public class TestOptionIncludeNonEmpty {

    public static void main(String[] args) throws IOException {
        ImmutableOptionIncludeNonEmpty nonEmpty = ImmutableOptionIncludeNonEmpty.of(Optional.empty())
                .withMap(ImmutableMap.of("one", 1));

        ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new Jdk8Module());

        final String json = mapper.writeValueAsString(nonEmpty);
        final OptionIncludeNonEmpty result = mapper.readValue(json, OptionIncludeNonEmpty.class);

        assert result != null;
    }
}
```

So, it looks to be a combination of null provided as an optional by Jackson (when `NON_EMPTY` is specified) AND disabling the builder. Not sure how you feel about this edge case but this investigation has led me to a workaround, re-enabling the builder, which is not a huge deal in my mind

**Comment by elucash** [comment]
Should be fixed now for deserialization via constructor. Please, try 2.1.5

**Comment by alexwen** [comment]
Eugene, I finally had a chance to check this out against the latest release and it works great. Thank you!
