### ISSUE TITLE
Support @Value.Immutable on custom annotation

### ISSUE THREAD

**Issue by whyicantusemyemailasusername** [immutables/immutables#200]
I'd like to be able to annotate my meta-annotation with `@Value.Immutable` and don't have it on my immutable beans.

```java
@Value.Style(typeImmutable = "")
@Value.Immutable /* getting compilation error now */
public @interface Aargh {
}
...

@Aargh
/*no need to have @Value.Immutable */
public interface AbstractBean {
}
```

**Comment by elucash** [comment]
Indeed it would be great way to declutter annotations for those cases when you cannot use global style (i.e. styles on parent package). In order for this to work, types of the annotations would be necessary to pass to annotation processor using parameters (like `-Aimmutable.annotations=...`) or using classpath extensions (think `META-INF/..` files with annotation names). Annotation processor declares the type of annotation it handles, we cannot make free-form queries for annotations. Have to investigate that.
As of now, you may only create meta annotations for styles, but you still need to have `@Value.Immutable`. Hopefully styles and meta-styles could be also placed on packages and parent packages using `package-info`
Thank you for the feature request!

**Comment by elucash** [comment]
Custom annotation support released in 2.1.1. Thank you!

**Comment by whyicantusemyemailasusername** [comment]
Thank you!

**Comment by elucash** [comment]
In order for this to work annotation names should be specified on the file 'META-INF/annotations/org.immutables.value.immutable' on annotation
processor classpath. When using standard compilation, you can create this file in a separate jar and just add it as compile dependency. Example https://github.com/immutables/immutables/blob/master/value-fixture/src/META-INF/annotations/org.immutables.value.immutable
