### ISSUE TITLE
PCollections support

### ISSUE THREAD

**Issue by jroper** [immutables/immutables#201]
Has any thought been given to supporting [PCollections](http://pcollections.org)?  The great thing about PCollections, when compared to something like Guava immutable collections, is that append/add/remove operations run in effective constant time, while adding to a guava immutable list requires creating a copy which takes linear time.  PCollections are also much easier for a user to work with directly, doing an append in Guava for example requires three method calls:

``` java
ImmutableList newList = oldList.builder().add(newElement).build();
```

While doing an append in PCollections is just one method call:

``` java
PVector newList = oldList.plus(newElement);
```

PCollections implement the Java collection interfaces, and so are highly compatible with the rest of the Java ecosystem, and can be used transparently if need be.

**Comment by elucash** [comment]
Definitely _pcollection_ support would be great!
My current thoughts on it is the same as expressed in another similar feature request #194. hope this would help.
Thank you for the feature request!

**Comment by elucash** [comment]
extension mechanism is available to integrate custom collection libraries, see http://immutables.github.io/encoding.html  and similar ticket #383 ( about https://github.com/immutables/immutables-vavr )
thank you!
