### ISSUE TITLE
Need the ability to remove classes from ClasspathAvailability.available

### ISSUE THREAD

**Issue by ldriscoll** [immutables/immutables#205]
we're very strict with our build process, such that if something is not declared in the pom dependencies, cannot be used in code being compiled.  During compile time, when the immutables are generated, there are other jars that include things like `javax.annotation.Nullable`, however the final application may not include it.

Currently the only way to get around this is to either include the jar in the pom, or exclude it from the imports of a different dependency.  

It would be nice if ClasspathAvailability only included things available at runtime to the application, using the dependencies in the pom, or we could annotate the individual class to not use something like `@Nullable`

@mjball

**Comment by elucash** [comment]
As far as I expect this should not be a problem, at least with `javax.annotation.Nullable`:
If it's present at compile time, compiler will accept it. If annotation is not available at runtime it should not cause any classloading or reflection problems.
Please correct me where I am wrong, more precisely, what exact runtime issues you're facing, so we could try to find appropriate solution (I guess there's simply no way to reason about runtime classpath at compile time)?

**Comment by ldriscoll** [comment]
I think the problem is to do with weirdness in google findbugs, I'm going to close.
