### ISSUE TITLE
@Value.Parameter on List produces noncompiling class

### ISSUE THREAD

**Issue by ellisjoe** [immutables/immutables#210]
Adding @Value.Parameter to a list property results in this error:

```ImmutableRegisterFilesRequest.java:135: error: name clash: of(Iterable<? extends FileReference>) in ImmutableRegisterFilesRequest and of(Iterable<FileReference>) in RegisterFilesRequest have the same erasure, yet neither hides the other```

I'd expect it to produce just the ```of(Iterable<FileResource>)``` method. Here's the class:
 
```
@Value.Immutable
@Value.Style(visibility = Value.Style.ImplementationVisibility.PACKAGE)
@JsonSerialize(as = ImmutableRegisterFilesRequest.class)
@JsonDeserialize(as = ImmutableRegisterFilesRequest.class)
public abstract class RegisterFilesRequest {

    @Value.Parameter
    public abstract List<FileReference> getFileReferences();

    public static RegisterFilesRequest of(FileReference... fileReferences) {
        return ImmutableRegisterFilesRequest.of(fileReferences);
    }

    public static RegisterFilesRequest of(Iterable<FileReference> fileReferences) {
        return ImmutableRegisterFilesRequest.of(fileReferences);
    }
}
```

**Comment by elucash** [comment]
This is definitely a some sort of complication, but here we, probably, little can do on _Immutables_ side to not break compatibility.
We're generating 2 kinds of constructors for the case of collections.

```java
RegisterFilesRequest of(List<FileResource>) { ... }
RegisterFilesRequest of(Iterable<? extends FileResource>) { ... }
```

The one is exact, the other is more permissive, allowing you to pass say `ImmutableSet<ExtendedFileResource>` as a parameter, for example. Your forwarding static factory methods is clashing with `Iterable<? extends FileResource>` constructor. To resolve conflict, just change your factory method by adding `? extends` to the argument. The rule of thumb is that generic signature should fully match if they have the same erasure

```java
    public static RegisterFilesRequest of(Iterable<? extends FileReference> fileReferences) {
        return ImmutableRegisterFilesRequest.of(fileReferences);
    }
```
