### ISSUE TITLE
Gson code generation and proguard 

### ISSUE THREAD

**Issue by digitalbuddha** [immutables/immutables#215]
We started using immutables with gson generated adapters and noticed that proguard doesn't play nice. Was wondering if there is a particular rule we can add? 
```  java.lang.ClassNotFoundException: Didn't find class "com.nytimes.android.api.config.model.overrides.GsonAdaptersGatewayOverride" on path: DexPathList```

**Comment by elucash** [comment]
We generate `GsonAdapters*` classes which are also included in `/META-INF/services/*`. You could try to somehow force Proguard to use class references in service files. The other, more reliable option is to explicitly add each adapter factory to `GsonBuilder` object, so Proguard will see all the classes references and, hopefully, will not remove them:

```java
GsonBuilder gsonBuilder = new GsonBuilder();
gsonBuilder.registerTypeAdapterFactory(new GsonAdaptersMyDocument());
gsonBuilder.registerTypeAdapterFactory(new GsonAdaptersGatewayOverride());
...
Gson gson = gsonBuilder.create();
...
```

**Comment by digitalbuddha** [comment]
We ended up adding a proguard rule to include all model package stuff.  Just wanted to double check if a canonical solution existed. Thank you for speedy reply, love the library.

**Comment by elucash** [comment]
There is no canonical solution, just things that works. Hope it helps. Thank you for the interest!

**Comment by frostymarvelous** [comment]
Is it possible to share your proguard rules? Especially what worked for you with gson?

**Comment by digitalbuddha** [comment]
Not sure if this is the optimal way to do it but here's what we did initially:
```
-keep class com.google.gson** { *; }
-keepclassmembers class com.google.gson** {*;}
```

I also keep any of my value object packages `-keep class com.friendlyrobot.android.api.config.model.** {*;}
`

Finally we went the route of using package level annotations:
```
@Gson.TypeAdapters
package com.friendlyrobot.foo;

import org.immutables.gson.Gson;
```

and then manually registering them, 
```
return new GsonBuilder()
                .serializeNulls()
                .registerTypeAdapterFactory(new GsonAdaptersEntities())
                .registerTypeAdapterFactory(new GsonAdaptersRoute())
                .registerTypeAdapterFactory(new GsonAdaptersPayload())
                .registerTypeAdapterFactory(new GsonAdaptersWarehouse())
                .registerTypeAdapterFactory(new GsonAdaptersResponse())
                .registerTypeAdapterFactory(new GsonAdaptersRequest())
                .registerTypeAdapter(Date.class, new DateDeserializer())
                .create();
```

The reason we went to registering manually is that the auto registering way had a huge startup hit due to reading resources in a non android way.

Hope this helps :-)

**Comment by frostymarvelous** [comment]
It might be because I'm very very tired, but I think I'm really confused.
Thanks btw. Guess I'll figure it out when after I nap.

On Thu, May 12, 2016 at 1:26 PM, Mike Nakhimovich <notifications@github.com>
wrote:

> Not sure if this is the optimal way to do it but here's what we did
> initially:
>
> -keep class com.google.gson** { *; }
> -keepclassmembers class com.google.gson** {*;}
>
> I also keep any of my value object packages -keep class
> com.friendlyrobot.android.api.config.model.** {*;}
>
> Finally we went the route of using package level annotations:
>
> @Gson.TypeAdapters
> package com.friendlyrobot.foo;
>
> import org.immutables.gson.Gson;
>
> and then manually registering them,
>
> return new GsonBuilder()
>                 .serializeNulls()
>                 .registerTypeAdapterFactory(new GsonAdaptersEntities())
>                 .registerTypeAdapterFactory(new GsonAdaptersRoute())
>                 .registerTypeAdapterFactory(new GsonAdaptersPayload())
>                 .registerTypeAdapterFactory(new GsonAdaptersWarehouse())
>                 .registerTypeAdapterFactory(new GsonAdaptersResponse())
>                 .registerTypeAdapterFactory(new GsonAdaptersRequest())
>                 .registerTypeAdapter(Date.class, new DateDeserializer())
>                 .create();
>
> The reason we went to registering manually is that the auto registering
> way had a huge startup hit due to reading resources in a non android way.
>
> Hope this helps :-)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/immutables/immutables/issues/215#issuecomment-218756372>
>



-- 
Regards,
Stefan Froelich.

**Comment by frostymarvelous** [comment]
Is that why my app is blank for a few seconds when I launch it?

**Comment by digitalbuddha** [comment]
correct. Look into package-info.java its a file that you can place in a package and then apply an annotation to that file (rather than each class in the package).  By placing the GsonAdapters annotation there you will have only a few `GsonAdapters` to register with your instance of gson

**Comment by frostymarvelous** [comment]
I have only one TypeAdapter luckily

Anyway, this is what I found for Gson.

```
##---------------Begin: proguard configuration for Gson  ----------
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-keep class sun.misc.Unsafe { *; }
-keep class com.google.gson.stream.** { *; }

# Application classes that will be serialized/deserialized over Gson
-keep class com.umaplay.android.model.** { *; }

#---------------End: proguard configuration for Gson  ----------
```

Initially, I added `-dontwarn com.immutables.gson.stream.**` but just realized `-keep class com.google.gson.stream.** { *; }` was commented out when I was posting this answer.
Haven't tested, but it should render my addition irrelevant.

Funny thing, I seem to have woken up.

**Comment by elucash** [comment]
`org.immutables.gson.stream.` is needed only if you use certain runtime capabilities (see http://immutables.github.io/json.html#gson). Most of the time you don't need anything of `org.immutable.gson` in runtime. But you do need `com.google.gson.` stuff I guess.
Thank you for discussing and sharing your experience!

**Comment by frostymarvelous** [comment]
Does using Typeadapters count as one of those features?

**Comment by elucash** [comment]
Runtime capabilities include Jackson/Gson bridge, field naming strategy support and, most recently with 2.2-beta3, complex generics. Runtime capabilities are in that sense that the generated classes in those cases are not fully self contained, but have dependencies on our support classes which should be present in runtime. If you never used any of those capabilities, generated classes would contain no such dependencies and you will be fine with having only regular gson classes needed.

**Comment by frostymarvelous** [comment]
On that front, I think I might be good. 
I finally got my apk to build so I'll be sharing my proguard when I test it finally. 
Thanks a lot.
