### ISSUE TITLE
@SuppressWarning for @Value.Default on container attributes

### ISSUE THREAD

**Issue by Coneko** [immutables/immutables#216]
`@Value.Default` on container attributes issues a warning, as per discussion in #59.

Is there a way to suppress that warning on a per-use-case basis using `@SuppressWarning` or a parameter to `@Value.Default`? We like building stuff with `-Werror`.

**Comment by elucash** [comment]
We've implemented some support for warning suppression, try using `@SuppressWarning("immutables")` on the element.

**Comment by Coneko** [comment]
That's exactly what I needed. I couldn't find it in the docs, sorry.

**Comment by elucash** [comment]
Good point! Added documentation section about warnings/suppression http://immutables.github.io/immutable.html#warnings
