### ISSUE TITLE
Json class getters that throw unsupported operation exception cause problems with `@Value.Lazy`

### ISSUE THREAD

**Issue by ldriscoll** [immutables/immutables#219]
any `@Value.Lazy` method that calls a getter causes an unsupported operation exception when deserializing.

**Comment by elucash** [comment]
Thank you for finding this! Should we override all lazy, derived and default values with unsupported operation? Need to reproduce this anyway

**Comment by ldriscoll** [comment]
just need to do an ObjectMapper.deserialize; I think we should probably JsonIgnore the setter.

**Comment by elucash** [comment]
```java
@Value.Immutable
@JsonDeserialize(as = ImmutableLazyAttributesSafe.class)
public abstract class LazyAttributesSafe {
  public abstract int getA();

  @Value.Lazy
  public String getLazy() {
    return String.valueOf(getA());
  }
}
...
  @Test
  public void lazyAttribute() throws Exception {
    String json = "{\"a\":1}";
    LazyAttributesSafe value = OBJECT_MAPPER.readValue(json, LazyAttributesSafe.class);
    check(value.getA()).is(1);
  }
```

Despite the inconvenience of unknown property "lazy", which requires additional annotation to ignore, the test for deserialization basically passes. Do you have a stack trace showing on which execution path `Json.getLazy() -> Json.getA()` is called?

**Comment by elucash** [comment]
Can you, please, try it with 2.1.4 and send a stack trace of the error

**Comment by ldriscoll** [comment]
Sorry for the delay, seems to be much remedied.
