### ISSUE TITLE
Gson Serialization, multiple keys same field

### ISSUE THREAD

**Issue by digitalbuddha** [immutables/immutables#221]
Here's my scenario:

I have a class that has a string articleURL.  When getting the json the value can be in either 1 of 2 keys (both will never be present). The key can either be URL or Article_URL.  Is there a way that I can associate both keys to map to a single field.  Thank you (as always) for your help.

**Comment by elucash** [comment]
There's a way to use combination features to get the result.

```java
@Value.Immutable
@Gson.TypeAdapters
public abstract class Whatever {
  @Gson.Named("URL")
  @Value.Default
  public String articleURL() {
    return articleURLAlternate().get(); // will fail if both absent
  }
  @Gson.Named("Article_URL")
  abstract Optional<String> articleURLAlternate();
}

```

I think we need to update _Immutables_ to use `@SeriazedName` annotation from _Gson_ 2.5. It is now applicable to methods (previously, only to fields). Moreover, it supports new attribute `SerializedName.alternate` to supply zero or more alternative names used during deserialization, this would be perfect match for what you need.

**Comment by digitalbuddha** [comment]
Sounds like a good thing for me to look into for first pr.

**Comment by elucash** [comment]
I actually managed to upgrade to _Gson_ 2.5 by using its `SerializedName` annotation and implementing support for `alternate` attribute. You can try in released version 2.1.4. Thank you!

**Comment by digitalbuddha** [comment]
Wow, don't know if I should be thanking or trying to recruit you ☺.  Just an FYI there's going to be a ny times engineering blog post with a  mention of how this library  solved our reflection and memory issues coming out soon. Wrapping up sample app this weekend.

**Comment by elucash** [comment]
Great! Can't wait to read the post!
