### ISSUE TITLE
Hash code calculation with Set causes collisions

### ISSUE THREAD

**Issue by before** [immutables/immutables#223]
While determining the `hashCode()` for an implementation which contains also an attribute of type `Set`, collisions may occur which may cause decreased performance with the internally used `Interner`.

The cause is, that the `hashCode()` implementation of a `Set` (e.g. `HashSet`, `ImmutableSet`) sums up the hash-code for each element, but does not regard the position. When creating a `Set` of (non-primitive) value objects with the same essential components, but differently structured, the same hash-code will be returned, even when the objects are not equal.

```Java
@Value.Immutable
abstract class AbstractValue {
    static AbstractValue.Builder builder() {
        return ImmutableValue.builder();
    }
    abstract String name();
    abstract int position();
    static interface Builder {
        AbstractValue build();
        Builder name(String name);
        Builder position(int position);
    }
}

@Value.Immutable
abstract class AbstractWithHashingIssue {
    static AbstractWithHashingIssue.Builder builder() {
        return ImmutableWithHashingIssue.builder();
    }
    abstract ImmutableSet<AbstractValue> values(); // this attribute causes issues with the interner
    static interface Builder {
        AbstractWithHashingIssue build();
        Builder addValues(AbstractValue element);
    }
}

public class Test {
    @org.junit.Test
    public void test() {
        AbstractValue valueA1 = AbstractValue.builder().name("A").position(0).build();
        assertEquals(10064, valueA1.hashCode());
        AbstractValue valueB1 = AbstractValue.builder().name("B").position(1).build();
        assertEquals(10082, valueB1.hashCode());

        HashSet<AbstractValue> valuesAB1 = new HashSet<>();
        valuesAB1.add(valueA1);
        valuesAB1.add(valueB1);
        valuesAB1.hashCode();
        assertEquals(20146, valuesAB1.hashCode());

        AbstractValue valueA2 = AbstractValue.builder().name("A").position(1).build();
        assertEquals(10065, valueA2.hashCode());
        AbstractValue valueB2 = AbstractValue.builder().name("B").position(0).build();
        assertEquals(10081, valueB2.hashCode());

        HashSet<AbstractValue> valuesAB2 = new HashSet<>();
        valuesAB2.add(valueA2);
        valuesAB2.add(valueB2);
        valuesAB2.hashCode();
        assertEquals(20146, valuesAB2.hashCode());

        AbstractWithHashingIssue values1 = AbstractWithHashingIssue.builder()
                .addValues(valueA1)
                .addValues(valueB1)
                .build();

        AbstractWithHashingIssue values2 = AbstractWithHashingIssue.builder()
                .addValues(valueA2)
                .addValues(valueB2)
                .build();

        assertNotEquals(values1, values2);
        // values should be different to avoid issues with the "interner", but they are equal
        assertNotEquals(values1.hashCode(), values2.hashCode()); // hash-code 20673
    }
}
```
Maybe when using an array or `List` when calculating the `hashCode()` for attributes of type `Set` could increase performance when using the `Interner`.

A workaround could be to customize the `hashCode()` implementation of `AbstractWithHashingIssue`. If we would generate it out-of-the-box, the maintainability would be less error-prone.
```Java
@Value.Immutable
abstract class AbstractWithHashingIssue {
    static AbstractWithHashingIssue.Builder builder() {
        return ImmutableWithHashingIssue.builder();
    }
    @Override
    public int hashCode() {
        return Objects.hash(values().toArray());
    }
    abstract ImmutableSet<AbstractValue> values();
    static interface Builder {
        AbstractWithHashingIssue build();
        Builder addValues(AbstractValue element);
    }
}
```

**Comment by elucash** [comment]
Thank you for revealing this! As it stands now, I barely see "corpus delicti" in how we manage hash codes here, so collisions are rather unfortunate if expected. The contract of that "equal object have equal hash-codes" (and not vice versa) is preserved. Of course, performance might suffer a bit when there are many unequal objects with equal hash-codes. Also bear in mind that idea of interned objects is to spend more time during construction/interning to trade it for a faster equality operations and smaller long-term memory footprint. So not-so-optimal interning is actually more or less expected. Currently, it is a great idea to use custom hash code implementation to improve performance as you demonstrated! Another option would be to have an attribute of type list with elements deduplicated (as verified during constructions) or even of custom container type which could combine notions of a set and a list.

My understanding is that if we would calculate hash codes for sets differently, we might end up in a strange situations when there could be two value objects where all attributes are equal by themselves, yet the 2 objects are unequal. Let's say we implement a set attribute hash-code as a list's one: would then two sets with the same elements but added in different order equal? That kind of complication just prevent us to implement custom calcularions which would contradict to the behavior of standard/jdk types.

Having that said, I'm still open to suggestions of how actually improve hashing as long as it will not break expected semantic of types.

**Comment by before** [comment]
@elucash yes, I agree with you on all points. Thank you
