### ISSUE TITLE
TypeAdapter loading performance

### ISSUE THREAD

**Issue by digitalbuddha** [immutables/immutables#230]
Did some performance analysis on loading generate type adapters using the ServiceLoader method and got some troubling results:
<img width="947" alt="screenshot 2015-12-16 11 45 42" src="https://cloud.githubusercontent.com/assets/4528092/11847338/e5d6f1b8-a3ea-11e5-99f8-5195f4cca454.png">

It seems like this method does not work well on android due to inefficiencies in reading service data from a JAR.  I was hoping to ask for an enhancement to how type adapters are registered.  Rather than using the service loader, would it be possible to instead generate a single class GeneratedTypeAdapters which would return the list of type adapters that were generated?  This way we would have a single entry point for getting the adapters rather than having to remember to add each manually.  Thank you kindly.

**Comment by elucash** [comment]
Thank you for consistently verifying performance! `ServiceLoader` integration was designed primarily for Java SE\EE usage, no surprise that it's not very performant on Android, however I didn't have a chance to verify that. The solution to generate registrar class seems like a good one, however, I want to try to share some difficulties we running into, based on my experience trying implementing similar feature before.

* Problem with incremental compilation. During incremental compilation we might not have full set of classes being processed. When adding any new type adapter factory — need to recompile whole module/or application. Might not be a problem, but sometimes this could give a lot of frustration during development iterations and unit testing.

* Even if forcing a full build, we still have ordering issues, so the module which generates adapter factory registrar class have to be built after all modules which define Gson-bound classes (and having those modules as dependencies). Also this requires that annotation processing classpath should probably equal to compile classpath in order to discover all generated factories/descriptors. This is the default when using javac/maven etc, but for Gradle/Android it usually configured differently.

I'm not sure the above explanation is easy to follow, but overall I only see it could make sense to use kind of hybrid approach: Use reflective descriptors for development and unit testing, and then generate registrar class using application-wide information (having all modules prebuilt as dependencies). It could be implemented given we will have more refined idea about it.

I'm don't know how you currently organize your codebase and how you use `@Gson.TypeAdapters`, but there's possible, for example, create special packages for bound classes and then put `@Gson.TypeAdapters` on a package (using `package-info.java`) in order to generate type adapter factory for the whole package, i.e. this factory will contain adapters for all value classes in the package. Then it might be easier to just add few package-level factories to `GsonBuilder` rather that adding all individual per-class factories.

**Comment by digitalbuddha** [comment]
I'll use the package annotations, great suggestion. As for the incremental compilations problems, I sort of get those with Dagger2, I find myself forcing a rebuild sometimes (since its only a recompile its not as slow as full apk generation).  Anyways thanks for package idea.

**Comment by digitalbuddha** [comment]
Package annotation does not pick up nested classes while service loader does. Just an fyi.

**Comment by elucash** [comment]
>> Package annotation does not pick up nested classes while service loader does. Just an fyi.

Added some tests for it d3e334ae4375655de2c4d36df226d690512f418c Seems to work though. Do you have repro case so we can fix it?

**Comment by digitalbuddha** [comment]
It was my mistake. It wasn't picking up nested package which is expected.

**Comment by elucash** [comment]
got it, thanks! Yeah, there's nothing we can do with nested packages as annotation should be present as a pin-point for invoking annotation processing, except for, probably, application-wide discovery as last step of compilation described as "hybrid approach".

**Comment by digitalbuddha** [comment]
Hello again, I added package annotations and everything seemed to be going great.  Release is about to ship so I ran our build through some startup traces and found that generated ```GsonAdapters.create``` contained what amounted to 600ms of blocking calls to 

<img width="606" alt="screen shot 2016-01-07 at 7 36 38 pm" src="https://cloud.githubusercontent.com/assets/4528092/12187068/94f7be9c-b576-11e5-94ba-dbd7a7e56374.png">


offending code:
```
  public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
        return (TypeAdapter)(GsonAdaptersOverrides.BNAOverrideTypeAdapter.adapts(type)?new GsonAdaptersOverrides.BNAOverrideTypeAdapter(gson):(GsonAdaptersOverrides.StoreOverrideTypeAdapter.adapts(type)?new GsonAdaptersOverrides.StoreOverrideTypeAdapter(gson):(GsonAdaptersOverrides.SkusTypeAdapter.adapts(type)?new GsonAdaptersOverrides.SkusTypeAdapter(gson):(GsonAdaptersOverrides.ECommOverrideTypeAdapter.adapts(type)?new GsonAdaptersOverrides.ECommOverrideTypeAdapter(gson):(GsonAdaptersOverrides.MeterOverrideTypeAdapter.adapts(type)?new GsonAdaptersOverrides.MeterOverrideTypeAdapter(gson):(GsonAdaptersOverrides.BodyTypeAdapter.adapts(type)?new GsonAdaptersOverrides.BodyTypeAdapter(gson):(GsonAdaptersOverrides.SplashPageOverrideTypeAdapter.adapts(type)?new GsonAdaptersOverrides.SplashPageOverrideTypeAdapter(gson):(GsonAdaptersOverrides.OverrideConditionTypeAdapter.adapts(type)?new GsonAdaptersOverrides.OverrideConditionTypeAdapter(gson):(GsonAdaptersOverrides.ExclusionsOverrideTypeAdapter.adapts(type)?new GsonAdaptersOverrides.ExclusionsOverrideTypeAdapter(gson):(GsonAdaptersOverrides.GatewayOverrideTypeAdapter.adapts(type)?new GsonAdaptersOverrides.GatewayOverrideTypeAdapter(gson):(GsonAdaptersOverrides.ConditionTypeAdapter.adapts(type)?new GsonAdaptersOverrides.ConditionTypeAdapter(gson):null)))))))))));
    }
```

The problem seems to be with how expensive ```java.lang.Class.getGenericSuperclass``` is to run on android. Thats also the reason why by default gson is slow on android.  Any advice/help would be appreciated

**Comment by elucash** [comment]
I saw Moshi use `Class<?>` objects directly (BTW we have experimental moshi support implemented). We could be try to find a way (if there is ) to construct Type tokens without overhead. Or use classes internally (where possible) and extract raw class out of `TypeToken` that passed to us by Gson, then compare raw classes instances by reference equality. I wonder if overhead is avoidable at all with Gson as construction of `TypeToken`s is part of it's machinery. If you'll have some best guesses or experiments that shows most promising solutions we might try to code some.

**Comment by digitalbuddha** [comment]
sure, I'll try some stuff out tomorrow and see what adjustments to the generated code work best.

**Comment by digitalbuddha** [comment]
good morning, I found the cause of the problem (in the context of android) due to collection<T> tokens. This works great:

```        private static final TypeToken<ImmutableExclusionsOverride> EXCLUSIONS_OVERRIDE_IMMUTABLE = TypeToken.get(ImmutableExclusionsOverride.class);
```

this does not
```private static final TypeToken<List<String>> BLOGS_TYPE_TOKEN = new TypeToken()```

When you create a type token threw calling new ```getSuperclassTypeParameter``` is called which in turn calls ```subclass.getGenericSuperclass()``` to an absolutely unbelievable 25-30ms per call for a substantially large (48k methods) android app.

Seeing as everything else you're doing is magical, could you have the annotation processor figure out and generate the generic superclass?

**Comment by elucash** [comment]
Good morning! `new TypeToken` are only generated when you have generic types. More precisely, as we handle `Optional<T>`, `List<T>`, `Set<T>` in a special way, the actual `T` should be generic itself in order to generate generic type token. Are you using `Optional<List<String>>` or something like that? If you're are, you would better change this to simply `List<String>`  (I might lookup links to some issues where I've tried to explain this in more detail). If not, then could you, please, pass value type definitions you use to see if we're generating this by mistake.

Other option would be to construct TypeTokens in a different way, but this could be involved, not yet investigated this

**Comment by digitalbuddha** [comment]
not optionals, just  collection<T>
```
@Gson.Named("previous")
    LinkedHashSet<String> previousSkus();
```

**Comment by digitalbuddha** [comment]
actually you are right its only optional generic collections. A resource of how else to do it would be appreciated thank you.

**Comment by elucash** [comment]
Oh, I see, so in this case we are having just `T previousSkus()`,  It is not recognized as special and while it is generic we fully delegate it . I'm sure that performance would be better if you will make it as `Set<String>`, the only thing is that it will be immutable (if you use guava it will be `ImmutableSet`, without guava with plain java it will be `Collections.unmodifiableSet(LinkedHashSet)`, both order preserving ). If immutability is a problem that force you to use `LinkedHashSet` directly, we might return to discussing GSON TypeAdapters support for plain pojos or `@Value.Modifiable` generated mutable classes

**Comment by digitalbuddha** [comment]
Got it, seems to be a combination of not recognized and Optional<Collection<T>>  Thanks for help.  I'll make adjustments and report back :+1:

**Comment by digitalbuddha** [comment]
is there a recommendation for an ordered set and map to use.  We use guava, mutability is not an issue just maintaining order for displaying values on screen

**Comment by elucash** [comment]
If you use just `Set<T>` it will maintain insertion order. However you can use `SortedSet<T>`, `NavigableSet<T>` or `ImmutableSortedSet<T>` with `@Value.NaturalOrder` annotation to maintain natural ordering in set.

If that could be of any interest, here are potentially helpful/or related discussions
https://github.com/immutables/immutables/issues/53
https://github.com/immutables/immutables/issues/193 https://github.com/immutables/immutables/issues/88

**Comment by digitalbuddha** [comment]
Following your suggestions knocked out most of the issues.  Few outstanding still generating type tokens through reflection:

```    
     Map<String, List<Integer>> imageCropMappings();
     Map<String, StoreOverride> currentSkus();
```
 but even with those we went from 600ms for serialization to 60 with immutables :-), 500k readers are going to get their news half a second faster now. Thanks for working through issues today

**Comment by elucash** [comment]
`Map<String, StoreOverride> currentSkus()` - should be fixed on our side I guess.

`Map<String, List<Integer>> imageCropMappings()` - probably "won't fix" but you can use `Multimap<String, Integer>` which should (IIRC) work as expected

**Comment by elucash** [comment]
Released v2.1.7 in which issue like `Map<String, StoreOverride> currentSkus()` is fixed.
`Map<String, List<Integer>>` could be changed to `ListMultimap` to avoid delegating to Gson/TypeToken generics.

**Comment by digitalbuddha** [comment]
you are a gentleman and a scholar, come visit NY Times if you're ever in NY...  Your lib is slowly taking over our codebase

**Comment by elucash** [comment]
Thank you for the kind words! I'm closing this in a good hope this issue is resolved. And hope you still have an enthusiasm to write a post about how you use _Immutables_ ;)

**Comment by digitalbuddha** [comment]
its at the editor as we speak...little preview of relevant part
"We saw a 10x improvement in parsing performance after writing our own type adapters. To keep developer overhead to a minimum we have leaned heavily on the Immutables library. <http://immutables.github.io/json.html> This generates customer type adapters for our data models at compile time and also gives us the added benefit of immutability in a manner similar to AutoValue."

**Comment by elucash** [comment]
:thumbsup:

**Comment by mrtristan** [comment]
gentlemen! @elucash great library, and @digitalbuddha thanks for the article and reddit post that drove me to these various tools that are helping me optimize my app... sorry if this isn't technically a proper spot for this, but it's extremely relevant to the discussion that happened here. two hopefully quickies:

1) can either of you point me in the right direction for proper syntax when adding `@Gson.TypeAdapters` to `package-info` as you guys mentioned here? I have a package full of intertwined models and I'm looking to help Gson deserialize some hefty server responses and @elucash it seems like you perfectly described the 'soupy' problem i'm about to face.

2) as it relates to using `new TypeToken()`, i was under the impression that i have to do that when trying to get a type for a list like: `TypeToken<ArrayList<DeviceFriendEvent>>() {}.getType();`. Is there a way to your knowledge to pull this off using the `TypeToken.get()` methodology that you guys discussed above? I've converted my other non-array instances and about to do a performance analysis.

and @digitalbuddha, i recognize your screenshot above, thanks much for that tool as well! i've been in talks with the guys over there in analyzing their capabilities and where they're going with it and they're great!

**Comment by digitalbuddha** [comment]
I also had no idea on package info, here's the SO post that explained it,
check out the @deprecated example
http://stackoverflow.com/questions/21940585/why-package-info-java-file-what-is-the-use-of-package-info-java-class-file

**Comment by elucash** [comment]
@mrtristan thank you for the interest!
1) Here are some examples of annotation usage in package-info
https://github.com/immutables/immutables/blob/master/gson/test/org/immutables/gson/packg/package-info.java
https://github.com/immutables/immutables/blob/master/value-fixture/src/org/immutables/fixture/style/package-info.java
2) Here are many things to keep in mind
 * You can easily use `TypeToken.get(RawType.class)` for raw types
 * You can create `new TypeToken<ArrayList<DeviceFriendEvent>>() {}.getType()` for generic types
 * You can get `TypeToken.get(getGenericTypeWithReflectionFromSomeFieldOrMethod())` to work but then you will need unchecked cast
 * In Immutables, all supported container types, including optional, list, maps, multiset, multimap (etc, see [collection attributes](http://immutables.github.io/immutable.html#collection)) have serialization/deserialization routines generated, so you only have to worry about performance of getting generic type tokens if type parameters for collections are itself generic.
```java
List<DeviceFriendEvent> events(); // <- nothing generic, list reading routine is generated operating with `TypeAdapter<DeviceFriendEvent>`
Set<List<DeviceFriendEvent>> setOfLists(); // But here you will have generic type token to get `TypeAdapter<List<DeviceFriendEvent>>` for the type argument of `Set`
```
