### ISSUE TITLE
Make library using immutables compatible with android < 19

### ISSUE THREAD

**Issue by ncornette** [immutables/immutables#232]
Immutables uses `java.util.Objects` unless it is not available on the classpath, or if `android.R` is available on the classpath.

Unfortunately none of these 2 conditions can be verified when building a library to be integrated in an Android project.

I eventually found a solution which is to create a module `immutables-android-compat` which includes only an empty `android.R` class, and added : 
`provided project(':immutables-android-compat')` in the lib dependencies.

My question is : could this artifact be available from the immutables project to make any library compatible with android api level <19 ?

**Comment by elucash** [comment]
Thank you for suggestion! I think we could add auxiliary module/artifact for that. The only wish is that once created it should be documented or at least mentioned somewhere in the docs. Will you help with that?

**Comment by ncornette** [comment]
Thanks you for doing the job ! waiting for the 2.1.8 release to integrate the artifact.

**Comment by elucash** [comment]
v2.1.8 available on central )
