### ISSUE TITLE
Support Guava Functions for field access

### ISSUE THREAD

**Issue by rgabbard-bbn** [immutables/immutables#235]
It would be handy if there were an option to generate Guava `Function`s for field access on generated immutable objects, like this:

```java
class MyClass {
    public String foo();
    public Function<MyClass, String> fooFunction() {
       return FooFunction.INSTANCE;
    }
    private enum FooFunction implements Function<MyClass, String> {
       INSTANCE;

       @Override
       public String apply(MyClass obj) {
           return checkNotNull(obj).foo();
       }

       public String toString() {
           return "MyClass.fooFunction()";
       }
   }
}
```

This would make it much easier to use Guava's functional features without cluttering up code with lots of boilerplate.  Of course, this is all unnecessary in Java 8, but lots of us cannot use it due to customer requirements or other reasons.

Also, perhaps `Predicate`s could be provided for boolean fields.

**Comment by elucash** [comment]
Actually, prior to version 1.0, we had such generator for functions and predicates, maybe we can bring it back. Thank you for feature request!

**Comment by rgabbard-bbn** [comment]
Great - if I can be helpful in testing or documenting such a feature, let me know.  (Or, if you can point me to the general area in the code to look, I may be able to implement it)

**Comment by elucash** [comment]
Just released in version 2.1.7
There's new `org.immutables:func` module with `@Functional` annotation, could be put on attribute or whole abstract value types. It generates functions or predicates for boolean attributes in a `FooFunctions` class.

Please see
https://github.com/immutables/immutables/blob/master/func/test/org/immutables/func/fixture/Val.java
https://github.com/immutables/immutables/blob/master/func/test/org/immutables/func/fixture/Use.java

Contributing module documentation is greatly appreciated! You can take https://github.com/immutables/immutables.github.io/blob/master/factory.md as an example.

**Comment by rgabbard-bbn** [comment]
Thanks!  I hope to get around to the documentation this evening.

**Comment by elucash** [comment]
released! documented! closing! thank you!
