### ISSUE TITLE
Problems with Optional fileds on Serializable values

### ISSUE THREAD

**Issue by redvasily** [immutables/immutables#243]
When using Serializable immutable value classes (implementing serializable interface), with java.util.Optional fields a generated Immutabe... class is not serializable as java.util.Optional is not serializable, and a generated class uses private java.util.Optional fields.

See this Stackoverflow answer: http://stackoverflow.com/questions/24547673/why-java-util-optional-is-not-serializable-how-to-serialize-the-object-with-suc

Leading to this email: http://mail.openjdk.java.net/pipermail/jdk8-dev/2013-September/003273.html

Apparently java.util.Optional authors don't want it be serializable.

Perhaps Immutables could generate regular (non-optional) fields and store null there if the value is not present, and return Optional.empty() if the value is not set. This would allow to keep interfaces use Optionals for optional fields in a public interface (which I think is very convenient), while the private implementation would become serializable.

**Comment by redvasily** [comment]
Sorry

**Comment by elucash** [comment]
we have been working on automatic "unboxing" of `java.util.Optional` and now it's seems ready and will be released soon https://github.com/immutables/immutables/issues/240 . There's also `org.immutables:serial` module which has `@Serial.Structural` annotation — it will generate special structural/flexible serialization code where as serialized form do not contain optionals so it won't be an issue. Thank you!

**Comment by redvasily** [comment]
Sorry about that, I guess I made a typo when looking for "Serializable" in the issues so I didn't find #240, and noticed it only after I've already created the issue.

I've switched to the snapshot version ("2.1.9-SNAPSHOT") and it's working fine so far for me.
