### ISSUE TITLE
Don't make a null check in an optional setter

### ISSUE THREAD

**Issue by amalinko** [immutables/immutables#245]
I've just tried new 2.1.9 with new enhancement about Optional. Everything is great, but builder has a null check in a setter of optional field.
```java
/**
     * Initializes the optional value {@link Order#comment() comment} to comment.
     * @param comment The value for comment
     * @return {@code this} builder for chained invocation
     */
    public final Builder setComment(String comment) {
      this.comment = Objects.requireNonNull(comment, "comment");
      return this;
    }

    /**
     * Initializes the optional value {@link Order#comment() comment} to comment.
     * @param comment The value for comment
     * @return {@code this} builder for use in a chained invocation
     */
    public final Builder setComment(Optional<String> comment) {
      this.comment = comment.orElse(null);
      return this;
    }
```
Maybe it shouldn't? Because this field could be null.

**Comment by elucash** [comment]
Thank you for raising this! Currently it is by design, fields are nullable as implementation detail, but we are null-hostile and not accepting nulls by default. We in favor of explicit null handling if necessary like `builder.setComment(Optional.ofNullable(nullableComment))`. However, if you wish that optional setters silently accept nulls converting them to `Optional.empty()`, you might enable special style `optionalAcceptNullable=true` (#152) activating the behavior you would expect

**Comment by amalinko** [comment]
Thank you for your answer. This is exactly what I need.
Just as a side note. If I use `bulder.setComment(Optional.ofNullable(nullableComment))` or `bulder.setComment(nullComment)` the result is the same, but I write more. I think it would be more convenient to have a setter with Optional as a helper and without Optional as a main setter. So maybe it would be more appropriate for default behavior. Here is the article where this is explained better: http://blog.joda.org/2015/08/java-se-8-optional-pragmatic-approach.html
Thank you for your help and a great project.

**Comment by elucash** [comment]
the problem with nulls is that unintended null can travel long distance between/inside objects and even autoconverted to empty optionals. Then it will blowup with NPE or cause functionality to unintendently no-op in a place from where it might be difficult to see where it came from. This happens often enough and when it happens an engineer could spend quite a lot time troubleshooting. That is why we have this as default to comply with _Immutables_' character of being null-hostile and detecting nulls early whenever possible. But we also support nullable attributes, or silent conversions null -> Optional.empty, just as opt-in
