### ISSUE TITLE
How to have Gson not bomb when required field missing

### ISSUE THREAD

**Issue by digitalbuddha** [immutables/immutables#253]
Before immutables, we were able to unmarshall json and if a field was missing life would be ok.  With immutables it seems like every field is required unless I make default value or optional.  Is there a way to make Immutables work the way Gson serialization works with regular pojos (no validation of required fields).  Use case is with an API where I do not know which fields may or may not be included.

**Comment by elucash** [comment]
In _Immutables_ a lot of things are about to be explicit and try to avoid magic and inconsistencies, at least we try to. So for the situation when you don't know if field would be present or not, the optional and the default attributes seems to be a best choice: you either have suitable default value or you know that you have to check if field is present. To be more lightweight than optional attributes there are following alternatives available: http://immutables.github.io/immutable.html#nullable
http://immutables.github.io/immutable.html#null-object-pattern-in-attribute-values

Then you can also use precondition check http://immutables.github.io/immutable.html#check-method
to validate some combination of values and blow things up with most tasty sort of exception.

Currently I just don't see that hiding optionality or nullability will serve any good
Hope this helps

**Comment by digitalbuddha** [comment]
thank you for explanation
