### ISSUE TITLE
Ability to detect plurals when using Collections and Maps

### ISSUE THREAD

**Issue by troinine** [immutables/immutables#254]
I would prefer having the possibility to auto-detect plurals and stripping the trailing "s" from the builder methods if possible. i.e. 

```
public interface MyInterface {
    List<String> getValues();
    Map<String, String> getOtherValues();
}
```

Would generate a builder similar to this:

```
public final class MyInterfaceBuilder {
    public final MyInterfaceBuilder addValue(String value) {
        // ...
    }

    public final MyInterfaceBuilder addOtherValue(String key, String value) {
        // ...
    }
}
```

Now I can customise the prefixes with ```@Value.Style``` for example in the case of ```Map``` but can't do much for the trailing "s". Stripping of the trailing "s" would probably be aligned with most naming conventions.

For backwards compatibility reasons this would probably have to be off by default and could be incorporated somehow to the ```@Value.Style```.

**Comment by elucash** [comment]
Once we tried to do this, but were unpleased on a number of exception to this rule. I've seen Lombok uses `@Singular` annotation to specify singular form of plural. But a fresh idea is that, as you proposed to use styles, we could supply a dictionary of exceptions to this rules. I'm basing this on the assumption that certain words/exceptions will be ubiquitous in a problem domain being modeled, so having dictionary attached to meta-style annotation or on a package style annotation might be an adequate way to deal with this. Thank you for the feature request!

**Comment by elucash** [comment]
Implementation landed to master/2.1.11-SNAPSHOT, please take a look and let us know
[javadoc](https://github.com/immutables/immutables/blob/master/value/src/org/immutables/value/Value.java#L813)
[test/example](https://github.com/immutables/immutables/blob/master/value-fixture/src/org/immutables/fixture/style/Depluralize.java)

**Comment by troinine** [comment]
Thanks for the fast feedback and implementation! Initially this looks exactly what I was after, even better with the dictionary.

I was wondering that would it make sense to split the depluralize style configuration into two parts:
```
boolean depluralize() default false;

String[] depluralizeDictionary() default {""};
```

This API would communicate clearly that you can enable / disable the depluralization with default naming conventions and in addition, if you want to specify exceptions / rules, then you declare them using the ```depluralizeDictionary()```. I would assume this would be clear for most developers whereas enabling the default with an empty string array is not evident until you look to the javadocs.

Anyways, many thanks for pushing this forward so fast. We'll be ready to migrate to this whenever this gets out!

**Comment by elucash** [comment]
you're right, first cut of api got somewhat cryptic, so changed it as you suggested.

**Comment by nhartner** [comment]
I want this. Please release 2.1.11 soon.

**Comment by elucash** [comment]
Released in 2.1.11. Thanks!

**Comment by troinine** [comment]
Works nicely! One small detail I noticed when testing our code with the new feature is that the varargs variant ```add*(Type .. elements)``` is depluralized as well. I'm not sure if you wanted it that way but since it technically adds an array of values I was thinking that should immutables generate the plural version of the method as it does for ```addAll*(Iterable<? extends Type> elements)```?

I do apologize I couldn't check the earlier before the release but I got context-switched...

**Comment by elucash** [comment]
Let's leave it as it is. Once I had similar concerns, but it's not clear what to do in this situation.
Here are some examples about what I mean.
```java
.addPerson(p1)
.addPeople(p1) // <- quite silly, maybe use (Person p, Person... ps) ?

.addPeople(peopleArray) // <- error, oops now I cannot splat arrays
// and one of the motivation behind keeping varargs variant was to handle arrays

// so let it be
.addPerson(p1)
.addPerson(p1, p2)
// you might just avoid using this varargs overload
// besides there are plan to add styles to fine tune what additional overloads are generated
// so maybe in future you will be able to disable doubtful stuff
```

**Comment by troinine** [comment]
I see, that makes sense. And fine tuning generated overloads with styles sounds great.
