### ISSUE TITLE
Copying-via-abstract-value?

### ISSUE THREAD

**Issue by io7m** [immutables/immutables#255]
Hello.

I have the following:

```
interface Base
{
  @Value.Parameter Area getArea();
}
```

I then have various implementations of `Base`, some of which are generated by the `immutables` package.

However, I now want to implement this following pseudo method:

```
public static <T extends Base> T scale(T b, double s)
{
   Area a = b.getArea();
   return b.withArea(new Area(a.x * s, a.y * s));
}
```

I can't work out how to achieve this. Specifically:

1. I want to be sure that the `scale` method doesn't know which concrete subclass it is receiving.
2. I want to be sure that the `scale` method returns a value of the same concrete class as the one it received.

If I define a `withArea` method on the abstract `Base` type, then the only possible type signature is:

```
interface Base
{
  @Value.Parameter Area getArea();
  
  Base withArea(Area a);
}
```

This means that implementations are permitted to return different subclasses from `withArea` and the use of the method won't satisfy the type signature of `scale` above.

**Comment by elucash** [comment]
There's one way that I know of, it is to use self type recursive generic definition.

```java
interface Base<T extends Base<T>>
{
  @Value.Parameter Area getArea();
  T withArea(Area a);
}

@Value.Immutable
interface HasArea1 extends Base<HasArea1> { }
@Value.Immutable
interface HasArea2 extends Base<HasArea2> { }

public static <T extends Base<T>> T scale(T b, double s)
{
   Area a = b.getArea();
   return b.withArea(new Area(a.x * s, a.y * s));
}
```
Hope this is useful.

**Comment by io7m** [comment]
Nice, didn't think of that. Thanks!
