### ISSUE TITLE
Cannot deserialize Mongo ObjectId

### ISSUE THREAD

**Issue by edreyer** [immutables/immutables#256]
I'm using version 2.1.10 of the immutables.org library.

The [documentation](https://immutables.github.io/mongo.html#id-attribute) indicates that you might configure Mongo Immutable entities like so...

```java
@Value.Immutable
@Gson.TypeAdapters
@Mongo.Repository("events")
public abstract class EventRecord {
  @Mongo.Id
  @Value.Default
  public Id id() {
    return Id.generate();
  }
  ...
}
```

However, when trying to deserialize a Mongo document into a class configured like this, there is a problem in the method `JsonParserReader.toGsonToken(com.fasterxml.jackson.core.JsonToken token)`

In this case, the supplied `com.fasterxml.jackson.core.JsonToken token` is a `VALUE_EMBEDDED_OBJECT`,  as defined in the `BsonParser:308`

```java
case BsonConstants.TYPE_OBJECTID:
					ctx.value = readObjectId();
					_currToken = JsonToken.VALUE_EMBEDDED_OBJECT;
					break;
```

but the `switch()` statement contained in the `toGsonToken()` method doesn't have a case for that, so it defaults to `JsonToken.NULL`

This obviously breaks and the entity cannot be successfully read from Mongo.

**Comment by elucash** [comment]
Thank you for the issue report! I think I can explain what happens, by I'm not sure what the actual situation. Special built in types such as `ObjectId`, `Binary` etc are handled by special set of adapters defined in [org.immutables.mongo.types.TypeAdapters](https://github.com/immutables/immutables/blob/master/mongo/src/org/immutables/mongo/types/TypeAdapters.java#L45), you can see how the code there bypasses code flow of `JsonParserReader.toGsonToken` by casting to `BsonReader` etc.. However, in order for this to work, the `TypeAdapters` adapter factory should be registered with `GsonBuilder`. If you use `RepositorySetup.forUri`, this will be done automatically by using `java.util.ServiceLoader` [see RepositorySetup.java:184](https://github.com/immutables/immutables/blob/master/mongo/src/org/immutables/mongo/repository/RepositorySetup.java#L184) and if it's not happening then something went wrong, you can check if `/META-INF/services/com.google.gson.TypeAdapterFactory` with correct entries is present in the classpath.

On the other hand, if you construct `RepositorySetup` using builder, you have to create `Gson` using `GsonBuilder` yourself registering the type adapter using already mentioned `ServiceLoader` mechanism or just by directly instantiating the factory.

```java
MongoClient mongoClient = ...
ListeningExecutorService executor = ...
GsonBuilder gsonBuilder = new GsonBuilder();
gsonBuilder. registerTypeAdapterFactory(new org.immutables.mongo.types.TypeAdapters());
```

RepositorySetup setup = RepositorySetup.builder()
    .database(mongoClient.getDB("test"))
    .executor(executor)
    .gson(gsonBuilder.create())
    .build();
```
 
Please, let us know if you can work around the problem. I also thinking how we can improve documentation for this case.

**Comment by edreyer** [comment]
Thank you very much.  That did in fact fix the problem for the 'Id' field.

I'm now configuring Gson like so...

```java
    @Bean
    public Gson gson() {
        GsonBuilder gsonBuilder = new GsonBuilder();

        for (TypeAdapterFactory factory : ServiceLoader.load(TypeAdapterFactory.class)) {
            gsonBuilder.registerTypeAdapterFactory(factory);
        }

        return gsonBuilder.create();
    }
```

However, I'm still running into a very similar issue with `java.util.Date` types.  The TypeAdapter<Date> doesn't appear to be doing it.  I'm experiencing the same issue I was having with the 'Id' type before I correctly configured the system.  

It appears to be an incompatibility between how Spring Data and Immutables persists dates.

Saved with Spring Data
```javascript
{
    ...
    "lastUse" : ISODate("2015-11-21T16:33:14.805Z"),
    ...
}
```

Saved with Immutables
```javascript
{
    ...
    "lastUse" : "Feb 17, 2016 10:00:12 AM",
    ...
}
```

It seems the first is more desirable, since it allows queries to do various date related operations, such as sorting, or where a date is less than X date.

Is there something else I'm not understanding?

**Comment by elucash** [comment]
`java.util.Date` is mutable so do not fit very well into Immutables, also this mongo module predates java 8, so we don't use `java.time` either. There just tiny wrapper around BSON special Date/ISODate type: `org.immutables.mongo.types.TimeInstant` which is basically UTC milliseconds holder. It is `Comparable`, so criteria object is generated with greater than, lower than and range constraint methods.

**Comment by edreyer** [comment]
That is a great point.  I'll have to re-evaluate some things.  Thanks for the comments.
