### ISSUE TITLE
mongodb module maintenance: upgrade to 3.x drivers and add some tests

### ISSUE THREAD

**Issue by elucash** [immutables/immutables#257]
Need to upgrade to 3.x version of MongoDB Java driver, currently we use 2.x version.
Plus it is desirable to add some tests.
Currently there is no resources to dig into this, hoping some committer or community contributor can help with this.

**Comment by asereda-gs** [comment]
Hello,

Are you planning to support both v2 and v3 versions at the same time ? I might try to submit a PR, if you don't mind.

**Comment by elucash** [comment]
Once upgraded, we don't need v2 support.
The upgrade PR is very welcome. I just didn't time to analyze changes in how v3 marshals object so our dirty hacks can be still be applied.
JFYI all those tricks were designed so you can, for example, parse result set with Gson/bson4Jackson streaming in one pass, as opposed to buffering each document separately and convert them individually. It's basically is the flaw is how v1/v2 driver and BSON infrastructure were designed. Basically, I've seen 2x to 3x times better performance for reasonably large result sets compared to Spring Data. v3 driver might have been improved for saner integration, but never actually looked into it.

**Comment by asereda-gs** [comment]
Please take a look at PR #688

**Comment by before** [comment]
Can this issue be closed because the MongoDB Java Driver version 3.5 is used already?

**Comment by elucash** [comment]
@before yep, it's done )
