### ISSUE TITLE
What is the best way to handle equality when floating-point values are involved?

### ISSUE THREAD

**Issue by bcalmac** [immutables/immutables#258]
The generated equals() compares floating-point values without an epsilon (as JUnit does), so values coming from different computations would end up as different even though they are equal from the point of view of the application.

Introducing a configurable epsilon for equals() wouldn't work either, because it breaks hashCode().

How do other people deal with comparing objects (or object graphs) that have floating-point values?

**Comment by elucash** [comment]
Immutables uses `Double.doubleToLongBits` and `Float.floatToIntBits` to strictly and unambiguously compare floating point values, and this is in line with how other built-in equality implementations works (think of contract and implementations of `Double.equals`, `Float.equals`, `Annotation.equals`  etc). If you need relaxed comparison of floating point values, you might need to customize (underwrite) `equals` or `hashCode`. But chances are that you will have to do this in a bunch of classes where you use floating point values, so it order to this under control, better alternative would be to create special immutables wrapper class around `double` or `float` to store and compareTo/equals/hashCode with a special semantic (with epsilon etc) but use unwrapped floats for actual computation.

**Comment by bcalmac** [comment]
Yes, that's probably the best approach. On the downside, the client API would need to unwrap the values on every use.
