### ISSUE TITLE
Style does apply to inner enclosed class

### ISSUE THREAD

**Issue by fzakaria** [immutables/immutables#260]
I've copied the sample online for `Tuple` and `Wrapped` however the generated source is not correct

```
@Value.Style(
        // Detect names starting with underscore
        typeAbstract = {"_*"},
        // Generate without any suffix, just raw detected name
        typeImmutable = "*",
        // Make generated it public, leave underscored as package private
        visibility = Value.Style.ImplementationVisibility.PUBLIC,
        // Seems unnecessary to have builder or superfluous copy method
        defaults = @Value.Immutable(builder = false, copy = false))
public @interface Wrapped {}
```

```
@Value.Enclosing
public class ExamplePrimitives {

    @Value.Immutable @Wrapped
    public abstract static class _Domain extends Wrapper<String> {}
}
```

The generated `ExamplePrimitives` has a `_Domain` class however I would have expected it to strip the underscore

**Comment by elucash** [comment]
`@Value.Enclosing` is a bit special. It requires that style definition will be consistent (read "the same") across top level and nested type, so that naming customization will work. In practice this means that if using `@Value.Enclosing` then a style definition should be put on the top level class or package rather than nested types. To correct the sample you provided either remove `@Value.Enclosing` or move `@Wrapped` to top level class, which will apply to all nested/enclosed types.

```java
@Value.Enclosing
@Wrapped
public class ExamplePrimitives {
    @Value.Immutable 
    public abstract static class _Domain extends Wrapper<String> {}
}

// or just..
public class ExamplePrimitives {
    @Value.Immutable @Wrapped
    public abstract static class _Domain extends Wrapper<String> {}
}
```

**Comment by fzakaria** [comment]
@elucash  thanks.
that explains it.

Do you mind answering me one more question:

Is there a recipe on how to get annotation processing for files within the test source directory?
I'm having difficulty with it.

(feel free to close this issue afterwards)

**Comment by elucash** [comment]
@fzakaria What kind of build tools/IDE do you use? For example in Eclipse the annotation processing only has one output/source folder. It might interfere with Maven in some ways. Usually some compromise might be achieved, either use build tool to generate java files and add those sources to IDE.

**Comment by fzakaria** [comment]
@elucash 
For those curious, here is a helpful entry for your `pom.xml` to make it work.
You then simply need to add the new directories as `generated-sources` in Eclipse/IntelliJ

I also like this approach because it does the pre-processing first and not at the same time as the compilation.

```
    <build>
        <plugins>
            <!-- Run annotation processors on src/main/java sources -->
            <plugin>
                <groupId>org.bsc.maven</groupId>
                <artifactId>maven-processor-plugin</artifactId>
                <executions>
                    <execution>
                        <id>process</id>
                        <goals>
                            <goal>process</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <outputDirectory>target/generated-sources/annotations</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- Run annotation processors on src/test/java sources -->
            <plugin>
                <groupId>org.bsc.maven</groupId>
                <artifactId>maven-processor-plugin</artifactId>
                <executions>
                    <execution>
                        <id>process-test</id>
                        <goals>
                            <goal>process-test</goal>
                        </goals>
                        <phase>generate-test-sources</phase>
                        <configuration>
                            <outputDirectory>target/generated-sources-test/annotations</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- Disable annotation processors during normal compilation -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <compilerArgument>-proc:none</compilerArgument>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

**Comment by elucash** [comment]
Preprocessing is indeed very useful, when you have annotation processing errors you can avoid a waterfall of "symbol not found" kind errors, but I also suspect you can configure this by using just compile plugin with 2 executions, one with `<compilerArgument>-proc:only</compilerArgument>` and the second with `<compilerArgument>-proc:none</compilerArgument>`

**Comment by fzakaria** [comment]
@elucash  I believe you are correct

**Comment by elucash** [comment]
added some words to documentation about `Enclosing` and styles, so this is at least mentioned. Thanks!
