### ISSUE TITLE
Add @SuppressFBWarnings if available so that findbugs doesn't complain on generated classes

### ISSUE THREAD

**Issue by pabad** [immutables/immutables#263]
I have a project that uses findbugs to do some linting, and have been struggling with generated classes causing violations (style violations in particular, which are not a problem for generated sources).

The problem is that findbugs works mostly analyzing classes, and our generated classes are already in the classpath used by findbugs. We need them there to properly analyze all the classes that use them, but it will be great if we don't get any report from those. 
I've seen that generated classes alredy include a `@SuppressWarning` annotation, but it has retention source, it is not available when analyzing class bytecode and hence FingBugs can't use it.

Findbugs provides it's own annotation for suppressing warnings (`edu.umd.cs.findbugs.annotations.SuppressFBWarnings`), which is retained at class level. It will be great to include such annotation when creating source files if the annotation is present in the classpath.

Having somehting like this will work (importing the annotation):
```java
@SuppressFBWarnings
final class ImmutableSomething implements Something {
```

For the record, findbug provides filtering capabilities, but as the generated classes live on the same package as their abstract/interface counterparts, I'd either have to filter by specifying each and every class name, or resorting to some wildcard like '**/Immutable*", which has a risk of matching other files.

**Comment by elucash** [comment]
Yes, we could add this one if it's in the classpath. Its very strange that those frameworks just not honor `SuppressWarinings("all")`, but that is not standard anyway. One the other hand it would be interesting to know if we have something that we could also fix in the generated code (I mean real issues, not funny dogmas circa 2002 ) )

**Comment by pabad** [comment]
The thing with Findbugs is that it doesn't see the annotation even if it would like to honor it, as it will check compiled bytecode instead of source code (hence the need for the custom suppresswarnings annotation).

As for the warnings, consider this value object:

```java
@Value.Immutable
public interface Test {
	String some();
	double other();
	int yet();
	Boolean something();
        Integer foo();
	MarketId m(); // Another Immutable

	static Builder builder() {
		return new Builder();
	}

	class Builder extends ImmutableTest.Builder { }
}
```

Findbugs is comlaining about:
1) Method withSome in the Immutable implementation, because it is comparing strings using ==.
```java
  public final ImmutableTest withSome(String value) {
    if (this.some == value) return this; // <--- Here is the warning flagged
    String newValue = Preconditions.checkNotNull(value, "some");
    return new ImmutableTest(newValue, this.other, this.yet, this.something, this.m);
  }
```

2) Method withFoo for a similar reason, comparing Integer instances using ==   (I've quickly tested and the same happens with other basic wrappers, like Double).
```java
  public final ImmutableTest withFoo(Integer value) {
    if (this.foo == value) return this;   // <--- Here is the warning flagged
    Integer newValue = Preconditions.checkNotNull(value, "foo");
    return new ImmutableTest(this.some, this.other, this.yet, newValue, this.something, this.m);
  }
```

3) Method withSomething, for comparing Boolean instances using == (you can create Boolean instances using the constructor):
```java
  public final ImmutableTest withSomething(Boolean value) {
    if (this.something == value) return this;
    Boolean newValue = Preconditions.checkNotNull(value, "something");
    return new ImmutableTest(this.some, this.other, this.yet, this.foo, newValue, this.m);
  }
```

4) Equals overriding a nullness annotation in an incompatible way:
```java
   public boolean equals(@Nullable Object another) {
```
This happens because unlike the rest of the world, findbugs interprets @Nullable as "I don't care for nullness analisys on this", and assumes that Object.equals has a potentially null argument (in findbugs terminology @CheckForNull). I would rather ignore this warning.


<br>
As a summary, It will be great adding the annotation, and I think you should consider comparing in the withXXX methods using equals whenever you are not using a basic type (which will require to add null-checks in some situations).

**Comment by elucash** [comment]
Yes, `SuppressWarnings` has source retention, so custom annotation for FindBugs makes some sense even if implementation dependent thing.
The way we handle comparison currently is according to documented http://immutables.github.io/immutable.html#copy-methods . But now I'm considering if it make sense to special case String and primitive wrapper types among other reference types and actually do `equals` check. Among these only very large equivalent strings could be a performance issue, though unlikely.

**Comment by elucash** [comment]
Released in 2.1.12. Thank you!

**Comment by Sarev0k** [comment]
Could you also add the `@SuppressFBWarnings` annotation to Modifiable generated classes as well?

I'm currently getting the following error from FindBugs, for the Modifiable generated implementation of equals in v2.2:
```
NP_METHOD_PARAMETER_TIGHTENS_ANNOTATION: Method tightens nullness annotation on parameter
```

**Comment by elucash** [comment]
Added, will be in the next release 2.2.1 Thanks!

**Comment by galan** [comment]
I get `RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE` on generated Immutables with version 2.4.1.
