### ISSUE TITLE
Question: Enclosing types,  can styles be applied ?

### ISSUE THREAD

**Issue by fzakaria** [immutables/immutables#268]
I'd like the enclosing class to have a style applied to it:

1. strip '_' prefix
2. Do not include "Immutable"

Is this possible?

I'm okay with the style applying both to the enclosing class and the inner classes, however they don't seem to be stick to the enclosing class.

**Comment by elucash** [comment]
There's separate attribute to customize enclosing `typeImmutableEnclosing`
here's an example. Hope this is what you are looking for
```java
@Value.Style(typeAbstract = "_*", typeImmutableEnclosing = "*")
@Value.Enclosing
public class _Enc {
	@Value.Immutable interface Cls {}
	@Value.Immutable interface Vls {}
}
```

**Comment by fzakaria** [comment]
bah can't believe I missed that.
