### ISSUE TITLE
Style parameter for specifying implementation target package

### ISSUE THREAD

**Issue by rolfw** [immutables/immutables#273]
It would be great if one could specify a target package for generating the implementation and associated classes. 

Example: an api designed with interfaces in `com.acme.api` with implementations in `com.acme.api.impl`. This is useful when you want to keep the API in a package that's free from the clutter of implementation classes. Especially when you have many of these, for instance when you design with value types as nested interfaces.

Currently there are two ways this can be done: 
 1) Create an abstract class in the target package and put the annotations there
 2) Apply the `@org.immutables.value.Value.Include(SomeAbstractClass.class)` to the package in `pacakge-info.java` of the desired target package (as suggested by Eugene in [this Google Groups topic](https://groups.google.com/forum/#!topic/immutables/We4G3Krti3g))

However, depending on how you use Immutables, these lead to either more boilerplate, less cohesion or both. Boilerplate because you have to create abstract classes just to indicate where you want the implementations to be generated. Less cohesion because in both approaches you design the API in one place and specify the implementation somewhere else. 

Although you could also argue that this implementation detail should then be in the `*.impl` package for another perspective on cohesion, I would like having the option to keep the design and specs of the implementation in one place.

**Comment by elucash** [comment]
Released in 2.1.14. Thank you!
