### ISSUE TITLE
Removing reduntant static modifier on abstract Builder nested in interface

### ISSUE THREAD

**Issue by rolfw** [immutables/immutables#275]
I'm declaring a builder type in my public API that should be extended in the implementation. I do that by declaring a static nested class named `Builder`, as described here: http://immutables.github.io/immutable.html#builder

My IDE indicates that the `static` modifier is redundant and because I try to limit visual clutter I removed it. 

However, when removed it doesn't get extended in the generated builder anymore.

Example:

```java
@Value.Immutable
interface AddSupplierCommand extends SupplierCommand {

    // #####  Properties  #####
    ...
    ...

    // #####  Builder  #####
    abstract static class Builder implements DomainCommand.Builder<AddSupplierCommand> {} // -> Remove the static modifier here and the generated builder doesn't extend this abstract type
}
```

Here's a screenshot of the warning:

![image](https://cloud.githubusercontent.com/assets/1259745/13547161/926cb5f6-e2c6-11e5-861d-7056d02cd9cb.png)

I couldn't easily find the documentation that confirms that static is indeed redundant when nested inside interfaces, but no compilation errors appear when I remove the static keyword after the implementation is generated.

**Comment by rolfw** [comment]
I just noticed I was using `v2.1.7` while the latest version of immutables is `v2.1.12`. In the latest version it seems this issue is already solved. Case closed, my apologies!

**Comment by elucash** [comment]
In Java modifiers have some implied values depending on context. Like all methods in the interfaces are implied to be `public` and `abstract`, and inner types implied to be `static`, during annotation processing if I ask member type of an interface if it's `static` it will say "yes", regardless of if modifier was present in a source or not.
Anyway, I'm glad that any fixes made work for this also.
