### ISSUE TITLE
@Value.Enclosing doesn't work with @Value.Include

### ISSUE THREAD

**Issue by rolfw** [immutables/immutables#276]
I'm using the @Value.Include annotation as suggested by Eugene [in this Google Groups topic](https://groups.google.com/forum/#!topic/immutables/We4G3Krti3g).

I'm also using `@Value.Enclosing` to instruct the compiler to generate the value type `Supplier.ID` as a nested class, i.e. `ImmutableSupplier.ID`. I do this to prevent name conflicts.

The ID type is generated as a nested class when applying `@Value.Immutable` to `Supplier.ID`. But when I apply `@Value.Include({Supplier.class, Supplier.ID.class})` to a target package instead, it generates a class `ImmutableID` at the upper level of that package.

**Comment by elucash** [comment]
It's not quite a "duplicate" but let's merge this discussion with #277 . I hope comments there will help to resolve this issue also.
