### ISSUE TITLE
unknown enum constant ImplementationVisibility.PACKAGE if style is applied to class directly

### ISSUE THREAD

**Issue by qinfchen** [immutables/immutables#291]
The consuming project would have the following warning if the immutable class that the project is consuming has Style annotation directly applied to the class. This error disappears if i create a style interface and apply it to the class.
```
warning: unknown enum constant ImplementationVisibility.PACKAGE
  reason: class file for org.immutables.value.Value$Style$ImplementationVisibility not found
1 warning
```

**Comment by qinfchen** [comment]
see https://github.com/palantir/dropwizard-web-security/pull/55

**Comment by elucash** [comment]
I guess I know what is happening here, I also checked the build file of the project you've referenced and it's seems that you need to actually add annotation jar. The combined jar (value-x.x.x.jar) works alone when it's used on compile classpath. If you put processors on the separate class-path like `processor`, then you still need annotations to be in a compile classpath.
You can get some hints from the Gradle example for Android http://immutables.github.io/getstarted.html#android

For your configuration it would be something like this
```groovy
  processor "org.immutables:value:$immutablesVersion"
  compile "org.immutables:value:$immutablesVersion:annotations"
```
Hope it will solve the problem, thank you!

**Comment by qinfchen** [comment]
thanks for the response. But I don't understand why the warning would disappear if i declare a new annotation with the same immutable styles.

**Comment by elucash** [comment]
I have no precise explanation, but there are all sort of quirks in the implementation of annotation processing and interactions with the compiler for both Javac and ECJ. Warning might disappear but the annotation configuration might not get processed correctly. 

Anyway when you run the annotation processor in a separate scope/classpath, then you should have annotation api (including enums etc) on the regular compilation classpath.

**Comment by qinfchen** [comment]
@elucash,  we don't want pull in a specific version of immutables, so that there is no version conflict for the consuming app. Do `annotations` change a lot?

**Comment by elucash** [comment]
It's the same version, but the artifact have an `annotations` classifier which usually indicates different packaging. The classifier logically is the part of the artifact name rather than version qualifier. in our case it is the same `value` artifact but with only annotation included and no annotation processor classes. You put this artifact on the compilation classpath as you would do for any other dependency. You dont need neither annotations-only nor the annotation processor artifact in runtime, so you can use `compileonly` or `provided` sort of dependency scope.
You have to do this only because of using special `processor` path for annotation processors. I cannot be sure how it works in gradle, but in maven its possible to just put single `value` artifact in 'provided' scope and all done. But there are many nuances with IDE intergration or other stuff that may require to use plugins with special isolated scope for annotation processors and thus requiring annotation artifact as compile dependency.

**Comment by qinfchen** [comment]
I tried `compileOnly`, `compileClassPath`, and `provided` and `Optional` from the https://github.com/nebula-plugins/gradle-extra-configurations-plugin and it still complains at compile time for the consuming project.

**Comment by qinfchen** [comment]
Friendly ping, @elucash anything suggestions?

**Comment by elucash** [comment]
@qinfchen can you please point me to a modules you have trouble with (if they are open source). I can clone the repo and try to play with the gradle configuration to see if there's a problem or at least to conclude the limitation of Immutables and explain workarounds.

**Comment by elucash** [comment]
There's another thought about it. The problem, as far as I understand, manifests itself when compiling some project that depends on already compiled immutable objects. In this case I suspect there's a thirdparty/rogue processor that scan annotations at a compile time and tries to make sense and warn about things it really shouldn't. For example if you're compiled some classes with annotations that are attached to a class file (as is the case with Immutables' annotations), then the dependent project could be compiled against those classes seemingly, but it should not mess with the annotations it has no class definitions for. So I would suggest to create a simple dependent project without bells and whistles and see if it compiles without warning, this may help to rule out an offending component.

Also the recommended way for the styles to be applied is via package (possibly even some parent package) or via a custom style annotation (which also may be attached to class or to a package). Inline styles should be used only for experimentation.

**Comment by qinfchen** [comment]
I will try to get a open source project that you look at soon. Sorry, I have been busy with other stuff for the past few days. It seems like there is bug somewhere, but unfortunately i am not familiar with annotation processor stuff enough to know the problem.

We may just go with applying the styles at the package level. Any particular reason that inline styles should be used only for experimentation? Thanks for all help by the way.

**Comment by elucash** [comment]
> We may just go with applying the styles at the package level. Any particular reason that inline styles should be used only for experimentation?

1. Processing time overhead for each style definition, but that is almost negligible
2. Bulky annotation clutter (http://www.annotatiomania.com/ would be a good illustration)
3. Duplication of the same (or worse: slightly differing) style definitions

But technically, inline styles work the same (except maybe for the case in this issue ;) ) as other kind of styles and win over package level or meta-annotation level ones.

**Comment by qinfchen** [comment]
@elucash, sorry about the delay. I created an example dropwizard app and it consumes a class that has inline style. Here is the PR for the change https://github.com/qinfchen/dropwizard-example-app/pull/2

**Comment by elucash** [comment]
Thank you! I cloned and was able to see the warning, will play with it and will report back about findings.

**Comment by elucash** [comment]
I've investigated that in a detail. It's a native javac warning issued when `-Xlint` is enabled. There is no category for it so it cannot be disabled, unlike other categorized warnings such as "unchecked" etc. Once you're linting, it's always enabled. Of course it would be no issues if we use source only annotation retention. But we use class-file retention for the annotations so incremental compilation and advanced discovery works during annotation processing.
As a workaround I may suggest using meta-annotation for styling as you did, and/or applying styles per package. Another option would be to create special source-only retention annotation used as both replacement for `@Value.Immutable` and a style holder: http://immutables.github.io/style.html#custom-immutable-annotation

**Comment by qinfchen** [comment]
Thanks for looking into this!
