### ISSUE TITLE
Value.Default should be treated as "nullable" by default

### ISSUE THREAD

**Issue by jangalinski** [immutables/immutables#294]
When I implement a property like this

     @Value.Default
     default String getFoo() {
           return "foo";
     }

The generated immutable checks for foo!=null in the setter, throwing an NPE when I try to set the vakue to null. This hurts when I use automatic mapping (from entity to immutable dto for example) because I can have null values in my source instance. My only way to work around this is marking the getFoo() method as Nullable. But reading the API this gives the wrong impression that the return value of getFoo() might be null, which is not the case, because I provided a Default value.

Expected behavior: when generating setters/builders for default values, imply that the set value can be null and do not throw an exception, as if it was annotated with Nullable.

Alternative solution (if switching existing behavior is not desired): allow boolean switch on Value.Default(nullable=true) so the generated code can be controlled as desired without poluting the API.

**Comment by ldriscoll** [comment]
I'm afraid I disagree on this, it breaks the convention that only getters that are marked @Nullable are nullable

**Comment by elucash** [comment]
Is there a way to configure mapper to not call setter/initializer at all instead of setting `null`? I think it is counter-intuitive to set `null` and then get back some other, default value.

**Comment by jangalinski** [comment]
Technically it would be something like this:

```
private Object value = null:

Object getValue() {
    return (this.value != null) ? value : DEFAULT_VALUE;
}

void setValue(Object value) {
     if (value != null) {
          this.value = value;
     }
}
```

I agree that using the Nullable annotation for this is somehow dirty. But what do you think about a configurable parameter in the Default annotation? Normal behavior would be like today, but in my special case I would add something like "softNullCheck=true" or "ignoreNPE="true" .... get what I mean?

**Comment by elucash** [comment]
What you might use is to declare attribute as `Optional` and use style `optionalAcceptNullable = true`, so it will have initializer that can accept null and treat it as `Optional.empty()`. Another consideration might be to create DIY attribute for this case.

```java
// just have nullable attribute and provide canonical, non-null getter for it
@Value.Immutable
public abstract class Val {
   abstract @Nullable A getAttribute();
   public A getAttributeCanonical() {
      @Nullable A a = getAttribute();
      return a != null ? a : DEFAULT_VALUE;
   }
}

// Use normalization feature
@Value.Immutable
public abstract class Val {
   public abstract @Nullable A getAttribute();
   @Value.Check protected Val normalize() {
      @Nullable A a = getAttribute();
      if (a == null) {
        return ImmutableVal.builder()
              .from(this)
              .setAttribute(DEFAULT_VALUE)
              .build();
      }
      return this;
   }
}

// here's an example using combination of internal nullable attribute and synthetic external attribute.
@Value.Immutable
public abstract class Val {
   abstract @Nullable A getInternal();
   @Value.Derived public A getExternal() {
      @Nullable A a = getInternal();
      return a != null ? a : DEFAULT_VALUE;
   }

  // will be auto-inherited by ImmutableVal.Builder
  // here assuming prefix (Style(init = "set*")
   abstract static class Builder { 
      public abstract ImmutableVal.Builder setExternal(@Nullable A value) {
          return setInternal(value);
      }
      abstract ImmutableVal.Builder setInternal(@Nullable A a); // will be implemented by inheriting builder
   }
}
```

Please, understand that we don't want to compromise more or less sound API that we generate for Immutables in order to adapt for the peculiarity of third-party mapping framework.
The "set null - get default" behavior just doesn't cut in.
If you just change the mapping framework to not invoke initializer if DTOs property value is null, that would solve the case easily.

**Comment by jangalinski** [comment]
Thank you all for  your input. I have a working workaround already but I will give the Optional-style approach a try, sounds good to me and I didn't know about it.
I still believe that "nullable" could be treated differently for getters and setters, but I see why you dont want to change this for Immutables. I will close this issue then.
