### ISSUE TITLE
@Value.Immutable doesn't work correctly if a Java package ignores convention and has a package with a capital letter

### ISSUE THREAD

**Issue by asheldon** [immutables/immutables#295]
Using Immutables 2.1.15

All lowercase packages work

```java
package org.immutables.example;

import org.immutables.value.Value;

@Value.Immutable
public interface Example {

}
```
but packages with uppercase do not work

```java
package org.Immutables.example;

import org.immutables.value.Value;

@Value.Immutable
public interface Example {

}
```

**Comment by elucash** [comment]
I would say it is by design (or rather shortcoming of import post-processing), but there is possible fix  to disable import post-processing if there are capitalized attribute names or packages (like in this case) detected. see #290

**Comment by asheldon** [comment]
I saw #290, I just didn't know capitalized properties were the same problem as a capital letter somewhere in a package name.  If this is a duplicate, then please feel free to close.

**Comment by elucash** [comment]
Yeah, I'll mention packages in #290. Thank you
