### ISSUE TITLE
Getting around not being able to have parameters at multiple levels

### ISSUE THREAD

**Issue by mmangliers** [immutables/immutables#303]
So I know (and understand why) we can't have something like the following:

```
Interface X {
    @Parameter x();
}
@Immutable Interface Y extends X {
    @Parameter y();
}
```

Parameters aren't allowed to be at different levels of the inheritance hierarchy, so this breaks. My issue is that my data model relies heavily on inheritance; I have items, and then many subtypes of items which need to introduce new parameters. I could have all the subtypes have default values and no new parameters, but this doesn't seem ideal. What's the standard approach here? Or is this an unavoidable limitation of immutables?

**Comment by elucash** [comment]
You can use builder to supply values across all hierarchy levels. Is there a case when you cannot use builder? Default values or optionals is also a good choice, and is actually it's what you might have to do if you want to safely introduce new attributes at a random level of hierarchy. It's a pity that we cannot provide compile time safety for builder (like error on missing attribute initializer), but only runtime exception.
