### ISSUE TITLE
InitShim causes problems with certain tools

### ISSUE THREAD

**Issue by dbevacqua** [immutables/immutables#309]
Certain tools (in our particular case, Hibernate and QueryDSL annotation processor) do not deal well with the InitShim field in classes generated from abstract value types with any @Default-annotated accessors. Making this field transient fixes the problem for us.

Given that the field is only ever referenced in constructors and is null thereafter, it seems like a valid change, and I cannot foresee any side-effects to not serializing initShim; it would be a pretty weird requirement to serialize an object half way through its construction (if indeed it is possible)!

I've created https://github.com/immutables/immutables/pull/308 but Travis build is currently failing as it is unable to deploy the snapshot. Should I update pom version on my side or is it just missing credentials?

**Comment by elucash** [comment]
released in v2.1.18. Thank you!
