### ISSUE TITLE
Maven javadoc plugin - cannot find symbol

### ISSUE THREAD

**Issue by owenrumney** [immutables/immutables#311]
I'm trying to retrofit immutables into our existing code base and I've modified an existing class 

``` java
@Value.Immutable()
@Value.Style(typeImmutable = "*", typeAbstract = "*Def")
@JsonDeserialize(as = PersistedChange.class)
@JsonSerialize(as = PersistedChange.class)
public abstract class PersistedChangeDef implements Comparable<PersistedChange>, Persistable {
...
}
```

Everything works and the regression tests run until I run `maven clean install` and the javadoc plugin runs. When this happens I get a load of `cannot find symbol` and `reference not found` errors 

eg; `cannot find symbol @JsonSerialize(as = PersistedChange.class)`

Not sure if I'm using it wrong or there is a work around - none of the existing issues seemed to quite reflect this issue.

Thanks

**Comment by elucash** [comment]
`PersistedChange.class` is not yet generated, but the javadoc should not assume everything is generated. But I guess it can, so some javadoc plugin/doclet might assume that. What you can try is to set `<additionalparam>-Xdoclint:none</additionalparam>` in maven-javadoc-plugin configuration. I'll try to reproduce it.

**Comment by elucash** [comment]
Another thought, if you use inverse generation, i.e. generated class considered canonical and used everywhere, then you don't need to specify `as = PersistedChange.class` which needed only if you use abstract class/interface everywhere so it can actually found implementation class for deserializtion. You can get away with having a single `@JsonSerialize` annotation.

```java
// assumming style defined elsewhere @Value.Style(typeImmutable = "*", typeAbstract = "*Def")
@Value.Immutable
@JsonSerialize
public abstract class PersistedChangeDef implements Comparable<PersistedChange>, Persistable {
...
}
```

**Comment by owenrumney** [comment]
Thanks. My preference is to go with inverse generation if I can solve the javadoc issue. The plugin is buried high in parent pom so need to look into making that change.

**Comment by elucash** [comment]
you already using the inverse generation judging from the example, all you need to do is to remove `as = PersistedChange.class`. One `@JsonSerialize` annotation would be enough, no need to add `@JsonDeserialize` also in this case.

**Comment by owenrumney** [comment]
Yes, sorry some context missing there - I had already successfully used PersistedChange as the abstract and ImmutablePersistedChange as my generated code. It worked fine but had a lot of knock on changes throughout the wider code base so I preferred to inverse generation.

**Comment by elucash** [comment]
Yeah, while non-inverse generation was our first strategy and have some straightforwardness, there are a lot small problems like the one you faced or with generic collection and variance where abstract and implementations mixed together. The reverse generation also have downsides in that if unable to compile you might get a whole lot of symbol not found errors. One of the ways to mitigate that is to split compilation in two phases, one with `-proc:only` during source-generation and `-proc:none` during actual compilation. But this is not required, just a way to get cleaned failures during compilation.

**Comment by elucash** [comment]
reopening as docbug, to somehow note this in documentation

**Comment by bbaugher** [comment]
I ran into this as well. Switching to `@JsonSerialize` helps but I had some abstract models that referenced other immutable implementations. I managed to get around this by setting `sourcepath` in the javadoc plugin config,

    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <configuration>
          <sourcepath>${project.basedir}/src;${project.basedir}/target/generated-sources/annotations</sourcepath>
          ...
      </configuration>
    </plugin>

**Comment by elucash** [comment]
@bbaugher I think it's a very good workaround to know about, thank you!
