### ISSUE TITLE
Avro Serialization

### ISSUE THREAD

**Issue by bkenned4** [immutables/immutables#312]
Hey everyone, 

The existing serialization support is immutables is great.  Any chance [Avro](https://avro.apache.org/) is on the radar?

Using immutables with avro is already pretty close to working; however, if one is to change the schema/datamodel, the existing framework falls a bit short.

Consider the case where a new field is added to a datamodel,  and with that new datamodel, you want to deserialize older data.  Avro can handle this, as long as you have a default value for this new field.  it can either be set as @Nullable or @AvroDefault("foo")

```
class OldPersonDatamodel {
   String firstName;
}
```

```
class NewPersonDatamodel {
   String firstName;
   @AvroDefault("foo") String lastName;
}
```

The breakdown is that the collection of annotations are required to be on the field level.

```
org.apache.avro.reflect
.
.
.
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.FIELD})
public @interface AvroDefault {
```

I'm sure there are other gotchas that crop up, but this was the first one I ran into, since schema evolution is a hard requirement for our usage of Avro.

Thanks,
Brad

**Comment by elucash** [comment]
Thank you for the feature request. Currently Avro is not a radar, but we might have something if we cab find a volunteer to contribute solution. The solution might put Avro annotations for generated fields.
Currently Immutables supports native java serialization, JSON and other binary serialization mechanisms are best supported by plugging in Jackson, like using CBOR, BSON or Smile. If you can you any of . We had a similar problem with Gson, where they had field annotation `@SerializedName`, but recently they switched to support methods also.
Also upcoming 2.2.beta version will allow having `Nullable` and `Value.Default` (or is it already supported?) on a attribute so you might get something without field annotation, but I'm do not have understarding how Avro works or how we can hook Immutables to work with it. Suggestions and contributions are welcome!

**Comment by bkenned4** [comment]
Thanks for the response.  One potential approach would be to have an annotation to specify what the fields should be annotated with.  
```
@FieldAnnotation(annoation=AvroDefault.class, value="food")
```

Definitely would be nice if the Avro followed Gson's lead and supported methods as well

**Comment by bkenned4** [comment]
InjectAnnotation gives the flexibility required to support Avro annotations, and thus schema evolution.  So I don't see a need for explicit Avro support
