### ISSUE TITLE
Wrap @Value.Modifiable+@Value.Immutable parameters with toImmutable

### ISSUE THREAD

**Issue by marquiswang** [immutables/immutables#314]
Right now, collection fields in Immutable classes are defensively copied and made immutable in the constructor. The same should be done with fields that are annotated with both @Value.Modifiable and @Value.Immutable (they should be defensively copied using Immutable*Class*.copyOf).

Preferable, the from method of the Modifiable version of a class with similar fields will pre-emptively call Modifiable*Class*.from as well.

**Comment by elucash** [comment]
The `Immutable*.copyOf` should already work if you enable `@Value.Style(deepImmutablesDetection = true)`. There are limitation is that it works only for plain attributes: doesn't work for collections of immutable objects etc.
I'll see how difficult is to make `Modifiable*.from()` to work in a similar manner. Thank you for suggestion!

**Comment by elucash** [comment]
released in 2.2 Thank you!
