### ISSUE TITLE
applying @jsonDeserialize at the package level

### ISSUE THREAD

**Issue by qinfchen** [immutables/immutables#315]
I couldn't get it to work when trying to use the generated value type. Is this still true? the linked example no longer use that pattern. 

>You can find some number of examples using Immutables and Jackson where annotations are cluttering definitions, annotations are piling on top of each other in many levels. But there are ways to significantly reduce annotation noise. Firstly, if using meta-annotated custom style annotation, you can move it to top level class, package (in corresponding pacakge-info.java file) or even parent package. Secondly, if you mostly use generated value type, rather that abstract value type, you don't need specify @JsonDeserialize(as = ImmutableForEverySingleValue.class), you can put @JsonSerialize on a package or use as meta-annotation along with style annotation to package or immutable type.

http://www.lagomframework.com/documentation/1.0.x/Immutable.html#Example-of-PersistentEntity-Events

**Comment by elucash** [comment]
I guess I need to correct the documentation, as  `@JsonSerialize` could not be applied to packages, but it can be applied as a meta-annotation, and that annotated annotation can be used on a package level. Let me know if it is not working this way. Thank you for reporting this!

**Comment by qinfchen** [comment]
sorry, meant to say that i applied it as a meta-annotation on a package level and couldn't get it to work. 
```
@JsonSerialize
@Value.Style(
    typeAbstract = "Abstract*",
    typeImmutable = "*",
    visibility = ImplementationVisibility.PUBLIC)
@interface MyStyle {}
```
and in my package-info.java
```
@com.madscience.MyStyle
package com.madscience.testing;
```

**Comment by elucash** [comment]
I tried just right now and it worked for me.

```java
package bbbb.xxxx;

import org.immutables.value.Value;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
@Value.Style(
		typeAbstract = "Abstract*",
		typeImmutable = "*",
		visibility = Value.Style.ImplementationVisibility.PUBLIC)
public @interface MyStyle {}
```

```java
@bbbb.xxxx.MyStyle
package bbbb.xxxx.gdgdg;
```

```java
package bbbb.xxxx.gdgdg;

import org.immutables.value.Value;

@Value.Immutable
public interface AbstractAurs {
	int a();
}
```

**Comment by elucash** [comment]
`Aurs` is generated and `Aurs.Json` too.
Can you spot any substantial differences in how you try it?

**Comment by qinfchen** [comment]
It didn't work for Eclipse Luna, but worked for gradle/Eclipse Mars/Intellij. I wonder if it has anything to do with the annotation processor that I am using.

**Comment by elucash** [comment]
Luna sr2 (4.4.2) works for me. Do you have a workaround or you're blocked by this?
Maybe there's something with other processors, I dunno

**Comment by qinfchen** [comment]
No, i am using Mars at the moment.

**Comment by elucash** [comment]
Closing as docbug, should work in later versions of Eclipse
