### ISSUE TITLE
META-INF/maven/com.google.guava/

### ISSUE THREAD

**Issue by pushbit** [immutables/immutables#321]
Is it necessary to include the `META-INF/maven/com.google.guava` directory in the `value` jar?  When running ProGuard these files are conflicting with the originals in the `guava` jar.  It's possible to work around this with extra build script configuration that tells ProGuard to ignore these files, but I would rather not have to include this extra step in the instructions for using my library (which uses Immutables) if possible.

**Comment by elucash** [comment]
They are not needed, I'll see if it's possible to disable them in jar and or shade plugin.
The other thought is: why this is a problem if you neither need annotation processor nor annotations at runtime. In a meanwhile can you use 'provided' or 'compileOnly' scope or instruct ProGuard to remove those jars (their content) completely?

**Comment by elucash** [comment]
Removed bogus maven-meta from jar files. Thank you for suggestion!

**Comment by elucash** [comment]
released in 2.2 Thank you!
