### ISSUE TITLE
FromAllAttributes was removed, create an alternative

### ISSUE THREAD

**Issue by ryan10132** [immutables/immutables#327]
Hello!

It looks like the static `fromAllAttributes` method is no longer generated as of ce76e4f29bd134b8afe09290b9313a512c3108e3, I'm wondering why as it's quite useful. Is there an alternative? I've seen others ask for an `of` method as well

**Comment by elucash** [comment]
Hi
but what is the use case?

If it's Jackson integration, we are covered by different means (JsonCreator method which takes synthetic object, which more compatible to pecularities of Jackson binding with special annotations).

If you just want to have a factory methods from all the attributes, you can use `@Value.Style(allParameters = true)`. This will turn all attributes as having an implicit `@Value.Parameter` annotation. This will result in the generated `of` method with all the parameters. And you can rename the `of` method by using styles also `Style(of = "myFavoriteName")`.
