### ISSUE TITLE
immutables maven install error with jdk7

### ISSUE THREAD

**Issue by gubei** [immutables/immutables#336]
I want to build immutables on my machine, but find error .

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project value-fixture: Execution default-compile of go
al org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-compiler-
plugin:3.5.1:compile: java.lang.UnsupportedClassVersionError: javax/tools/DiagnosticListener : Unsupported major.minor version 52.0

How can I fix it?  
thank you

**Comment by elucash** [comment]
While compiled Immutables are working with JDK7 and JDK8, the actual build contains modules which require java 8 to build. Unfortunately we don't have any maven profiles to disable this, but you can try disable compilation of some (or one) modules which use 1.8  (like commenting out `<module>value-fixture</module>` in the main `pom.xml`)

**Comment by gubei** [comment]
Thank you for your helping.
But I still want to know why value-fixture need JDK8 to compile ?

**Comment by elucash** [comment]
There are tests for a lot of features, among them are java 8 language features and JDK 8 apis (`java.util.Optional` etc). Other modules also have tests which can be run in java7 environment.

**Comment by gubei** [comment]
thank you! n
