### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/base/Objects;

### ISSUE THREAD

**Issue by vovkab** [immutables/immutables#337]
Config per documentation:

```
apt 'org.immutables:value:2.2'
provided 'org.immutables:value:2.2'
provided 'org.immutables:builder:2.2'
provided 'org.immutables:gson:2.2'
```

Is guava is now required starting from 2.2?

```
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/base/Objects;
  at ImmutablePhoto.equalTo(ImmutablePhoto.java:355)
  at ImmutablePhoto.validate(ImmutablePhoto.java:422)
  at ImmutablePhoto.access$2700(ImmutablePhoto.java:31)
  at ImmutablePhoto$Builder.build(ImmutablePhoto.java:633)
  at Photo$Builder.build(Photo.java:193)
```

**Comment by elucash** [comment]
The problem is in runtime, not compile time, so there're chances that you've compiled with guava in the classpath. Can you, please, help trace from which artifact the dependency is coming from during compilation?
You can try to use style `jdkOnly = true` to force generation of code without guava references. If that will not work that is definitely a bug.

**Comment by vovkab** [comment]
@elucash thanks for details!

Yes you right, I checked dependencies and problem with one of the libraries we use. In documentation they say to use `provide` for their compiler, which leaks guava in our class path. Replacing `provide` with `apt` for this library compiler fixed my issue.

**Comment by vovkab** [comment]
p.s. `jdkOnly` is missing from documentation:

**Comment by elucash** [comment]
There we basically outline what is possible with styles and ask to resort to javadocs for specific style attributes as there are too much to cover/duplicate. Contributions to documentation are very welcome
