### ISSUE TITLE
[android] Generated modifiable type has compile errors (incorrectly references immutable type)

### ISSUE THREAD

**Issue by sschaap** [immutables/immutables#343]
Generated code for types annotated with `@Modifiable` contains compile errors. Specifically, it references the immutable type's `requireNonNull(...)` method, which

1. may not exist when the `@Immutable` annotation is not also specified; and
2. otherwise has private access in the generated immutable type and is not accessible.

This behavior is observed with at least version 2.1.18 and the current 2.2 release.

Please find attached a sample android project showcasing the issue and a ZIP with generated sources:

[modifiable-android.zip](https://github.com/immutables/immutables/files/284232/modifiable-android.zip)
[generated-sources.zip](https://github.com/immutables/immutables/files/284233/generated-sources.zip)

**Comment by elucash** [comment]
To be fixed in next release (2.2.1). Thank you for reporting this!

**Comment by sschaap** [comment]
My pleasure. Thanks in advance!

**Comment by elucash** [comment]
Released in 2.2.1 Thank you!
