### ISSUE TITLE
IndexOutOfBoundsException for raw Map

### ISSUE THREAD

**Issue by josuf107** [immutables/immutables#344]
Code to generate exception:

    @Value.Immutable
    public interface RawResult {
        public Map getResult();
    }

generates:

    [javac] error: org.immutables.value.internal.$processor$.$Processor threw java.lang.IndexOutOfBoundsException: index (1) must be less than size (0)
    [javac]     at org.immutables.value.internal.$guava$.base.$Preconditions.checkElementIndex($Preconditions.java:310)
    [javac]     at org.immutables.value.internal.$guava$.base.$Preconditions.checkElementIndex($Preconditions.java:292)
    [javac]     at org.immutables.value.internal.$guava$.collect.$RegularImmutableList.get($RegularImmutableList.java:65)
    [javac]     at org.immutables.value.internal.$guava$.collect.$Iterables.get($Iterables.java:728)
    [javac]     at org.immutables.value.internal.$processor$.meta.$ValueAttribute.secondTypeParameter($ValueAttribute.java:527)
    [javac]     at org.immutables.value.internal.$processor$.meta.$ValueAttribute.getSecondaryElementType($ValueAttribute.java:713)
    [javac]     at org.immutables.value.internal.$processor$.$Generator_Immutables$44.run($Generator_Immutables.java:10747)
    [javac]     at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:251)
    [javac]     at org.immutables.value.internal.$generator$.$Templates$Fragment.toCharSequence($Templates.java:261)
    [javac]     at org.immutables.value.internal.$generator$.$Output$OutputFilter.toCharSequence($Output.java:105)
    [javac]     at org.immutables.value.internal.$generator$.$Output$OutputFilter.run($Output.java:98)
    [javac]     at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:251)
    [javac]     at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
    [javac]     at org.immutables.value.internal.$processor$.$Generator_Immutables._t36__immutableImplementationType($Generator_Immutables.java:10693)
    [javac]     at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:12715)
    [javac]     at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:251)
    [javac]     at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
    [javac]     at org.immutables.value.internal.$processor$.$Generator_Immutables._t20__generateImmutableMembers($Generator_Immutables.java:6647)
    [javac]     at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:12699)
    [javac]     at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:251)
    [javac]     at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
    [javac]     at org.immutables.value.internal.$processor$.$Generator_Immutables._t4__generateImmutable($Generator_Immutables.java:359)
    [javac]     at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:12683)
    [javac]     at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:251)
    [javac]     at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
    [javac]     at org.immutables.value.internal.$processor$.$Generator_Immutables$1.run($Generator_Immutables.java:23)
    [javac]     at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:251)
    [javac]     at org.immutables.value.internal.$generator$.$Output$6.invoke($Output.java:161)
    [javac]     at org.immutables.value.internal.$generator$.$Intrinsics.$($Intrinsics.java:96)
    [javac]     at org.immutables.value.internal.$processor$.$Generator_Immutables._t0__generate($Generator_Immutables.java:20)
    [javac]     at org.immutables.value.internal.$processor$.$Generator_Immutables$FragmentDispatch.run($Generator_Immutables.java:12679)
    [javac]     at org.immutables.value.internal.$generator$.$Templates$Fragment.invoke($Templates.java:251)
    [javac]     at org.immutables.value.internal.$generator$.$AbstractGenerator.invoke($AbstractGenerator.java:59)
    [javac]     at org.immutables.value.internal.$processor$.$Processor.process($Processor.java:49)
    [javac]     at org.immutables.value.internal.$generator$.$AbstractGenerator.process($AbstractGenerator.java:89)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
    [javac]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
    [javac]     at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
    [javac]     at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:439)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:353)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:342)
    [javac]     at com.sun.tools.javac.main.Main.compile(Main.java:333)
    [javac]     at com.sun.tools.javac.Main.compile(Main.java:76)
    [javac]     at com.sun.tools.javac.Main.main(Main.java:61)
    [javac] 1 error

It looks like the code is trying to use the second type parameter and blowing up because it isn't there. On the one hand, I guess raw maps shouldn't ever be used, on the other, this was a perplexing error to encounter.

**Comment by elucash** [comment]
We'll make raw containers as regular, pass-thru attributes, and, probably, should issue additional warning about this. Thank you for reporting this!

**Comment by elucash** [comment]
Released in 2.2.1 Thank you!

**Comment by josuf107** [comment]
Sorry to swing back to this so much later but really appreciate the quick resolution here! Thanks!

**Comment by elucash** [comment]
There's latest 2.2.5 with some more fixes, thank you!
