### ISSUE TITLE
Using Nullable with Value.Default do not work as expected

### ISSUE THREAD

**Issue by vovkab** [immutables/immutables#345]
I think @Value.Default should be not null by definition, since nullability is already covered by `@Nullable/@NonNull` annotations. For example this looks really confusing:

```java
public class ModelTest {
    @org.immutables.gson.Gson.TypeAdapters @Value.Immutable
    private abstract static class Model {
        @Nullable @Value.Default
        String name() { return "default"; }
    }

    private Gson gson = new GsonBuilder()
            .registerTypeAdapterFactory(new GsonAdaptersModel())
            .create();

    @Test public void test() {
        assertNotNull(gson.fromJson("{}", Model.class).name());
        assertNotNull(gson.fromJson("{'name':null}", Model.class).name());
        assertNotNull(ImmutableModel.builder().build().name());
        assertNotNull(ImmutableModel.builder().name(null).build().name());
    }
}
```

Tests will pass, but this will be highlighted as warning and you need to make null checks everywhere in your code:

```java
// Method invocation 'toString' may produce 'java.lang.NullPointerException'...
String name = ImmutableModel.builder().build().name().toString();
```

**Comment by elucash** [comment]
With 2.2 we added ability for default attributes to be nullable. (see #299) This allows `null` to be the default value, but also be computed to some other value (body of the default initialized can compute value based on other mandatory attributes). Some of the use cases is REST CRUDs where some distinction need to be made between specified as null and non-specified values.
So the workaround is simple, just don't put `Nullable` on a default method.

**Comment by elucash** [comment]
But on the other hand I'm checking if it's work correctly, as we should be able to set such attributes to `null` and as you mentioned this do not work.

**Comment by vovkab** [comment]
If you don't put `@Nullable` test will fail :)

Back to #299 , what are our requirements?
1. by default it is null
`@Nullable List<String> names();`
2. if we add value it should create list and add value
`builder().addName("John")`
3. be able to create empty list
`builder().setNames(new LinkedList())`

Why we need Value.Default again? :)

**Comment by vovkab** [comment]
> But on the other hand I'm checking if it's work correctly, as we should be able to set such attributes to null and as you mentioned this do not work.

I think it is working correctly right now, the only issue is how we treat `Value.Default` and what it actually  mean. In my opinion it should be always NonNull and be a way to fallback if actual value is null.

**Comment by elucash** [comment]
I totally agree that nullability with default attributes maybe not the best idea ever, but as it's done it works pretty orthogonally: nullability says that the attribute can be null, but default value is what value to use when none is supplied. When `null` is supplied and is allowed, well it should be `null`, it cannot resort to default value in this case. It's just nullable in implicitly defaults to `null` when there's no default initializer.

I've fixed the behavior so in the initial case the second and the forth assertNonNull should fail.
