### ISSUE TITLE
@Value annotations and immutables processor are published in the same jar

### ISSUE THREAD

**Issue by tjwilson90** [immutables/immutables#350]
It would be nice if a separate annotations jar were published containing only the annotations.

This would make it possible for a project to depend on the annotations at compile and runtime, but the processor only at compile time. This is nice for cutting down size of deployed dependencies and avoiding version conflicts without having to exclude the annotations at runtime (which is technically legal, but makes for lots of compiler warnings).

Ultimately not super important, but a nice to have.

**Comment by tjwilson90** [comment]
Also, another really nice thing to go along with this (from my perspective) would be to publish the annotations jar with 1.6 source compatibility.

**Comment by elucash** [comment]
There's artifact with `annotations` classifier like `org.immutables:value:2.2.1:annotations`. IIRC it's compiled for java 6 target. Please, take a look if you can use it.

**Comment by tjwilson90** [comment]
Cool, never mind then. Thank you
