### ISSUE TITLE
Immutable or modifiable are shadowing fields from superclass

### ISSUE THREAD

**Issue by digitalillusion** [immutables/immutables#351]
Hello,
I have the following code which uses immutables library; in the example I use Value.Modifiable annotation, but the same happens for Value.Immutable.

      public class Unit {

           protected String type = null;

           public String getType() {
               return type;
           }

           @Value.Modifiable
           @SuppressWarnings("immutables")
           @Value.Style(typeAbstract = "Abstract*", typeModifiable = "*", set = "with*", visibility =   Value.Style.ImplementationVisibility.PUBLIC)
           static abstract class AbstractUnitBuilder extends Unit {
  
             @Nullable
             public abstract String getType();
           }
         }

This is generating the following builder (extract):

         @SuppressWarnings("all")
         @ParametersAreNonnullByDefault
         @Generated({"Modifiables.generator", "Unit.AbstractUnitBuilder"})
         @NotThreadSafe
         public final class UnitBuilder extends Unit.AbstractUnitBuilder {
                private @Nullable String type;

                @Override
                public final @Nullable String getType() {
                      return type;
                }

                public static UnitPriceBuilder create() {
                    return new UnitPriceBuilder();
                }

                public UnitBuilder withType(@Nullable String type) { ... }
        }

As you may see above the problem is that the type field is not inherited from the superclass Unit.AbstractUnitBuilder (and thus from Unit)
This leads to the following problem:

        Unit unit = UnitBuilder.create().withType("T");
        System.out.println(unit.getType()); // OUTPUT: T
        System.out.println(unit); // OUTPUT: class Unit { type: null }

The reason is that the type field of the builder is shadowing the type field in the superclass.
Is there a way to have Immutables not generate fields that are inherited from superclass, or to explicitly tell not to add any field at all in generated class (so that the superclass fields will be used by generated code instead)? Thank you very much.

**Comment by elucash** [comment]
Hi
It's not fully clear to me what result is desirable, but I guess it could be achieved without changing anything in Immutables. First of all, it's strongly suggested to not introduce fields in value objects. Other than that, just use abstract attributes.

```java
public abstract class Unit {
       public abstract @Nullable String getType();
       public abstract Unit withType(String type); // optionally declare abstract setter if needed

       @Value.Modifiable
       @SuppressWarnings("immutables")
       @Value.Style(typeAbstract = "Abstract*", typeModifiable = "*", set = "with*", visibility =   Value.Style.ImplementationVisibility.PUBLIC)
       static abstract class AbstractUnitBuilder extends Unit {
       }
     }
```

I suspect that the trouble is with integration JAXB, but it's also possible to use Jackson with some XML extensions to integrate.

**Comment by digitalillusion** [comment]
Hi, thanks for replying. The problem with your proposition is that the state of the object is contained in the UnitBuilder generated implementation, while it would be more desirable that the state is completely contained in the built Unit and the builder is just a wrap around.

**Comment by elucash** [comment]
to finish this thread. Immutables toolkit is based on the concept of abstract value type and abstract accessors where immutable (or mutable) implementation is generated. Custom managed is state is beyond the scope of Immutables. I've seen projects like Pojo-builder which may be what you're looking for.
