### ISSUE TITLE
Codegen still isn't quite right in Eclipse (but it's close)

### ISSUE THREAD

**Issue by bolinfest** [immutables/immutables#352]
I filed an issue against Eclipse because I'm not sure if it's Immutables or Eclipse that needs to get fixed:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=495225

`import` statements for the other generated files do not seem to get generated, even in the most recent release candidate for the new Eclipse that's supposed to come out this month.

/cc @bhamiltoncx

**Comment by elucash** [comment]
While investigating this, it looks like we have some trouble as Eclipse guys changed the way annotation processor as loaded in IDE with regard to classloading, rendering quite a few of our Eclipse-specific workarounds useless. Can you, please, provide isolated repro case? Although I have suspicion that it might work from the command line (but it might not, as well). All in all, buck classes are compiling great with older Eclipse (with the exception of very few cases unrelated to this problem).
So I'm currently investigating workarounds for workarounds to work (pun intended)

**Comment by bolinfest** [comment]
In the build.xml file for Buck, you can see that, for automated builds, we
do use ECJ to compile most of our Java code with a version we have vendored
into our third-party directory. So yes, it does seem to work from the
command line.

**Comment by elucash** [comment]
newly released 2.2.2 contains fix/workaround for this. I've tried Eclipse IDE compilation in Neon and Luna, as well as `ant clean compile` for Buck project, both successfully. Upgrade from 2.1.18 to 2.2.2 should be non-issue as backward compatibility is maintained, but there are still may be unknown bugs etc. Can you, please, try if it works in all the scenarios we are interested in.

**Comment by dbevacqua** [comment]
Hello. It looks like this bug has reappeared. I am seeing identical behaviour in both STS 3.7.0/Eclipse 4.5.0 and STS 3.8.4/Eclipse 4.6.3 using this minimal-ish Maven project:

https://github.com/treatwell/immutables-eclipse-test

I notice that incremental compilation seems to work OK, i.e. when I touch a Java file which is missing imports (in my example, `ImmutableThingHolder`), then the problem resolves itself.

I have reproduced the issue with Immutables 2.4.4 (the version we are currently using) and 2.5.3. 2.2.2 works fine as described in the comments on this issue.

**Comment by dbevacqua** [comment]
I now only seem to be able to able to reproduce this intermittently, albeit on vanilla STS/clean workspace and checkout.
