### ISSUE TITLE
@Modifiable creates objects whose collection fields are UnmodifiableCollection

### ISSUE THREAD

**Issue by digitalillusion** [immutables/immutables#358]
Hello,

it appears that the following code:

```
  @Value.Modifiable
  class  Unit {
      abstract List<Float> getPrices();
  }
```
generates a ModifiableUnit that exposes a getPrices(). However, the list throws UnsupportedOperationException when attempted to call its add() method.

**Comment by elucash** [comment]
Just tried

```java
@Value.Modifiable
abstract class Unit {
  abstract List<Float> getPrices();
}
```

```java
  @Test
  public void modifiableCollection() {
    ModifiableUnit unit = ModifiableUnit.create();
    unit.getPrices().add(1.0f);
    unit.addPrices(2.0f);

    check(unit.getPrices()).isOf(1.0f, 2.0f);
  }
```

The test passes. Can you, please, provide some additional details or create a repro case?

**Comment by digitalillusion** [comment]
Indeed it's not reproducible. I demand pardon for having you lose time about this, I'll try to be more analytic in the future.
