### ISSUE TITLE
Maven maven-compiler-plugin Xmaxerrs tip

### ISSUE THREAD

**Issue by nezda** [immutables/immutables#365]
Our team uses immutables extensively and runs into an interesting problem while adding / changing the api of a value object and making mistakes, as you do.  If you have a code error in your immutables annotations and you do clean build (`mvn clean install`), you may well hit the default 100 error limit of `javac` and end up clipping the nice immutables error message describing what you did wrong.  This might look like this

```
...
[ERROR] /Users/nezda/code/src/main/java/Bar.java:[13,19] cannot find symbol
  symbol: class Foo
[INFO] 100 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.096 s
```

If you were using plain `javac` to compile, you'd find you need to add compiler flag `-Xmaxerrs 1000000`.  If you're using `mvn`, you'd probably try customizing `maven-compiler-plugin` (I'm using version 3.2) `configuration` by adding `<compilerArgs><arg>-Xmaxerrs 1000000</arg></compilerArgs>` but the compiler plugin will reject that with `Fatal error compiling: invalid flag: -Xmaxerrs 1000000`.  Ultimately no variant of this seemed to work *in* `<compilerArgs>`. But this works,

```xml
    ...
    <compilerArguments>
        <Xmaxerrs>1000000</Xmaxerrs>
    </compilerArguments>
</configuration>
```

(potentially as a sibling to other `<compilerArgs>` configuration) and then you'll see all the errors including the awesome immutables error message telling you what to do! e.g.,

```
[ERROR] /Users/nezda/code/src/main/java/Baz.java:[18,17] Should not inherit Bar which is a value type itself. Avoid extending from another abstract value type. Better to share common abstract class or interface which are not carrying @Immutable annotation
[INFO] 108 errors
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.033 s
```
(hacked the class names / error messages)

There are related issues ([[1](https://issues.apache.org/jira/browse/MCOMPILER-130)][[[2](http://stackoverflow.com/questions/3358242/is-it-possible-to-get-maven-to-accept-maxerrs-for-its-compiler-plugin)]) but until those are resolved something about this might make a good addition to the docs - this makes developing with immutables more pleasant for us.

Related, when I was trying to see if this was already mentioned in the docs, I always go straight to the [Guide](http://immutables.github.io/immutable.html) and found it a little suprising it wasn't a superset of the content of [Getting Started](http://immutables.github.io/getstarted.html) - maybe Getting Started could be a section in / repeated in the Guide?

**Comment by elucash** [comment]
Thank you for the tip! I'll try to integrate this somehow into guides/getting started section.

**Comment by elucash** [comment]
Added to http://immutables.github.io/getstarted.html#troubleshooting section. Thanks!
