### ISSUE TITLE
Contribute documentation to Dash

### ISSUE THREAD

**Issue by jfairley** [immutables/immutables#374]
I use an awesome app called [Dash](https://kapeli.com/dash) for offline documentation. Basically it downloads documentation into a local cache, so that it can be accessed and searched offline.

It would be great if I could cache the Immutables documentation, too, but it's not free. It requires someone to upload a docset to their server. I considered doing it myself, but in order to keep documentation up-to-date over time, it should probably come from the owner. 😉 

Here's a link to Dash's docset generation guide.
https://kapeli.com/docsets

**Comment by elucash** [comment]
This is a good idea. Unfortunately, currenly, I don't have much time to invest into this kind of tool, but if you can contribute initial files/structure for this, then I'll try to update it when adding new pages/topics.

The documentation is currently in `immutables/immutables.github.io` repository in the `src` branch: https://github.com/immutables/immutables.github.io/tree/src , it is compiled with jekyll to the master branch, during build most of the non-`.md` files are just copied. Please, feel free to create a PRs there.

**Comment by jfairley** [comment]
Sounds good. I'll TODO this, and comment back when I have something.

On Wed, Jun 22, 2016, 2:23 PM Eugene <notifications@github.com> wrote:

> This is a good idea. Unfortunately, currenly, I don't have much time to
> invest into this kind of tool, but if you can contribute initial
> files/structure for this, then I'll try to update it when adding new
> pages/topics.
>
> The documentation is currently in immutables/immutables.github.io
> repository in the src branch:
> https://github.com/immutables/immutables.github.io/tree/src , it is
> compiled with jekyll to the master branch, during build most of the non-
> .md files are just copied. Please, feel free to create a PRs there.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/immutables/immutables/issues/374#issuecomment-227865079>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA8k4-J1M5TClHY0BnGJXsXJO4wd-JRiks5qOZmugaJpZM4I8BHw>
> .
>
-- 

- Jeff
