### ISSUE TITLE
Wrapper annotation including @Value.Immutable

### ISSUE THREAD

**Issue by alexeyr** [immutables/immutables#376]
Examples in http://immutables.github.io/immutable.html#wrapper-types look good, but still have a bit of boilerplate in that `@Value.Immutable @Wrapped` has to be repeated every time. Is there a way to reduce it to `@Wrapped`? Or would it be impossible because there is no way to tell the annotation processor to look for it?

**Comment by elucash** [comment]
Yes, there is, please see  http://immutables.github.io/style.html#custom-immutable-annotation documentation section

**Comment by alexeyr** [comment]
Yes, sorry. Saw it later on.

**Comment by alexeyr** [comment]
Maybe it should also be linked directly from the "Wrapper types" section?

**Comment by elucash** [comment]
just thought about that, crosslink would be nice
