### ISSUE TITLE
Immutable Json template: wrapper types necessary?

### ISSUE THREAD

**Issue by henryptung** [immutables/immutables#380]
Was looking into how the `IsSet` fields are used in the `Json` Jackson kludge type, and noticed that despite the flag, the nullable wrapper types are still used for the values. (I was using version 2.2.2, which didn't actually use the `IsSet` fields, which made Findbugs angry, but that seems to have been fixed since).

In particular, for this line: https://github.com/immutables/immutables/blob/3ec7ee7af94e0c70f9702fbee44776e7dc7a93b3/value-processor/src/org/immutables/value/processor/Immutables.generator#L2008

Can `[atNullable][v.wrapperType] [v.name]` be replaced with `[v.atNullability][v.type] [v.name]` for a (very minor) avoidance of boxing?

**Comment by elucash** [comment]
Maybe, need to think about it. I would stress that this could be refined more because of clarity/style to avoid boxing rather than avoiding runtime overhead associated with it.
Thank you for raising this!

**Comment by elucash** [comment]
Released in 2.2.9 Thank you!
