### ISSUE TITLE
Mongo repository.find(<criteria>).fetchAll() never completing

### ISSUE THREAD

**Issue by Favorlock** [immutables/immutables#382]
Futures are never completing with the mongo repositories. Client shows as connected to MongoDB.

**Comment by elucash** [comment]
Thank you for reporting this! Can you please, provide some details. Does it never completing for all queries or only for some? Can you provide a repro case (archive with files or some Gist?)

**Comment by Favorlock** [comment]
I discovered the issue. I was using the executors incorrectly it appeared. Changed it to use an executor produced by MoreExecutors class.
