### ISSUE TITLE
Unsupported Operation Exception when executing find query.

### ISSUE THREAD

**Issue by Favorlock** [immutables/immutables#384]
Stacktrace: http://pastebin.com/FGin0z9m
Entity Code: http://pastebin.com/3w7SPXbF
Query Code: http://pastebin.com/nbnfMiWg

If there is any other information you need please let me know.

**Comment by elucash** [comment]
I haven't looked deeply into this yet, but can you, please, make sure you're running version of 2.12+ of Java driver as opposed to 3.0+ which is supported yet (#257)
