### ISSUE TITLE
Code not generated in some projects

### ISSUE THREAD

**Issue by ldriscoll** [immutables/immutables#386]
I'm having a really hard time tracking this down, but we have some projects, that have the correct imports, but are no longer generating the immutable classes.
All was working in 2.1.15, but after upgrading to 2.2.8 the files are just not being created.  I've experimented around, and things work with 2.2, but not 2.2.1.
It's worth noting that the project I'm seeing this on is quite large.

**Comment by elucash** [comment]
Doing a bit of archeology, the probable reason might be the change #352 , but I'm nor sure yet. Can you, please, force the annotation processor to be `org.immutables.value.processor.Processor` (instead of `org.immutables.processor.ProxyProcessor`, autodiscovered using `META-INF/services` ) and see if it works with  2.2.1+

**Comment by ldriscoll** [comment]
I just tried `org.immutables.value.processor.Processor` and `org.immutables.value.internal.$processor$.$Processor` in META-INF/services/javax.annotation.processing.Processor; neither helped.

**Comment by ldriscoll** [comment]
it's worth noting that if you try to compile individual files in intellij, it will generate the code.

**Comment by elucash** [comment]
sorry, I forgot about name mangling. I'm not sure were compilation is not working, in the build or in the IDE? Is there any chance for repro case?

**Comment by ldriscoll** [comment]
compilation is failing through maven, as well as building the whole project in the IDE, however building individual files in the IDE is working

**Comment by ldriscoll** [comment]
sadly this is an internal repo, and since I can't see what is the cause, it's hard to make it reproducible.

**Comment by ldriscoll** [comment]
is it possible to get a debug version of the processor, so it spits stuff out as it's parsing files.  I wonder if it's failing somewhere and just dying quietly.

**Comment by elucash** [comment]
Can you make some debug build, like `-X` or something to see underlying exception if any?
Can we see actual error, please, refer to note about max errors #365
Do you use any tools on the classpath that supply/use compiler classes (Findbugs, Errorprone or similar)?

**Comment by elucash** [comment]
You can split compilation in phases as discussed in this thread:
https://groups.google.com/forum/#!topic/immutables/LQonwnhXSOo
This may help to isolate errors

**Comment by ldriscoll** [comment]
sadly, I'm not 100% confident what file it was working on at the time

**Comment by elucash** [comment]
The check failed is this (most probably)
checkArgument(typevarArguments == null || allowedTypevars.length == typevarArguments.length);

**Comment by elucash** [comment]
Is there some interesting cases with extending parametrized types and supplying (or not supplying) type parameters. Are there cases when class/interface extends another as raw type. I can remove the check, but have to understand implications.

**Comment by ldriscoll** [comment]
I'm not 100% sure, sadly, I'm just helping out with trying to get it to build, it's another person's project.  We definitely extend interfaces. Any chance that the precondition.checkArgument there can give out some details of the file it's working on

**Comment by ldriscoll** [comment]
I'm adding some locally to see what comes of it.

**Comment by ldriscoll** [comment]
PRd

**Comment by ldriscoll** [comment]
oh, and this is definitely a bug in my colleagues code, super class takes a `<T>`, nothing is passed to it, and it's never used :)

**Comment by elucash** [comment]
Yeah, but annotation processor should not fail spuriously on that, but somehow work around it. Thank you @ldriscoll! looking into PR

**Comment by Amanpreet15** [comment]
<dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-annotations</artifactId>
        <version>2.3.0</version>
    </dependency>

Adding above dependancy to the POM resolved my problem

**Comment by Amanpreet15** [comment]
above are in the form of . groupID, artifactID & versions

**Comment by dsinghvi** [comment]
Hitting the same issue & I am on Immutables 2.7.5 and jackson-annotations 2.9.8

**Comment by antemo** [comment]
For me this issue appeared when I switched our build from JDK11 to JDK17 (still targeting 11).
We are on immutables 2.5.5 and jackson 2.9.7

Old build on JDK11 still passes without issues, but new one fails with no warnings or errors whatsoever (even with using -X), just compile errors because code that was supposed to be generated is missing.

We had one issue with generics as described in comments before, but resolving that didn't help.
Worth noting is that the issue didn't show in failed build at all, only in the build that is passing.

Is there an "accepted solution/workaround" to this problem?

**Comment by elucash** [comment]
it's an unknown problem, every case we had here have specific cause: either exception in the annotation processor or mistake in the source code (regardless if both exist and interrelated). Can you create any minimal repro? Do you have any other quirky compilation tools (which sometimes masquerade as annotation processors) or compiler plugins/flavors (vanilla javac, error-prone, ECJ) ?

**Comment by antemo** [comment]
I don't think source code is the problem, since our JDK11 build is working normally.
We do however use several annotation processors in our project, but there are no exceptions in build log even though I enabled debug logging
