### ISSUE TITLE
Issue compiling with JDK 7

### ISSUE THREAD

**Issue by trask** [immutables/immutables#389]
Hi,

I'm getting this error when compiling my project with JDK 7 using Immutables 2.2.7/2.2.8/2.2.9:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile
(default-compile) on project glowroot-storage: Fatal error compiling:
java.lang.NoClassDefFoundError: com/sun/tools/javac/code/Attribute$UnresolvedClass:
com.sun.tools.javac.code.Attribute$UnresolvedClass
```

It works fine when compiling with JDK 7 using Immutables 2.2.6 (and prior).  It also works fine when compiling with JDK 8 using Immutables 2.2.7/2.2.8/2.2.9.

I'm hoping you might have thoughts what has changed?

Thanks,
Trask

**Comment by elucash** [comment]
I've added this code, wishfully thinking that `Attribute.UnresolvedClass` was not something only jdk8+
```java
    private void printValue(AnnotationValue value) {
      if (Compiler.JAVAC.isPresent() && value instanceof Attribute.UnresolvedClass) {
        Attribute.UnresolvedClass unresolved = ((Attribute.UnresolvedClass) value);
```
It has to be redone a bit. Thank you for revealing this!

**Comment by elucash** [comment]
Please, can you try 2.2.10 and see if the issue is gone

**Comment by trask** [comment]
Looks good, thanks
