### ISSUE TITLE
Lint warnings for generic builder methods taking variadic arguments

### ISSUE THREAD

**Issue by jfancher** [immutables/immutables#392]
Example:

````java
@Value.Immutable
interface Bug<E> {
  Set<E> getItems();
}
````

This does not compile cleanly with `javac -Xlint` because `Varargs method could cause heap pollution from non-reifiable varargs parameter elements` on each of the methods that takes a `E...` and passes it as an argument to a method that takes a `E[]`. This warning is not affected by `@SuppressWarnings("all")` nor by `@SafeVarargs`.

A solution is to add `@SuppressWarnings("varargs")`. This may not be great, because it's very javac-specific. But the only other solution I've found is to change the implementation of the method to iterate the array instead of passing it around.

Alternatively (or additionally), I don't find the varargs overloads to be all that useful... maybe the simplest fix would be to have a style option to turn them off?

**Comment by elucash** [comment]
Agree, will try to do something about it. It came on radar once, but did not received enough attention then. Thank you for reporting this!

**Comment by elucash** [comment]
Getting back to this, there are no much issue left as `@SafeVarargs` is generated on the `(E...)` initializer, with the fix to #393, there's possible to specify suppression for `"varargs"`.
The encoding functionality, currently in final stage of development, will allow to override/specify a custom attribute handling, so if some overloads are just painfully unnecessary, then it will be possible to provide own set of methods instead (see #363). Thank you!
