### ISSUE TITLE
Support for external models (Schema API)

### ISSUE THREAD

**Issue by asereda** [immutables/immutables#399]
Hello,

First of all thanks for this nice library. 

We have a use-case where our models are defined in a separate repository (eg. [Json Schema](http://json-schema.org/) or some XML file).  Do you think it will be possible to create an API where one would define schema programmatically and then generate code out of it ? 

Is it within the scope of immutables ?

Thanks.

**Comment by elucash** [comment]
Hi! Thank you for the kind words! You can use your own generator based on any technology you find accessible to read some sort of spec and then generate interfaces/abstract classes annotated with `@Value.Immutable` and other annotations from our project.
Let's say you have definition like 

```javascript
{
  "types": {
     "OriginDestination": {
         "origin": "Airport",
         "destination": "Airport",
     },
     "Trip": {
        "segments": ["Array", "OriginDestination"]
     },
     "Airport": {
         "code": "String"
     }
  }
}
```

Your goal would be to generate classes like (I assume Gson integration as an example, but Jackson one could be picked also)

```java
@Gson.TypeAdapters 
@Value.Enclosed // just a matter of style we will put definitions inside
// enclosing type, but it's not required
interface Types {
  @Value.Immutable 
  interface OriginDestination {
    Airport origin();
    Airport destination();
  }
  @Value.Immutable 
  interface Trip {
    List<OriginDestination> segments();
  }
  @Value.Immutable 
  interface Airport {
    String code();
  }
}
```

Having `GsonAdaptersTypes` generated you can register it with `GsonBuilder` and deserialize/serialize JSON objects from your spec.

What technology to choose to white such transformation? It depends what you're most comfortable with.
Just as an example.
1. Use nodejs script to read the spec . With some ES6 features you don't even need not to use template engines:

```javascript
// (pseudocode)
let model = JSON.parse(fs.readFileSync(path.join(__dirname, 'model.json'), 'utf-8'))
let typesCode = ''
for (let name in model.types) {
   let attributes = model.types[name]
   typesCode += generateType(name, attributes)
}

function generateType(name, attributes) {
   return `
   @Value.Immutable
   interface ${name} {
    ${  Objects.keys(attributes).map(k => generateAttribute(k, attributes[k])).join('') };
  }
`
  function generateAttribute(name, type) {
    if (type.length == 2 && type[0] == 'Array') {
        type = `java.util.List<${ type[1] }>`
    }
    return `
    ${type} ${name}();
`
  }
}

let code = `
@Gson.TypeAdapters 
@Value.Enclosed
interface Types { ${ typesCode }
}
`

fs.writeFileSync(code, 'Types.java', 'utf-8')
```

well, you should get the point. The same could be written in Java, using Immutables' internal mechanisms for code generation. Or some other, maybe better documented libs like `JavaPoet` etc.
As an example of Immutables' internal, undocumented facilities, the `mirror` maven submodule may be a good place to see how to create standalone annotation processor/generator using utility functionality of Immutables: https://github.com/immutables/immutables/tree/master/mirror

**Comment by asereda** [comment]
Hi Eugene,

Thanks for your reply. 

I understand that one can generate new java interface out of existing meta-model but I wanted to avoid having 2 phase code generation: meta-data -> java interface -> pojo. I will check  Mirror and see if it can be used. 

Regards.

**Comment by elucash** [comment]
Just a note, "java interface -> pojo" is automatic process during compilation. Well, if you make "meta-data -> java interface" also a part of annotation processing (as opposed to standalone script), so the whole chain "meta-data -> java interface -> pojo" will work seamlessly during compilation, as the annotation processing use so called rounds where it's able to pick up newly generated classes and process annotation on them which possibly generate new files and all that until no new annotation-processable files are generated. From the standpoint of build tool it will be just a single compilation step, not the abundance of plugins and phase/goal configurations.
Here's rather elaborate example of my experiments (WIP), where we read grammar file during annotation processing and generating parser/AST (including `@Value.Immutable class/interface` files) and all that as regular compilation with annotation processing enabled:
https://github.com/immutables/nextgen/tree/master/src/io/immutables/grammar
