### ISSUE TITLE
Generic repository support

### ISSUE THREAD

**Issue by elucash** [immutables/immutables#4]
There's idea to create repository view as a generic repository interface with simple set of operations (findAll, findById, deleteAll, delete, upsert, update). This generic repository could be passed along other repositories for some generified processing

``` java
MyRepository repository = ...

GenericRepository<MyRepository> r =  repository.asGeneric();
FluentFuture<MyRepository> doc12 = r.findById(12);
```

Questions left: Do we need parametrize by id or left it as Object? Specific set of exposed operations and naming.

UPDATE Expanding scope of this to be able to create repositories not only for mongodb, but for some other database technologies as well. Excerpt from the email on the mailing list:

_What would be really nice would be for immutables to build a generic repository with some "most common" subset of your MongoDB builder functions that could then be easily adapted for a wider set of uses._

``` java
Repository<Bean> repo = repo.all_of().a_is("x").b_in(Arrays.asList("x", "y")).c_in_closed_open_range("z", "zx"); 
```

_and then have a simple way of getting a list of those (including nested ones) for the person developing the mapping between that repo and whatever the end use is_.

**Comment by vorburger** [comment]
IMHO something like, à la Spring Data's Repository, this should never be in the "core" of Immutables, but an Add On.

**Comment by elucash** [comment]
Currently, repositories are on hold, there's a lot to be done and, frankly, the result might be an ugly monster not any better than Spring Data. While we could be still proud of the MongoDB repository generation we've created, there's not much resources or interest in maintaining it.

**Comment by asereda-gs** [comment]
Superseded by [Criteria API](https://immutables.github.io/criteria.html) (specifically Facets)
