### ISSUE TITLE
Generated class couldn't be found

### ISSUE THREAD

**Issue by meNESS** [immutables/immutables#402]
Hi,

```java
import org.immutables.value.Value;

import java.util.Set;

@Value.Immutable
abstract class AbstractAlireza {
    abstract String getName();

    abstract Set<String> getTags();

    abstract String getDescription();
}
```

No generated class could be found and there's no any exception. I tested the already provided sample codes on the website and that's not working too. I'm using the latest version.

**Note:** I'm using SDK 24.1.0

**Comment by elucash** [comment]
Just confirming that you've configured the build properly for Android:  http://immutables.github.io/getstarted.html#android
Please, let me know if you have different setup

**Comment by meNESS** [comment]
You saved me world, man :+1:
