### ISSUE TITLE
Invalid generated hashCode for Optional<Array>

### ISSUE THREAD

**Issue by xavier-calland** [immutables/immutables#405]
version : 2.2.10

Given this interface
```
@Value.Immutable
interface Foo {
  byte[] myByteArray();
  Optional<byte[]> myOptionalByteArray();
}
```

The method `hashCode` of `ImmutableFoo` will use `Objects.hashCode` for the optional array and not `Arrays.hashcode` (as it is done for the array field).

Generated code :
```
h = h * 17 + Arrays.hashCode(myByteArray);
h = h * 17 + Objects.hashCode(myOptionalByteArray);
```
instead of :
```
h = h * 17 + Arrays.hashCode(myByteArray);
h = h * 17 + Arrays.hashCode(myOptionalByteArray);
```

**Comment by elucash** [comment]
We just don't support arrays as optional or collection parameter. More specifically we treat it as any other object. Arrays are used mostly for compactness of storage, and wrapping`Optional<byte[]>` or `List<int[]>` isn't very compact memory-wise. You can use empty array, separate field or custom wrapper to have absent/present indicator.
Also, we are working on functionality that would allow to "encode" any custom combination of types with custom implementation using exemplary java code (as opposed to extending annotation processor), but that functionality is not ready yet (#363 #383 etc)

**Comment by xavier-calland** [comment]
Thank you for this explanation.
