### ISSUE TITLE
Customisation to have @JsonProperty on generated fields instead of having on generated properties

### ISSUE THREAD

**Issue by tetv** [immutables/immutables#410]
I would like to control how the transformation to Json should be done.
By default the implementation sets `@JsonProperty` to all the properties defined in the Immutable interface/abstract class, however I would like to see that signature on the level of the generated fields. How can I do that?

A Simple class:

````java
@Value.Immutable
@JsonDeserialize(as = ImmutableOrder.class)
@Value.Style(visibility=ImplementationVisibility.PACKAGE, init="set*", get="maybe*")
public abstract class Order implements Serializable {
    public abstract String name();
    public abstract OptionalInt maybeQuantity();
    public abstract Optional<LocalDate> maybeDate();

    public interface Builder {
        Builder setName(String name);
        Builder setQuantity(int quantity);
        Builder setQuantity(OptionalInt quantity);
        Builder setDate(LocalDate date);
        Builder setDate(Optional<LocalDate> date);
        SiteDate build();
    }
}
````

When I transform an Order (assuming date is empty) to json I would like to see:
Expected: `{"name":"aName", "quantity":10}`
Received: `{"name":"aName", "quantity":{"value":10}, "date":{}}`

Is any way to configure the Immutable to change the @JsonProperty to the level of fields (that would solve it - because the fields are @Nullable without Optional by design) instead of level of properties?

Many thanks.

**Comment by elucash** [comment]
Hi, there is solution for this: add appropriate Jackson module that handles the appropriate types like shown here http://immutables.github.io/json.html#jackson-and-java-
Please, let us know if there's any trouble with it

**Comment by tetv** [comment]
Didn't solved.
Expect: `{"name":"aName", "quantity":10}`
Received: `{"name":"aName", "quantity":10, "date":null}`

**Comment by elucash** [comment]
Is there any magic-knob annotation in Jackson to suppress null attributes? IIRC there was such, place it on abstract value type.
Another option would be to use our support for Gson type adapters, they can give you clean optionals out of the box, and can even interoperate with jackson streaming for maximum performance (http://immutables.github.io/json.html#gson)

**Comment by ldriscoll** [comment]
`mapper.setSerializationInclusion(Include.NON_NULL);`

**Comment by tetv** [comment]
Already had that definition.
However, with `mapper..setSerializationInclusion(Include.NON_ABSENT)` solved in some wired way:
`Expected: {"name":"aName", "quantity":10}`
`Received: {"quantity":10, "name":"aName"}`

It seems that the `Optional` properties goes always to the from of the json.
If I remove `Optional` from the value entity, the serialisation it's matches.

````java
@Value.Immutable
@JsonDeserialize(as = ImmutableOrder.class)
@Value.Style(visibility=ImplementationVisibility.PACKAGE, init="set*", get="maybe*")
public abstract class Order implements Serializable {
    public abstract String name();
    @Nullable abstract Integer quantity();
    @Nullalbe abstract LocalDate date();
    public OptionalInt maybeQuantity() { return quantity() != null ? OptionalInt.of(quantity()) : OptionalInt.empty(); }
    public Optional<LocalDate> maybeDate() { return Optional.ofNullable(date()); }

    public interface Builder {
        Builder setName(String name);
        Builder setQuantity(int quantity);
        Builder setQuantity(@Nullable Integer quantity);
        Builder setDate(@Nullable LocalDate date);
        SiteDate build();
    }
}
````

**Comment by elucash** [comment]
I wonder if there any different between `Include.NON_ABSENT` and `Include.NON_NULL`, but anyway, since JSON object order of fields should not matter, I guess you're got it working. In the case if Jackson, we try to outsource as much as possible to Jackson, so it's handlers, modules and  annotations would fully guide the serialization/deserialization.

**Comment by tetv** [comment]
`Include.NON_NULL` is applicable only for pure Java `null` objects.
`Include.NON_ABSENT` is applicable for `Optional.empty()` or `Optional.absent()` and it make sense because it gives the user more control in what he wants to do.
There is also `Include.NON_EMPTY` that I assume that is applicable for empty strings `""`.

**Comment by tetv** [comment]
Although I could reach the results that I expected, I still think that this requirement (see title) and more two related ones, should be present in the next release of Immutable. To sum up (with reasons):

***1) @JsonPropertyOnFields*** *(or similar way e.g. via Style or other methods)*
**Reason:** To avoid unnecessary creation of `Optional` in serialisation and deserialisation to Json. In my experience, applications tend to create several gazillions of Immutables and pay the price of creating `Optional` just for serialisation and deserialisation purpose is not wise. This option should become the default in the next major release of Immutable (to avoid break downs in version 2.x).

***2) @JsonPropertyOrder*** *automatically present on the Immutable generated class if not defined.*
**Reason:** When there is `Optional` properties, the generated json string always include all the optional properties first. Because typically the most important properties tend to be described first, this annotation should respect the order of the json properties defined in the file.

***3) @GenerateNullableForOptionalsOnBuilder*** *this optional could be activated by default.*
**Reason 1:** Some APIs and legacy code returns already a *Nullable* object, and transform it to `Optional` just to set the builder is pay an unnecessary price.
**Reason 2:** Intellij's help advice with warnings not to have `Optional` fields and *parameters*.
**Reason 3:** Java Lambda (JSR-335) expert group considered the primary design goal for Optional is to be used as the return value of functions when a return value might be absent. The intent is that the caller immediately check the Optional and extract the actual value if it's present. If the value is absent, the caller can substitute a default value, throw an exception, or apply some other policy. They have suggested that a better name for `Optional<T>` would be `OptionalReturn<T>`.
````
@Value.Immutable
@JsonDeserialize(as = ImmutableOrder.class)
@Value.Style(visibility=ImplementationVisibility.PACKAGE, init="set*", get="maybe*")
public abstract class Order implements Serializable {
    public abstract String name();
    public abstract OptionalInt maybeQuantity();
    public abstract Optional<Integer>maybeSize();
    public abstract Optional<LocalDate> maybeDate();
}

// The default ImmutableOrderBuilder should generate...
ImmutableOrderBuilder setName(String name);
ImmutableOrderBuilder setQuantity(int quantity);
ImmutableOrderBuilder setQuantity(OptionalInt quantity); // For compatibility
ImmutableOrderBuilder setQuantity(@Nullable Integer quantity); // NEW method
ImmutableOrderBuilder setSize(int quantity);
ImmutableOrderBuilder setSize(Optional<lInteger> quantity); // For compatibility
ImmutableOrderBuilder setSize(@Nullable Integer quantity); // NEW method
ImmutableOrderBuilder setDate(@Nullable LocalDate date); // CHANGED method
ImmutableOrderBuilder setDate(Optional<LocalDate> date); // For compatibility
````

**Comment by ldriscoll** [comment]
For better Jackson optional support, you need to make sure that you have https://github.com/FasterXML/jackson-datatype-jdk8, then yes non absent is the right thing. 

If you switch `optionalAcceptNullable = true` on in your style, then the builder and `withX` methods are generated with optionals and non optionals. 

As to creating optionals in the gets, I'm ambivalent, it used to store optional things as optional, but that is on itself inefficient. 

I disagree that the json property order should be automatically added, it's unnecessary overhead and if you care about order then you should put it on your template class.

**Comment by elucash** [comment]
> 1) @JsonPropertyOnFields

Fields are implementation details in the case of Immutables. We're, probably, solving the wrong problem here. If allocations are of concern, isn't using `@Nullable` attributes is the best choice? There are tools to statically validate null-semantics and give quite good type\null-safety (CheckerFramework/Findbugs/IDEA/Eclipse)

> 2) @JsonPropertyOrder

We try to mess with Jackson at a very minimum, so unless we generate fields or accessors out of order, we would prefer to not annotate with anything extra. (It's already akin to a house of cards, any change may break backward compatibility and a lot of subtle use-cases). There's ability to pass annotations all along the way (can use `Style.additionalJsonAnnotations` if some annotations do not auto-propagate). It's seems that the reordering issue might be reported to jackson-bind or jackson-datatype-jdk8 repositories if you can observe the same issue while using regular POJO with Optional.

> 3) @GenerateNullableForOptionalsOnBuilder

as @ldriscoll mentioned, there's `optionalAcceptNullable = true`. Again, using `@Nullable` attributes could be more adequate choice. We are in process of developing extension functionality that would allow (at some point) to specify customization/additions to custom and annotated types: imagine you just define `@Nullable String getX()` and `Optional<String> maybeX()` would be auto-implemented etc. Or you may want to specify fully custom "encoding" for ` `Optional<String>` with the "correct" accessors and initializers as you may see it. The new "encoding" functionality would enable us to do that and all with regular exemplary java code (not codegen templates or annotation processing plugins).

**Comment by tetv** [comment]
Thank @ldriscoll and @elucash for you feedback.
Having the option `optionalAcceptNullable = true` is really good news!
And glad to see the future extension mechanism.

> 1) @JsonPropertyOnFields

The idea is to have as small as possible value classes, and I have projects with 80+ properties.
Using `@Nullable` requires additional maybe methods to wrapper the `@Nullable` properties what should be avoided by Immutable features (repetitive code).

Some optimisations could be done in the generated code to avoid creating additional and unnecessary `Optional` instances, like checking if the instance is an Immutable instance in order to direct access to the fields level. (e.g. `Build.from`)

> 2) @JsonPropertyOrder

Unfortunately `Style.additionalJsonAnnotations={JsonPropertyOrder.class}` doesn't generate the `@JsonPropertyOrder` property, or maybe I don't know how to use it. However you probably are right and it could be a Jackson bug.

> 3) @GenerateNullableForOptionalsOnBuilder*

The `Style.optionalAcceptNullable=true` solves partially. Unfortunately doesn't support `OptionalInt`, `OptionalDouble`, ... and for `Optional<Double>` doesn't generate the `set(double ...)` method what can be tricky for some automatically conversions between `Number` (e.g. int to Double).

**Comment by elucash** [comment]
I've rechecked that `@JsonPropertyOrder` placed on abstract value type works as expected (https://github.com/immutables/immutables/blob/master/value-fixture/src/org/immutables/fixture/jackson/GeoPoint2.java). So, probably, any reordering we're experiencing with Jdk8Module/Optional serializer would not be fixed by generating one more `@JsonPropertyOrder` annotation.

Extension mechanism is currently almost ready (incubating) and can be used to have different way of how properties are handled, while there are many limitations, capabilities are quite powerful. Please see #363 thread.

**Comment by tetv** [comment]
The previous problem with the serialisation order mentioned previously:
`Expected: {"name":"aName", "quantity":10}`
`Received: {"quantity":10, "name":"aName"}`

Doesn't happen anymore if using the new Json Builder functionality introduced in 2.2.12 version. :)
This is because now the serialisation are done using the fields it self, therefore no need to use the Optional serialisation (that contains the bug).

To sum-up: The `setVisibility(PropertyAccessor.FIELD, Visibility.ANY)` and `.setSerializationInclusion(Include.NON_NULL)` do the job.

No need to use anymore: `setVisibility(PropertyAccessor.FIELD, Visibility.ANY)` and
`.registerModule(new Jdk8Module())`.
