### ISSUE TITLE
unset doesn't work

### ISSUE THREAD

**Issue by marquiswang** [immutables/immutables#420]
"unset" is an option in @Value.Style, but doesn't appear to be actually supported.

It would be pretty convenient when dealing with Modifiable classes to undo a set.

**Comment by elucash** [comment]
It was, probably, meant to be used with Modifiables or Mongo repositories. As of now it's seems that its unused. If you have a good idea how it could be implemented, please, try fork Immutables and sketch it in Modifiables.generator template, I believe you should find there any kind of example how to get attributes, names, types etc, feel free to ask any question about it. Thank you!

**Comment by tyler-reeves** [comment]
Just submitted a pull request, #430, aimed at addressing this issue.

**Comment by elucash** [comment]
@tyler-reeves thank you for the excellent contribution!

**Comment by elucash** [comment]
released in 2.3 Thank you!
