### ISSUE TITLE
Package with german umlauts (äöü) causes wrong imports 

### ISSUE THREAD

**Issue by mvonrenteln** [immutables/immutables#422]
Like in issue #372 (for "_") cause german umlauts (äöü) in return types of methods in the Immutable class wrong imports

    @Value.Immutable
    public interface MyImmutableClass {
      de.mycomp.proj.context.api.ändern.Zahlungsempfänger getZahlungsempfaenger();
    }

produces the import

`de.mycomp.proj.context.api.äZahlungsempfänger`

Checked with Version 2.2.8

**Comment by elucash** [comment]
Disabling import rewriting when any non-ascii character encountered outside of comments or char/string literals (commit ac8542a295d31725a4fd217753d560d946e38d97)

**Comment by elucash** [comment]
released in 2.2.12

**Comment by mvonrenteln** [comment]
This works for package names and classes as well! Thanks a lot! And thank you for the quick release!!
