### ISSUE TITLE
Build error: Dependency com.atlassian.fugue:fugue not found in public repos

### ISSUE THREAD

**Issue by mvonrenteln** [immutables/immutables#424]
I tried to build immutables locally. The Dependency com.atlassian.fugue:fugue:jar:2.2.1 ist not found by maven.

Could you please add a repository to the POM where you got this dependeny? Or, if this is not possible, state this in a howto file in value-fixture...?

**Comment by elucash** [comment]
It comes from the repository, declared in each pom which use this dependency:

```xml
  <repositories>
    <repository>
      <id>spring-milestones</id>
      <url>http://repo.spring.io/libs-milestone/</url>
    </repository>
  </repositories>
```

This should work (it works on CI, not only on my machine) unless you have something that prohibit repositories other than central or your company-wide one.
