### ISSUE TITLE
Improvement: Builder.from / copy generation code

### ISSUE THREAD

**Issue by tetv** [immutables/immutables#426]
In generated builder code, it would make sense to validate first if the entity is it self, and setup the builder with the fields.

Current generated code:
````java
    public final Builder from(Foo instance) {
         Objects.requireNonNull(instance, "instance");
          Optional<String> barOptional = instance.maybeBar(); // Property level
          if (barOptional.isPresent()) {
             setBar(barOptional);
         }
         // more code...
         return this;
    }
````

Improved generated code (avoiding creating Optionals unnecessarily):
````java
    public final Builder from(Foo instance) {
        Objects.requireNonNull(instance, "instance");
        if(instance instanceof ImmutableFoo) {
            ImmutableFoo immutableInstance = (ImmutableFoo) instance;
            setBar(immutableInstance.bar); // Field level
            // setup directly all fields
        } else {
            // Current generated code
        }
        return this;
    }
````

**Comment by elucash** [comment]
Thank you for the proposal! The code currently is universal for different kinds of attributes and kinds of optional, special casing implementation specific field of `java.lang.Optional` (other optionals are stored directly) is unwise. As of performance on JVM, hotspots (which invoked very often) are compiled with aggressive inlining and escape analysis. I would not be surprised if all boxing/unboxing of optionals will gone completely, and the machine code would be an equivalent of the example you've provided. For non-hotspots it's just doesn't matter. On Android things are different, but more straightforward way is to use `@Nullable` there.

**Comment by tetv** [comment]
Ok, it's faire to trust in compilation optimisation.
