### ISSUE TITLE
Alternate OptionalLong implementation encoding

### ISSUE THREAD

**Issue by nezda** [immutables/immutables#428]
The generated implementation class of [`OptionalLong`](https://docs.oracle.com/javase/8/docs/api/java/util/OptionalLong.html) currently stores it as a `Long` (assuming 32-bit references, 4B missing, 24B present).  Storing it as a `boolean isPresent` and a `long value` (like `OptionalLong` itself does, but with a shared container `Object`) would result in less memory consumed (8B + 0-8B = 16B worst case, 8B (0B extra) best case depending on `Object` padding) _if_ more than half of the instances are present.  In the meantime, I can encode this manually with a (package private) `@Value.Default false fooIsPresent`, a (package private) `long fooValue` field (maybe package private), and a public `@Value.Derived OptionalLong foo`.

Likely similar tradeoff possible for `OptionalInt`, `OptionalDouble`.

**Comment by nezda** [comment]
I implemented a variant of the hand-rolled version for an `OptionalInt` field and avoided the `boolean isPresent` field by using a sentinel value (0).  Required some Jackson futzing.

```java
  @JsonIgnore
  public OptionalInt foo() {
    if (fooValue() > 0) {
      return OptionalInt.of(fooValue());
    } else {
      return OptionalInt.empty();
    }
  }

  /**
   * backing value for {@link #foo()}
   * {@code 0} is a sentinel value representing a missing {@code foo}
   */
  @JsonProperty("foo")
  @Value.Default
  int fooValue() {
    return 0;
  }
```

I also customized my `Builder` to hide this from client code

```java
  public static class Builder extends ImmutableMyRecord.Builder {
    public Builder foo(final Integer foo) {
      return fooValue(firstNonNull(foo, 0));
    }

    public static Builder builder() {
      return new Builder();
    }
  }
```

Would be really slick if this could get generated but it is even more complicated than my initial proposal.

**Comment by elucash** [comment]
Can you try brand new "encoding" functionality, it's scarcely documented in #363, but it allow custom type encodings? A known limitation as of now is that implementation field is forced to be single (with allowed additional supplementary fields), but It might be corrected/enhanced to support decomposition to multiple implementation fields. Thank you!

**Comment by nezda** [comment]
I updated to `value` to 2.2.12, added
```
        <dependency>
            <groupId>org.immutables</groupId>
            <artifactId>encode</artifactId>
            <version>2.2.12</version>
            <scope>provided</scope>
        </dependency>
``` 

wrote
```java
package com.lexmachina.utils;

import java.util.OptionalInt;

import org.immutables.encode.Encoding;
import com.google.common.primitives.Ints;

import static com.google.common.base.Preconditions.checkArgument;

@Encoding
public final class OptionalIntWithSentinel {
  //TODO make sentinel an annotation parameter (or a static constant?) (non-static field would waste space!)

  @Encoding.Impl
  private int value;

  public boolean equals(final OptionalIntWithSentinel that) {
    return this.value == that.value;
  }

  @Encoding.Expose
  public OptionalInt get() {
    if (value != 0) {
      return OptionalInt.of(value);
    } else {
      return OptionalInt.empty();
    }
  }

  @Override
  public int hashCode() {
    return Ints.hashCode(value);
  }

  @Override
  public String toString() {
    return String.valueOf(get());
  }

  @Encoding.Init
  static int initFrom(OptionalInt optional) {
    if (optional.isPresent()) {
      checkArgument(optional.getAsInt() != 0, "Field value can't match the sentinel");
      return optional.getAsInt();
    } else {
      return 0;
    }
  }

  @Encoding.Init
  static int initFrom(Integer value) {
    if (value != null) {
      checkArgument(value != 0, "Field value can't match the sentinel");
      return value;
    } else {
      return 0;
    }
  }

  @Encoding.Init
  static int initFrom(int value) {
    checkArgument(value != 0, "Field value can't match the sentinel");
    return value;
  }

  @Encoding.Builder
  static final class Builder {
    private int value;

    @Encoding.Build
    int build() {
      return value;
    }

    // wrong?
//    @Encoding.Build
//    OptionalInt build() {
//      if (value != 0) {
//        return OptionalInt.of(value);
//      } else {
//        return OptionalInt.empty();
//      }
//    }

    @Encoding.Init
    @Encoding.Copy
    void setFrom(OptionalInt optional) {
      if (optional.isPresent()) {
        setFrom(optional.getAsInt());
      } else {
        value = 0;
      }
    }

    @Encoding.Init
    void setFrom(Integer value) {
      if (value != null) {
        setFrom(value.intValue());
      } else {
        value = 0;
      }
    }

    @Encoding.Init
    void setFrom(int value) {
      checkArgument(value != 0, "Field value can't match the sentinel");
      this.value = value;
    }
  }
}
```

annotated a little `static` inner value `class` with newly generated `@OptionalIntWithSentinelEnabled` but generated class appears to be using the default `OptionalInt` encoding `private final @Nullable Integer easyId;`

Tips?

**Comment by elucash** [comment]
First of all, let me congratulate you with the first encoding you're wrote! it's actually fascinating to see how people can pick up such non-trivial concepts with little to no documentation (will improve on this this). 

I've tried the encoding you provided and it worked with few minor changes.

First of all annotation should work `@OptionalIntWithSentinelEnabled`, please, can you try to apply it on a class, top class, package or style annotation, if one of other places will work, let us know. Also, this should be a separate module, or separate compilation set from the encoding classes. If you put encoding to `src` and the class you test with in `test` (assuming something like Maven)  it should work, If put in a separate encoding module and used in another module it also will work. But if an encoding and an immutable class (which using it) is placed within the same `src` folder it won't work.

About corrections to encoding.
First thing to note is that there's now unfortunately no error signaling this, but method overloading is not supported and each encoding method name should be unique (only field and method can share the same name as they have different "namespaces"). Definitely will add compilation error for this.
The second is (here's the same problem of having no proper compilation error) only one static `@Init` method on value is supported. The return type should be the type of impl field (you've got it right), but only one way to initialize it from constructor argument. We currently cannot generate multiple variants of constructors for each overload as it might turn into combinatory explosion etc. But we can declare multiple with-copy templates to have `with` methods overloads.

Here's how the encoding can be written with those corrections. (Haven't checked that fully correct at runtime immutable value is generated though)

```java
import java.util.OptionalInt;
import org.immutables.encode.Encoding;
import static com.google.common.base.Preconditions.checkArgument;

@Encoding
public final class OptionalIntWithSentinel {
  // TODO make sentinel an annotation parameter (or a static constant?) (non-static field would
// waste space!)
  private static final int SENTINEL_VALUE = 0;

  @Encoding.Impl
  private int value;

  public boolean equals(final OptionalIntWithSentinel that) {
    return this.value == that.value;
  }

  @Encoding.Expose
  public OptionalInt get() {
    if (value != SENTINEL_VALUE) {
      return OptionalInt.of(value);
    }
    return OptionalInt.empty();
  }

  @Override
  public int hashCode() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(get());
  }

  @Encoding.Init
  static int initFrom(OptionalInt optional) {
    if (optional.isPresent()) {
      return safeValue(optional.getAsInt());
    }
    return SENTINEL_VALUE;
  }

  @Encoding.Copy
  int withOptional(OptionalInt optional) {
    return initFrom(optional);
  }

  @Encoding.Copy
  int withInt(int intValue) {
    return safeValue(intValue);
  }

  @Encoding.Copy
  int withInteger(Integer integer) {
    return integer != null ? safeValue(integer.intValue()) : SENTINEL_VALUE;
  }

  private static int safeValue(int intValue) {
    checkArgument(intValue != SENTINEL_VALUE, "Field value can't match the sentinel");
    return intValue;
  }

//  @Encoding.Init
//  static int initFrom(Integer value) {
//    if (value != null) {
//      checkArgument(value != 0, "Field value can't match the sentinel");
//      return value;
//    } else {
//      return 0;
//    }
//  }
//
//  @Encoding.Init
//  static int initFrom(int value) {
//    checkArgument(value != 0, "Field value can't match the sentinel");
//    return value;
//  }

  @Encoding.Builder
  static final class Builder {
    private int value = SENTINEL_VALUE;

    @Encoding.Build
    int build() {
      return value;
    }

    // wrong? YES it's wrong, return type should match impl field name
//    @Encoding.Build
//    OptionalInt build() {
//      if (value != 0) {
//        return OptionalInt.of(value);
//      } else {
//        return OptionalInt.empty();
//      }
//    }

    @Encoding.Init
    @Encoding.Copy
    void setFrom(OptionalInt optional) {
      if (optional.isPresent()) {
        setFromInt(optional.getAsInt());
      } else {
        value = SENTINEL_VALUE;
      }
    }

    @Encoding.Init
    void setFromInteger(Integer value) {
      if (value != null) {
        setFromInt(value.intValue());
      } else {
        value = SENTINEL_VALUE;
      }
    }

    @Encoding.Init
    void setFromInt(int value) {
      this.value = safeValue(value);
    }
  }
}
```

**Comment by nezda** [comment]
@elucash always so impressed with you and this awesome project - always one step ahead!  I had annotated a little static inner value class with newly generated `@OptionalIntWithSentinelEnabled` and that didn't do anything.

I put your modified version above in `src/test` of my maven project and it wasn't recognized at compile time, so i guess whole new maven subproject is my only option (any easier hack i could do?).  I'll see about that in the next few days.

**Comment by nezda** [comment]
This can be closed as working!  Awesome functionality.
