### ISSUE TITLE
Programatically accessible builder exceptions

### ISSUE THREAD

**Issue by kag0** [immutables/immutables#429]
Currently when building a value from a builder with missing fields an exception like this is thrown 
> java.lang.IllegalStateException: Cannot build MyValue, some of required attributes are not set [someField]

I'm wondering if it is possible to access that list of missing field names or if that feature could be added (perhaps a subclass of `IllegalStateException`).

My specific use case is when deserializing JSON input. If it's invalid due to missing fields then I would like to return an error with those field names.

**Comment by elucash** [comment]
Hi, thank you for raising this. There's no exactly such functionality yet and I dunno if it need to be created, but you can easily work around with existing functionality.
I would create an exception and parse attributes, as format of the message expected to be relatively stable. It have to be a runtime exception, extending `IllegalStateException` would work fine also.
```java

public class CannotBuildValueException extends IllegalStateException {
   private static final Splitter SPLITTER = Splitter.on("[,]").trimResults().omitEmptyStrings();
   private final List<String> attributes;
   public CannotBuildValueException(String message) {
      super(message);
      int i = message.indexOf('[');
      this.attributes = SPLITTER.splitToList(i > 0 ? message.substring(i) : "");
   }
   public List<String> getAttributes() {
      return attributes;
   }
}
....
// this style will change IllegalStateException for CannotBuildValueException in builder
@Value.Style(throwForInvalidImmutableState = CannotBuildValueException.class)
@Value.Immutable
interface Val {
   int a();
   Integer b();
}
// just as reminder: don't place Style on values directly except for experimentation, better place it on package or as meta annotation.
```

**Comment by elucash** [comment]
closing, superseded by #451
