### ISSUE TITLE
Default attributes not honored without a builder

### ISSUE THREAD

**Issue by TiborVyletel** [immutables/immutables#439]
I have this custom annotation in place:

``` java
@Target(ElementType.TYPE)
@Value.Style(
    allParameters = true,
    get = {"get*", "is*"},
    defaultAsDefault = true,
    jdkOnly = true,
    defaults = @Value.Immutable(builder = false, copy = false),
    typeImmutable = "Imm*"
)
public @interface Request {
}
```

and here it is used:

``` java
@Request
public interface CategoriesReq {
  String getLanguage();
  default Long getLimit() {
     return 100L;
   }
}
```

the generated constructor looks like this:

``` java
private ImmCategoriesReq(String language, Long limit) {
    this.language = Objects.requireNonNull(language, "language");
    this.limit = Objects.requireNonNull(limit, "limit");
}
```

The default value of getLimit method has no effect in this style setup.
Would it be possible to take default values (and initialize collections to empty if necessary) in generated constructor when builder is not used?

(The idea behind is the will to use jackson's ParameterNamesModule with the generated private constructor.)

Thanks for great library!

**Comment by elucash** [comment]
Hi, thank you for raising this. In the example shown everything works as expected: `defaultAsDefault = true` turns all default methods into default attributes, while `allParameters true` turns all settable attributes (read as "all except for derived and lazy ones") into constructor parameters. If you want to deviate from this, it's better to remove `allParameters` setting and annotate parameters using `@Value.Parameter`. Please, note that `defaultAsDefault` and `allParameters` are kinda coarse grained and opinionated, like one-size-fits-all. The only refinement you can apply is to use `@Value.Parameter(false)` to cancel-out default parameters while still using `allParameters = true`, like this:

```java
@Request
public interface CategoriesReq {
  String getLanguage();
  @Parameter(false)
  default Long getLimit() {
     return 100L;
   }
}
```

I would suggest to not rely on private constructors or other hacks. Please, also consider to use default Jackson integration (http://immutables.github.io/json.html#jackson): generated `Json` internal pojo will map pretty efficiently and converted to object using builder or using constructor plus withers if no builder available and this stuff might be efficiently inlined by JIT and intermediate allocations would be [hopefully] eliminated due escape analysis. Anyway, arbitrary use of wrapper types like `Long` suggest that some additional allocations might not be a problem in your setup.

**Comment by TiborVyletel** [comment]
Hi @elucash,
thanks for your quick response.
I am aware of the default Jackson integration, but I was trying to keep my (published) interfaces without jackson annotations and leverage ParameterNamesModule as an alternative way of deserialization (I do not see any big difference in looking up a @JsonCreator (jackson-databind) annotated method or a private constructor... - in the end jackson has to use reflection anyway)

**Comment by TiborVyletel** [comment]
Along the way I came across this exception:

Caused by: com.fasterxml.jackson.databind.JsonMappingException: Could not find creator property with name 'json' (in class ***)

also reported here:
https://groups.google.com/forum/#!topic/immutables/2cC7hcjOLOY

I would suggest updating the documentation about conflict between default immutables Jackson support and ParameterNamesModule. Might save some ObjectMapper configuration troubleshooting...
