### ISSUE TITLE
"With" generation only works for interfaces, not abstract classes

### ISSUE THREAD

**Issue by rgabbard-bbn** [immutables/immutables#443]
I cannot seem to get the "sandwich encoding" mentioned in https://twitter.com/ImmutablesOrg/status/740826987883814912 to work for `abstract` classes. Using it with interfaces works fine:

```java
@Value.Immutable
public interface A extends WithA {
    String name();
    class Builder extends ImmutableA.Builder {}
}
```

However, when I attempt it for an abstract class:

```java
@Value.Immutable
public abstract class B implements WithB {
    public abstract String name();
    static class Builder extends ImmutableB.Builder {}
}
```

I get `cannot find symbol: class WithB`.

**Comment by elucash** [comment]
Just to confirm: had you tried to use `public abstract class B implements WithB`? This functionality only generates interfaces, but not abstract classes.

**Comment by rgabbard-bbn** [comment]
Ah, what a silly mistake. I'll update the example above. Unfortunately after making that fix the error persists.

**Comment by rgabbard-bbn** [comment]
Ah, no, wait - it works now.  Apologies for the false alarm!

**Comment by elucash** [comment]
np, just tried it and it worked ok

```java
@Value.Immutable
public abstract class B implements WithB {
	public abstract String name();
	static class Builder extends ImmutableB.Builder {}
}
```
