### ISSUE TITLE
Generated hashCode implementation for arrays generates compiler warnings

### ISSUE THREAD

**Issue by alex-sherwin** [immutables/immutables#444]
Immutables Version: 2.3.1
JDK Version: 1.8.0_102

For array properties, the genereated `hashCode` implementation generates compiler warnings when compiled from IntelliJ (but no warnings emitted from maven under its default settings).  These do appear to be actual compiler warnings, and not some kind of inspection from IntelliJ

```
Warning:(1112, 35) java: non-varargs call of varargs method with inexact argument type for last parameter;
  cast to java.lang.Object for a varargs call
  cast to java.lang.Object[] for a non-varargs call and to suppress this warning
```

I have Guava on my path, so the generated `hashCode` functions utilize `com.google.common.base.Objects.hashCode(..)`, so effectively something like this gets generated:

```
  @Override
  public int hashCode() {
    int h = 31;
    h = h * 17 + Objects.hashCode(scopes);
    return h;
  }
```

Where scopes is type `String[]` , originally defined as `public abstract Optional<String[]> scopes();` on the abstract class.

The warning seems legitimate, in that the signature of `Objects.hashCode(Object... args)` takes an  `Object` varargs, but the generated code is passing a `String[]` into it.

I can't find anyone else complaining of these warnings, or anything in the documentation about the generated `hashCode` behavior in this regards.

So I'm only left to believe that the library should provide some kind of mechanism to control this? The argument passed into it could be casted, for example `Objects.hashCode((Object[]) scopes)` to provide the compiler enough context to decide on a code path.

**Comment by alex-sherwin** [comment]
The difference being, when defined as `Optional<String[]>` the generated `hashCode` uses `Objects.hashCode(Object... args)` where `@Nullable String[]` generates `Arrays.hashCode` instead

**Comment by elucash** [comment]
Hi, thank you for bringing this up! At the moment I don't think we should do anything here. While we do have limited support for arrays (and even special form of nullable array), but this is limited and do not compose with other features. If you need an optional array for performance reasons, use `@Nullable String[]`, this will serve you well. If you more into strong typing and consistency, please use `List<String>` or `Optional<List<String>>`. Just to note: type inside `Optional<*>` have no specific meaning and treated as any object.
Having that said, if you really, really need special handling of the attributes, there's a great way to redefine stuff like that using new experimental functionality called "encodings" which let you encode handling of a certain type or combination of types, please see #363 as a starting point.

**Comment by alex-sherwin** [comment]
The main reason I'm using arrays in general is that I find the experience with JSON mappers like Jackson to be much easier to deal with when you have no type erasure, and don't have to use library specific extensions like type tokens for complex types found under generic collection types.

I think this is even more true when using something to generate the POJO models like immutables does, since trying to use custom type token extensions etc would be even more difficult.

What's throwing me off here is that the immutable generated class creates the same type of `String[]` in either logically equivalent scenario, but, the `hashCode` implementation varies.

I guess what I'm saying is, the generated code has already figured out the contents of my `Optional<>` was `String[]` and created a property of type `String[]`, but generated a `hashCode` implementation which seems wrong

**Comment by elucash** [comment]
>I guess what I'm saying is, the generated code has already figured out the contents of my Optional<> was String[] and created a property of type String[], but generated a hashCode implementation which seems wrong

Type inside Optional<*> have no specific meaning and treated as any object: that's why `Object.hashCode` is used. Replicating correct type is not the same as recognize it or treat differently. Our code, unfortunately, does not perform recursive type analysis, and even if it could it would be extremely difficult to structure code generation in the way to honor it.

There should not be any problem using `List<String>` with Jackson or Gson.
Use `@Nullable String[]` if you try to avoid allocations at all cost.
If the way types are handled are handled you can override it with encodings.

**Comment by alex-sherwin** [comment]
That's true of the JSON serialization for a simple type like List<String> but less true for complex types in deep graphs, so I prefer to use arrays for all the types for consistency sake

So I guess I'll live with the warnings, thanks
