### ISSUE TITLE
@Gson.TypeAdapters don't work on super types

### ISSUE THREAD

**Issue by EduFrazao** [immutables/immutables#446]
@Gson.TypeAdapters does not work when on java.util.List typed with a super type that does not carry the @Value annotation.

Example:

``` java
@Value.Immutable
@Gson.TypeAdapters
public abstract class AbstractConfig implements Serializable {
    @Value.Default
    public boolean calculable() {
        return true;
    }   
    @Nullable abstract AbstractToolbox toolbox();

    abstract List<AbstractDataSerie> series();
}
```

AbstractDataSerie is an abstract class, without @Value annotation.
When I fill this collection with implementations of the class (and this implementation is @Value.Immutable), they don't work on GSON. An empty array is created.
If I change the type of the list to any type annotated with @Value, it works, but I loose the class design and can't add other types to series().

**Comment by elucash** [comment]
Hi @EduFrazao ! I've tried the following example

```java
@Value.Immutable
@Gson.TypeAdapters
public abstract class AbstractConfig implements Serializable {
	@Value.Default
	public boolean calculable() {
		return true;
	}
	@Nullable
	abstract AbstractToolbox toolbox();

	abstract List<AbstractDataSerie> series();

	public static void main(String... args) {

		com.google.gson.Gson gson = new GsonBuilder()
				.registerTypeAdapterFactory(new GsonAdaptersAbstractConfig())
				.create();

		String json = gson.toJson(ImmutableConfig.builder()
				.addSeries(new AbstractDataSerie() {}) // dummy implementation
				.build());

		System.out.println(json);
	}
}
```

and I got this output

```javascript
{"calculable":true,"series":[{}]}
```

I would say it's the expected output, but of course, I doubt it will correctly deserialize as the type is abstract. However, if you want polymorphic marshaling of subtypes you can try to use the following feature: http://immutables.github.io/json.html#polymorphic-mapping

If your case is not covered, please, let us know and provide additional details/examples.

**Comment by EduFrazao** [comment]
Hi @elucash . Thank you very mutch for your answer. I will test it today. I think that it will solve, because its exactly my scenario. As far I confirm, I will close this issue. Thanks!
