### ISSUE TITLE
Specify 'mode' for Jackson `@JsonCreator` annotation

### ISSUE THREAD

**Issue by cowtowncoder** [immutables/immutables#448]
When generating a single-argument constructor for `Json` inner class currently creator is specified simply as:

    @JsonCreator
    public ValueType(Json temp) { ... }

which should work just fine. However, since there are two different possible interpretations of a 1-arg creator method -- one that assigns value to a named property ("properties"); other that takes value as is ("delegating") -- it is possible wrong mode is used. This apparently happens with `jackson-module-parameter-names`.

But it is possible to remove ambiguity by explicit annotation:

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public ValueType(Json temp) { ... }

which should not be mislead by anything (like existence of argument names provided by parameter names module).

`mode` property was added in Jackson 2.5, so this addition seems plausible for current version.

**Comment by elucash** [comment]
Thank you @cowtowncoder for reporting this! To be added in 2.3.2

**Comment by cowtowncoder** [comment]
Excellent, thank you for quick response. Let me know if I can be of further help.

**Comment by cowtowncoder** [comment]
Also: I think this lead me to a subtle bug in Jackson -- all the tests for similar case were only checking case of single-arg constructor as creator, but not single-arg static method. But it looks like handling differs between the two in way it should not. I filed this:

https://github.com/FasterXML/jackson-databind/issues/1383

to track it, and hopefully fix the issue once I see what exactly is going on.

Regardless, I think addition of explicit mode annotation makes sense. But I also want to improve mode defaulting.

**Comment by cowtowncoder** [comment]
Ok, found and fixed the underlying issue on Jackson side; fix will be in 2.7.8 / 2.8.4; former should get released within a week or so.

Unfortunately I also realized that addition of `Mode.DELEGATING` does NOT resolve the problem; fix is needed on Jackson side. So while it is good to specify mode explicitly, it will not resolve the underlying problem, unlike I thought earlier.
I'll let you decide whether you want to implement this improvement or not.

**Comment by elucash** [comment]
@cowtowncoder thank you for investigating it! we suspected this us an inconsistency in Jackson. I would gladly implement the change on our side if it will serve any good (even if it will not work without corresponding Jackson fix)

**Comment by cowtowncoder** [comment]
@elucash no problem -- it's good this was caught now, as the reason was discrepancy between two code paths, one for constructor case (working), the other for static factory method (not working).
I think addition of `mode` makes sense. I'll try to get jackson 2.7.8 release out soon (2.7 and 2.8 are active branches, both to have the fix).

**Comment by elucash** [comment]
same here, the change is there, will be released in a couple in of days, thanks!

**Comment by jroper** [comment]
lol, this issue has plagued us on Lagom for almost a year, I just researched into it and realised this was the solution, then went to fix it myself only to find you already fixed it 3 days ago, thanks @cowtowncoder!

**Comment by cowtowncoder** [comment]
@jroper I was hoping this might help with Lombok too, just couldnt find specific matching desc. Very glad if and when it does help. Also.. bit embarrassed that the discrepancy lead to this bug outliving its welcome; constructor-variant counterpart was fixed quite a while ago.

Anyway: 2.7.8 is now out.

**Comment by elucash** [comment]
Released in 2.3.2 Thank you!
