### ISSUE TITLE
Annotations should be runtime retention? MetaType generation?

### ISSUE THREAD

**Issue by jdmwood2** [immutables/immutables#45]
Hi,

I'm just trying to write something to integrate immutables with JDBI (I will send you a copy if I can get it working :) ).

My plan was to use reflection to try and deal with the immutable.

What I've noticed is that the Value.Immutable annotation is set to SOURCE retention so it isn't visible at runtime. This makes it hard for runtime code to try and do special things with Immutables value types.

Maybe there is an argument that this kind of work should be done by a pre-processed code (like how the JSON code is generated)? 

On the other hand I don't think there is any harm in making them runtime retention?

John

**Comment by elucash** [comment]
currently there's no plans to generate metadata or provide an adequate view of model via runtime annotation
