### ISSUE TITLE
Calling final builder step without providing required arguments

### ISSUE THREAD

**Issue by androidfred** [immutables/immutables#450]
STEPS TO REPRODUCE
Call final builder step (usually .build()) without providing required arguments

EXPECTED RESULT
Compiletime error

ACTUAL RESULT
Runtime error

MISC
Instead of returning the builder on all steps, return the next required argument. When there are no required arguments left, return the builder. See eg http://blog.crisp.se/2013/10/09/perlundholm/another-builder-pattern-for-java

**Comment by elucash** [comment]
Thank you for filing the issue. Please, refer to the following topic as a background for this discussion https://groups.google.com/forum/#!topic/immutables/4VqoSvB0IRQ

Right now it's a tradeoff of a linear (or combinatorial, depending on an approach) explosion of a number of class/interface files. For a small number of arguments (one, two or three) you can easily get away by having a constructor factory method. When a number of parameter increase, more and more classes generated will have an impact on the application footprint, compilation and classloading times when used excessively.

There was a separe discussion about having compile time analysis for builder usage, but it's also quite complicated and fragile to implement as it depends on the details of the compiler and source code parsing which is way beyond competence of the annotation processing.

**Comment by androidfred** [comment]
Glad to hear it's been on the radar.

**Comment by androidfred** [comment]
@elucash I'll just mention that looking at the blog post I'm referring to, it's not obvious to me how it leads to the problems you mention. Maybe you're thinking of a different style of implementation?

**Comment by elucash** [comment]
The problem I've mentioned is the increase in the number of class files for interfaces linearly to the number of the required attributes. If you'll have an interface with 3 attributes, it will result in about 5 or more class files being compiled, even if those will be optimized away at runtime it's still might pressure for compilation and classloading if used extensively. Anyway you can evaluate experimental implementation in version 2.3.3 as `Style.stagedBuilder = true`

**Comment by androidfred** [comment]
@elucash Can't thank you enough! Works exactly as desired as far as I can tell!

```java
import org.immutables.value.Value;
import java.util.Optional;

@Value.Immutable
@Value.Style(strictBuilder = true)
interface Person {
    String name();
    String title();
    Optional<String> department();
}
```

```java
import org.immutables.value.Value;
import java.util.Optional;

@Value.Immutable
@Value.Style(stagedBuilder = true)
interface Individual {
    String name();
    String title();
    Optional<String> department();
}
```

```java
import org.junit.Assert;
import org.junit.Test;
import java.util.Optional;

public class PersonAndIndividualTests {

    @Test(expected = IllegalStateException.class)
    public void personBuildCalledWithoutRequiredArguments() throws Exception {
     ImmutablePerson.builder().build();
    }

    @Test(expected = NullPointerException.class)
    public void personBuildCalledWithRequiredArgumentsNull() throws Exception {
        ImmutablePerson.builder().name(null).title(null).build();
    }

//    @Test
//    public void personBuildCalledWithNonRequiredArgumentsNull() throws Exception {
//        ImmutablePerson.builder().name("John").title("Dev").department(null).build(); doesn't compile
//    }

    @Test
    public void personBuildCalledWithoutNonrequiredArguments() throws Exception {
        ImmutablePerson john = ImmutablePerson.builder().name("John").title("Dev").build();
        Assert.assertEquals("John", john.name());
        Assert.assertEquals("Dev", john.title());
        Assert.assertEquals(Optional.empty(), john.department());
    }

    @Test
    public void personBuildCalledWithAllArguments() throws Exception {
        ImmutablePerson john = ImmutablePerson.builder().name("John").title("Dev").department("IT").build();
        Assert.assertEquals("John", john.name());
        Assert.assertEquals("Dev", john.title());
        Assert.assertEquals(Optional.of("IT"), john.department());
    }

//    @Test
//    public void individualBuildCalledWithoutRequiredArguments() throws Exception {
//        ImmutableIndividual.builder().build(); doesn't compile (YES THANK YOU SO MUCH)
//    }


    @Test(expected = NullPointerException.class)
    public void individualBuildCalledWithRequiredArgumentsNull() throws Exception {
        ImmutableIndividual.builder().name(null).title(null).build();
    }

//    @Test
//    public void individualBuildCalledWithNonRequiredArgumentsNull() throws Exception {
//        ImmutableIndividual.builder().name("John").title("Dev").department(null).build(); doesn't compile
//    }

    @Test
    public void individualBuildCalledWithoutNonrequiredArguments() throws Exception {
        ImmutableIndividual john = ImmutableIndividual.builder().name("John").title("Dev").build();
        Assert.assertEquals("John", john.name());
        Assert.assertEquals("Dev", john.title());
        Assert.assertEquals(Optional.empty(), john.department());
    }

    @Test
    public void individualBuildCalledWithAllArguments() throws Exception {
        ImmutableIndividual john = ImmutableIndividual.builder().name("John").title("Dev").department("IT").build();
        Assert.assertEquals("John", john.name());
        Assert.assertEquals("Dev", john.title());
        Assert.assertEquals(Optional.of("IT"), john.department());
    }
}
```
