### ISSUE TITLE
annotations processor does not run with google guava 20-rc 

### ISSUE THREAD

**Issue by squiddle** [immutables/immutables#460]
Due to a misconfiguration we pulled the latest RC of guava-20 (released on Oct. 6th) into our classpath.

The net result is that the annotation processor just never runs. It took me very long to figure it out, so i wanted to give a heads up in case others run into the same issue.

**Comment by elucash** [comment]
Thank you for reporting this. Very interesting, as we fully repackage guava with the annotation processor, so no clashes possible, it could only be some issue when analysing classes from the using project's classpath.
I'll try to pull the RC to see if there any traces.

**Comment by elucash** [comment]
I've just tried with 20.0-rc1 and the project using immutables & guava was compiled successfully including annotation processing. So it might be some specific combination of features. Please, can you supply any additional information or repro-case?
For example, when running maven, you can run with `-X` to get a verbose printout of what's going on.
