### ISSUE TITLE
Jackson w/ immutables deserializes 2 times

### ISSUE THREAD

**Issue by brentryan** [immutables/immutables#461]
@cowtowncoder

So I noticed while playing around with immutables and jackson deserialization that when I have an entity like this:

```
@Immutable
@JsonSerialize(as = ImmutableEntity.class)
@JsonDeserialize(as = ImmutableEntity.class)
@JsonInclude(JsonInclude.Include.NON_NULL)
public interface Entity {

    int MIN_LEN_ANOTHER_FIELD = 2;
    int MAX_LEN_ANOTHER_FIELD = 10;

    /**
     * @return The field
     */
    String field();

    /**
     * @return another field
     */
    @Size(min = MIN_LEN_ANOTHER_FIELD, max = MAX_LEN_ANOTHER_FIELD)
    String getAnotherField();
}
```

That the deserialization process gets called twice when trying to deserialize a string like this:
```
        String json
                = "{\"field\":\"f\",\"anotherField\":\"a\"}";
        ImmutableEntity pe = mapper.readValue(json, ImmutableEntity.class);
```

I noticed this because when I trying to apply a custom deserializer that I wasn't expecting a 2nd pass because it breaks my custom deserializers.  The first pass changes the ObjectNode json graph while the 2nd pass breaks because of the first call which changes it.

It seems like it's related to this part of the generated ImmutableEntity.java:
```
  @Deprecated
  @JsonCreator
  static ImmutableEntity fromJson(Json json) {
    ImmutableEntity.Builder builder = ImmutableEntity.builder();
    if (json.field != null) {
      builder.field(json.field);
    }
    if (json.anotherField != null) {
      builder.anotherField(json.anotherField);
    }
    return builder.build();
  }
```

But I can't figure out why it's calling deserialize 2 times (it seems wrong).

Is there a bug here and/or a workaround?  I've tried this with 2.8.3 and 2.3.3 of jackson + 2.2.1 of immutables.

**Comment by brentryan** [comment]
It seems like this might be related to deserializers that implement the interface

```
implements ResolvableDeserializer
```

because this seems to cause deserialize() to be called twice when used with immutables.

**Comment by elucash** [comment]
@brentryan thank you for reporting this! While I hope for some support from @cowtowncoder in this case, I would suggest to upgrade to 2.3.3 or 2.3.4 version of Immutables where we added "delegation mode" attribute to `JsonCreator` method so it might somehow change the behavior in question (or not, I dunno)

**Comment by brentryan** [comment]
So I tried updating to 2.3.4 and it seems to have similar behavior.  FWIW, we're trying to use this handy versioning module (https://github.com/jonpeterson/jackson-module-model-versioning) with immutables.  Most everything works fairly well.

However, in the case of this versioning module there's a special attribute called "modelVersion" which gets stripped out by the deserializer and the problem is that the immutables implementation causes it to be called twice.  I have a workaround for this problem as implemented here (https://github.com/jonpeterson/jackson-module-model-versioning/pull/7).

Some more details maybe linked in this issue: https://github.com/jonpeterson/jackson-module-model-versioning/issues/6

I'm kinda stumped on what else to try.  Thoughts?

**Comment by brentryan** [comment]
@elucash One downside of going to 2.3.4 of immutables is that it forces us onto a later version of jackson as well.  We're currently on 2.3.3 because of our use of an old dropwizard fork internally.  It's not the end of the world to updated everything, but a bit of PIA. :)  FWIW, I tested above on jackson 2.8.3 + immutables 2.3.4.

**Comment by ldriscoll** [comment]
eek, for immutables to force to a newer version of jackson would prevent us from upgrading, for the same issue, of using an older dropwizard.  We definitely can't upgrade jackson anytime soon.

**Comment by brentryan** [comment]
Looks like you need 2.5+ because of @JsonCreator(mode = JsonCreator.Mode.DELEGATING)

**Comment by brentryan** [comment]
I wonder if doing a slightly different pattern like AutoValue does would work better in immutables: https://github.com/artem-zinnatullin/AutoJackson/blob/master/auto-jackson-example/src/main/java/com/artemzin/autojackson/Tweet.java

and discussed here a bit: https://github.com/google/auto/issues/255

**Comment by elucash** [comment]
@ldriscoll @brentryan  sorry for the inconvenience, my thought was 2.5.x is old enouph for people to use. I'll fix this for the next release, will check Jackson version availability.
JFYI you may use `@JsonDeserialize(builder = ImmutableFoo.Builder.class)` in Immutables too, given you configured builder generation to public constructor `(builder = "new")`

**Comment by brentryan** [comment]
@elucash I'm probably missing something, but I tried using the builder stuff and it fails with the following error:

```
Exception in thread "main" com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "field" (class com.cvent.example.model.ImmutableEntity$Builder), not marked as ignorable (0 known properties: ])
 at [Source: {"field":"f","anotherField":"a","modelVersion":"1"}; line: 1, column: 11] (through reference chain: com.cvent.example.model.Builder["field"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1096)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1469)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1447)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:271)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:154)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2833)
```

This is using:

```
@JsonDeserialize(builder = ImmutableEntity.Builder.class)
@Value.Style(builder = "new")

```

**Comment by elucash** [comment]
let me check, maybe there are some additional caveats

**Comment by ldriscoll** [comment]
apologies, 2.5 is fine for us, sorry, we can't use newer than that though.

**Comment by elucash** [comment]
@brentryan I figured it out it would only work if used as in autovalue by using annotated builder interface, useful addition would be to auto-generate `@JsonProperty` annotations on builder initializers for this to work, will be released in the next version.

**Comment by brentryan** [comment]
@elucash Do we think this will solve the issue with deserializer being called twice?  Is this the best option?

**Comment by elucash** [comment]
I don't know, for me, those are unrelated, most likely if something is called twice may be some peculiarity of Jackson, where Immutables is only doing some demarcation. But if other deserialization/construction path would skip this issue, then it might be fine as well

**Comment by brentryan** [comment]
@elucash So I figured out what the problem is here.  Because immutables is generating another inner class called "Json", it inherits the annotations of the class which means the custom deserializers are used on it as well.  The problem with this is 1) performance of doing it twice and 2) the inputs to the 2nd time is taking the output from the first deserialization case which breaks things.

To fix this, you can simply remove the inner Json class and update your @JsonCreator fromJson method to look like this instead (from my earlier example):

```
  @JsonCreator
  static ImmutableEntity fromJson(@JsonProperty("serializeToVersion") String serializeToVersion, @JsonProperty(
            "field") String field, @JsonProperty("anotherField") String anotherField) {
    ImmutableEntity.Builder builder = ImmutableEntity.builder();
    if (serializeToVersion != null) {
      builder.serializeToVersion(serializeToVersion);
    }
    if (field != null) {
      builder.field(field);
    }
    if (anotherField != null) {
      builder.anotherField(anotherField);
    }
    return builder.build();
  }
```

Could we update immutables to do this instead or at least have the option for doing this instead?

**Comment by brentryan** [comment]
@elucash The easier solution that also seems to work is to modify your inner "Json" class so that it doesn't implement the interface of the immutable type.  So just changing it to this works as well:
```
  @Deprecated
  @JsonDeserialize
  @JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE)
  static final class Json {
    @Nullable String serializeToVersion;
    @Nullable String field;
    @Nullable String anotherField;
    @JsonProperty("serializeToVersion")
    @JsonSerializeToVersion(defaultToSource = true)
    public void setSerializeToVersion(@Nullable String serializeToVersion) {
      this.serializeToVersion = serializeToVersion;
    }
    @JsonProperty("field")
    public void setField(String field) {
      this.field = field;
    }
    @JsonProperty("anotherField")
    public void setAnotherField(String anotherField) {
      this.anotherField = anotherField;
    }
    public String getSerializeToVersion() { throw new UnsupportedOperationException(); }
    public String field() { throw new UnsupportedOperationException(); }
    public String getAnotherField() { throw new UnsupportedOperationException(); }
  }
```

**Comment by elucash** [comment]
@brentryan thank you for digging this deeper!
It (extending the class) was done on purpose so that `Json` class would inherit annotation from abstract value type. In my understanding, having created type descriptor by merging all possible properties and annotations from supertypes, there's no need to invoke deserializers twice, it should not be required, at least in theory. Summoning the expert: @cowtowncoder )

We cannot change now to a list of parameters because of "been there, done that" thing, to be more specific, there's a lot of Jackson binding functionality may be lost because of annotations that might be placed on attributes and cannot copy on method parameters (or will not work if copied) etc.

Having that said, we could still improve(fix actually) lightweight binding with a builder as alternative construction path which might not incur the double invocation of deserializers.

**Comment by cowtowncoder** [comment]
@elucash I would really need an as-simple-as-possible reproduction, with annotations applied.
I don't know of a case where deserialization happened twice, or mechanism for this to happen. But with reproduction I should be able to figure out what happens.

**Comment by elucash** [comment]
thank you @cowtowncoder for the comment! we'll try to come up with a repro

**Comment by cowtowncoder** [comment]
@elucash excellent, looking forward to it.

**Comment by brentryan** [comment]
[immutables-461.tar.gz](https://github.com/immutables/immutables/files/522925/immutables-461.tar.gz)

Here's a project that reproduced the exact issue I'm seeing.  It has 1 junit test that fails because of this issue, but I think the problem might be much bigger.  If you look at the STDOUT print statements you'll see 
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.example.immutables.EntityTest
testSerialization
testDeserializationWithModelVersion
current count: null
current count: 1
testDeserializationWithNoModelVersion
current count: null
current count: 1
```

Where the current count being equal to 1 here is the 2nd call to the custom deserializer VersionedModelDeserializer.java.

If there's a bug in the custom deserializer or something we're doing wrong here then I'd be happy to adjust things.

Hopefully this is helpful to resolving this issue.

**Comment by elucash** [comment]
@brentryan thank you! Looking into

**Comment by cowtowncoder** [comment]
@brentryan Custom deserializer gets called twice because of delegating-creator for type `Json`: first time is wrapping bean deserializer used to get a `ImmutableEntity$Json` helper object; second time to deserializer `ImmutableEntity` itself. So that seems to work as it should, strictly from Jackson's perspective. In this case only inner deserializer has any real work to do, outer deserializer just delegates to it as necessary. You could perhaps avoid wrapping (de)serializer for outer type (`ImmutableEntity`).

As to failing test, looks like `VersionedModelDeserializer` specifically removes the version property from tree, but does not add it back in. I don't know how business logic there should work.

Having said that, there are couple of things could be improved and might have effect:

1. In addition to `Resolvable[De]Serializer`, it is typically also necessary to implement `Contextual[De]Serializer`. Jackson has `StdDelegatingDeserializer`/`StdDelegatingSerializer` that might help here, either as base class or just sample code.
2. There is no need to use `@JsonSerialize(as=[impl type])`, since runtime type is used for serialization by default (for deserialization it is necessary as type would not be known).
3. In `VersionedModelSerializer` you may want to use `TokenBuffer` instead; it implements `JsonGenerator`, and has method `asParser()` to get a buffer-backed parser -- it's simpler and more efficient than full serialization.

Of these only (1) could be relevant for business logic here I think.

**Comment by elucash** [comment]
@cowtowncoder thank you for looking into it!  I would agree that serializer could be made to better account for the way it is invoked under current circumstances, but Is there something you may suggest on the side of Immutables?

**Comment by brentryan** [comment]
@cowtowncoder thank you. The model version. Ring removed is on purpose because we don't want that propert in our models. However it is in the json so that it allows us to handle versioning of our models fairly cleanly I think. 

Are you saying that if we change the deserializer to imply the contextualdeserializer that there is a way to skip the deserialzer call on the outer layer?

@elucash what if you made immutables create all of the Jackson annotations on the inner class only for deserialization? Would that work?

It's not clear to me what @cowtowncoder recommendation is for immutables.

**Comment by cowtowncoder** [comment]
@elucash I didn't see anything obviously wrong or sub-optimal on immutables side, as far as I understand separation.

**Comment by cowtowncoder** [comment]
@brentryan No, I am saying that without implementing contextual (de)serializer, some part of initialization for delegate may be missing or incomplete, so it should be implemented, not just `Resolvable[De]Serializer`.
There are no two calls to same (de)serializer, but rather there are two separate (de)serializers: one for inner class, one for outer class. But you probably do not need wrapping for both of them, so perhaps you can change `modifyDeserializer` to only add wrapping to one place.

I mentioned version handling just because I was not sure why test failed; behavior seemed consistent with implementation of version handling (de)serializers.

**Comment by elucash** [comment]
@cowtowncoder thank you for the analysis!
@brentryan If I understand correctly, deserializer can be adjusted to behave consistently for given circumstances (as per Tatu's suggestions). With Immutables I'll provide an alternative, builder-based deserialization path, which might work differently, so the issue might not arise then (just no guarantee)

**Comment by elucash** [comment]
Just released  2.3.5 (Currently it's making its way to Central)
Jackson 2.5.0 should not be required anymore (`JsonCreator.Mode` detected in the classpath)
`@JsonDeserialize(builder = ImmutableObj.Builder)` should now work with transparently with generated builders (if they have public constructors), you may give it a shot to see if it's of help for deserializer (but I believe some changes might be required in the deserializer itself if you all for correctness, as per Tatu's suggestion)

**Comment by brentryan** [comment]
Thanks!  Where is Tatu's suggestion?  I plan on trying out a change to the deserializer to use `Contextual[De]Serializer`.  Assuming that works then I'll close this issue.  Does that work?

**Comment by brentryan** [comment]
Because this particular library uses this custom deserializer using an extension of BeanDeserializerModifier, it looks like I don't need to use a ContextualDeserializer.  Instead, the implementation of the VersioningBeanDeserializationModifier class can look like this:

```
    @Override
    public JsonDeserializer<?> modifyDeserializer(DeserializationConfig config, BeanDescription beanDescription, JsonDeserializer<?> deserializer) {
        if(deserializer instanceof StdDeserializer) {
            JsonVersionedModel jsonVersionedModel = beanDescription.getClassAnnotations().get(JsonVersionedModel.class);
            Class classType = beanDescription.getType().getRawClass();
            if(jsonVersionedModel != null && classType.getEnclosingClass() == null 
                    && !Modifier.isStatic(classType.getModifiers()))
                return createVersioningDeserializer(
                    (StdDeserializer)deserializer,
                    jsonVersionedModel,
                    VersionedModelUtils.getSerializeToVersionProperty(beanDescription)
                );
        }

        return deserializer;
    }
```

This allow the custom deserializer to only get applied to the outer class and it seems to work.

@cowtowncoder @elucash Do you see a problem going this route instead? Or is it preferred to still do this via a ContextualDeserializer?

**Comment by brentryan** [comment]
@jonpeterson Not sure if you see a downside to this approach for non-immutable use cases?  If so, I'd probably make another module called ImmutableVersioningModule.java that has the different implementation of this.  I could either do this as a separate library OR we could add it to your library.  Any thoughts?

**Comment by elucash** [comment]
@brentryan I meant `@cowtowncoder`'s suggestions, but hope it will work either way. Sorry, I'm a bit unfamiliar with Jackson binding infrastructures, as I only did some digging into Jackson core/streaming modules. On the side of Immutables we try to provide options and to not get in the way (too much).

**Comment by cowtowncoder** [comment]
@brentryan If you stick to only wrapping `BeanDeserializer` you may be right in that it is not strictly necessary to delegate `createContextual()` call. It is mostly needed for other deserializers, which do use contextual annotations like `@JsonFormat`, other resolve value deserializers (like array, List, Map deserializers may do).

It's just that in general delegation case, you should delegate relevant callbacks, that's all. If not necessary for known case may leave out. I hope this helps.

**Comment by brentryan** [comment]
Looks like we can solve this using a ContextualDeserializer OR a BeanDeserializationModifier so I'm closing this bug.

**Comment by elucash** [comment]
Even if not solved the original issue, now we have additional construction path using builder )
Thank you!

**Comment by brentryan** [comment]
How is the documentation updated for immutables?

**Comment by elucash** [comment]
https://github.com/immutables/immutables.github.io
"src" branch
