### ISSUE TITLE
Problems with Android-Jack compiler and Immutables

### ISSUE THREAD

**Issue by tmtron** [immutables/immutables#467]
There are currently problems when using the [Jack-compiler](https://source.android.com/source/jack.html). 

I've prepared a test-project to illustrate the error: [jack-immutables](https://github.com/tmtron/jack-immutables/).

The problem is easy to reproduce in Android Studio 2.2.1 (in the projects `master` branch):
- click `Run` - `Rebuild Project` works
- then make any change (e.g. alter a fixed string in `MainActivity.java`)
- use `Run` - `Make Project`: this fails with the error shown below in the gradle `transformJackWithJackForDebug` stage

`Error:/home/tmtron/AndroidStudioProjects/JackImmutables/app/src/main/java/com/tmtron/jackimmutables/MainActivity.java:30.36: ImmutableSimpleData cannot be resolved`

This is strange, because the file `ImmutableSimpleData.java` file still exists in the file-system.

Note: this seems not to be a general problem of the Jack compiler: e.g. the branch `generatedCode` also uses some annotation processing [Android Annotations](http://androidannotations.org/): and this works as expected.

**Comment by elucash** [comment]
Thank you @tmtron for reporting this! I was able to reproduce the issue, but frankly, don't know where to start with as it seems like tooling (gradle/jack/androidstudio) issue rather than the annotation processor, but it's too early to rule the processor out. I'll try to see if some additional trace/verbose information would be of any help.

**Comment by elucash** [comment]
enabling `--debug` did not reveal anything.

I was able to use generated `MainActivity_` in the `buttonClicked()` method without problem. But when referencing `ImmutableSimpleData`

Interesting enough, if switch to not using generated type directly, problem disappears

```java
@Value.Immutable
interface SimpleData {
    String data();

    class Builder extends ImmutableSimpleData.Builder {}
}
...
...

    @Click
    public void buttonClicked() {
        /* when Immutables is used the jack-compilation takes about 1 minute
         * even when I only make a small change (e.g. change the data-text), I must rebuild the
         * whole project
         * Run will fail with an error.
         */
        SimpleData immutaleData = new SimpleData.Builder().data("button Clicked").build();
        textView.setText(immutaleData.data());
    }
```

**Comment by tmtron** [comment]
Thanks for the quick response - good to have a workaround.

After some research, I found some more info and it might really be an issue with the jack-tools:  
[Android issue 210615#11 Databinding with Jack compiler](https://code.google.com/p/android/issues/detail?id=210615#c11) refers to 3 other bugs and states:

> These issues do not affect all apps and are not specific to data binding (any annotation processor can hit them).

**Comment by elucash** [comment]
After looking at the bugs linked there I'm yet to find similarity. Also, I've found out that it's not directly related to just using yet-to-be-generated type during incremental compilation, it's probably some more complicated combination.

```java
        SimpleData immutaleData = new SimpleData.Builder().data("button Clicked!").build();
        String s =
               // this kind of referencing ImmutableSimpleData worked just fine
                ImmutableSimpleData.copyOf(immutaleData)
                        .withB("")
                        .withData("")
                        .data();
        textView.setText(immutaleData.data());
```

**Comment by danielesegato** [comment]
Can you open [a bug to Android](https://b.android.com) and report this?

As author of immutables if you open it you'll have a louder voice then me.

Thank you.

**Comment by tmtron** [comment]
closing this bug, since [Jack](http://tools.android.com/tech-docs/jackandjill) is deprecated
