### ISSUE TITLE
overshadowImplementation and Jackson deserialization failure

### ISSUE THREAD

**Issue by justinuang** [immutables/immutables#468]
Running into an issue with how overshadowImplementation interacts with jackson.

My guess is that that when jackson tries to deserialize the abstract type, because of the `@JsonDeserialize(as = ImmutableMyType.class)` annotation, it goes to the ImmutableMyType class, where it finds the the method with the `@JsonCreator` annotation.

After overshadowImplementation is applied, this method changes the signature from

    static ImmutableMyType fromJson(Json json)

to 

    static MyType fromJson(Json json)

which jackson then decides to ignore as a potential constructor. I think get a failure saying that a suitable constructor could not be found.

Can we change fromJson not to return the abstract type even when overshadowImplementation is applied? It shouldn't cause any issues since it is only meant to work with Jackson binding, and it's already broken.

**Comment by elucash** [comment]
Good point, thank you @justinuang!

**Comment by justinuang** [comment]
I'm happy to take a crack at making a PR for this.

**Comment by elucash** [comment]
It would be great! basically, it can be as easy as using `[type.typeImmutable]` instead of `[type.typeValue]` or something like for the `@JsonCreator` method in `Immutables.generator` template

**Comment by justinuang** [comment]
On second though, in the interest of both of our time, do you mind making the PR, I'm having understanding how the generator works.

**Comment by elucash** [comment]
Strangely, I was able to find following test

```java

@Value.Immutable(builder = false)
@Value.Style(
    jdkOnly = true,
    overshadowImplementation = true,
    implementationNestedInBuilder = true,
    visibility = Value.Style.ImplementationVisibility.PACKAGE)
@JsonDeserialize(as = ImmutablePackageNoBuilderHidden.class)
interface PackageNoBuilderHidden {
  List<String> getStrings();
  Optional<Integer> getInt();
}
```

Which generates the following `@JsonCreator` method

```java
  @Deprecated
  @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
  static ImmutablePackageNoBuilderHidden fromJson(Json json) {
    ImmutablePackageNoBuilderHidden instance = (ImmutablePackageNoBuilderHidden) ImmutablePackageNoBuilderHidden.of();
    if (json.strings != null) {
      instance = instance.withStrings(json.strings);
    }
    if (json.getInt != null) {
      instance = instance.withInt(json.getInt);
    }
    return instance;
  }
```

The template code already refers `type.typeImmutable`

```java
...
@com.fasterxml.jackson.annotation.JsonCreator
[/if]
static[type.generics.def] [type.typeImmutable.relative] fromJson(Json[type.generics.args] json) {
...
```

So it seems. Can you check with the latest version of immutables (like 2.3.2 or above) ?
Maybe we are facing some other problem here, if upgrade will not work.

**Comment by justinuang** [comment]
On 2.3.5, it works! Looks like it was already fixed.

**Comment by elucash** [comment]
Yeah, I remember someone stumbled on this previously, so we've fixed it. Thank you for reporting this, anyway
