### ISSUE TITLE
Annotations on fields

### ISSUE THREAD

**Issue by ysndr** [immutables/immutables#475]
Like in #456 I ran into the issue that one can not annotate the generated fields/constructors.
I tried to use the storIO annotation processor which needs its annotations set directly on the fields.
A possible solution might be as @VaclavPokorny [proposed](https://github.com/immutables/immutables/issues/456#issuecomment-253627059)
@bkenned4 had a similar [idea](https://github.com/immutables/immutables/issues/312#issuecomment-215854698)

**Comment by elucash** [comment]
Thank you for reporting this! It seems that we have to design something along proposed solutions

**Comment by ysndr** [comment]
Is there any progress on this issue yet, because I'd really like to use Immutables but can not get them to work with most db helpers as they rely on some sort of annotation.. Also using some kind of database entity classes solemnly for storing data in the db and mapping them to their immutable counterparts is not an option either because that would be against the whole sense of why I'd use Immutables in the first place

**Comment by elucash** [comment]
@ysndr sorry, no progress yet, but we're getting to it. Hope I can sketch something out this week.  Thank you for reminding!

**Comment by zstd** [comment]
+1 for this feature
We also using library that highly relies on annotations on field level and this functionality will be very helpful.

**Comment by mattomatic** [comment]
Also interested in the context of #456. In lieu of immutables offering Avro support directly, allowing some means of field annotations would allow me to use immutables for avro myself with just a bit more work. 

Side note: technically immutables + avro will already sorta work as long as you don't need schema evolution or any other fancy features, which of course I do :p

**Comment by danielesegato** [comment]
I may have just (unknowingly) created a duplicated of this issue with #551 (or maybe not?)

**Comment by ysndr** [comment]
@danielesegato I don't think you created a duplicate issue
what you describe is related to the annotation of attributes in the Builder, whereas this issue asks for support to apply annotations  on the fields of the created immutable class ;)

**Comment by SerialVelocity** [comment]
@elucash There's another use case for this feature too. With the Java Validation API PR merged (#26, #513), you either need to have the prefix `get*` on all of your getters or you need to have the validation annotations on the fields.

The latter is definitely preferred but I'm not sure if you would want a generic solution like this, or just put all validation annotations on the fields automagically by detecting whether the annotation has `@javax.validation.Constraint` as an annotation.

**Comment by bandyguy** [comment]
+1. Swagger annotations don't work in all instance when you can only put the annotation on the getter.

**Comment by Diagoras** [comment]
Are there any updates on the status of this issue? Is this something that an encoder could help with?

**Comment by andrey-cabonline** [comment]
What if make it really simple:
@Value.FieldAnnotation("@org.springframework.data.mongodb.core.mapping.Field(ID_FIELD)")

Basically @Value.FieldAnnotation will just put this raw string on the field. That should solve problem when @Target does not have ElementType.METHOD and at the same time it will be easy to write and read code.

Correctness of that expression will be guaranteed by compiler naturally.

**Comment by andrey-cabonline** [comment]
@elucash what's your opinion?

**Comment by elucash** [comment]
Thank you for reminding. Actually, I started to work on this. Should be quite flexible, will allow to inject annotation in a number of places (fields, getters, initializers, params) and to use both source code string and strongly typed annotations (via meta-annotations). Will share some early version this weekend.

**Comment by tanadeau** [comment]
@elucash Any more information on your prototype?

**Comment by elucash** [comment]
This is still work in progress. I work on this in small chunks, unfortunately, I couldn't get enough time to just finish earlier, but 2-3 steps and it will be ready.

**Comment by archieby** [comment]
@elucash this feature is exactly what we need. Hope it will be implemented some time soon

**Comment by elucash** [comment]
thank you, @lsowen would be very grateful if you can help with this. As of now, I merged everything into master, but it's just incomplete. I'll try to find time tomorrow to write more detailed instructions or pointers where to start, but I can just point to something already there: 

* `annotate` module with [`InjectAnnotation.java`](https://github.com/immutables/immutables/blob/master/annotate/src/org/immutables/annotate/InjectAnnotation.java)
* Handling of `InjectAnnotation`as [meta-annotation](https://github.com/immutables/immutables/blob/master/value-processor/src/org/immutables/value/processor/meta/Proto.java#L204)
* Code to analyze and derive annotation code [https://github.com/immutables/immutables/blob/master/value-processor/src/org/immutables/value/processor/meta/AnnotationInjections.java]

There many pieces incomplete, in particular, 3 major parts:

* Calculation of applicable injections
* Derivation/creation of annotation code
* Render injected annotation fragments into templates (on fields and other generated elements)

**Comment by elucash** [comment]
basic idea is that we need to inject annotation `@X` on fields, for example. For this, we create annotation custom `@Y` and meta-annotate it with `@InjectAnnotation` which specifies code (or class) for annotation `X`. Then we put `@Y` on a specific attribute (abstract accessor) or the whole abstract value type (package). Then the annotation processor would put the annotation code of `@X` on all applicable elements (`InjectAnnotation(where=)`) which are derived by attributes covered by annotation `@Y` on the attribute itself, on its abstract value type or package.
