### ISSUE TITLE
No source code can be extracted for @Encoding class. Unsupported compilation mode

### ISSUE THREAD

**Issue by chrisbouchard** [immutables/immutables#477]
I'm trying to use an encoding class for Guava's `ImmutableTable`, based on #363 and [TableEncoding.java] from `value-fixture`.

I have two gradle projects set up, `encoding` and `api`, the latter including the former as a `compile` dependency. I have `TableEncoding` in `encoding`, and I am able to reference `@TableEncodingEnabled` in my style annotation in `api`. However, the encoding doesn't seem to do anything and I get the following error in Eclipse on the `TableEncoding` class:

    No source code can be extracted for @Encoding class. Unsupported compilation mode

I'll include the source code of my encoding below. It's mostly copy-pasted, and I admit I don't really understand how it's supposed to work. (I was hoping to play around with it to see how it behaves.) What should I do to make my compilation mode supported?

#### Specifics:
* Immutables 2.3.7
* Java JDK 1.8.0_91
* Eclipse Oxygen (4.7)
* Gradle 3.1 with apt 0.8
* Windows 10

#### TableEncoding.java:
```java
@Encoding
public final class TableEncoding<R, C, V> {

    @Encoding.Impl private final ImmutableTable<R, C, V> value = ImmutableTable.of();

    @Encoding.Expose
    Table<R, C, V> accessor() {
        return value;
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    @Override
    public String toString() {
        return value.toString();
    }

    boolean equals(TableEncoding<R, C, V> other) {
        return value.equals(other.value);
    }

    @Encoding.Of
    static <R, C, V> ImmutableTable<R, C, V> init(Table<? extends R, ? extends C, ? extends V> table) {
        return ImmutableTable.copyOf(table);
    }

    @Encoding.Copy
    @Encoding.Naming("with*Put")
    public ImmutableTable<R, C, V> withPut(R row, C column, V value) {
        return ImmutableTable.<R, C, V>builder()
                .put(row, column, value)
                .build();
    }

    @Encoding.Naming("*CellSet")
    public ImmutableSet<Table.Cell<R, C, V>> cellSet() {
        return value.cellSet();
    }

    @Encoding.Builder
    static class Builder<R, C, V> {
        private final ImmutableTable.Builder<R, C, V> builder = ImmutableTable.<R, C, V>builder();

        @Encoding.Naming("put*")
        @Encoding.Init
        void put(R row, C column, V value) {
            builder.put(row, column, value);
        }

        @Encoding.Naming("putAll*")
        @Encoding.Init
        @Encoding.Copy
        void putAll(Table<R, C, V> table) {
            builder.putAll(table);
        }

        @Encoding.Build
        ImmutableTable<R, C, V> build() {
            return builder.build();
        }
    }

}
```

[TableEncoding.java]: https://github.com/immutables/immutables/blob/master/value-fixture/src/org/immutables/fixture/encoding/defs/TableEncoding.java

**Comment by elucash** [comment]
Thank you for reporting this! It is a tough question why this might happen, for some reason, none of the ways we use to extract the required source code of the encoding worked. Do you use annotation processing inside Eclipse or just use sources generated by Gradle? Can you, please, send you Gradle configuration to try to reproduce with both Gradle and Eclipse

**Comment by chrisbouchard** [comment]
I'm using the [apt plugin](https://github.com/tbroyer/gradle-apt-plugin) to do annotation processing in Gradle, and it automatically sets it up in the imported Eclipse project. I use Buildship to import the Gradle project as an Eclipse project.

So the short answer is, yes, I'm doing annotation processing in Eclipse.

Here are the relevant gradle config files.

#### Root `build.gradle`:
```gradle
plugins {
    id 'eclipse'
}

allprojects {
    group = 'com.automate.bill'
    version = '0.1'
}

subprojects {
    repositories {
        jcenter()
    }
}
```

#### `encoding` subproject's `build.gradle`:
```gradle
plugins {
    id 'eclipse'
    id 'java'
    id 'net.ltgt.apt' version '0.8'
}

sourceCompatibility = '1.8'
targetCompatibility = '1.8'

dependencies {
    apt 'org.immutables:value:2.3.7'
    compileOnly 'org.immutables:builder:2.3.7'
    compileOnly 'org.immutables:encode:2.3.7'
    compileOnly 'org.immutables:value:2.3.7'

    compile 'com.google.guava:guava:19.0'
    
    // Other (almost certainly) irrelevant dependencies...
}
```

**Comment by chrisbouchard** [comment]
For what it's worth, I updated the `apt` plugin to 0.9, but no change. Also, the generated source files for the `api` subproject created by Gradle in `api/build/generated/source/apt/` don't seem to have any of the `Table`-related builder methods. I don't see any errors or warnings in the `gradlew build` output.

Let me know if you would like to see the `api` project and I'll create a minimum working example.

**Comment by elucash** [comment]
Luckily, was able to reproduce and fix it! We already have the solution for this (special classloading in Eclipse) for the main processor, but the one for encodings tripped on the same landmine. I've merged encodings processor into the main one to reuse the classloading solution and was able to compile encodings successfully in Eclipse (v4.6, but I think it will work in 4.7 too). You can try Immutables 2.3.8 (currently propagating to Central). Let me know it works as expected. "encodings" is relatively new, experimental functionality, may things can go wrong )

**Comment by chrisbouchard** [comment]
Updated to 2.3.8, and the error has gone away. Still figuring out how encodings work, but it looks like the methods are generating. Thanks!
