### ISSUE TITLE
java.lang.IllegalAccessError for method references for wrapper types

### ISSUE THREAD

**Issue by bartosz-bilicki** [immutables/immutables#481]
I am using wrapper type https://immutables.github.io/immutable.html#wrapper-types
Class I write is 
_abstract class  _SomeClass extends Wrapper<String>_
That class is not public.

I declare my object as SomeClass (generated type).

When using method references in lambdas, I am getting runtime(!) Exception

> java.lang.IllegalAccessError: tried to access class _SomeClass from class AnotherClassWithLambda.

Root cause is fact that my _SomeClass is not public. When I make it public everything works fine.
I find it really suprising and dangerous. Could something be done at side of immutables library (generated code), is this JVM bug or JVM limitation?

I use Immutables 2.3.7

**Comment by bartosz-bilicki** [comment]
It is Java issue. It does not work in JDK 101, works in JDK 112. I use Windows 10, 64bit JDK.

**Comment by elucash** [comment]
this, of course, is troubling. I didn't have time to assess what we can or need to do about it, if you have any practical suggestions, please share.

**Comment by bartosz-bilicki** [comment]
Found

**Comment by bartosz-bilicki** [comment]
I suggest adding note to documentation that latest JDK is advised, otherwise strange compilation or runtime errors can occur. I am surprised that after such a long time JDK101 still had bugs related to lambdas. Luckily, bug is now resolved and no other actions than java update are needed.

**Comment by elucash** [comment]
Added (very generic) statement to http://immutables.github.io/getstarted.html#troubleshooting
thank you!
