### ISSUE TITLE
Recursive data structures with reference to parent

### ISSUE THREAD

**Issue by rtedin** [immutables/immutables#482]
Hi,

Is is possible to create an immutable data structure, say a tree, where the nodes of the tree reference the parent node?

```java
@Value.Immutable
public interface Node {
    List<Node> getSubNodes();

    @Nullable
    Node getParent();
}
```

I've been trying for a while, but my understanding is that this is not possible due to a chicken and egg problem (the parent needs to know the subnodes, but the subnodes need to know the parent upon construction), right?

**Comment by elucash** [comment]
@rtedin although it's not very common, but nonetheless recurring theme to have bidirectional references in the immutable object trees.
I was able to find this post, where I tried to come up with the recommendations about how to handle it: https://groups.google.com/d/msg/immutables/uNiviayBSGk/x79GvUJ8AQAJ

**Comment by rtedin** [comment]
Thanks for the info. I'll try that approach.

**Comment by rtedin** [comment]
The mentioned approach would work, but it causes a bit of hassle to the users of our API I think. Currently I'm experimenting with the following;

```java
@Value.Immutable
@Serial.Version(1L)
public abstract class Group {

    @SuppressWarnings("immutables")
    private transient Group parent;

    public abstract List<Group> getSubGroups();

    @JsonIgnore
    public Group getParent() {
        return parent;
    }

    synchronized void setParent(Group parent) {
        if (this.parent == null) {
            this.parent = parent;
        } else {
            throw new IllegalArgumentException("The group already has a parent group.");
        }
    }

    @Value.Check
    protected Group normalize() {
        for (Group group : getSubGroups()) {
            group.setParent(this);
        }

        return this;
    }
}
```

Throwing an exception might be a bit harsh, but this way we ensure that the users knows that they are doing something wrong.

**Comment by elucash** [comment]
@rtedin That is really good way to do this! I'm glad that check method could be usefully in this way

**Comment by rtedin** [comment]
A couple of fixes:

```java
@Value.Immutable
@Serial.Version(1L)
public abstract class Group {

    @SuppressWarnings("immutables")
    @JsonIgnore
    private transient Group parent;

    public abstract List<Group> getSubGroups();

    public Group getParent() {
        return parent;
    }

    private synchronized void setParent(Group parent) {
        if (this.parent == null) {
            this.parent = parent;
        } else {
            throw new IllegalArgumentException("The group already has a parent group.");
        }
    }

    @Value.Check
    protected Group normalize() {
        for (Group group : getSubGroups()) {
            group.setParent(this);
        }

        return this;
    }
```

I've also experimented with Java reflection. It's very similar to the code above. But we couldn't use it since we need GWT compatibility.

With you permission, I'm closing this issue. Thanks for the help!

**Comment by rtedin** [comment]
I continue with my experimentation... FYI, the solution above has the side effect of breaking the `from` method in builders. 

If a group G has subgroups and we want to create a copy of G, the `from` method in the builder adds the same subgroups to a copy of G instead of adding *copies* of the subgroups to a the copy. Since the subgroups already have a parent the `normalize` of the copy method (actually `setParent`) throws.

I'm considering adding a copy method to the Group class to handle this and inform our users that they can't use `from` in the builder for creating copies.

Nevertheless I wonder if the behavior of `from` is completely correct. It is for the majority of cases, but I guess it's not for the case where the objects have to refer to each other as in this example.  I wonder if it would be possible to support deep copies of objects that annotated with `@Immutable` in `from`?

It could become too complicated though, so I'm still aiming to add a copy method. At least `from` works as I would expect if the group does not have subgroups. `from` could then be used as a base case in a recursive copy method (I think, will let you know).

**Comment by rtedin** [comment]
This copy method seems to work:

```java
    public Group copy() {
        List<Group> newSubGroups = new ArrayList<>();

        for (Group subGroup : getSubGroups()) {
            Group newSubGroup;
            if (subGroup.getSubGroups().isEmpty()) { // Base case: we can make a copy through the builder.
                newSubGroup = new GroupBuilder().from(subGroup).build();
            } else { // Recursive case: we need a deep copy.
                newSubGroup = subGroup.copy();
            }
            newSubGroups.add(newSubGroup);
        }

        return new GroupBuilder().from(this).subGroups(newSubGroups).build();
    }
```

**Comment by xenoterracide** [comment]
> I was able to find this post, where I tried to come up with the recommendations about how to handle it: https://groups.google.com/d/msg/immutables/uNiviayBSGk/x79GvUJ8AQAJ

too bad that link is dead...

interesting that I found this looking to see if I could find out how functional programmers handle this problem... how does one do this in haskell, or lisp, or something like that.
