### ISSUE TITLE
Help Wanted: How to have booleans work with gson both directions :-)

### ISSUE THREAD

**Issue by digitalbuddha** [immutables/immutables#488]
I have a bit of trouble getting my data to work correctly when serializing back and forth with Gson.  Consider the model:
```
@Gson.TypeAdapters
public interface GameStateUpdate {
    Boolean isSolved();
}
```
With this model I  can do 
`GameStatusUpdate update= gson.fromJson(" {solved:true}",GameStatusUpdate.class);`

but then if I do `gson.toJson(update)` I get a json that looks like `{isSolved:true}`

I feel that this behavior is unexpected.  I believe I can annotate the field with `@SerializeName("solved")` but I'm not sure why I need to do that for the serialization to work but not for the inflation of the models.

Thank you kindly, I'm sure I'm missing something :-)

**Comment by augustotravillio** [comment]
Hi @digitalbuddha  I've tried to reproduce this like this

```java
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import org.immutables.value.Value;

@org.immutables.gson.Gson.TypeAdapters
@Value.Immutable
interface GameStateUpdate {
	Boolean isSolved();
}

public class TryRoundtrip {
	public static void main(String... args) {
		Gson gson = new GsonBuilder()
				.registerTypeAdapterFactory(new GsonAdaptersGameStateUpdate())
				.create();

		// GameStateUpdate fromJson1 = gson.fromJson(" {solved:true}", GameStateUpdate.class);
		// throws IllegalStateException: Cannot build GameStateUpdate, some of required attributes are not set [isSolved]
		// System.out.println(fromJson1);

		String json = gson.toJson(ImmutableGameStateUpdate.builder()
				.isSolved(true)
				.build());

		System.out.println(json);
		// prints
		// {"isSolved":true}

		GameStateUpdate fromJson2 = gson.fromJson(json, GameStateUpdate.class);

		System.out.println(fromJson2);
		// prints
		// GameStateUpdate{isSolved=true}
	}
}
```

The results I got are correct and reasonable per my understanding. Can you, please, check if your `Gson` configuration is correct?
Just a note that, by default, `is` prefixes are not handled and is tweakable using styles, or apply `@SerializeName` as you've mentioned.

**Comment by digitalbuddha** [comment]
hmm thats odd, with the same setup as you I see a GsonAdapter with the following code:
```
  Boolean isSolvedValue = instance.isSolved();
      if (isSolvedValue != null) {
        out.name("isSolved");
        isSolvedTypeAdapter.write(out, isSolvedValue);
      } else if (out.getSerializeNulls()) {
        out.name("isSolved");
        out.nullValue();
      }
```

**Comment by digitalbuddha** [comment]
what does your type adapter look like?

**Comment by augustotravillio** [comment]
```java
    private void writeGameStateUpdate(JsonWriter out, GameStateUpdate instance)
        throws IOException {
      out.beginObject();
      out.name("isSolved");
      isSolvedTypeAdapter.write(out, instance.isSolved());
      out.endObject();
    }

    private GameStateUpdate readGameStateUpdate(JsonReader in)
        throws IOException {
      ImmutableGameStateUpdate.Builder builder = ImmutableGameStateUpdate.builder();
      in.beginObject();
      while (in.hasNext()) {
        eachAttribute(in, builder);
      }
      in.endObject();
      return builder.build();
    }

    private void eachAttribute(JsonReader in, ImmutableGameStateUpdate.Builder builder)
        throws IOException {
      String attributeName = in.nextName();
      switch (attributeName.charAt(0)) {
      case 'i':
        if ("isSolved".equals(attributeName)) {
          readInIsSolved(in, builder);
          return;
        }
        break;
      default:
      }
      in.skipValue();
    }
```

> I think the issue is that the GsonAdapter is doing isSolved because the method is called isSolved
That is correct behavior. Do you expect it to be `solved` automatically? It could be done using styles

```java
@org.immutables.gson.Gson.TypeAdapters
@Value.Immutable
@Value.Style(get = {"get*", "is*"})
interface GameStateUpdate {
	Boolean isSolved();
}

public class TryRoundtrip {
	public static void main(String... args) {
		Gson gson = new GsonBuilder()
				.registerTypeAdapterFactory(new GsonAdaptersGameStateUpdate())
				.create();
		String json = gson.toJson(ImmutableGameStateUpdate.builder()
				.solved(true) // <-- initializer now is "solved", not "isSolved"
				.build());
		System.out.println(json); //{"solved":true}
		GameStateUpdate fromJson2 = gson.fromJson(json, GameStateUpdate.class);
		System.out.println(fromJson2); // GameStateUpdate{solved=true}
	}
}
```

**Comment by digitalbuddha** [comment]
OK I will use styles. Here's my argument. getFoo becomes foo in json, isFoo becomes isFoo in json. I don't see this as consistent behavior. Every new dev in our codebase has erroneously made this mistake. Figured I'd report it in hopes of getting default changed.

**Comment by augustotravillio** [comment]
I don't know if it would be a backward-compatible or desirable change, @elucash ??

**Comment by elucash** [comment]
If we change the default now, we will definitely break people's code. I'm surprised that current defaults are not mentioned in the main documentation guide. It should be reasonable to document this and consider as a change for 3.0 version if there ever will be one. Looking back, I'm not quite sure there was anything good in the decision to include `get*`, but not `is*` in defaults, so it feels quite random now.

Having style placed on a parent package can make it "global" for your team/project. I always recommend each project maintain certain agreed style.

**Comment by digitalbuddha** [comment]
Hi @elucash, the problem actually manifests itself in one other circumstance. Say I have a isBool() method . Gson works well with that but my issue is that the underlining field is called isBool and not bool. So say I use an ORM that reads the field names, it will not be consistent with the network logic. 

Would defaulting to missing prefix on field be a breaking change as well? If it is can I achieve a strategy where the method is called isBool()  but the field is called bool?  Apologies for lack of formatting, I'm on phone

**Comment by elucash** [comment]
@digitalbuddha I don't see the issue if you just apply the style `(get={"get*", "is*"}`. When applied, you'll get `isBool()` accessor and `bool` field. You can apply it on different levels of granularity: per class, per package, per parent package (project-global) or as meta-annotation.

**Comment by digitalbuddha** [comment]
That works, thank you!
