### ISSUE TITLE
Collection field should be an empty collection by default

### ISSUE THREAD

**Issue by frederic-gendebien** [immutables/immutables#489]
**Given** an interface annotated with @Value.Immutable
**When** a field of the given interface is defined as a Collection<Something>
**Then** the field is not initialized, so we are forced to set the the collection as Collections.emptyList()
**Should** be defined in the generated builder constructor as Collections.emptyList() or equivalent, as it is a standard behavior/practice.

**Comment by elucash** [comment]
Hi, this is barely explained in http://immutables.github.io/immutable.html#array-collection-and-map-attributes section of the documentation. In nutshell, it's absolutely not clear what kind of implementation you would want, a list, a set or something else (for example, Guava have `ImmutableCollection`,  but you cannot construct it). `Collection` is usually a bad way to generalize over sets, lists, bags. If you really want the default value, default attributes can be used

```java
@Value.Immutable
abstract class Obj {
  @Value.Default Collection<String> coll() {
    return Collections.emptyList();
  } 
}
```

**Comment by elucash** [comment]
On a second thought, there's also new experimental "encoding" functionality (sorry that it's not fully documented) that allows implementing any new container (and not only) types, including override handling of `Collection`. See #363 for the details
