### ISSUE TITLE
Possible to define Builder in super-type?

### ISSUE THREAD

**Issue by renedewaele** [immutables/immutables#490]
I'm struggling with the following. As it is something pretty basic I'm guessing it is possible using the framework but I don't know how.

I have an abstract type `A` and two `Value.Immutable` annotated types `B` and `C` that extend from `A`. Say I now got an object of type `A` (so actually a `B` or `C`) and want to create a copy of the object with modifications what do I do?

Ideally I want to define an abstract Builder on the supertype that I can use to make a copy (with changed attributes if desired).

Is such a thing possible?

**Comment by elucash** [comment]
With builders you can do the following
```java
interface Supertypes {

	abstract class A {
		abstract int x();
		abstract Builder copyBuilder();
		static abstract class Builder {
			abstract Builder x(int v);
			abstract Builder from(A a);
			abstract A build();
		}
	}

	@Immutable
	abstract class B extends A {
		abstract int y();
		static abstract class Builder extends A.Builder {}
		@Override
		Builder copyBuilder() {
			return ImmutableB.builder().from(this);
		}
	}

	@Immutable
	abstract class C extends A {
		abstract int z();

		static abstract class Builder extends A.Builder {}
		@Override
		Builder copyBuilder() {
			return ImmutableC.builder().from(this);
		}
	}

	public static void main(String... args) {
		A a = ImmutableC.builder()
				.x(0)
				.z(0)
				.build();
		a = modify(a);
		System.out.println(a);
	}

	public static A modify(A a) {
		return a.copyBuilder()
				.x(1)
				.build();
	}
}
```

But I would actually use `with` copy methods for the same:

```java
interface Supertypes2 {

	abstract class A {
		abstract int x();
		abstract A withX(int x);
	}

	@Immutable
	abstract class B extends A {
		abstract int y();
	}

	@Immutable
	abstract class C extends A {
		abstract int z();
	}

	public static void main(String... args) {
		A a = ImmutableC.builder()
				.x(0)
				.z(0)
				.build();
		a = modify(a);
		System.out.println(a);
	}

	public static A modify(A a) {
		return a.withX(1);
	}
}
```

**Comment by renedewaele** [comment]
Thanks a lot. I did meanwhile figure out about method 1 but method 2 is indeed much shorter. I will use that. 

However, I was hoping that I did not need to define all those with..() methods in the super type myself but that the framework could generate an abstract builder class for this. The builders for the concrete (@Immutable) types could then extend from this abstract builder.

**Comment by renedewaele** [comment]
I had another idea for this. Wouldn't it be possible to generate the super-type of an immutable type? The super-type could contain the `withX(...)` methods and a Builder interface.

Here's an example:

```java
@Value.Immutable
interface A extends SuperA {
  int a();
}
```
would generate:

```java
interface SuperA {
  A withA(int a);
  Builder toBuilder();

  interface Builder {
    A build();
    Builder from(A a);
    Builder withA(int a);
  }
}
```

The Builder in ``ImmutableA`` should implement the generated Builder interface in `SuperA`.

This would expose the `withX(...)` methods on the interface which would be pretty neat. No idea if this is possible though ..

**Comment by elucash** [comment]
We already generating `With*` interface for copy methods, but not for builder yet. You can evaluate the functionality like this

```java
@Value.Immutable
interface A extends WithA {
  int a();
}
```

The naming pattern is derived from `Value.Style.typeWith` attribute. I would be very glad is someone could contribute implementation for `Builder` inside `With` interface. Otherwise, I can come to this only after some time.

**Comment by renedewaele** [comment]
Great to hear that this functionality is already (partly) supported!

Unfortunately this doesn't work on the super-type of an `@Immutable` type which is where I would have wanted it in this case :/. 

Having a dedicated annotation on a super-type that only generates the `WithA` interface and nothing else does seem like the cleanest solution. In time the Builder interface could be generated as well but that would just be an added bonus.

**Comment by elucash** [comment]
I'll see how easy/difficult it would be to tweak this a bit to allow it for non-immutable supertype.

**Comment by renedewaele** [comment]
Thanks for investigating and good to hear! I've meanwhile figured out I needed to build my value object a little bit different anyway. Now using composition i.o. inheritance which turned out to be a better fit anyway. However, I can imagine that this may be useful in a future case.
