### ISSUE TITLE
Warnings in hashCode generated code with using ErrorProne tool

### ISSUE THREAD

**Issue by idyatlov** [immutables/immutables#492]
When Immutables used and compiled with [ErrorProne](https://github.com/google/error-prone), using [Gradle ErrorProne plugin](https://github.com/tbroyer/gradle-errorprone-plugin), there is a warning [BoxedPrimitiveConstructor](http://errorprone.info/bugpattern/BoxedPrimitiveConstructor) when using double values. In it said that we should use Double.valueOf() insyead of new Double() because of allocations.

**Comment by elucash** [comment]
Thank you for the PR! This will be released in the next version

**Comment by elucash** [comment]
released in 2.4.0, thank you!
