### ISSUE TITLE
Compiler Warnings

### ISSUE THREAD

**Issue by kadaan** [immutables/immutables#500]
If an immutable class is both Json serializable and Serializable, like:

```java
@JsonSerialize
@Target(ElementType.TYPE)
@Value.Style(depluralize = true, typeImmutable = "*")
@Value.Immutable
@Serial.Structural
public abstract class Clazz implements Serializable {
    private static final long serialVersionUID = -8909894915412895697L;

    public abstract Object name();
}
```

The generated code doesn't compile because the `serialVersionUID` is not copied to `ImmutableClazz` and `ImmutableClazz.Json`.  Additionally, the generated `ImmutableClazz` as a `redundant cast to java.lang.Object` error.

**Comment by elucash** [comment]
Released in 2.3.10, can you please try it and report if any similar/unresolved issues found. Thank you!
