### ISSUE TITLE
Using more specific types for @Modifiable?

### ISSUE THREAD

**Issue by io7m** [immutables/immutables#504]
Hello.

I have a type definition for a vector type that looks somewhat like this:

```
// Read-only interface
interface VectorReadable4DType { float x(); float y(); float z(); float w(); }
// Read-write interface
interface Vector4DType extends VectorReadable4DType { void setX(float x); ... }

// Mutable 4D vector type
class VectorM4D implements Vector4DType { ... }

// Immutable 4D vector type
class VectorI4D implements VectorReadable4DType { ... }
```

I'm wondering how I might declare fields of the above types that behave in a pleasant way as part of an Immutables definition. The problem I'm seeing with regards to behaviour is as follows:

The obvious definition for an immutable-only type might look like this:

```
@Value.Immutable
interface SomethingType {
  @Value.Default
  @Value.Parameter
  VectorReadable4DType vector0() {
    return new VectorI4D(0.0, 0.0, 0.0, 1.0);
  }
}
```

This works fine because if the user doesn't specify a vector, they get a default read-only vector implementation. If they do specify a value via a builder or constructor, they get to pick which class they want as long as it implements VectorReadable4DType (obviously, this doesn't stop them from passing in something that's actually mutable, but that's their problem to deal with).

If I want to have both mutable and immutable versions, I might do this:

```
@Value.Immutable
@Value.Modifiable
interface SomethingType {
  @Value.Default
  @Value.Parameter
  VectorReadable4DType vector0() {
    return new VectorI4D(0.0, 0.0, 0.0, 1.0);
  }
}
```

Now, the generated `SomethingModifiable` type will let me set a new value for the `vector0` field by calling `setVector0(...)`, but it obviously won't let me actually mutate the existing field because the `VectorReadable4DType` doesn't allow for mutation and anyway, the real type of the field is not mutable. This entails allocating a new vector, and my specific reason for providing mutable alternatives of my types is so that users can avoid making lots of small object allocations (it's a realtime simulation, so avoiding GC by reducing the allocation rate is desirable).

What I'm looking for is some way to write a definition such that the `vector0()` method can be of a mutable `Vector4DType` in the generated modifiable `SomethingModifiable` class, can be of the read-only `VectorReadable4DType` in the generated immutable `Something`
class, and will be exposed as a read-only `VectorReadable4DType` when viewed as a value of the abstract `SomethingType` type.

I feel like the answer might involve a lot of subclassing, and a lot of overriding as I tend to use `@Value.Parameter` everywhere, and the annotation processor warns me against failing to override super methods that have that annotation applied.

Is there a smart way to do what I want?

**Comment by io7m** [comment]
I should point out actually that I think the `@Value.Default` semantics are slightly surprising in the presence of mutable parameter types. For example, this is behaviour that's consistent with `@Value.Default`, but possibly looks a bit weird for new users:

```
SomethingModifiable s = SomethingModifiable.create();
Vector4DType v = s.vector0()
System.out.println(s.vector0()); // Prints [1.0, 1.0, 1.0, 1.0]
v.setX(23.0);
System.out.println(v);  // Prints [23.0, 1.0, 1.0, 1.0]
System.out.println(s.vector0());  // Prints [1.0, 1.0, 1.0, 1.0]
```

`s.vector0()` creates a new default value on each call, because `setVector0()` has not been called.

**Comment by io7m** [comment]
Additional: If writing encodings would help, I'm happy to write them. It's not clear if they're suited to this problem, though.

**Comment by io7m** [comment]
Something along these lines seems to work reasonably well:

```
public interface SomethingBaseType
{
  @Value.Default
  default VectorReadable3DType vector0()
  {
    return new VectorI3D(0.0, 0.0, 0.0);
  }
}

@Value.Immutable
public interface SomethingType extends SomethingBaseType
{
  @Override
  @Value.Parameter
  @Value.Default
  default VectorReadable3DType vector0()
  {
    return SomethingBaseType.super.vector0();
  }
}

@Value.Modifiable
public interface SomethingMutableType extends SomethingBaseType
{
  @Override
  @Value.Parameter
  Vector3DType vector0();
}
```

The `SomethingType` becomes the immutable definition, whilst the `SomethingMutableType` definition becomes the mutable form. The mutable form specifically avoids providing defaults to avoid the surprising behaviour I mentioned above. The need to call `return SomethingBaseType.super.vector0();` is a little annoying when there are a lot of methods. Is there a way to eliminate that?

**Comment by elucash** [comment]
Hi @io7m! My first thought is that can you look at #314 and #333 to see if it will help. Otherwise, we can try to identify missing pieces.

**Comment by elucash** [comment]
About `@Default` for `@Modifiable`s: you should consider that `@Default`, `@Derived` or `@Lazy` are just unsupported for modifiable objects. They will not necessarily throw an exception, but you should not rely on any sensible behavior. I would argue that there are no sound semantic can be defined for default/derived/lazy in the presence of ongoing modification. In the same way, I think that any equals/hashcode implementations are, essentially, nonsensical for mutable objects. They are provided as is, but if you need correct behavior you'd better switch to immutable objects.

**Comment by io7m** [comment]
'Ello.

Looking at the complexity involved... I think I'm going to drop the `@Modifiable` definitions and just live with the allocations. However, this has highlighted one thing that I still have a use case for even without the `@Modifiable`. I sometimes want immutable definitions to share methods via a common supertype. If I provide defaults, I end up having to write lots of stubs that simply call a super method:

```
public interface SomethingBaseType
{
  @Value.Default
  default VectorReadable3DType vector0()
  {
    return new VectorI3D(0.0, 0.0, 0.0);
  }
}

@Value.Immutable
public interface SomethingType extends SomethingBaseType
{
  @Override
  @Value.Parameter
  @Value.Default
  default VectorReadable3DType vector0()
  {
    return SomethingBaseType.super.vector0();
  }
}
```

If I want to define a supertype that contains `@Default` definitions, I have to override them and am required to provide an initializer body even though the supertype contains one already. Would it be possible to allow omitting the override so that I can just write:

```
public interface SomethingBaseType
{
  @Value.Default
  default VectorReadable3DType vector0()
  {
    return new VectorI3D(0.0, 0.0, 0.0);
  }
}

@Value.Immutable
public interface SomethingType extends SomethingBaseType
{
  @Override
  @Value.Parameter
  @Value.Default
  VectorReadable3DType vector0();
}
```

I suspect the rule is fairly simple: If a `@Default` annotation exists and the current method is abstract, check to see if there's a `default` ancestor method and fail if one does not exist (instead of the current behaviour of just failing if the current method is abstract). I think code generation is unchanged.

**Comment by io7m** [comment]
Ok, so I'm not using `@Modifiable` in these cases, but I still think the point I raised about the surprising semantics deserves a new ticket, so I've opened one there. I consider this issue closed.
