### ISSUE TITLE
@Derived Exception

### ISSUE THREAD

**Issue by kadaan** [immutables/immutables#506]
Is it possible to add support for @Derived and @Lazy methods that throw exceptions?

**Comment by elucash** [comment]
Like in having declared checked exceptions? It's troublesome. Derived attribute' initializer is called from the inside construction sequence, so either whole construction sequence (including constructor and build methods) should propagate it or convert a checked exception to unchecked. Neither of these is desirable. It seems simpler for a lazy method, but in general, it was not designed that lazy computation should ever do some side effects or have legit exceptions thrown. Also semantic of lazy exceptions is unclear: either we will try to recompute body if, previously, an exception was thrown or we'll memorize exception and throw it again. As much as it is strange, the latter should be considered "correct" behavior if we think of lazy as memoized. For now, we've got it simple: unchecked-exception == programming mistake, so don't care about memoization semantic.

Do you have a compelling case where this would be really useful and will not raise those pesky thoughts as the ones above?

**Comment by kadaan** [comment]
One scenario we had was the creation of an HttpConnection on an Immutable object which represents a remote file.  In the C# world, @Lazy memoizes the exception and throws every time the lazy method is evaluated.

**Comment by elucash** [comment]
In the case of specific APIs, such as HTTP connection, you can create a special wrapper to handle it in DIY manner. 
I think that for this case, I'll not pursue the change, but it would be considered as use-case to extend "encodings" #363 (incomplete guide http://immutables.github.io/encoding.html) where's the goal is being able to customize how attributes are compiled in, it's not yet powerful to support initializer methods and annotations (in addition to supported abstract method attributes and types to apply the encoding), but it would be expanded to cover more advanced cases like custom memoization.

**Comment by kadaan** [comment]
I had created a CheckedSupplier to allow this to work, but it isn’t a nice as the rest of immutables.

**Comment by elucash** [comment]
will be resolved via #877
Lazy methods will propagate checked exception, for all other attributes like derived/default/regular-abstract there will be a warning (+ any errors in generated code)
