### ISSUE TITLE
Gson FieldNamingPolicy not working

### ISSUE THREAD

**Issue by Khang-NT** [immutables/immutables#514]
I try to map this `json`:
```json
{
     "token": "abc...",
     "refresh_token": "..."
}
```
to my model:
```java

@Value.Immutable
@Gson.TypeAdapters
public abstract class AccountInfo {
    public abstract String getToken();

//    @SerializedName("refresh_token"), if I uncomment this line, it will work
    public abstract String getRefreshToken();
}
```
then I got this error:
`Cannot build AccountInfo, some of required attributes are not set [refreshToken]`

Seem like Gson field naming policy wasn't working with the generated type adapter, here is my Gson config:
```java
GsonBuilder gsonBuilder = new GsonBuilder()
                .setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES);

gsonBuilder.registerTypeAdapterFactory(new GsonAdaptersAccountInfo());
```

**Comment by elucash** [comment]
Hi @Khang-NT There's a mention about field naming policy in the documentation, see under http://immutables.github.io/json.html#field-names section. Let us know if it helps

**Comment by Khang-NT** [comment]
yeah, I got it. Thank you.
