### ISSUE TITLE
Error Prone analyzer triggers optional equality bug pattern in generated immutables

### ISSUE THREAD

**Issue by davido** [immutables/immutables#519]
Trying to activate Error Prone checks on Buck code base in context of this PR (facebook/buck#1047), is failing with optional equality bug pattern:

```
@SuppressWarnings({"all"})
@ParametersAreNonnullByDefault
@Generated({"Immutables.generator", "AbstractApplePlatform"})
@Immutable
@CheckReturnValue
public final class ApplePlatform extends AbstractApplePlatform {
[...]
```

thriggers this error:

```
/home/travis/build/facebook/buck/buck-out/annotation/src/com/facebook/buck/apple/__platform_gen__/com/facebook/buck/apple/ApplePlatform.java:333: error: [OptionalEquality] Comparison using reference equality instead of value equality
    if (this.stubBinaryPath == value) return this;
                            ^
    (see http://errorprone.info/bugpattern/OptionalEquality)
  Did you mean 'if (Objects.equals(this.stubBinaryPath, value)) return this;' or 'if (this.stubBinaryPath.equals(value)) return this;'?
```

Here is the full Travis log: https://travis-ci.org/facebook/buck/builds/189866663 . See related issues:

* https://github.com/google/error-prone/issues/505
* https://github.com/google/error-prone/issues/329

**Comment by elucash** [comment]
@davido thank you for reporting this. Would you mind if I close this a duplicate of #502 ? We can fix it, just didn't get proper attention yet.

**Comment by davido** [comment]
Thanks for the pointer.
