### ISSUE TITLE
JsonTypeInfo/JsonSubTypes annotations not copied to the builder

### ISSUE THREAD

**Issue by vraptorche** [immutables/immutables#520]
When annotation @JsonDeserialize is used as @JsonDeserialize(builder=SomeObject.Builder.class and some fieldshave Json typing annotations attached, deserialization for these fields does not work - I get back Map object instead if the real one

**Comment by elucash** [comment]
@vraptorche thank you for reporting this. Can you, please, provide some code example to reproduce this. I'm not quite understanding the "some fields have Json typing annotations attached" part.

**Comment by vraptorche** [comment]
https://gist.github.com/vraptorche/1aded3893a8e777eaa506bab0867772c

**Comment by vraptorche** [comment]
When change @JsonDeserialize(as = Invitation.class) to @JsonDeserialize(builder = Invitation.Builder.class)
deserialiyation fails.

**Comment by elucash** [comment]
Ok, got it, thank you, it's probably related to #517, we need to copy over Jackson annotations to a builder and corresponding setters.

**Comment by elucash** [comment]
released in 2.4.0, thank you!
