### ISSUE TITLE
How to support more MultiMaps

### ISSUE THREAD

**Issue by nuclearg** [immutables/immutables#521]
Yes, we know, JDK doesn't have a 'standard' MultiMap.

So we have lots of MultiMap now...

guava.Multimap [supported by Immutable]
commons.collections.MultiMap
commons.collections4.MultiValuedMap
springframework.MultiValueMap
...

I use spring.MultiValueMap in my own project, so, is there anyway I can extend the Immutable lib to support one of these Multimaps? Thanks!

**Comment by elucash** [comment]
@nuclearg yes, we have partially documented functionality to create extensions for custom types. To get started please read the following info:
feature issue #363
incomplete guide/tutorial http://immutables.github.io/encoding.html
example project with Javaslang extensions https://github.com/immutables/immutables-javaslang

**Comment by nuclearg** [comment]
Done. GREAT!
