### ISSUE TITLE
Upgrade Gson Serialization to remove some reflection 

### ISSUE THREAD

**Issue by digitalbuddha** [immutables/immutables#523]
Following up to https://github.com/immutables/immutables/issues/230.  Gson 2.8 has a new way to use TypeTokens which removes reflection for parameterized types. Would it be possible to change usage to this rather than doing new TypeToken() for cases when we have something like `Map<Foo,List<Bar>>` 
https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/reflect/TypeToken.java#L310

Thank you kindly.  To put in perspective this would shave 100ms of startup time on our app.

**Comment by digitalbuddha** [comment]
for reference here is the PR to GSON https://github.com/google/gson/pull/900

**Comment by digitalbuddha** [comment]
please see example implementation in the competitor  auto-value-gson https://github.com/rharter/auto-value-gson/pull/99

**Comment by elucash** [comment]
Am I missing something, looks like they have it one level deep (https://github.com/rharter/auto-value-gson/pull/99/files). I wonder if they support `Map<String, List<Set<Foo>>>` correctly.

I know this is not about this particular issue, but have you tried to use `ListMultimap<String, Foo>`? It has no such problems.

**Comment by digitalbuddha** [comment]
Sure I can optimize particular ones. The discussion came up because I was trying to sell another dev on using Immutables. They looked at the website documentation which said "Generation of TypeAdapterFactories which use no reflection." but then looked at generated code that did in fact still do new TypeToken in certain places.

**Comment by elucash** [comment]
Well, using type tokens (and class literals) at all is a form of reflection if nitpicking. The "no reflection" is about JSON mapping is done with no reflection. I can take a look if we can analyze types deeper

**Comment by digitalbuddha** [comment]
asked some people that are smarter than me and got a "yeah it should support infinite depth", someone is going to create a test in autovalue to verify.  Will circle back then

**Comment by elucash** [comment]
maybe they have recursive call somewhere, I could work then. Anyway, I'll see how to optimize our `new TypeToken<V>() {}`

**Comment by digitalbuddha** [comment]
Howdy!  Someone created a test to show nested behavior https://github.com/rharter/auto-value-gson/pull/104/files

**Comment by elucash** [comment]
released in 2.4.1
As a nice side effect, the need for runtime components has been greatly reduced, needless to say, there will be a lot less reflective lookups.
