### ISSUE TITLE
Allow all validation to be handled by bean validation

### ISSUE THREAD

**Issue by cdeszaq** [immutables/immutables#529]
When using bean validation, `null` checks are still happening through the `Objects.requireNonNull` mechanism rather than relying on the bean validation API. This causes inconsistencies in error handling, since null values cause `NullPointerException` to be thrown instead of `ConstraintValidationException`, and the NPEs are great for pulling out information about what field caused the exception (when building error messages, for example).

It would be AMAZING if, when using [the new bean validation API support](https://github.com/immutables/immutables/pull/513), if _all_ error checking could be done through the bean validation API. There are probably wrinkles around the builders, but I'm not as concerned about per-field validation while using the builders because it's clear what field you're trying to set based on what method got called.

I would be happy to take a stab at fixing this if someone could point me in the right direction. I took a quick look, but couldn't quite figure out how exactly the `Objects.requireNonNull` checks were getting included in the places it was causing problems.

And, of course, if things should already be working the way I want them to, please point me in the direction of how to get it to work and I will happily raise a PR to update the docs so that others can leverage this goodness!

**Comment by elucash** [comment]
Hi! Something like you've described is already implemented. It's not featured in the guide, so any contributions to the guide are welcome. Please see `Style(validationMethod)` attribute and it's values to change validation strategy, including delegating to JSR303 implementation

**Comment by elucash** [comment]
To be clear, the newly released 2.4.1 contains fixes to the functionality so that there are no more places where unwanted null check would occur (hopefully)

**Comment by cdeszaq** [comment]
The fixes in 2.4.1 do indeed seem to have corrected the problems I was running into. Thank you very much, and sorry for the already-solved issue! I'll see if I can add a blurb about this to the docs, since it's such a great feature!

**Comment by elucash** [comment]
np, we've yet to advertised those fixes, so no expectations about it. just in case you can help with the guide: here's the repository https://github.com/immutables/immutables.github.io
again, there are no expectations about it )
thank you!
