### ISSUE TITLE
Nullable could not be used with primitive type attributes

### ISSUE THREAD

**Issue by garakelian** [immutables/immutables#531]
There is a bug in 2.4.1 with ValidationMethod.VALIDATION_API.  

This class produces the error, "Nullable could not be used with primitive type attributes".

@Value.Immutable
@Value.Style(validationMethod = ValidationMethod.VALIDATION_API)
public interface TestMe {
	public int getHello(); 
}

It appears that a change was made in 2.4.1 to treat all attributes as implicitly "nullable" when using the Validation API.  That has an unfortunate side effect with primitives.

**Comment by elucash** [comment]
I've fixed it in 2.4.2, but for some reason cannot get it out of the door (doesn't propagate to Central) maybe will re-release it as 2.4.3

**Comment by elucash** [comment]
2.4.2 is available now. The bug should be fixed there. Thank you!

**Comment by garakelian** [comment]
@elucash That fixed it! Thank you!
