### ISSUE TITLE
Better Jackson round-tripping with map serialization proxies

### ISSUE THREAD

**Issue by rgabbard-bbn** [immutables/immutables#540]
Objects generated by Immutables are for the most part round-trip serializable through Jackson with the notable exception of `Map` and `Multimap` fields with non-string keys (due to a limitation of the JSON format).  

It is frequently handy to use Jackson as a serialization mechanism in cases where we don't care about the actual JSON representations conforming to how JSON maps usually behave - we just want to be able to write our data and read it back in some format which is nicely human-readable for debugging.  Internally, we handle this in our non-Immutables classes by replacing `Map` and `Multimap` fields with ["proxy"](https://github.com/BBN-E/bue-common-open/blob/master/common-core-jackson-serialization-open/src/main/java/com/bbn/bue/common/serialization/jackson/ImmutableMapProxy.java) [objects](https://github.com/BBN-E/bue-common-open/blob/master/common-core-jackson-serialization-open/src/main/java/com/bbn/bue/common/serialization/jackson/ImmutableMapProxy.java) for serialization which write them as key-value lists.  

We would like to convert many of our classes which currently use this trick to `Immutables`, but there isn't really a way to do it without creating so much ugliness as to outweigh the benefit (there is the approach from #356, but contorting our object's data representation to make serialization happy seems undesirable). 

Would it be possible to add some sort of annotation (applicable per-field or in a style or both) to request that `Maps` and `Multimap`s be written to JSON in a round-trippable way?

**Comment by elucash** [comment]
Thank you for the feature request! While I'm still digesting it, let me ask a quick question, isn't this a job for custom serializers (in Gson they called are TypeAdapters)? You would just write one and plug it using `ObjectMapper` or by putting an annotation.

**Comment by rgabbard-bbn** [comment]
Thanks for the suggestion! It turns out that doing this in Jackson using a custom serializer is tricky, unless I am missing something.  Actually, the serializer is not bad, but at a glance the deserializer seems to require handling the rather complex logic in  [the default Jackson map serializer](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ser/std/MapSerializer.java).  

However, your suggestion led me to another option I didn't know about: using the [`converter`](https://fasterxml.github.io/jackson-databind/javadoc/2.5/com/fasterxml/jackson/databind/util/Converter.html) option on `@JsonSerialize/JsonDeserialize` to translate to and from the proxy object. I expect this has a performance penalty but it works with Immutables and is good enough for our needs, so feel free to close this. Thanks!

**Comment by elucash** [comment]
Yes, I would suggest converters as a way to go. Indeed, de-/serializers in Jackson are complex enough.
