### ISSUE TITLE
Modifiable with deepImmutablesDetection in different packages

### ISSUE THREAD

**Issue by DennisRippinger** [immutables/immutables#541]
I discovered that the usage of @Modifiable together with deepImmutablesDetection can lead to compilation problems if the referenced value is in another package. It fails to compile because it generates no import or FQN of such values. I created a [MWE](https://github.com/DennisRippinger/immutables-MWE).

This problem could be located in the [Modifiables.generator](https://github.com/immutables/immutables/blob/master/value-processor/src/org/immutables/value/processor/Modifiables.generator#L720), here typeModifiable.relativeRaw and typeModifiable.relative appear to return just the name, or whatever is needed for the PostprocessingMachine.

**Comment by elucash** [comment]
yep, I think fqn should be used instead of relative. Thank you for reporting this!

**Comment by elucash** [comment]
Thank you for the PR, released in 2.4.3
