### ISSUE TITLE
Disable special collection attributes

### ISSUE THREAD

**Issue by vgonzalo** [immutables/immutables#542]
Hi, when I use a getter with a **List** type the generated setters and builders are using an **Iterable** type as the attribute, which is a nice feature for some collection types to add more flexibility. However, I have a case in which I need to use a **List** as a parameter type in the setters and builders (is a condition imposed by the DynamoDBMapper marshaller).
Is there any way to disable this feature? I know that using a specific type would disable this feature (e.g. ArrayList), but is not what I need.

Thanks

**Comment by elucash** [comment]
Use `Style(builtinContainerAttributes = false)` to disable built-in containers. However, any custom encoding might apply, if you need to fine tune how attribute is implemented, you might try create custom encoding (see https://github.com/immutables/immutables/issues/522#issuecomment-271809714 as a starting point).
Released in 2.4.3. Thank you for the feature request!
