### ISSUE TITLE
Any chance we can get an updated changelog with the newer releases?

### ISSUE THREAD

**Issue by ldriscoll** [immutables/immutables#547]

**Comment by elucash** [comment]
There will be one! Just having too much turbulence in life to dedicate time to this now, but you can dig something up using milestones on Github:
https://github.com/immutables/immutables/milestone/56?closed=1
https://github.com/immutables/immutables/milestone/57?closed=1
https://github.com/immutables/immutables/milestone/58?closed=1

**Comment by elucash** [comment]
Updated changelog a bit, thank you!
https://github.com/immutables/immutables#24x-244-2017-03-12

**Comment by ldriscoll** [comment]
Sweet thanks!
