### ISSUE TITLE
Incorrect Builder.from(Object) implementation

### ISSUE THREAD

**Issue by tjwilson90** [immutables/immutables#552]
Given the following source classes
```
package com.example;

public interface Foo<T> {
    T getFoo();
}
```
```
package com.example;

public interface Bar extends Foo<Bar> {
    String getBarId();
}
```
```
package com.example;

import org.immutables.value.Value;

@Value.Immutable
public interface Baz extends Bar {
    String getBazId();
}
```
The generated `ImmutableBaz.Builder` class contains
```
    public final Builder from(Baz instance) {
      Preconditions.checkNotNull(instance, "instance");
      from((Object) instance);
      return this;
    }

    public final Builder from(Bar instance) {
      Preconditions.checkNotNull(instance, "instance");
      from((Object) instance);
      return this;
    }

    private void from(Object object) {
      if (object instanceof Baz) {
        Baz instance = (Baz) object;
        bazId(instance.getBazId());
        foo(instance.getFoo());
      }
      if (object instanceof Bar) {
        Bar instance = (Bar) object;
        barId(instance.getBarId());
      }
    }
```
which is incorrect (`.foo` is not set if `from` is called with a class that implements `Bar` but not `Baz`). The generics and deep inheritance hierarchy appear to be critical to making this fail. If `Foo` is not generic, or `Baz` is removed and `Bar` is made immutable, this doesn't fail.

Another minor issue is that no `.from(Foo<Bar>)` overload is generated. This is far less important since it's only an inconvenience, it can't cause any actual problems.

**Comment by tjwilson90** [comment]
Also, this is a problem both for javac and ecj. They generate the same code.

**Comment by elucash** [comment]
@tjwilson90 thank you for reporting this, the problem here is that generic attributes/superclasses with generics are skipped rather than being correctly specialized. Even if we skip `Foo<Bar>` supertype, we would expect generated `from` method to be of the following form:

```java
    private void from(Object object) {
      long bits = 0;
      if (object instanceof FromGenericInh.Baz) {
        FromGenericInh.Baz instance = (FromGenericInh.Baz) object;
        bazId(instance.getBazId());
        if ((bits & 0x1L) == 0) {
          foo(instance.getFoo());
          bits |= 0x1L;
        }
      }
      if (object instanceof FromGenericInh.Bar) {
        FromGenericInh.Bar instance = (FromGenericInh.Bar) object;
        barId(instance.getBarId());
        if ((bits & 0x1L) == 0) {
          foo(instance.getFoo());
          bits |= 0x1L;
        }
      }
    }
```

To have code like this, the workaround is to override `getFoo` with refined type:

```java
public interface Bar extends Foo<Bar> {
  String getBarId();
  @Override Bar getFoo();
}
```

I remember I faced this issue while back, but it was too hard to correctly specialize generic attributes. I can check it again maybe some new, better ways to solve this will come to mind.

**Comment by tjwilson90** [comment]
I can understand if this is too difficult to generate properly, but even in that case, I don't think it's right to simply leave this alone. When this causes a problem, it's _silent_. The example I gave came from a real bug I had.

If it won't get fixed completely, I think the right thing to do is to simply not generate a `from` implementation if you can't be sure it's correct, or generate it with a different name (I prefer the former since the later would cause an api break if you ever fixed it).

In either case, you could leave a descriptive comment behind in its place so people know what's going on and how to work around it.

**Comment by elucash** [comment]
Totally agree. Just didn't have enough time to dive into this, but this is on the priority list
