### ISSUE TITLE
incorrect equalTo/hash methods generated for an Optional<byte[]> field

### ISSUE THREAD

**Issue by bavardage** [immutables/immutables#554]
I have a field which is of type Optional<byte[]>

this produces code:
```
private boolean equalTo(ImmutableThing another) {
    return Objects.equal(myOptionalByteArray, another.myOptionalByteArray)
        && somethingElse == another.somethingElse;
  }
```

but surely it should be using Arrays.equal for this.

I'm happy to provide a fix if someone could point me in the right direction.

**Comment by bavardage** [comment]
currently looking at `Immutables.generator:3107` and something to do with the `wrappedElementType`, but not sure how to check whether `wrappedElementType` is an array type/get a handle on the wrapped type as an element kind

**Comment by elucash** [comment]
Hi @bavardage, please see following duplicate issues: #193 #444 #405. I hope you will find some arguments as to why it works as intended.
As another matter, there is a perfectly good way to override how particular types(and their combinations) are handled using  experimental "encodings" functionality, please refer to info here https://github.com/immutables/immutables/issues/521#issuecomment-271666775

**Comment by bavardage** [comment]
aha, sorry - i did a cursory search but didn't find these. Will look at the encodings stuff - thanks!
