### ISSUE TITLE
Question: how to handle mutable attributes

### ISSUE THREAD

**Issue by tmtron** [immutables/immutables#557]
For example, let's say I must use the Java7 `java.util.Date` type which is mutable (or any other 3rd party class).

I can use it as an attribute, everything will be generated correctly, but now the generated Immutable* class is not immutable.

Is there a way to override the getter for such an attribute, so that I can manually return a defensive copy of the mutable object?

```
public Date creationDateTime() {
    return new Date(creationDateTime.getTime());
}
```

**Comment by elucash** [comment]
Hi @tmtron, there are 2 main strategies to handle mutable types. The first one is creating special immutable wrapper types which would encapsulate functionality of mutable types. Of course, this maybe not practical in a lot of cases. Fortunately, the second way is more or less what you're looking for, you can indeed customize how particular types are "encoded" within an immutable object. Please read directions here: https://github.com/immutables/immutables/issues/521#issuecomment-271666775

**Comment by tmtron** [comment]
Thanks. The [encoding-docs](http://immutables.github.io/encoding.html) are helpful.

**Comment by tmtron** [comment]
I've created an open-source project to provide a custom encoded type annotation for `java.util.Date`: [tmtron-immutables encoding](https://gitlab.com/tmtron-immutables/encoding).  
The `@DateEncodingEnabled` encoding will make sure that only the primitive long value of the Date class is stored on the immutable object and the accessor will always create a new Date object.

```
@Value.Immutable
@DateEncodingEnabled
public interface ValueObject {
    Date creationDate();
}
```

The project also contains a `@DateEncodingNullable` annotation which stores the Date as a Long and thus allows `null`-values. Not sure, if it's a good idea to use it...

**Comment by elucash** [comment]
This is awesome! Don't you mind if I will feature this project as a good example (in docs or on twitter)?

**Comment by tmtron** [comment]
Sure, I'm happy when it is helpful.
