### ISSUE TITLE
Custom builder in Immutables 

### ISSUE THREAD

**Issue by shyam4u** [immutables/immutables#559]
If I have a scenario as below.I have a customer class in which I have a CustomerKey as instance variable .Now I need to make the below class as immutable by allowing builder .But while creating an instance of Customer I would be getting CustomerKey name and Id instead of CustomerKey instance .How can I have a custom builder while using immutable library 

public  class Customer {
private CustomerKey customerKey;
} 
public  class CustomerKey{
private String name;
private Integer id;
}

**Comment by elucash** [comment]
@shyam4u sorry for the late response. There are couple of ways to do this

1) Use separate attributes and have derived attribute

```java
@Value.Immutable
abstract class Customer {
  abstract String customerId();
  abstract String customerName();
  @Value.Derived // with derived annotation, instance will be created during construction
  CustomerKey customerKey() {
     return new CustomerKey(customerId(), customerName());
  }
}
```

2) Create CustomerKey using immutables and enable `Style.deepImmutableDetection = true`

```java
@Value.Immutable abstract class CustomerKey {
  @Value.Parameter abstract String id();
  @Value.Parameter abstract String name();
}

@Value.Style(deepImmutableDetection = true)
@Value.Immutable abstract class Customer {
  abstract CustomerKey customerKey();
}
// then builder will contain overload to set CustomerKey parameters
// ImmutableCustomer.Builder builder = ImmutableCustomer.build();
// builder.customerKey("ID", "Name");
```

3) You can fully customize how particular types are implemented using "encodings". Please see https://github.com/immutables/immutables/issues/521#issuecomment-271666775

**Comment by valentinUni** [comment]
Has anything changed throughout the past three years in regards to achieving the desired result (fluent nested builder)?

1. The first option implies duplication of fields which explodes in code (in case of many immutable objects - I have 4 with > 5 fields each causing more than 20 additional ones).
2. The second option seems nice, but the usability when having an object with more than just a few variables becomes troublesome. Calling a method and passing some 10 variables is no good, some of the examples I have are not worth even pasting here to take a look.
3. Is there a reasonable snippet that could be referenced to achieve this? I seem to be unable to achieve it with several levels of nested builders.

Using `attributeBuilderDetection` allows to achieve something close to the desired result:

```
ImmutableParent.Builder parentBuilder = ImmutableParent.builder().name("parent");
ImmutableChild.Builder childBuilder = parentBuilder.childBuilder().name("child");
Parent parent = parentBuilder.build();
```

Is there any way to achieve: (?)

```
Parent parent = ImmutableParent.builder()
                               .name("parent")
                               .withNewChild()
                               .withName("child")
                               .endChild() // (or just .end())
                               .build();
```
