### ISSUE TITLE
Inconsistency between org.immutables:value and org.immutables:value-annotations

### ISSUE THREAD

**Issue by AlexShafir** [immutables/immutables#560]
When using `@Value.Style` from value artifact, I am able to specify `@Value.Style(allParameters = true)`

However,when using separated version of artifact (value-annotations + value-processor), `allParameters` does not exist

Versions:
org.immutables:value:2.4.3

org.immutables:value-annotations:2.0.9
org.immutables:value-processor:2.4.2

**Comment by elucash** [comment]
Hi @AlexShafir, You mentioned different versions of annotation and processor jars (2.0.9 vs 2.4.2). I think it's better to have same latest version. Apparently, older 2.0.9 annotation artifact do not have this style attribute declared yet.

**Comment by AlexShafir** [comment]
@elucash found out that annotations were attached as classifier.
As I see it, there are 2 approaches regarding splitting annotations and annotation processor:
1. Make 2 separate packages
 ```
org.immutables:value-annotations:2.0.9
 org.immutables:value-processor:2.4.2
```
2. Attach annotations by classifier (e.g. both inside same version)
 ```
org.immutables:value:2.4.3
 org.immutables:value:2.4.3:annotations
```
3. Merge everything into one jar

You have chosen 2-nd route, but forgot to update first option chosen initially. Maybe it's time to delete old package (`org.immutables:value-annotations`)

P.S.
How do you make jar with "annotations" classifier not having dependencies of processor jar?

**Comment by elucash** [comment]
> How do you make jar with "annotations" classifier not having dependencies of processor jar?
you can take a look how shade plugin in configured in `value/pom.xml`

While I would not consider how we handle this as an ideal approach, but I hope following will explain how you can use it now:

First, there's a simple way to plug in immutables: You just add `org.immutables.value` to the classpath. Tools such maven, plain javac etc if not configured for certain sophistication (like separate processor paths etc).

Second, when you use build tool with a separate processor path, you would configure  `org.immutables.value` in annotation processing classpath, and annotation-only artifact (with `annotations` classifier. Please, use the same version for both artifacts, not different ones!

In Gradle it can look like this:

```groovy
  apt "org.immutables:value:2.4.3" // for annotation processor classpath, 
 // not propagated to runtime
  provided "org.immutables:value:2.4.3:annotations" // annotation-only artifact for compilation classpath
  // not propagated to runtime
```

Third, there is a very advanced modes of using `org.immutables:value:{version}:annotations` and `org.immutables.processor:{version}` artifacts, but you're on you own here with configuring scopes, dependencies and avoiding any conflicts.

Returning to your original question, you can use following artifacts with the same version:

* `org.immutables:value:2.4.3:annotations` for annotations
* `org.immutables:value:2.4.3` for annotation processor

**Comment by AlexShafir** [comment]
@elucash thanks for shade plugin!
