### ISSUE TITLE
@Modifable should have an option for generating non-chainable setters to satisfy pure Javabean style

### ISSUE THREAD

**Issue by anuraaga** [immutables/immutables#567]
```@Modifable``` seems like a great tool to interop with libraries that require Javabeans, but for which we'd then like to convert into an immutable object in our own business logic with a simple ```toImmutable()``` call - get to use useful tools in the Java ecosystem without breaking our own requirements of immutability :)

Unfortunately, currently ```@Modifiable``` setters always return ```this``` for chaining. This is great for manually constructing mutable objects, but unfortunately is not the spec for JavaBeans, where setters must be ```void```. Some libraries that expect JavaBeans may still work with this, but others may not (especially ones using the standard library ```java.beans``` for introspection). One specific example I've run into is typesafe config.

It would be great if there was a ```@Style``` option for generating ```@Modifiable``` objects without chained setters for use in JavaBean-accepting libraries.

**Comment by anuraaga** [comment]
Thanks for the commit! Wrote a comment on the commit itself, but figured it'd be better to discuss here so copying it here, sorry for the confusion.

Thanks for working on this! I happened to hack on this over the weekend myself and was just about to send a PR, oh well :)

Here's what I had written for reference, looks very similar to this :) The unit test may be useful as it checks for JavaBean spec.
https://github.com/anuraaga/immutables/pull/1/files

One point I realized is that since Collection setters take Iterable always, they are not picked up as properties, so my PR also added an option to allow collection setters to take their exact type. WDYT?

**Comment by elucash** [comment]
@anuraaga  thank you for your work! Heh, wish you send something earlier ))
Let me incorporate some of the pieces to make sure it will work for your case. The only significant difference is that I don't want to advertise JavaBean support because we're not, in that sense that we would just support certain patterns which would make it more JavaBean-friendly

**Comment by anuraaga** [comment]
Yep good point, totally agree that JavaBean compatibility is completely best effort and I'm not expecting it to be 100% (e.g., I think there will be extra read-only properties on a Modifiable, and that should be totally fine for almost all use cases). But just these changes will open things up a lot.

Thanks for the help :)

**Comment by elucash** [comment]
consolidated all changes under single style called `beanFriendlyModifiables` to better align with what we're doing, i.e. we're not merely making void setters, we what them to be bean-friendly (the same goes for having same parameter type as getter return type). @anuraaga please, can you take a look to see if this is enough to support the use case

**Comment by anuraaga** [comment]
Thanks! I left one comment on the commit to improve the Test a little, but it looks like it satisfies the use case quite well :)

**Comment by elucash** [comment]
released in 2.4.4. thank you!
