### ISSUE TITLE
emptry constructor creation

### ISSUE THREAD

**Issue by gsaxena888** [immutables/immutables#569]
For our use-case (we are using Google Cloud Dataflow with AvroCoder), the classes that Immutable builds needs to have an **empty constructor** for the generated immutable class. (Otherwise, AvroCoder fails at runtime.) Is there a way currently that the generated immutable class could have an empty constructor? 

If there is no existing way, is there a hack/workaround you could recommend to us? (I tried manually adding this empty constructor to the generated immutable class, but it seems that Eclipse always re-generates the original code  for the generated immutable class within seconds.)

**Comment by elucash** [comment]
@gsaxena888 I assume private constructor would be ok for this, you can use `@Value.Style(privateNoargConstructor = true)`. The style annotation usage (in general) is described here: http://immutables.github.io/style.html
