### ISSUE TITLE
mongo repositories don't work with Fongo

### ISSUE THREAD

**Issue by asereda-gs** [immutables/immutables#575]
Hello,

We're trying to use [MongoDB repositories](https://immutables.github.io/mongo.html) with [Fongo](https://github.com/fakemongo/fongo) (lightweight java implementation of MongoDB). 

Unfortunately nothing is being saved / updated. After debugging, a little, I believe the problem is in delegate implementation of the `java.util.List` (inside `BsonEncoding` class). 

MongoDB driver [saves documents](https://github.com/mongodb/mongo-java-driver/blob/2.x/src/main/com/mongodb/InsertCommandMessage.java#L44) using traditional loop (which works):

```java
 for (int i = 0; i < documents.size(); i++) {
     writer.write(documents.get(i));
 }
```
[Fongo performs](https://github.com/fakemongo/fongo/blob/master/src/main/java/com/mongodb/FongoDBCollection.java#L115) a for-each operation (which uses `List.iterator()` and doesn't work):
```java
for (DBObject obj : toInsert) {
    //.... 
     put(obj); 
   //....
}
```
`BsonEncoding.InsertObjectList`  always[ returns empty iterator](https://github.com/immutables/immutables/blob/master/mongo/src/org/immutables/mongo/repository/internal/BsonEncoding.java#L428) (while correctly implementing `get()` / `size()` ):

```java
private static class InsertObjectList<T> implements List<DBObject> {

  public DBObject get(int index) {
      position = index;
      return this;
  }

    public int size() {
      return list.size();
    }

    public Iterator<DBObject> iterator() {
      return ImmutableSet.<DBObject>of().iterator(); // always empty iterator here
    }
}
```
Would it be possible to fix it ?

Thanks in advance.

**Comment by elucash** [comment]
the change released in 2.4.6, please, evaluate if it works with Fongo

**Comment by asereda-gs** [comment]
Now I see a different error: Fongo tries to call `BsonEncoding$InsertObjectList.containsField` which throws UOE: 

```
Caused by: java.lang.UnsupportedOperationException
	at org.immutables.mongo.repository.internal.BsonEncoding$InsertObjectList.containsField(BsonEncoding.java:378)
```

Would you consider adding fongo as part of unit tests ? In addition to existing (and manual) [ManualStorage ](https://github.com/immutables/immutables/blob/master/mongo/test/org/immutables/mongo/fixture/ManualStorage.java)

**Comment by elucash** [comment]
If you can help this Fongo or MongoDB driver v3 support and tests (#257) it would be great, otherwise I don't know when I'll have time to get to this. As of now I can only fix only specific issues.

**Comment by asereda-gs** [comment]
Let me try to address this ticket

**Comment by asereda-gs** [comment]
Is there a contribution agreement to be signed ?

**Comment by elucash** [comment]
no, we have copyright "Immutables Authors and Contributors" and ASF2. If you agree, then ok

**Comment by asereda** [comment]
Quick update. I have a working version of Fongo integration.
Just waiting for my company to approve this contribution.

**Comment by elucash** [comment]
@asereda thank you for the contributions! take your time to sort everything out.

**Comment by asereda-gs** [comment]
Please take a look at PR #616

**Comment by elucash** [comment]
I think I got an idea. Great job! Thank you for the PR, merged! Hope to release soon in 2.5.1

**Comment by asereda** [comment]
I will submit one more PR for [JsonParserReader](https://github.com/immutables/immutables/blob/master/gson/src/org/immutables/gson/stream/JsonParserReader.java). We had some issues with primitive numbers (float / int) for embedded entities. 

When are you planning to make new release ?

**Comment by elucash** [comment]
not precise plans, maybe this week, maybe next week. anyway we will re-release when something is available / on demand

**Comment by asereda-gs** [comment]
Please also check #617
