### ISSUE TITLE
Vote on IntelliJ fix for annotation-processor sources in gradle projects

### ISSUE THREAD

**Issue by tkruse** [immutables/immutables#576]
Sorry if this is spam.
IntelliJ IDEA has a bug when trying to import gradle projects using annotation-processor generated sources. I think that may cause users to avoid using Immutables.

Please vote for this to be fixed:
https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FIDEA-124090

Close this ticket without further comment if you like.

**Comment by elucash** [comment]
broadcasted via twitter for more visibility. Thank you for support!
