### ISSUE TITLE
Modifiable#addAll* misses null check on @Nullable

### ISSUE THREAD

**Issue by DennisRippinger** [immutables/immutables#578]
Assume a modifiable model with `@Nullable List<Object> nullableObjects();` This will create a code similar to:
```
  public ModifiableModel addAllNullableObjects(Iterable<Object> elements) {
    if (nullableObjects == null) {
      nullableObjects = new ArrayList<Object>();
    }
    for (Object element : elements) {
      addNullableObjects(element);
    }
    return this;
  }
```
This will lead to a NPE when the foreach loop accesses a null reference. This is problematic when calling modifiableModel.from(model) which eventually calls addAll*.
Here is a MWE: https://github.com/DennisRippinger/immutables-MWE

**Comment by elucash** [comment]
released in 2.4.6 thank you for PR!
