### ISSUE TITLE
Support more than 120 attributes on Value types

### ISSUE THREAD

**Issue by jbagdis** [immutables/immutables#586]
I'm trying to use Immutables to model the response types of a third-party API that contains a large number of fields on each of its response objects. The Value.Immutable annotations processor throws the following error when I try to compile my types:

"Value objects with more than 120 attributes (including inherited) are not supported. You can decompose 'MyClass' class into a smaller ones"

I totally get that it would be cleaner design to decompose these classes into smaller ones, but I need an interface that mimics this third-party API over which I have no control.

The limit of 120 seems to be hard-coded in `AccessorAttributesCollector.java`, with this comment here:
```
/**
   * Something less than half of 255 parameter limit in java methods (not counting 2-slot double
   * and long parameters and reserved slots for technical parameters).
   */
  private static final int USEFUL_PARAMETER_COUNT_LIMIT = 120;
```

I don't see a situation where the number of attributes of an Immutables object would ever be passed as the arguments to a single method (unless I'm using the constructor pattern instead of / in addition to the builder pattern, which I'm not).

My question is: is there an actual, practical limitation on the number of attributes an Immutables object can have when not using the constructor pattern, and if not, could we please remove this arbitrary limit (or at least make it configurable). Thanks.

**Comment by elucash** [comment]
@jbagdis This limitation was probably added when we generated constructors taking all parameters, but this have changed since. I think we can lift the limitation, leaving it up to the compiler to rant about maximum argument length if such generated code ever produced. Thank you for raising this
