### ISSUE TITLE
Potential issue with Jackson when using combination of JsonNaming and JsonDeserialize

### ISSUE THREAD

**Issue by troinine** [immutables/immutables#588]
I'm not entirely sure if this is a bug or a feature but since it not clear to me based on the documentation of `@Style(forceJacksonPropertyNames)` I decided to report this one.

Anyways, when I use the combination of `@JsonNaming` and `@JsonDeserialize`, the generated immutable sources do not honor the property naming strategy anymore. An example as demonstrated by a JUnit test:

```
package test.immutables;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.restassured.path.json.JsonPath;
import org.immutables.value.Value;
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class JacksonTest {
    @Test
    public void test() throws JsonProcessingException {
        MyImmutable myImmutable = ImmutableMyImmutable.builder()
                .longField("test")
                .build();

        String json = new ObjectMapper().writeValueAsString(myImmutable);

        JsonPath jsonPath = JsonPath.from(json);

        assertThat(jsonPath.getString("long_field")).isEqualTo("test");
    }

    @Value.Style
    @Value.Immutable
    @JsonNaming(PropertyNamingStrategy.LowerCaseWithUnderscoresStrategy.class)
    @JsonDeserialize(as = ImmutableMyImmutable.class)
    @JsonSerialize(as = ImmutableMyImmutable.class)
    public interface MyImmutable {
        String getLongField();
    }
}
```
In this configuration, Immutables seems to enforce Jackson property names as the default configuration of `@Style(forceJacksonPropertyNames = true)` suggests. As a result, the generated code has strict property name definition like this:

```
  @JsonProperty("longField")
  @Override
  public String getLongField() {
    return longField;
  }
```

which means that the naming strategy does not get applied. However, if I go and remove the `@JsonDeserialize` and `@JsonSerialize` annotations, things get changed:

```
  @Override
  public String getLongField() {
    return longField;
  }
```

which means that Jackson will properly honor the `@JsonNaming` strategy when serializing the actual object. 

Therefore, it is not clear to me how the generator should behave here. I would assume that it should not matter whether you have the `@JsonDeserialize/@JsonSerialize` annotations in place or not. 

Anyways, for now, I can work around this by defining  `@Style(forceJacksonPropertyNames = false)` but just wanted to raise the issue if it is actually a bug and not a feature :)

The combination of immutables and jackson is used in testing:
- Immutables: 2.4.4
- Jackson Databind: 2.6.7

**Comment by elucash** [comment]
Hi @troinine that's right, if you disable forcing names `forceJacksonPropertyNames = false` it will allow `JsonNaming` to do its work. In practice, there are number of occasions where having forced property names work more correctly, depending if you use or don't use bean-like getter prefixes etc.

**Comment by troinine** [comment]
Hey @elucash! 

This is what I anticipated from the javadocs as well. But you are also saying that the behavior when using `@JsonDeserialize` is normal that it would affect whether `@JsonNaming` has an effect or not?

**Comment by elucash** [comment]
@troinine well, we support really lot of the Jackson functionally transparently. But we can never claim 100% compatibility because we're modeling value objects and Jackson Binding is about Bean-like objects and POJOs. If I have the precise list of supported/unsupported I would include that in documentation. Here, with `JsonNaming`, we're included this switch to undo fixes we've made to support other use cases which deemed to be more idiomatic for users of Immutables. Here also some "popular" blog about pros/cons of using naming translation strategies: https://publicobject.com/2016/01/20/strict-naming-conventions-are-a-liability/
