### ISSUE TITLE
Impossible to set auxiliary values on a class with no parameters

### ISSUE THREAD

**Issue by hendrikvanantwerpen** [immutables/immutables#591]
### How to reproduce

1. Create an immutable class with no parameters, but an auxiliary default value.
2. Set the auxiliary value on a new value.
3. The old value will be returned on read.

### Expected behaviour

The object returned by setting the auxiliary value returns the new value.

### Workaround

The issue only appears when using `builder = false`. So a work-around is to only use parameter-less classes with a builder.

### Diagnosis

The internal `validate` functions checks for equality with `INSTANCE`, and only creates a new object when not equal. Of course, the auxiliary values do not conrtibute to equality, so `INSTANCE` is returned every time.

When the class contains parameters as well, this behaviour does not occur. A new object is always created in the case.

### Example program

See https://gist.github.com/hendrikvanantwerpen/19edaf9908be4f6a7109d17064f6ba8d for an example that shows this behaviour.

**Comment by elucash** [comment]
Very interesting edge case, thank you for reporting this! The should be some obvious fix for that by not short-circuiting on instance equality. It uses singleton inside in the presence of no regular attributes - this behavior was revised some time ago, but this is, probably, a leftover.
