### ISSUE TITLE
Mongo: Query on Embedded/Nested Documents by attribute

### ISSUE THREAD

**Issue by asereda** [immutables/immutables#594]
Hello,

Consider this simple example : 

```java
interface Parent {
    List<Child> children();
}

interface Child {
    int id();
    String name();
}
```
Say I want to query all parents which have a child named `John` (by `name` attribute) . Immutables already provide generated stub : `repository.criteria().childrenContains(child)`

The problem is that `child` instance has to be a correctly constructed object, meaning I have to know, in advance, all required attributes (in our case both `id` and `name`).  Unfortunately [modifiable classes](https://immutables.github.io/immutable.html#modifiable-classes) don't work either (since they're partially constructed).

Is there a way to do such queries in immutables (we'd like to avoid writing raw JSON using `repository.find(String)`). 

Thanks,
Andrei.

**Comment by elucash** [comment]
It was one of the hard decision early on. Currently, only one level is supported. Nested criteria require very careful and sound design. We would generate criteria for that object and then somehow combine criteria.
An alternative (or rather workaround) would be to use redundancy for lookups. Let's say you would have

```javascript
{
  childrenIds: [1, 2,] // <--index on this field
  children: [{
     id: 1,
     name: "One"
  },
  {
     id: 2,
     name: "Two"
  }]
}
```
 
But If you have any spare time, it would be great if you try to generate criteria for nesting object (at first, just by making it a repository of itself, but not used as a repository), then try to poke around and tweak code generation to allow composition of nested criteria. As usual, we really appreciate contributions, especially when talking about designing non-trivial things.

**Comment by asereda** [comment]
What about : 
```
// currently not allowed because Child is not full initialized
repository.criteria().childrenContains(ModifiableChild.create().name("John"));
```
or does it defeat the purpose of immutables ?

**Comment by elucash** [comment]
Queries/Criteria are immutable, so you can create those and store as constants or pass around to create flexible data access services. I understand that you're looking for a simple way to pass a subset of attributes to a query. We can try to define passing of arbitrary Gson bound objects, but still, it has to be somehow designed and thought out. There's also request to generate/validate at compile time subsets or attributes #494.

**Comment by asereda-gs** [comment]
[Criteria API](https://immutables.github.io/criteria.html) now supports nested queries

**Comment by Sarev0k** [comment]
Does the new Criteria API support nested queries?

[According to this commit](https://github.com/immutables/immutables/commit/d3943127359015bf0c27ef92001b866af4a12c41) and the current state of [IterableMatcher](https://github.com/immutables/immutables/blob/0062b374207b7e2e92b9cefdfb39accc84dcd0c3/criteria/common/src/org/immutables/criteria/matcher/IterableMatcher.java) it doesn't look like it does.
