### ISSUE TITLE
Latin-1 diacritic characters are not properly rendered in generated code.

### ISSUE THREAD

**Issue by FSeidinger** [immutables/immutables#598]
Hi there,

can you please revisit issue #423? I'm not the owner of the issue and therefore cannot reopen it. I've commented the issue and that IMHO the provided solution is not sufficient.

Kind regards,

Frank.

**Comment by elucash** [comment]
Let just file it as a new bug, i.e. this one. I think the problem is not in the solution to #423.  I see it as a separate problem with charset processing.

**Comment by novityFS** [comment]
Hi Eugene,

I must apologize. The current problem is not with your annotion processor but with IntelliJ. If I use maven on the command line everything works as expected.

I've come to the conclusion by forking your project and doing some tests with the annotation processor.
