### ISSUE TITLE
[Question]: should we use the Interface or ImmutableValueObject

### ISSUE THREAD

**Issue by tmtron** [immutables/immutables#599]
In the documentation you seem to use the `ImmutableValueObject` only to construct the instance and then in the code you use the `ValueObject` (interface or abstract base class) like this:

```java
ValueObject valueObject =
    ImmutableValueObject.builder()
        .name("My value")
        .addCounts(1)
        .addCounts(2)
        .build();
```

Wouldn't it be better to always just use the `ImmutableValueObject`?

e.g.:

```java
ImmutableValueObject valueObject =
    ImmutableValueObject.builder()
        .name("My value")
        .addCounts(1)
        .addCounts(2)
        .build();
```

Especially for method parameters, etc. The `ValueObject` does not guarantee immutability (e.g. someone could just subclass the `ValueObject` and pass a mutable instance).

Often, I want to use an interface, because I can simply use a different implementation in my tests. But in the case of an immutable object (which is just a data-object), I don't need this: in the test I just prepare my object the way it should be.

Are there any other reasons, I am missing? Is there some doc about the pros and cons?

**Comment by elucash** [comment]
Nowadays, I'm mostly using "sandwich" pattern where abstract value type is the type which is referenced anywhere and is considered "immutable". As for documentation and initial generation style, it is up to the user. Some people use abstract value types, some people promote `Immutable*` and it's like using `List<T>` or `ImmutableList<T>`. For historical reasons, it's hard to promote any of these. In my [tentative] plans there should be something like Immutables 3, where we would settle on and promote a single, most effective style.
