### ISSUE TITLE
A potential bug by code smell

### ISSUE THREAD

**Issue by lifove** [immutables/immutables#600]
Hi

In a recent snapshot, I've found a following suspicious code in value-processor/src/org/immutables/value/processor/meta/ValueAttribute.java

```
1089 
1090   private boolean canAccessImplementation(Protoclass p) {
1091     return p.constitution().implementationVisibility().isPublic()
1092         || (!p.constitution().implementationVisibility().isPrivate()
1093         && p.constitution().implementationPackage().equals(p.constitution().implementationPackage()));
1094   }
```

In Line 1093, equals compares the same expression. Since I don't have enough domain knowledge for this project, I'm not sure if this is intended. This may not be an issue as it always returns true but wanted to report just in case. Thanks!

**Comment by elucash** [comment]
The comparison looks bogus, indeed. Should be revised. Thank you for reporting this.

**Comment by elucash** [comment]
should be, corrected in master
```java
return p.constitution().implementationVisibility().isPublic()
        || (!p.constitution().implementationVisibility().isPrivate()
        && p.constitution().implementationPackage().equals(p.constitution().definingPackage()));
```
