### ISSUE TITLE
Undesirable compilation warning when supertype contains final hashCode/equals methods

### ISSUE THREAD

**Issue by shabino** [immutables/immutables#608]
The classes I generate with Immutables are in a polymorphic hierarchy, and I want their equals/hashCode methods to defer to Object's implementation (identity). In the base of my hierarchy, I defined equals/hashcode, made them both defer to their super impl, and marked them as final. The code that is generated is as I expect, but I receive the warning message below at compilation time:

"Type inherits non-default 'hashCode' method but have some non-inherited attributes. Please override 'hashCode' with abstract method to have it generated. Otherwise override with calling super implemtation to use custom implementation"

I know that I could cut & paste my equals/hashCode impls into every class on the top level of my hierarchy and avoid this warning, but making these methods final in a super class ought to be sufficient expression of a developer's intent that this warning is unnecessary.

**Comment by elucash** [comment]
I agree in general, but trying to recall what was original motivation. Also, need to see if changing the behavior would break other's people code in terms of ending up with not the one implementation of `toString` that they may have used to
