### ISSUE TITLE
Is there a way to rename parameters in a backwards-compatible way?

### ISSUE THREAD

**Issue by io7m** [immutables/immutables#609]
Hi.

I have a type declaration:

```
@Value.Immutable
interface SizeType
{
  @Value.Parameter
  long width();

  @Value.Parameter
  long height();
}
```

I'd like to rename those methods to:

```
@Value.Immutable
interface SizeType
{
  @Value.Parameter
  long sizeX();

  @Value.Parameter
  long sizeY();
}
```

However, I have code that depends on the API/ABI exposed by these types. I could do something like:

```
@Value.Immutable
interface SizeType
{
  @Deprecated
  default long width()
  {
    return sizeX();
  }

  @Deprecated
  default long height()
  {
    return sizeY();
  }

  @Value.Parameter
  long sizeX();

  @Value.Parameter
  long sizeY();
}
```

This would be fine, but it would obviously result in an API and ABI change for the generated builder types. Is there some trick that I can use to treat `sizeX` as a synonym of `width` and so on in a backwards-compatible way?

**Comment by elucash** [comment]
Unfortunately (or fortunately, because of the complexity) there's nothing built-in for this. But we can bridge the gap by patching the generated builder:

```java
@Value.Immutable
interface SizeType
{
  @Deprecated
  default long width()
  {
    return sizeX();
  }

  @Deprecated
  default long height()
  {
    return sizeY();
  }

  @Value.Parameter
  long sizeX();

  @Value.Parameter
  long sizeY();

  class Builder // Inner builder will exteded by generate builder
  {
    @Deprecated
    public ImmutableSizeType.Builder width(long width)
    {
      return (ImmutableSizeType.Builder) sizeX(width);
    }

    @Deprecated
    public ImmutableSizeType.Builder height(long height)
    {
      return (ImmutableSizeType.Builder) sizeY(height);
    }
  }
}
```

**Comment by io7m** [comment]
Ah, thank you! This looks like it'll work well.

I've not actually used custom builders before, so this will be a first.

**Comment by elucash** [comment]
Changed example a bit: abstract methods should be used.

**Comment by io7m** [comment]
Thanks, this worked well. I actually checked the resulting generated code with `japicmp` and the result is binary compatible.
