### ISSUE TITLE
Accept Property during JSON deserialization, but ignore on serialization

### ISSUE THREAD

**Issue by eztinkerdreams** [immutables/immutables#610]
Is there a way to decorate the abstract value type with a nullable, or optional property that can be deserialized, but will not be serialized. I've been unable to do it so far. Perhaps I'm missing something?
This works as expected, but I cannot figure how to decorate the abstract value type to produce this from the generated code...
```
@JsonSerialize
public class Foo {
	
	private String name;

	@JsonIgnore
	public String getName() {
		return this.name;
	}

	@JsonProperty
	public void setName(String name) {
		this.name = name;
	}
```
I'm using the Jackson library. Thanks

**Comment by ldriscoll** [comment]
doesn't this work:
```java
@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
String getMyNonSerializedField()
```

**Comment by eztinkerdreams** [comment]
I'm using Spring boot and I don't have that this... JsonProperty.Access.WRITE_ONLY i think its an older version of Jackson?

**Comment by ldriscoll** [comment]
yeah, it seems to have been added in Jackson 2.6. It was new to me, but we've only just upgraded to jackson 2.7
https://github.com/FasterXML/jackson-annotations/blob/master/src/main/java/com/fasterxml/jackson/annotation/JsonProperty.java#L124

**Comment by eztinkerdreams** [comment]
I was able to upgrade, and get things to compile, but it makes no difference on the serialized output. Doesn't seem to have any affect at all.

**Comment by eztinkerdreams** [comment]
any version of this attribute breaks things badly. 
@JsonIgnoreProperties(value = "name", allowGetters = false, allowSetters = true)
The other one seems to have no affect at all, even though it does get into the generated class.

**Comment by eztinkerdreams** [comment]
There were some [issues](https://github.com/FasterXML/jackson-databind/issues/935) with 2.7 that have been resolved in the 2.8 version of the libraries. I've updated all my dependencies, and I'm able to deserialize the object as expected. 
BUT... when I try and serialize it back out, its unable to find an HttpMessageConver.
""No converter found for return value of type"

**Comment by eztinkerdreams** [comment]
With version 2.8.8 of the jackson dependencies This works... BUT there must be at least ONE other property on the object or serialization fails. 
```
@Value.Immutable
interface AbstractFoo {

	Optional<String> someOtherProperty();

	@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
	String getName();
```
<img width="526" alt="screen shot 2017-05-09 at 3 29 07 pm" src="https://cloud.githubusercontent.com/assets/7387907/25873638/84ad5cf0-34cc-11e7-819f-d47cb9052b62.png">

**Comment by elucash** [comment]
@eztinkerdreams  thank you for raising non-trivial topic. There's nothing built-in for this in Immutables, but seems that `JsonProperty.Access.WRITE_ONLY` worked for me even without additional attribute (Jackson version 2.8.4)

```java
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import org.immutables.value.Value;

@JsonDeserialize(as = ImmutableFoo.class)
@Value.Immutable
interface Foo {
  // Optional<String> someOtherProperty();
  @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
  String getName();

  public static void main(String... args) throws Exception {
    ObjectMapper mapper = new ObjectMapper();
    mapper.registerModules(new Jdk8Module());
    String json = mapper.writeValueAsString(mapper.readValue("{\"name\":\"a\"}",
        ImmutableFoo.class));
    System.out.println(json);
    // outputs:
    // {}
  }
}
```

**Comment by eztinkerdreams** [comment]
@elucash Yes, it's working fine, I'll close the issue. It's not immutables related. It's something about they way that Spring Boot serializes @ResponseBody, its unable to find a message converter unless I add an additional property that is not WRITE_ONLY. If I add an additional property everything works as expected.
