### ISSUE TITLE
Generated add() method of a modifiable class does not use fully qualified name

### ISSUE THREAD

**Issue by vbachvarov** [immutables/immutables#611]
Hi, I found a bug in the generation of the add() method for a modifiable class: @Value.Modifiable.
I have two classes: pkg1.A and pkg2.B. A has an attribute Set&lt;B&gt;. Both classes have the style _deepImmutablesDetection_.
In the generated code the method ModifiableA.addB() refers to "B" by simple name instead of fully qualified name but an import is missing. The generated code does not compile.
Here is the code:
A.java
```
package pkg1;
@Value.Modifiable
@Value.Style(deepImmutablesDetection = true, depluralize = true)
public interface A
{
    Set<pkg2.B> x();
}
```
B.java
```
package pkg2;
@Value.Modifiable
@Value.Style(deepImmutablesDetection = true, depluralize = true)
public interface B
{
    String yy();
}
```
The generated code should be using fully qualified name of ModifiableB after "instanceof":
ModifiableA.java
```
  public ModifiableA addX(B element) {
    B nonNullElement = Preconditions.checkNotNull(element, "x element");
    x.add(element instanceof ModifiableB ? element : pkg2.ModifiableB.create().from(element));
    return this;
  }
```

**Comment by vbachvarov** [comment]
I believe I found the error. I am attaching a patch that should solve the problem. Please test and apply in the next release. :o)

[patch.zip](https://github.com/immutables/immutables/files/997196/patch.zip)

**Comment by augustotravillio** [comment]
Thank you for nailing it down! Fix applied and will be available in the next release. In the meantime, you can use snapshots or build from the source .
