### ISSUE TITLE
vavr support?

### ISSUE THREAD

**Issue by emmanueltouzery** [immutables/immutables#612]
immutables has some special support for javaslang options (see commit 0b59a5b73daaf8a2fc5b03119c835118f1ae1f88). However now javaslang renamed to [vavr](http://www.vavr.io/) and the special support does not apply to vavr.

Ideally special support should be added also for vavr.

**Comment by io7m** [comment]
We're way ahead of you. 😄 

https://github.com/immutables/immutables-javaslang/issues/5

We're just waiting for a `1.0.0` release.

**Comment by io7m** [comment]
Closing this one, as the discussion is going on over there instead.
