### ISSUE TITLE
encodings: NPE during compilation if dependencies are marked as provided

### ISSUE THREAD

**Issue by emmanueltouzery** [immutables/immutables#613]
i'm attempting to extract some bits of immutables-javaslang and using them in my project, but I'm getting a null pointer exception during compilation when attempting to enable it.
I'm not sure what to do next. I'm actually unable to find EncMetadataMirror.java at all...?

[ERROR] org.immutables.value.internal.$processor$.$Processor threw java.lang.NullPointerException: value for 'name'
[ERROR] at org.immutables.value.internal.$guava$.base.$Preconditions.checkNotNull($Preconditions.java:228)
[ERROR] at org.immutables.value.internal.$processor$.encode.$EncMetadataMirror.<init>($EncMetadataMirror.java:255)
[ERROR] at org.immutables.value.internal.$processor$.encode.$EncMetadataMirror.find($EncMetadataMirror.java:68)
[ERROR] at org.immutables.value.internal.$processor$.encode.$EncMetadataMirror.find($EncMetadataMirror.java:56)
[ERROR] at org.immutables.value.internal.$processor$.meta.$Proto$MetaAnnotated.encodings($Proto.java:111)
[ERROR] at org.immutables.value.internal.$processor$.meta.$ImmutableProto$MetaAnnotated.access$801($ImmutableProto.java:1318)
[ERROR] at org.immutables.value.internal.$processor$.meta.$ImmutableProto$MetaAnnotated$InitShim.encodings($ImmutableProto.java:1387)
[ERROR] at org.immutables.value.internal.$processor$.meta.$ImmutableProto$MetaAnnotated.<init>($ImmutableProto.java:1340)
[ERROR] at org.immutables.value.internal.$processor$.meta.$ImmutableProto$MetaAnnotated.of($ImmutableProto.java:1728)
[ERROR] at org.immutables.value.internal.$processor$.meta.$Proto$MetaAnnotated.from($Proto.java:205)
[ERROR] at org.immutables.value.internal.$processor$.meta.$Proto$AbstractDeclaring.metaAnnotated($Proto.java:506)
[ERROR] at org.immutables.value.internal.$processor$.meta.$ImmutableProto$DeclaringType.metaAnnotated($ImmutableProto.java:3386)
[ERROR] at org.immutables.value.internal.$processor$.meta.$Proto$DeclaringType.isEnclosing($Proto.java:924)
[ERROR] at org.immutables.value.internal.$processor$.meta.$ImmutableProto$DeclaringType.isEnclosing($ImmutableProto.java:3026)
[ERROR] at org.immutables.value.internal.$processor$.meta.$Proto$DeclaringType.validate($Proto.java:1003)
[ERROR] at org.immutables.value.internal.$processor$.meta.$ImmutableProto$DeclaringType.validate($ImmutableProto.java:3587)
[ERROR] at org.immutables.value.internal.$processor$.meta.$ImmutableProto$DeclaringType.access$3300($ImmutableProto.java:2634)
[ERROR] at org.immutables.value.internal.$processor$.meta.$ImmutableProto$DeclaringType$Builder.build($ImmutableProto.java:3681)
[ERROR] at org.immutables.value.internal.$processor$.meta.$Round.declaringTypeFrom($Round.java:168)
[ERROR] at org.immutables.value.internal.$processor$.meta.$Round$ProtoclassCollecter.collectIncludedAndDefinedBy($Round.java:282)
[ERROR] at org.immutables.value.internal.$processor$.meta.$Round$ProtoclassCollecter.collect($Round.java:186)
[ERROR] at org.immutables.value.internal.$processor$.meta.$Round$ProtoclassCollecter.collect($Round.java:176)
[ERROR] at org.immutables.value.internal.$processor$.meta.$Round.collectProtoclasses($Round.java:110)
[ERROR] at org.immutables.value.internal.$processor$.meta.$Round.collectValues($Round.java:64)
[ERROR] at org.immutables.value.internal.$processor$.$Processor.process($Processor.java:61)
[ERROR] at org.immutables.value.internal.$generator$.$AbstractGenerator.process($AbstractGenerator.java:87)
[ERROR] at org.immutables.processor.ProxyProcessor.process(ProxyProcessor.java:72)
[ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
[ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
[ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
[ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
[ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
[ERROR] at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
[ERROR] at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
[ERROR] at com.sun.tools.javac.main.Main.compile(Main.java:523)
[ERROR] at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
[ERROR] at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
[ERROR] at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:125)
[ERROR] at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:171)
[ERROR] at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:886)
[ERROR] at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:497)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
[ERROR] -> [Help 1]

**Comment by emmanueltouzery** [comment]
i had the dependencies in the project with the encoding as "provided", as recommended there:
http://immutables.github.io/encoding.html#setting-up-projects

changing them to non-provided stopped that error from happening. maybe it would be worth updating the docs and/or improving the error message?

the encoding still doesn't seem to work though :-(

**Comment by elucash** [comment]
There's definitely a mistake in the doc, `<scope>provided</scope>` should not be used for `org.immutables:encode` dependency for the project defining the encoding. When `provided` (essentially, compile-only) module defining the encoding is added to the module using the encoding, the `org.immutables:encode` should creep into compilation scope as well even if not propagated further (by being a dependency of provided module). Having `org.immutables:encode`  provided in defining module prevents it's from propagating to compilation of a module which uses an encoding . I wish the error message would be better so I'll see if this can be improved somehow, along with the docs

**Comment by elucash** [comment]
updated docs
