### ISSUE TITLE
Package private builder should return definition class rather than implementation class

### ISSUE THREAD

**Issue by ocrease** [immutables/immutables#623]
I am trying to hide my implementation class using the pattern explained in the last part of the [Builder](https://immutables.github.io/immutable.html#builder) section, but the Builder leaks the Immutable implementation class. With the following definition:

```java
package immutables;
import org.immutables.value.Value;

@Value.Style(visibility = Value.Style.ImplementationVisibility.PACKAGE)
@Value.Immutable
public abstract class Container
{
    public abstract int value();
    
    public static class Builder extends ImmutableContainer.Builder {}
}
```

And using this to test the code (in a different package):

```java
package immutables.test;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import immutables.Container;

public class TestContainer
{
    public void test()
    {
        //This compiles
        Container container = new Container.Builder().value(1).build();
        
        //This doesn't
        List<Container> containers = Arrays.asList(1, 2, 3, 4)
            .stream()
            .map(i -> new Container.Builder().value(i).build())
            .collect(Collectors.toList());
    }
}
```

You get the following compilation error:

> src\test\java\immutables\test\TestContainer.java:[19,17] error: ImmutableContainer is not public in immutables; cannot be accessed from outside package

This is particularly an issue when using streams. Since the implementation class is package private, I think that the generated builder's build method should return the definition class `immutables.Container` rather than `immutables.ImmutableContainer`.

**Comment by elucash** [comment]
Please use `overshadowImplementation = true` style attribute to use abstract type as return type of a builder, rather than generated implementation type.

**Comment by ocrease** [comment]
Thanks, that seems to do exactly what I want. Is it worth adding that to the documentation? Having searched through the issues list for `overshadowImplementation` I can see this has been asked a few times.

**Comment by elucash** [comment]
I though it was added somewhere. Well, anyway, will add this. Mark the issue as "docbug".

**Comment by elucash** [comment]
added mention of `overshadowImplementation` to the guide
