### ISSUE TITLE
How to turn off Parcelables generator

### ISSUE THREAD

**Issue by ggggxiaolong** [immutables/immutables#630]
Parcelables.generator overide my Parcelables implement method and CREATOR, but I didn't found where to turn it off.

**Comment by elucash** [comment]
this is a problem, need to add some code to disable generation if `CREATOR` or `writeToParcel` method already defined. sorry for the inconvenience, will try to fix it promptly.

**Comment by elucash** [comment]
released in 2.5.3 . When CREATOR is present, the auto-generation will be disabled. thank you!
