### ISSUE TITLE
generating different types of mongo repositories (eg. read-only)

### ISSUE THREAD

**Issue by asereda-gs** [immutables/immutables#636]
Hello,

In some cases we would like to generate read-only repositories (for Mongo) where modifications are not allowed. I'm thinking about enhancing `@Mongo.Repository` annotation (or introduce new one) to allow customization. Depending on repository settings, code generator will include or omit write operations.

### Example
```java
@Value.Immutable
@Mongo.Repository(collection="myCollection", indexer = true, replacer = false, modifier = false, updater = false)
interface Doc {
  ....
}
```
In this case no `update` / `andReplaceFirst` / `andModifyFirst` methods will be generated for `DocRepository`.

Would you consider such change  ? If yes, do you think Repository annotation is appropriate location ?

**Comment by elucash** [comment]
This is actually a good idea and it's very consistent how we use `Immutable(builder = false, copy = false)` etc. Also we can deprecate `value` attribute in favor of `collection` while having both working. Inserts, probably, also need to be guarded by a separate attribute. `Repository` annotation is the way to go for this. Will keep settings `true` by default for the "ease" of use, disabling where needed. We can introduce separate annotation but it doesn't add anything useful and I definitely don't want to introduce another `@Value.Style`-like infrastructure but for repositories. Thank you for the proposal and PRs are very welcome!

**Comment by asereda-gs** [comment]
I'm debating wherever to have separate annotation attribute for each functionality:
```java
@Repository(finder = true, indexer = true, modifier = false, updater = false)
```

or array of features (defined as enum) : 
```java
@Repository(features = {Feature.FINDER, Feature.INDEXER})
```
Do you have any preference ?

**Comment by elucash** [comment]
My preference is to have boolean attributes as we use in immutable
annotation for similar purposes (builder, copy etc) With enums we will have
to decide if we need exclusion or inclusion set etc. And all those enum
constants feels like too formal and heavyweight approach. So preference is
clearly on the side of boolean knobs.

**Comment by elucash** [comment]
closing as merged/released
