### ISSUE TITLE
encodings init clauses don't work on @Value.Default fields

### ISSUE THREAD

**Issue by emmanueltouzery** [immutables/immutables#638]
immutables encodings work great for us, but `@Encoding.Init` clauses don't apply on fields annotated with `@Value.Default`. I can understand why, default values have a different initialization, but in the end default values can also be initialized in the builder, even though the user doesn't _have_ to do it.

if we give up the `@Value.Default` then the encoding feature is applied, and we can specify a default value in the encoding, but we are now reduced to one default value per type, not a default value per field use.

That said, it's not major for us, because we hit the problem on an optional type, and `None()` makes for a good universal default value for the type. Would still be nice to have though.

**Comment by elucash** [comment]
indeed, encodings were not designed (yet) to properly integrate with default/derived attributes. It's better to flag it as compiler warning/error or maybe simply fixing it by property integrating features. I don't know when I can get back to this due to low priority, but thank you for pointing it out

**Comment by nezda** [comment]
I just ran into this with the following custom encoding and use case:

`CompactLocalDateTime`:
```java
import org.immutables.encode.Encoding;
import org.joda.time.DateTimeZone;
import org.joda.time.LocalDateTime;

@Encoding
public class CompactLocalDateTime {
  @Encoding.Impl
  private long value;

  @Encoding.Expose
  LocalDateTime get() {
    return toLocalDateTime(value);
  }

  @Encoding.Of
  static long fromLocalDateTime(LocalDateTime localDateTime) {
    if (localDateTime == null) {
      return 0L;
    } else {
      //FIXME might be slow?
      return localDateTime.toDateTime(DateTimeZone.UTC).getMillis();
    }
  }

  private static LocalDateTime toLocalDateTime(long value) {
    if (value == 0L) {
      return null;
    } else {
      // fully qualified form here seems to be required for using code to compile?
      return new org.joda.time.LocalDateTime(value);
    }
  }
}
```

Example usage
```java
import javax.annotation.Nullable;

import org.immutables.encode.Encoding;
import org.joda.time.DateTimeZone;
import org.joda.time.LocalDateTime;

@Encoding
public class CompactLocalDateTime {
  @Encoding.Impl
  private long value;

  @Encoding.Expose
  @Nullable LocalDateTime get() {
    return toLocalDateTime(value);
  }

  @Encoding.Of
  static long fromLocalDateTime(@Nullable LocalDateTime localDateTime) {
    if (localDateTime == null) {
      return 0L;
    } else {
      //FIXME might be slow?
      return localDateTime.toDateTime(DateTimeZone.UTC).getMillis();
    }
  }

  @Nullable
  private static LocalDateTime toLocalDateTime(long value) {
    if (value == 0L) {
      return null;
    } else {
      // fully qualified form here seems to be required for using code to compile?
      return new org.joda.time.LocalDateTime(value);
    }
  }
}
```

**Comment by nezda** [comment]
Thinking about this more I think I can workaround this issue by changing `[firstSeen, lastSeen]` fields to a `Range<LocalDateTime>` and doing a custom encoding of that (maybe even round it to minute resolution and possibly use a delta encoding), and default it to `[firstSeen ?: now(), lastSeen ?: now()]` with a custom builder.

**Comment by elucash** [comment]
looking into this; maybe this could just be fixed, thinking about this: there should be no hard impediment to initialize impl field by calling super method.

**Comment by nezda** [comment]
I pulled `b1f1f5186ff370685dee80de770d735c11c18a36` and upgraded my project to `2.6.0-SNAPSHOT` from `2.5.0` and doesn't compile because of incompatible types like

```java
/**
   * @return The value of the {@code firstSeen} attribute
   */
  @JsonProperty("firstSeen")
  @Override
  public LocalDateTime getFirstSeen() {
    InitShim shim = this.initShim;
    return shim != null
        ? shim.getFirstSeen()
        : this.getFirstSeen$get();
  }

  private LocalDateTime getFirstSeen$get() {
    return firstSeen_toLocalDateTime(firstSeen);
  }

// ... `shim.getFirstSeen()` is `long` with this definition
private final class InitShim {
// ...
  long getFirstSeen() {
      if (firstSeenBuildStage == STAGE_INITIALIZING) throw new java.lang.IllegalStateException(formatInitCycleMessage());
      if (firstSeenBuildStage == STAGE_UNINITIALIZED) {
        firstSeenBuildStage = STAGE_INITIALIZING;
        this.firstSeen = firstSeen_fromLocalDateTime(MyImplClass.super.getFirstSeen());
        firstSeenBuildStage = STAGE_INITIALIZED;
      }
      return this.firstSeen;
    }

```

Here's a smaller test case

```java
import org.immutables.value.Value;
import org.joda.time.LocalDateTime;

import com.lexmachina.value_encodings.CompactLocalDateTimeEnabled;

@CompactLocalDateTimeEnabled
public abstract class UseCompactLocalDateTime {
  public abstract static class Base {
    @Value.Default
    public LocalDateTime firstSeen() {
      return LocalDateTime.now();
    }

    @Value.Default
    public LocalDateTime lastSeen() {
      return firstSeen();
    }
  }

  @Value.Immutable
  public abstract static class SomeSubclass extends Base {
    public abstract String name();
  }
}
```

fails with
```ImmutableSomeSubclass.java:[134,24] incompatible types: bad type in conditional expression
[ERROR] long cannot be converted to org.joda.time.LocalDateTime```

**Comment by elucash** [comment]
(just to make sure, sonatype-oss-repo snapshots are not working no, travis is not building, so I assume you used custom built snapshots)

**Comment by nezda** [comment]
(Correct, pulled and built my own copy of b1f1f51 `2.6.0-SNAPSHOT`)

Note that this most recent version of `UseCompactLocalDateTime` which isn't working (and matches my internal project use case's structure) has a different structure with non-`@Value.Immutable` `Base`and subclass `@Value.Immutable` `SomeSubclass`.  (The simpler one [here](https://github.com/immutables/immutables/issues/638#issuecomment-354655183) works fine as I'm sure you saw which developing this change.)

**Comment by elucash** [comment]
it appears that helper fields, virtual fields and internal field of another type than encoded field are fundamentally incompatible with being called from inside initializers (ordering issues). there's another variant how to handle get method which reads as `if (initShim != null) throw new...`  I'm thinking of enabling this for all such encoding/lazy default methods, but then... it seems it will break your use case, so I'm lost

**Comment by nezda** [comment]
One weird thing that occured to me is that I didn't explicitly use `@Encoding.Impl(virtual = true)`
```java
  @Encoding.Impl
  private long value;
```
If I was using `virtual = true` maybe this could be simpler? (I haven't ever looked at the implementation details of any of this under the hood so have no idea.)

If there was an easy way for me to ditch `@Value.Default` for this particular field and "implement it" myself in a custom `Builder` I'd be happy to just do that, but it seems I can't query if fields are "set" from within the builder.

**Comment by elucash** [comment]
there are similar cases: virtual fields (non-stored) and the ones which have a different type than exposed type. Both of this can be complicated by helper fields which can be initialized from impl fields (be it virtual or not)

as a side note, have you tried to encode helper builder method to query if it set (do not annotate one with `@Encoding.IsInit`, but of the similar shape), I wonder if they would auto-appear on a builder.

I'll spend some time thinking about this situation (custom fields + default/derived), I really dislike the idea of leaving it in a current broken state for a long time, have some ideas, need to try

**Comment by elucash** [comment]
> // fully qualified form here seems to be required for using code to compile?
we try to discover and copy imports to the destination, need to check if imports are present in EncodingMetadata on activation annotation and put `//-no-import-rewrite` in the start of the file together with `Style.headerComments = true` to copy it to the output and see if imports are propagated
(just notes to myself)

**Comment by elucash** [comment]
now it should be better, haven't fully tested, but it should handle arbitrary interdependencies between initializers for encoded default/derived attributes except cycles.
imports also corrected (probably I wanted to fully join full class imports into encoding code, but for now just adding them literally)

**Comment by nezda** [comment]
I pulled and attempted to build my internal project again and it didn't compile due to silly difference I didn't have in my previous test case: `getXxx()` props vs. `xxx()` props.  Here's test case that matches my internal project better.

```java
@CompactLocalDateTimeEnabled
@Value.Immutable
public abstract class UseCompactLocalDateTime {
  public abstract static class Base {
    @Value.Default
    public LocalDateTime getFirstSeen() {
      return LocalDateTime.now();
    }

    @Value.Default
    public LocalDateTime getLastSeen() {
      return getFirstSeen();
    }
  }

  @Value.Immutable
  public abstract static class SomeSubclass extends Base {
    public abstract String getName();
  }
}
```

**Comment by nezda** [comment]
Excellent work @elucash ! I pull'd to 46d8db4650327bcc832615388113b102e09276ea and [`UseCompactLocalDateTime`](https://github.com/immutables/immutables/issues/638#issuecomment-355161625) generates the expected code.  I'm looking forward to the release of 2.6.0!
