### ISSUE TITLE
`@Value.Modifiable` + immutable collection fields generates broken code

### ISSUE THREAD

**Issue by rgabbard-bbn** [immutables/immutables#643]
```java
@Value.Immutable
@Value.Modifiable
abstract class Foo {
  public abstract ImmutableList<String> bar();
}
```

generates

```java
...
final class ModifiableFoo extends Foo {
  private ImmutableList<String> bar;

  ....
  @Override
  public final ImmutableList<String> bar() {
    return bar;
  }

...

  public ModifiableFoo addBar(String element) {
    String nonNullElement = Preconditions.checkNotNull(element, "bar element");
    bar.add(nonNullElement);
    return this;
  }
```

Any attempt to use `ModifiableFoo#addBar` will result in an `UnsupportedOperationException`. 

While, the ideal solution would be to have special handling of the Guava collections, until then it might  be better to decline to generate the `add` methods.  The current behavior is a particular problem because [errorprone](http://errorprone.info/) will quite rightly complain about this, even in generated code (since it is an error, not a warning).

**Comment by elucash** [comment]
there is internal recognition of Guava's immutable collection variants so we should be able to suppress generation of unwanted methods. thank you for reporting this!

**Comment by rgabbard-bbn** [comment]
Thanks!  For easy of tracking, I've made #644 for the longer term goal (or to allow it to be explicitly marked as a non-goal).

**Comment by elucash** [comment]
implementing #644, closing this one
