### ISSUE TITLE
@Value.Default on interface default method  generates invalid code for subtype

### ISSUE THREAD

**Issue by cjkent** [immutables/immutables#67]
If an interface declares a default method with ``@Value.Default`` and another interface inherits from it, the generated class for the child interface contains invalid code.

    @Value.Immutable
    public interface Foo {
    
      @Value.Default
      default String foo() {
        return "default value of foo";
      }
    }

    @Value.Immutable
    public interface Bar extends Foo {
    
      String bar();
    }

The generated class ``ImmutableBar`` contains a call to ``Foo.super.foo()`` which fails because ``Foo`` is not an enclosing class. The call should be ``Bar.super.foo()``.

**Comment by elucash** [comment]
This was released, current version is 1.1.3

**Comment by cjkent** [comment]
Works perfectly. Thanks.
