### ISSUE TITLE
Modifiables are missing the @CanIgnoreReturnValue on Setters

### ISSUE THREAD

**Issue by bmhm** [immutables/immutables#671]
Dear all,

Google Errorprone again. It complains that my modifiables don't have a `@CanIgnoreReturnValue` on setters.

I tried to specifiy the setters in my interface, but still the `@CanIgnoreReturnValue` annotation won't show up in the modifiables.

Also, this won't be ignored using `-XepDisableWarningsInGeneratedCode` since this is an error, not a warning.

So, please put `@CanIgnoreReturnValue` on all modifiable setters, since they are mutable and won't create a new instance. The return value can safely be ignored.

Version used: **2.3.10**

Can you please also create a bugfix release in the **2.3.x** branch? thanks.

Thanks a lot!

**Comment by elucash** [comment]
Sure, we will probably add these. A little bit disappointing they dump this on us with insufficient configuration options. For now I would not add these for immutable builders (which can be used both ways wrt return value of initializer methods), but for Modifiable this should be straightforward.

**Comment by bmhm** [comment]
Hi @elucash,

Thank you so much for looking into this! Also I don't think it is needed for immutable builders (yet).

> they dump this on us with insufficient configuration

who is "they"? Google?

Also. is it possible to create an additional **2.3.x** release?
