### ISSUE TITLE
json: revise concept of JSON marshaler generation

### ISSUE THREAD

**Issue by elucash** [immutables/immutables#68]
While this was cool and valuable 3 years ago, after that, there were no much of benchmarking done.
Recently tried benchmarking ([immutables/samples/json](https://github.com/immutables/samples/tree/master/json)). As a baseline I took AutoValue with Jackson annotations (I could take Immutables with Jackson annotations, results would be the same). I would not argue about how representative was sample JSON file or how typical it is. Under different sizes of documents and different set of mapped types and their complexity (primitives, Strings, Enums, Optional, nested Documents) and so on... performance gain [of generated marshalers] on modern JVM comprises about  5-20% which is neither impressive nor something that worth maintenance of separate generator.

```
// Macbook pro, Late 2013, 16GB, 2.3 GHz, Java 8
Benchmark                             Mode  Samples     Score    Error  Units
o.i.s.j.JsonBenchmarks.autojackson    avgt        5  1207.283 ± 26.579  us/op
o.i.s.j.JsonBenchmarks.immutables     avgt        5  1182.491 ± 26.972  us/op
```

As @ivysharev said "maybe world don't need one more JSON marshaler, but that one [of immutables] I really liked".

Now we need to continue benchmarking and also think of alternative ways. How well MongoDB repositories could fit with Jackson only marshaling? Is there still value in polymorphic marshaling by structure?

**Comment by augustotravillio** [comment]
Cool! where is the code?

**Comment by elucash** [comment]
Fresh results

```
o.i.s.j.JsonBenchmarks.autoJackson                    avgt        5   700.167 ±  25.570  us/op
o.i.s.j.JsonBenchmarks.immutables                     avgt        5   693.361 ±  29.186  us/op
o.i.s.j.JsonBenchmarks.immutablesGson                 avgt        5  1120.252 ±  41.352  us/op
o.i.s.j.JsonBenchmarks.immutablesGsonJackson          avgt        5   693.409 ± 108.643  us/op
o.i.s.j.JsonBenchmarks.pojoGson                       avgt        5  1414.169 ±  37.945  us/op
o.i.s.j.JsonBenchmarks.pojoGsonJackson                avgt        5   934.635 ±  38.132  us/op
o.i.s.j.JsonBenchmarks.pojoJackson                    avgt        5   706.698 ±  42.788  us/op
o.i.s.j.NarrowJsonBenchmarks.immutablesGsonJackson    avgt        5   675.735 ±  37.179  us/op
```

2.0-SNAPSHOT Gson marshaling generation is on par with Jackson. It uses speed up gained from Jackson streaming, also it is somewhat more performant then Gson POJO/reflective binding

**Comment by elucash** [comment]
Latest benchmark, just to see what's going on before 2.0 is going to be released.
```
Benchmark                                             Mode  Samples     Score     Error  Units
o.i.s.j.JsonBenchmarks.autoJackson                    avgt        5   709.249 ±  19.170  us/op
o.i.s.j.JsonBenchmarks.immutablesGson                 avgt        5  1155.550 ±  48.843  us/op
o.i.s.j.JsonBenchmarks.immutablesGsonJackson          avgt        5   682.605 ±  20.839  us/op
o.i.s.j.JsonBenchmarks.pojoGson                       avgt        5  1402.759 ± 101.077  us/op
o.i.s.j.JsonBenchmarks.pojoGsonJackson                avgt        5   935.107 ±  58.210  us/op
o.i.s.j.JsonBenchmarks.pojoJackson                    avgt        5   721.767 ±  47.782  us/op
```

**Comment by elucash** [comment]
Updated benchmark project for 2.0-rc
https://github.com/immutables/samples/tree/master/json/src/org/immutables/samples/json
