### ISSUE TITLE
Suppress @JsonProperty annotation when using @JsonUnwrapped

### ISSUE THREAD

**Issue by henryptung** [immutables/immutables#681]
A `@JsonUnwrapped` annotation controls serialization format already; adding an additional `@JsonProperty` confuses Jackson and makes it serialize/deserialize wrapped, instead of unwrapped.

**Comment by henryptung** [comment]
Nevermind, false alarm - I was wrapping a custom deserializer which failed to delegate `unwrappingDeserializer`. Changing that fixed deserialization, even with both `@JsonProperty` and `@JsonUnwrapped` on the same property.

**Comment by abhiInCalif** [comment]
@henryptung What did you end up changing the custom deserializer to to get around this? We're running into a similar issue with having @JsonUnwrapped not unwrapping the underlying object properly when deserializing as the builder or as the ImmutableClass.

**Comment by abhiInCalif** [comment]
Nevermind, we figured it out. It turns out that @JsonUnwrapped doesn't work with Optional<Type>, so we just moved the property to be nullable / not optional.
