### ISSUE TITLE
Add 'transient' keyword to the fields generated from @Value.Lazy and @Value.Derived methods

### ISSUE THREAD

**Issue by ghost** [immutables/immutables#689]
Those fields are calculated therefore they should not been a part of serialised data

**Comment by andrey-cabonline** [comment]
According to documentation lazy attributes suppose to have transient keyword on them. But seems like they don't (on version 2.5.6 at least)

**Comment by elucash** [comment]
this is probably a bug, thank you for reporting this!

**Comment by andrey-cabonline** [comment]
@elucash could you have a look also on #659? Is it also a bug or it supposed to work as it is?

**Comment by elucash** [comment]
lazy attributes had transient added only if serializable, following changed made
* lazy fields always have `transient`
* derived fields have `transient` unless serializable (simple, not for structural)
* precomputed hashCode have `transient` unless serializable (simple, not for structural)

to be released in 2.6
