### ISSUE TITLE
Protected builder and copy methods to hide internal flags

### ISSUE THREAD

**Issue by mcliedtke** [immutables/immutables#690]
(Using Immutables 2.5.6)

Hello,
I predominately use abstract types when using immutables. I have a use case where I have a type that has many fields that get normalized (several strings that get trimmed). I use a single @Value.Check method to do the normalization. However, to stop recursive cases, many fields have to be checked to see if the type is already normalized. This leads to a bunch of conditionals and a really large @Value.Check method. 

I was thinking of using an @Value.Default, protected boolean return method as a flag to denote whether normalization had occurred.

```java
@Value.Immutable
@Value.Style(
    overshadowImplementation = true
)
public static abstract class SomeClass {
        
    public abstract String someStringField();

    //Many more String fields....
        
    @Value.Default
    protected boolean isNormalized() {
        return false;
    }
        
    @Value.Check
    protected SomeClass normalize() {
        if(isNormalized()) {
            return this;
        }
        return builder().from(this)
                .someStringField(someStringField().trim())
                //trim many more Strings
                .isNormalized(true)
                .build();
    }
        
    public static class Builder extends ImmutableSomeClass.Builder {}
    public static Builder builder() {
        return new Builder();
    }
}
```

However, I don't what this field to be visible outside of this class. At the moment, the field is leaked as public in the Builder and the copy methods: 

```java
public final class ImmutableSomeClass extends SomeClass {

  //...
 
  public final ImmutableSomeClass withIsNormalized(boolean value) {
    //... 
  }
  
  // ...
  
  public static class Builder {
  
    //...
	
    public final SomeClass.Builder isNormalized(boolean isNormalized) {
      //...
    }
  }
}
```

Can there be some way to indicate that the corresponding Builder and copy methods be made protected  so that it can effectively be a hidden field? Perhaps a certain @Value annotation, or style indicator? Or maybe fields that are protected can have this behavior by default?

**Comment by elucash** [comment]
`Style(alwaysPublicInitializers = false)` will enable initializers to follow the same access level as the attribute accessor. To be released in the next milestone / 2.6 release. Used style flag to avoid breaking compatibility code if someone depends (being unaware) on the old/current behavior.
