### ISSUE TITLE
Depluralize option removes 's' from builder add method that takes varargs.

### ISSUE THREAD

**Issue by matt-isaman** [immutables/immutables#692]
```java
@Immutable
@Style(typeAbstract = "*Defn", typeImmutable = "*", visibility = PUBLIC, depluralize = true)
abstract class FooDefn {

    public abstract List<String> getFoos();
}
```
Generates:
```java
public final class Foo extends FooDefn {
  ...
  public final Foo withFoos(String... elements) { ... }

  public final Foo withFoos(Iterable<String> elements) { ... }
  ...
  public static final class Builder {
    ...
    public final Builder addFoo(String element) { ... }

    public final Builder addFoo(String... elements) { ... } // should be plural like the parameter name

    public final Builder foos(Iterable<String> elements) { ... }

    public final Builder addAllFoos(Iterable<String> elements) { ... }
}
```
All the plural/singular stuff looks good except for the vararg builder method which seems like it should be pluralized since it takes a vararg parameter of elements.

**Comment by elucash** [comment]
Thank you for the issue report! I assume it was done intentionally, and I would agree this is probably was a mistake, I just worry about breaking source compatibility if we fix this. Both single argument and varargs methods use the same naming template, so only changing it to `addAll*(plural)` or creating separate `add*(plural)` template can be considered. I'm not sure still, but this change will be considered for 2.6
