### ISSUE TITLE
A null value in JSON input triggers a NPE when using @Value.Parameter

### ISSUE THREAD

**Issue by lassemaatta** [immutables/immutables#695]
When receiving JSON input with GSON I'd like to differentiate between a) an explicit null value and b) a missing field. To achieve this I've tried to implement a Java 8 Optional-like construct with `@Value.Parameter`, which would allow null values and return a special token using `@Value.Default` to detect a missing value. 

As an example, for a String-field I might define an Optional wrapper such as

```
@Gson.TypeAdapters
@Value.Immutable(builder = false)
public interface OptionalString {

    String STRING_FIELD_IS_ABSENT =
            "absent_field_" + UUID.randomUUID();

    OptionalString MISSING = ImmutableOptionalString.of(STRING_FIELD_IS_ABSENT);

    @Nullable
    @Value.Default
    @Value.Parameter
    default String value() {
        return STRING_FIELD_IS_ABSENT;
    }

    @Value.Derived
    default boolean isPresent() {
        final String value = value();
        return !STRING_FIELD_IS_ABSENT.equals(value);
    }
}
```

and refer to it in an actual DTO as 

```
    @Nonnull
    @Value.Default
    public OptionalString getData() {
        return OptionalString.MISSING;
    }
```

The generated `GsonAdaptersOptionalString` contains:

```
    @Override
    public OptionalString read(JsonReader in) throws IOException {
      if (in.peek() == JsonToken.NULL) {
        in.nextNull();
        return null;
      }
      return readOptionalString(in);
    }

    private OptionalString readOptionalString(JsonReader in)
        throws IOException {
      return ImmutableOptionalString.of(readParameterValue(in));
    }

    private @Nullable String readParameterValue(JsonReader in)
        throws IOException {
      JsonToken t = in.peek();
      if (t == JsonToken.NULL) {
        in.nextNull();
        return null;
      }
      String value = in.nextString();
      return value;
    }

```
However, this implementation causes a NPE when receiving JSON where `"data": null`. Instead of forwarding the `null` value to the `ImmutableOptionalString.of()` method, the read() method immediately returns `null` to the caller, which causes an NPE as `getDate()` is non-null in the parent DTO.

Is this a bug in the parser or am I doing something horribly wrong?

**Comment by elucash** [comment]
I kinda understand what you're doing. Intuitively, such single argument wrappers should just work, however, early null check prevents it from constructing a proper empty instance. So this is a bug, need to see if early `in.peek() == JsonToken.NULL` check should be removed, at least for such single argument wrapper types. Thank you for reporting this!
