### ISSUE TITLE
Compilation error if staged builders i.c.w. hide implementation pattern

### ISSUE THREAD

**Issue by rolfw** [immutables/immutables#699]
I'm experimenting with staged builders to see how I can use it in conjunction with the [hide implementation class pattern](https://immutables.github.io/immutable.html#hide-implementation-class).

But there is a compilation error in the implementation class when I add an abstract `Builder` type;

**With a Builder interface:**

```
@Immutable
@Style(stagedBuilder = true)
public interface Foo {

	String name();

	int age();

	interface Builder {

	}
}
```

Results in an error due to the following generated code: `public static final class Builder implementsNameBuildStage, AgeBuildStage, BuildFinal Foo.Builder {` (space and comma missing).

**With an abstract Builder class:**

```
 @Immutable
@Style(stagedBuilder = true)
public interface Foo {

	String name();

	int age();

	abstract class Builder {

	}
}
```
Here the `implements NameBuildStage, AgeBuildStage, BuildFinal` part is missing from `public static final class Builder extends Foo.Builder implements NameBuildStage, AgeBuildStage, BuildFinal {` (the latter is after I made corrections to make it compile).

**With an abstract Builder class and stages defined:**

```
@Immutable
@Style(stagedBuilder = true)
public interface Foo {

	String name();

	int age();

	abstract class Builder implements NameBuildStage, AgeBuildStage, BuildFinal {

	}

	interface NameBuildStage {

		AgeBuildStage name(String name);
	}

	interface AgeBuildStage {

		BuildFinal age(int age);
	}

	interface BuildFinal {

		ImmutableFoo build();
	}
}
```

Here there are two issues:

- Builder in implementation doesn't implement build stages (same issue as previous case)
- the staged builder interfaces in the implementation don't extend those in the abstract type

**Comment by alter-kaker** [comment]
I'm having this same issue with v2.10.1, the staged builder interfaces in the implementation don't extend those in the abstract type.

**Comment by elucash** [comment]
@alter-kaker  this issue was fixed and closed. we can reopen issue, but it also can be another issue with staged builders worth a new issue to opened. Can you please provide some example / minimal repro of the issue you have. This closed issue was specifically for "staged builder with inner super-builders", at least that was my understanding at that time
