### ISSUE TITLE
Builder for abstract classes are final

### ISSUE THREAD

**Issue by andreaseberhoefer** [immutables/immutables#702]
I try to use the example for hiding the implementation of the Builder, where you implement an inner class which extends from the immutable builder. This works for interfaces, but not for abstract classes. This wasn't a big problem for me until I tried to use jackson. The problem is, that the generated Builder is always final, so I can't extend from it. I want to use abstract classes, because of I want to use methods annotated with @Check, and this methods should be protected.

**Comment by andreaseberhoefer** [comment]
Thank you for the quick response, you were right.  That I can extend final classes, if the class is an inner static class, was new to me.

**Comment by elucash** [comment]
You're welcome! Inner builder is required to be `static`, in interfaces they are always static (whether there is keyword or not). If static builder found and it extends yet-to-be-generated builder, then generated code no longer use `final` on that builder, which is obviously supposed to be extended by our inner builder. If done right, you can look into generated code and find generated builder is not longer `final`.
