### ISSUE TITLE
@Value.Modifiable with @Value.Style(stagedBuilder = true) produces bad code for @Value.Default attributes

### ISSUE THREAD

**Issue by tonio-ramirez** [immutables/immutables#705]
When applying `@Value.Modifiable` to a class affected by the `stagedBuilder = true` style, attributes marked as `@Value.Default` generate two conflicting `attributeNameIsSet()` methods.

**Comment by elucash** [comment]
reproduced with `stagedBuilder = true` or `strictBuilder = true` and Modifiables. thank you for reporting this! fix to be released in 2.6
