### ISSUE TITLE
json: support to generate Gson type adapter factories for Immutables

### ISSUE THREAD

**Issue by elucash** [immutables/immutables#71]
While playing with benchmarking of JSON marshalers, one of the exercises was a creation of Gson steaming based genereated bindings. Contrary to Jackson's based marshaler generation (implemented in _Immutables_), this time, for Gson, there was an improvement over POJO binding.
Overall, Gson was measured to be less performant then Jackson, sometimes about 2x. Gson APIs are really great and there's much of appreciation to it, also performance could be not an issue in many cases. _Immutables_ can generate bindings/serializers, deserializers for Gson to uniformly marshal value to JSON (along with Jackson).

Should we promote experimental Gson bindings as feature? How many people are interested in this?

**Comment by augustotravillio** [comment]
We are using gson on Android and on the backend. It would be great to try a prototype. Is it a bunch of new annotations and some code generated?

**Comment by arteam** [comment]
+1 for Gson support.
We use it extensively on the server side. It's small, focused and has great API for JSON marshalling and databinding. I would even argue it's more simple to work with Gson in common cases than with Jackson, despite all the features and speed of the latter.

**Comment by elucash** [comment]
@augustotravillio There's no need for a lot of annotations, mostly reuse Gson's `@Expose` and `@SerializedName`, but `TypeAdapterFactory` implementations have to be generated.

@arteam that's why we considering Gson support

**Comment by elucash** [comment]
Actually Gson's annotations will not cut in because they applicable only to fields, not accessor methods.

**Comment by elucash** [comment]
Released in 2.0
