### ISSUE TITLE
TypeAdapters in package-info.java doesn't work for me

### ISSUE THREAD

**Issue by abhineet255** [immutables/immutables#710]
I have added this line to package-info.java (following lead from [immutables test](https://github.com/immutables/immutables/blob/master/gson/test/org/immutables/gson/packg/package-info.java))

`@org.immutables.gson.Gson.TypeAdapters(emptyAsNulls = true, fieldNamingStrategy = true)`

But it is not working for me. I get these errors:

> /build/private/classes/library/com/amazon/dcube/bureau/internal/GsonAdaptersInternal.java:773: error: cannot find symbol
>     [javac]           (TypeToken<List<String>>) TypeToken.getParameterized(List.class, String.class));
>     [javac]                                              ^
>     [javac]   symbol:   method getParameterized(Class<List>,Class<String>)
>     [javac]   location: class TypeToken
>     [javac] /build/private/classes/library/com/amazon/dcube/bureau/internal/GsonAdaptersInternal.java:1133: error: cannot find symbol
>     [javac]       return gson.fieldNamingStrategy().translateName(sampleClass.getField(fieldName));
>     [javac]                  ^
>     [javac]   symbol:   method fieldNamingStrategy()
>     [javac]   location: variable gson of type Gson
>     [javac] 2 errors

Is anyone else observing this? I am using immutables-value/immutables-gson 2.5.6

**Comment by elucash** [comment]
I've seen similar issue reported recently, `TypeToken.getParameterized` and `Gson.fieldNamingStrategy()` is available in newer versions of Gson. Please, upgrade to newer version of Gson, or check if some dependency transitively brings older version and either exclude such transitive dependency or explicitly override it to a newer version (Currently, Immutables compiles against `2.8.0` of Gson)

**Comment by abhineet255** [comment]
Sweet! I was using Gson 2.6.x. Updating to Gson 2.8.x made it work. Thanks!
