### ISSUE TITLE
Violations reported in duplicate with Validator API 2.0

### ISSUE THREAD

**Issue by Stephan202** [immutables/immutables#712]
As of Validator API 2.0 the `javax.validation.constraints` annotations are annotated `@Target(TYPE_USE)` (in addition to their existing targets). As a result such annotations, when placed on an immutable property, are copied to the generated class' private fields. This causes Hibernate Validator to report each violation _twice_: once for the field, and one for the getter methods. Right now this prevents us from upgrading to Validation API 2.0 / Hibernate Validator 6.

(This ticket was extracted from the discussion following https://github.com/immutables/immutables/issues/709#issuecomment-340109003.)

**Comment by Stephan202** [comment]
For completeness, my current thinking on this topic, extracted from https://github.com/immutables/immutables/issues/709#issuecomment-340157667:

A white-/blacklist for `TYPE_USE` annotations could go a long way, if package-basked. Unfortunately for this particular issue it doesn't play very nice with setups where a single `@Value.Style` is used throughout a large project. (Because there'll inevitably be an edge case, and `@Value.Style` doesn't support composition/inheritance.)

Alternatives that I'm currently pondering:
1. Omission from anywhere in the generated code, based on the above-mentioned `@javax.validation.Constraint` meta-annotation.
2. Omission from private fields (and maybe methods/constructors/parameters?) in the generated code of _any_ `TYPE_USE` annotation.

I'm currently tending towards (2), as that seems to be both safer and more general: Immutables would nicely respect `TYPE_USE` on the public API of generated classes, without causing surprising behavior due to its implementation details. And in some sense this type of omission is (paradoxically) consistent with the fact that Immutables currently _adds_ `@JsonIgnore` and `@SuppressionWarnings` annotations (#694, #706) to private fields. In each case it's about preventing implementation details from leaking, be it at runtime (Jackson serialization, Hibernate Validation) or compile time (built-in `javac` warnings, Error Prone analysis).

**Comment by archieby** [comment]
@Stephan202, I'm actually not sure how you made it work for properties at all.
For the rather simple immutable class:

    @Value.Immutable
    public interface Person {
        @Size(max = 5)
        String name();
    }
after it doing the following, I get no constraint vialation 

    ImmutablePerson p = ImmutablePerson.builder().name("asdasdasdasdasdas").build();
    validator.validate(p);
Using Hibernate 6.0.4.Final, validation API 2.0, java 8

**Comment by Stephan202** [comment]
@archieby, it seems the constraint is not verified because `name()` is not a getter. Changing the method `getName()` does trigger a constraint violation. Full test:
```java
public final class ImmutablesValidationTest {
    @Value.Immutable
    public interface Person {
        @Size(max = 5)
        public abstract String getName();
    }

    @Test
    public void test() {
        ImmutablePerson p = ImmutablePerson.builder().name("asdasdasdasdasdas").build();

        Validator validator = Validation.buildDefaultValidatorFactory().getValidator();
        Set<ConstraintViolation<ImmutablePerson>> violations = validator.validate(p);
        assertCorrectConstraintTypes(violations, Size.class);
    }
}
```

**Comment by archieby** [comment]
@Stephan202, that gives me constraint violation. That is correct. But just one. So, I'm not sure how you are getting two of them.

**Comment by Stephan202** [comment]
True. Something more subtle is going on. The following test _does_ fail due to duplicate violations (three, in fact):
```java
public final class ImmutablesValidationTest {
    @Value.Immutable
    public interface OrderRating {
        @Max(5)
        int getStars();
    }

    @Test
    public void test() {
        ImmutableOrderRating orderRating = ImmutableOrderRating.builder().stars(42).build();
        Validator validator = Validation.buildDefaultValidatorFactory().getValidator();
        Set<ConstraintViolation<ImmutableOrderRating>> violations = validator.validate(orderRating);
        assertCorrectConstraintTypes(violations, Max.class);
    }
}
```

(Interestingly Immutables generates `java.lang.@Size` in `ImmutablePerson`, but simply `@Max` in `ImmutableOrderRating`.)

**Comment by Stephan202** [comment]
Hah, changing the `int` for `Integer` the problem goes away, and the generated code then contains `java.lang.@Max(5)`.

**Comment by archieby** [comment]
Yeah. It's weird. Looks like simple validation annotations are being propagated to the the primitives, while ones prefixed with `java.lang.` are being propagated to the Objects.
And while simple validation annotations work for field annotations, `java.lang.` ones do not.
What I would like is the way to use field annotations not having to name all accessors as getters, but it doesn't seem possible now.

**Comment by archieby** [comment]
So, it seems that validation api v2.0 is not completely supported by the Immutables. 
You can probably use the solution @mcgaw uses for bval [here](https://github.com/immutables/immutables/issues/709#issuecomment-340078946). Using hibernave validator v5.x and `@Value.Style(passAnnotations = {...})` as a workaround or smth

**Comment by mcgaw** [comment]
I ended up using AutoValue and living with the slight increase in boiler plate. 2.0 is supported because of the  way annotations are handled. Instead of white listing as above, you have to black list using `@CopyAnnotations` annotation. The validation spec dictates that annotations on the super class will be respected, so everything works out OK (at least in my use case).

**Comment by jestan** [comment]
There are multiple issues using bean validation (1.1 or 2.0) with immutables
1. bean validation requires getters and immutables default style is against it :)
for example following code doesn't work (it doesn't work with ```@Value.Style(passAnnotations = ...)```)
```java

@Value.Immutable
interface Car {

 @Min(2)
  Integer seatCount();
}

```

but it works with getter prefix

```java

@Value.Immutable
interface Car {

 @Min(2)
  Integer getSeatCount();
}

```

2. immutables post processor copies java.lang.@ annotation and it doesn't work (can use ```@Value.Style(passAnnotations = ...)``` as a solution with bean validation 1.1 but it leads to duplicate error with bean validations 2.0)

3. immutables doesn't copy parameterized type annotations, for example

```java

@Value.Immutable
interface Resource {
 @JsonProperty
 List<@Pattern(regexp = "urn:oid:(0|[1-9][0-9]*)(\\.(0|[1-9][0-9]*))*") String> oids();
}
```


finally i am using oval with ```@IsInvariant``` annotation

**Comment by elucash** [comment]
> 3. immutables doesn't copy parameterized type annotations, for example

This is Javac problem, it does not return those using annotation processing API, worked with ECJ
Maybe someday we will insert ugly hacks like parsing those from the source code.

**Comment by elucash** [comment]
don't know if this is the solution, but just have added code to ignore type_use annotations from top-level type use (not the nested generics, that are problematic on its own) which can also be used on method.

**Comment by Stephan202** [comment]
@elucash I am also not sure this is the best solution possible, but it does the trick :+1:. While testing the fix I did hit another issue; filed #744.

**Comment by paulo166** [comment]
Go to the dependecies project and delete, hibernate.validator, and reinstall that in the most recent version. It has solved the problem for me.

**Comment by airm5500** [comment]
i had the same problem
i solved it by comment on entity that following lines like at column
@Size(max = 5) //
@NotNull //
