### ISSUE TITLE
JDK-only classes in generated code

### ISSUE THREAD

**Issue by augustotravillio** [immutables/immutables#72]
Hey Eugene, we really want to use more of _Immutables_ on our new project, but on android and some java API we can use only java standard library. I know that you've been reluctant to not use Guava, but would you mind if I prototype pure JDK support?
Also other people are asking for it: #50

BTW I see you've changed a lot of internals, my head goes round, but it still feels familiar.

**Comment by elucash** [comment]
Great! I assume `Collections.unmodifiable*` and co will be used for collection, but I'm not sure we can cover existing functionality completely. Then I worry about how to not turn templates into a complete mess, It's not that they are very pretty, but let's keep them sane ).

**Comment by augustotravillio** [comment]
Using both kind of optional (Jdk and Guava) do not work well due old import processor it's seems that it's time to merge in @ivysharev's work now

**Comment by augustotravillio** [comment]
I've put everything we need there and even some extra! Seems like a major upgrade. When do you planning to release it?

**Comment by elucash** [comment]
Yay! Thanks! I think we could release it as is in 1.1.1. But real benefits we could get along with #74

**Comment by elucash** [comment]
Released as experimental feature in 1.1.1
I expect that functionality will refined for 2.0

**Comment by elucash** [comment]
With some minor fixes this functionality will be cornerstone of 2.0 release. #74

**Comment by elucash** [comment]
Released in 2.0
