### ISSUE TITLE
Remove "throws IllegalStateException" from checkRequiredAttributes() to satify error-prone ThrowsUncheckedException

### ISSUE THREAD

**Issue by vorburger** [immutables/immutables#720]
The `throws IllegalStateException` should be removed from this generated code:

    private void checkRequiredAttributes() throws IllegalStateException {

this would have no impact, and would satisfy [error-prone's ThrowsUncheckedException bug pattern](http://errorprone.info/bugpattern/ThrowsUncheckedException).

PS: Due to https://github.com/google/error-prone/issues/808, one cannot currently enforce  MethodCanBeStatic in a project using Immutables; that's error-prone's problem though, not Immutables' - just FYI.

**Comment by vorburger** [comment]
@elucash I tried to raise a PR to fix this one as well (together with the 2 other ones just sent), and [found line 1990 in Immutables.generator](https://github.com/immutables/immutables/blob/master/value-processor/src/org/immutables/value/processor/Immutables.generator#L1990), BUT I see there's a `throws [type.throwForInvalidImmutableState]` there, which I doubt you would be happy if I just removed... ;-) 

How can you do something kind of like `[if NOT type.throwForInvalidImmutableState instanceof RuntimeException]throws [type.throwForInvalidImmutableState][/if]` in whatever template engine you're using here?

@Stephan202 FYI another error-prone related one - I see you're onto them as well... good! :smiley_cat:

**Comment by elucash** [comment]
`throwForInvalidImmutableState` is in form of string, `instanceof` is not trivial in this case. I'll see if I can add some classpath lookup/hierarchy analysis for this.
