### ISSUE TITLE
Overriding equals and hashCode does not work for @Value.Modifiable

### ISSUE THREAD

**Issue by hgschwibbe** [immutables/immutables#724]
We are working with immutables and modifiables in our project and we want to handle them equal.
The call `immutable.equals(modifiable)` returns true, but `modifiable.equals(immutable)` returns false.
This breaks the general contract for equality.

I modified the [OmniValue example](https://immutables.github.io/immutable.html#customize-tostring-hashcode-and-equals) from the documentation a little bit to reproduce the problem:
```
@Value.Immutable
@Value.Modifiable
public abstract class OmniValue {
    @Override
    public boolean equals(Object object) {
        return object instanceof OmniValue;
    }

    @Override
    public int hashCode() {
        return 1;
    }

    @Override
    public String toString() {
        return "OmniValue{*}";
    }
}

public class OmniValueTest {
    @Test
    public void testForEquality() {
        ImmutableOmniValue immutableOmniValue = ImmutableOmniValue.builder().build();
        ModifiableOmniValue modifiableOmniValue = ModifiableOmniValue.create();
        Assert.assertTrue(immutableOmniValue.equals(modifiableOmniValue)); // returns true
        Assert.assertTrue(modifiableOmniValue.equals(immutableOmniValue)); // fails with false
    }
}
```

I reproduced this issue with version 2.4.6 and 2.5.5 of immutables, build with Jdk 1.8.0_92.

**Comment by elucash** [comment]
Thank you for reporting this. I reviewed the code, seems that we carefully designed classes to behave this way. Equals and hashcode generally meaningless for mutable objects, and immutable types were never supposed to be equal to modifiable objects even if custom equals can be coded in this way. Also, modifiable types can be not fully initialized and with throw runtime exceptions when compared in such state.

> This breaks the general contract for equality.

this depends on how it is coded. the general consensus on this is that anything other than leaf-subtype equality is ill-defined.

To "fix" your use-case there will be an option to declare `hashCode` and `equals` as `final`. The generator will not attempt to override them for whatever reason. Available in the master and will be released in upcoming 2.6
