### ISSUE TITLE
Have missing required attributes in Exception

### ISSUE THREAD

**Issue by tobias-bahls** [immutables/immutables#730]
I use Immutables in some of my projects to represent entities for REST requests. For invalid requests, I want to return the missing required fields in the entity body like so:

```javascript
{
  "missingAttributes": [ "requiredField" ]
}
```

However, the current implementation does not make this very easy, as the information about the missing required fields is only encoded in the exception message: `java.lang.IllegalStateException: Cannot build ObjectWithRequiredField, some of required attributes are not set [requiredField]`.

I do not think that parsing the exception message is the correct way to solve this problem. Ideally, the thrown exception would include a field that contains all missing required attributes.

I'm willing to contribute if I get some pointers how one might accomplish this without breaking any existing users of the library.

**Comment by elucash** [comment]
Hi Tobias, thank you for raising this. This or similar topic has been raised before, so the concern is very valid. If interested you can read the previous discussions, but in a nutshell, here's what we can do
1. As a workaround, you can parse field names. While suboptimal, there's a promise of stable format (comma separated list in square brackets)
2. Using more heavyweight BeanValidation (jsr 303) integration. Special style attribute (`Style.validationMethod`) can switch-off built-in null/absence checking to. There are a lot of details, many of which are discussed in #26 and linked issues/PRs
3. There's `Style.throwForInvalidImmutableState` style attribute which may help with 1. (custom exception parsing the received string). In a hindsight, I can think of extending this functionality to allow exception class to have a constructor which accept the array of string for missing attributes names, so there will be no need to parse those. It's not yet developed, but given enough interest, it can be done (for example, you can help contributing, of course, with guidance to do it)

**Comment by elucash** [comment]
added code to handle option 3: if `Style.throwForInvalidImmutableState` has the custom exception with a public constructor that takes an array of strings, then if attributes are missing, the exception will be constructed and thrown with the array of missing attributes. Will be available in 2.6.0 (released soon, hopefully)

**Comment by tobias-bahls** [comment]
Thanks Eugene, this really helps :) I've been meaning to look into this, but couldn't find the time :/
