### ISSUE TITLE
Feature suggestion: optional builder method for @Value.Default attributes

### ISSUE THREAD

**Issue by ledoyen** [immutables/immutables#733]
For attributes marked with `@Value.Default`, initial value is optional.
For now, generated builder offers to use the generated method with a non-null value or not to use this method at all.
This kind of data can be represented upstream by an `Optional<T>`.

It would be nice, if generated builder also had a method for this attribute taking an `Optional` of the type of the attribute and avoid breaking the fluent construct in case of an optional value as a defaulted attribute.

**Comment by elucash** [comment]
Thank you for the feature proposal! Seems like a small and useful addition. On one hand, I would ok to add something like this, on the other hand, there are ways to achieve this more or less easily with some boilerplate.

1) Using separate optional and derived attributes:
```java
@Immutable abstract class Aaa {
   abstract Optional<Yyy> valueOpt(); // this way you can set optional in builder
   @Derived Yyy value() {
     return valueOpt().orElse(DEFAULT_VALUE); // a way to compute default value on construction
   }
}
ImmutableAaa.builder().valueOpt(Optional.of(NON_DEFAULT)).build();
```
2) Adding convenience methods to a builder:
```java
@Immutable abstract class Bbb {
   @Default Yyy value() {
     return DEFAULT_VALUE;
   }
   static final class Builder extends ImmutableBbb.Builder {
      public Builder value(Optional<Yyy> opt) {
         opt.ifPresent(this::value);
         return this;
      }
   }
} 
new Bbb.Builder().value(Optional.of(NON_DEFAULT)).build();
```
please, let us know if workarounds would work for you, or this is a recurring pattern and there are too many attributes to customize in this way, for example.

**Comment by ledoyen** [comment]
It is a fast way to achieve what we needed.

There is no need to alter the generated code template to include optional builder method.

If it's okay with you, the issue can be closed.
