### ISSUE TITLE
Add configuration option for disabling errorprone

### ISSUE THREAD

**Issue by stevegutz** [immutables/immutables#734]
The errorprone annotation `com.google.errorprone.annotations.CanIgnoreReturnValue` is currently added to lots of places if errorprone is on the compile classpath. Unfortunately, recent versions of Guava have errorprone as a dependency and maven includes transitive dependencies on the compile classpath. The result of this is that our generated code has errorprone annotations even though it is not a direct dependency. Because we require all used dependencies to be declared, our builds break. 

It's not really feasible for us to add errorprone as a dependency across all of our projects where we use immutables, so it would be nice if there were a configuration option for disabling it altogether.

**Comment by elucash** [comment]
Hi @stevegutz , thank you for the issue report . We will try to think how to improve this controversial situation with error-prone. For now, you can use classpath-fence as explained in the following ticket: #566

**Comment by stevegutz** [comment]
Thanks for the fast response, Eugene. The classpath-fence solution works great. Feel free to close this issue if it's a duplicate or will be unhelpful going forward 😄

**Comment by elucash** [comment]
adding additional whitelist style option in upcoming 2.6.0: #740,
classpath-fence will still work as a blacklist. thank you
