### ISSUE TITLE
Why declared immuables library style in package-info.java doesn't apply for subpackages in java 9 project?

### ISSUE THREAD

**Issue by m-titov** [immutables/immutables#736]
Please see https://github.com/originalrusyn/java9_immutables for more details

So, the following config works correctly with sourceCompatibility = 1.8

```
p.package-info.java

@Value.Style(
    defaults = @Value.Immutable(copy = false),
    strictBuilder = true,
    overshadowImplementation = true,
    implementationNestedInBuilder = true
)
package p;

import org.immutables.value.Value;
```

build.gradle

```
buildscript {
    ext {
        immutablesVersion = '2.5.6'
    }
    repositories {
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath "net.ltgt.gradle:gradle-apt-plugin:0.13"
    }
}

group 'java9'
version '1.0-SNAPSHOT'

apply plugin: 'java'
apply plugin: 'net.ltgt.apt'

sourceCompatibility = 1.9

repositories {
    mavenCentral()
}

sourceSets {
    main
    generated
    test
}

compileJava {
    generatedSourcesDestinationDir = "$projectDir/src/generated/java"
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
}

dependencies {
    apt "org.immutables:value:${immutablesVersion}"

    compileOnly "org.immutables:value:${immutablesVersion}:annotations"

    testCompile group: 'junit', name: 'junit', version: '4.12'
}
```

p.b.B.java

```
package p.b;

import org.immutables.value.Value;

@Value.Immutable
public interface B {

    String getText();
}
```

Why does it produce p.b.ImmutableB.java rather than p.b.BBuilder.java for sourceCompatibility=1.9?

**Comment by elucash** [comment]
This should work, at least on Java8. Most likely this is either bug in Java compiler or Gradle, or maybe new "feature" (or peculiarity) or Java 9 which we have yet to adapt to. For any class, we scan styles on top level types, packages, and parent packages. If for any reason package `p` or its metadata is not accessible while compiling `p.b.B`, the style would not be applied. It would be great if you can investigate source-path which Gradle is using to compile the module or find out any other useful information about this.

**Comment by m-titov** [comment]
It produce `p.b.BBuilder` when I add empty java class `p.A`. But it still produce `p.c.c.ImmutableC` for new interface `p.c.c.C` 
![image](https://user-images.githubusercontent.com/25036750/34077285-f5915f12-e308-11e7-8b67-93026c741896.png)

**Comment by m-titov** [comment]
> It would be great if you can investigate source-path which Gradle is using to compile the module or find out any other useful information about this.

Something like this?:

`09:12:46.427 [DEBUG] [org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler] Compiler arguments: -source 1.9 -target 1.9 -d /Users/m/git_repo/java9_immutables/build/classes/java/main -s /Users/m/git_repo/java9_immutables/src/generated/java -g -sourcepath  -processorpath /Users/m/.gradle/caches/modules-2/files-2.1/org.immutables/value/2.5.6/dfe48bb1214750b932cd59e6953a32a038b74fd/value-2.5.6.jar -XDuseUnsharedTable=true -classpath /Users/m/.gradle/caches/modules-2/files-2.1/org.immutables/value/2.5.6/b6a247a2b31a87f0d20d854308e48708b203a0e4/value-2.5.6-annotations.jar /Users/m/git_repo/java9_immutables/src/main/java/p/A.java /Users/m/git_repo/java9_immutables/src/main/java/p/b/B.java /Users/m/git_repo/java9_immutables/src/main/java/p/c/c/C.java /Users/m/git_repo/java9_immutables/src/main/java/p/package-info.java`

**Comment by tbroyer** [comment]
This is indeed a JDK 9 behavior.

Copy-paste the compiler arguments above (make sure you add an empty-string value to the -sourcepath argument: -sourcepath ''; this is a small glitch in Gradle logging) and pass them to javac. Then repeat the same with `-source 1.8 -target 1.8` or `--release 8`.

**Comment by casidiablo** [comment]
Ok, so it does not work in JDK 9 (and JDK 10, by the way). But why? And how can we work around it?

**Comment by elucash** [comment]
I don't know if this is something that can be "fixed" on the side of a compiler. The workaround to try is to add style meta-annotation or single custom annotation (http://immutables.github.io/style.html#custom-immutable-annotation) combing `Value.Immutable` and `Value.Style`. Not sure 100% it will work either.

**Comment by casidiablo** [comment]
It does not. I tried.

Do we know why this happens though? I still don't get it. Why does it work in Java 8 but not in >= 9? What changed?

**Comment by elucash** [comment]
Compiler implementation is changing, most probably due to modularity. Some elements may no longer available for discovery. I actually have to see check it myself, just cannot find enough time for this

**Comment by Stephan202** [comment]
@m-titov and @casidiablo if you're up for it, please give the change in #884 a spin and let us know whether that fixes the problem for you :)
