### ISSUE TITLE
Can mutate immutable with Optional<Collection<?>> field

### ISSUE THREAD

**Issue by yb172** [immutables/immutables#737]
Hi immutables team.

There is a very nice feature of auto-transforming collections to immutable collections. So if I have
```
public interface Example {
    List<Integer> numbers();
}
```

then I'll have ImmutableList in generated ImmutableExample.
However if I'll change the example a little bit to:
```
public interface UpdatedExample {
    Optional<List<Integer>> numbers();
}
```
then my ImmutableUpdatedExample is no longer mutable. Test case would be:
```
@Test
public void testOptionalCollectionMutation() {
    List<Integer> nums = Lists.newArrayList(1);
    UpdatedExample example = ImmutableUpdatedExample.builder().numbers(nums);
    assertThat(example.numbers().get()).containsExactly(1);
    nums.add(2);
    assertThat(example.numbers().get()).containsExactly(1); // Currently this line will fail
}
```

Such behavior was unexpected for me: I caught this issue when I've modified the entity to be optional and then few of my tests started failing because of mockito matchers:
```
when(shippingService.create(eq(shipping))).thenReturn(sh1);
```
and the reason was `Optional<Multimap<Long, Long>>` field inside `Shipping` object which had type `LinkedListMultimap` while my test case was generating entity using `HashMultimap`.

If there is a replacement of collections to immutable collections I would expect this replacement to happen also if collection is inside of `Optional<?>`.

Thanks.

**Comment by elucash** [comment]
Hi @yan-by, thank you for raising this! The way Immutables works is that it applies the special treatment to an attribute type itself (List, Optional),  but do not apply to the type parameters recursively, as you've stumbled on this. This was raised couple at least once before, but unfortunately, implementing this as one would "expect" is too complicated and we cannot afford this at this moment (backward compatibility and overall complexity of implementation). On the other hand, there's extensibility mechanism called _Encodings_ http://immutables.github.io/encoding.html with which you can totally override how particular type is implemented, this includes attaching special implementation to a combination of types such as `Optional<List<T>>`.
There's yet another related mechanism to convert to immutable types implicitly is `Value.Style(immutableCopyOfRoutines)`. This allows wrapping internal type handling into `immutableCopyOf` static calls imported from classes specified as `immutableCopyOfRoutines` style attributes. Unfortunately, as I just checked, this still don't work for Lists and other types wrapped in Optionals `Optional<List<T>>`. I can take a look at extending `immutableCopyOf` routines support for objects inside optionals, but this is not implemented yet.
