### ISSUE TITLE
Consider going 2.0 for minor breaking changes

### ISSUE THREAD

**Issue by elucash** [immutables/immutables#74]
Despite there's an intent to preserve stability and compatibility, some breaking changes have to be introduced. Most core functionality will remain unchanged, including annotation API.

Things that might change
* Some changes to experimental functionality of 1.0 and 1.1
* Artifact packaging have to be greatly simplified. It's just hard to explain what combination of jars needed
* Removal of unvalidated or out of date `@Beta` features and templates
* Removal of deprecated stuff
* Correct some not-frequently used defaults (generating copy methods by default)

Reasons to introduce changes:
- More simple API
- Simpler artifact structure
- Toolkit should give better expectations about what it will do

**Comment by freben** [comment]
If there were to be changes to the string coercion / type strictness as reported in https://github.com/immutables/immutables/issues/75 , may I suggest they fall under this version break too?

**Comment by elucash** [comment]
Any changes to strictness could also be packed into major (breaking change) set. There's probably much more changes will go for JSON infrastructure, including Gson support, and plain Jackson annotations (without generated marshalers). In that context strictness will be probably an better option

**Comment by elucash** [comment]
Released in 2.0
