### ISSUE TITLE
Style-level whitelist for annotation classpath auto-discovery

### ISSUE THREAD

**Issue by elucash** [immutables/immutables#740]
> Citing added javadoc:

Immutables applies some annotations if found on classpath. These include:

* @javax.annotation.Generated
* @java.annotation.processing.Generated
* @javax.annotation.concurrent.Immutable
* @javax.annotation.ParametersAreNonnullByDefault
* @javax.annotation.CheckReturnValue
* @edu.umd.cs.findbugs.annotations.SuppressFBWarnings
* @com.google.errorprone.annotations.Var
* @com.google.errorprone.annotations.Immutable
* ... and others, etc

This annotation attribute provides a whitelist (if not empty by default) to those annotation discovered. This is motivated that a lot of build configurations gets very complex with different build tools and IDEs, making it hard to solely use classpath management as a way to configure auto-applied annotations.
In order to simply disable all such annotation auto-discovery, you can put some dummy annotation like `java.lang`, as in:

```java
 Style(..., allowedClasspathAnnotations = {java.lang.Override.class})
 ```

The array will no longer be empty as by default so only specified entries will be applied. Please note that standard java.lang annotations like `java.lang.Override`, `java.lang.Deprecated`, `java.lang.SuppressWarnings` will always be applied where supported, so this configuration have no effect on those. At the same time, `javax.annotation.*` or `java.annotation.processing.*` are configurable by this style attribute. Another exception is when some annotation is put on abstract value type or attribute and then propagated to corresponding/related elements of generated classes, these other mechanisms do not count as complementary annotation generation regulated by this property.
Another, more universal way to inhibit some classpath entries from discovery is using class-path fence using META-INF extension mechanism. Add unwanted fully qualified class name prefixes (for example, like full class names, or package names ending with a dot) as the lines to the `META-INF/extensions/org.immutables.inhibit-classpath` resource file available in classpath.

Returns:
a non-empty array of only allowed auto-discovered annotations. Empty by default, which allows any auto-discovered annotation support for backward compatibility.

**Comment by Stephan202** [comment]
:thinking: I'd expect that in general users have classpath issues with a small (likely empty) subset of those types. Would a _blacklist_ thus not make more sense?

**Comment by elucash** [comment]
@Stephan202 classpath-fence works well as blacklist already. The whitelist approach is for people wanting to guard against unexpected classpath leakages (and are concerned about that): the use case is to guard against changes when adding dependencies and they accidentally propagate error-prone, fb and other stuff. That is how I think about it

**Comment by Stephan202** [comment]
Cool, that makes sense :+1:.
