### ISSUE TITLE
immutable mongo some of required attributes are not set

### ISSUE THREAD

**Issue by bhargodevarya** [immutables/immutables#748]
I am using immutables to interact with MongoDB.
I am creating a very simple example below:-

    @Mongo.Repository
    @Value.Immutable
    @Gson.TypeAdapters
    @JsonDeserialize(as = ImmutablePerson.class)
    @JsonSerialize(as = ImmutablePerson.class)
    public interface Person {
    
        @Mongo.Id
        @Value.Auxiliary
        int id();
    
        String name();
    }

When I create an object by 

    ImmutablePerson.builder().name("Amar").build();

I get an exception, which is the following:-

    Cannot build Person, some of required attributes are not set [id]
    	at com.model.ImmutablePerson$Builder.build(ImmutablePerson.java:247) ~[classes/:na]
    	at com.Main.run(Main.java:56) [classes/:na]
    	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)

I have also tried the following, but it also does not work.

    @Mongo.Repository
    @Value.Immutable
    @Gson.TypeAdapters
    @JsonDeserialize(as = ImmutablePerson.class)
    @JsonSerialize(as = ImmutablePerson.class)
    public abstract class Person {
    
        @Mongo.Id
        @Value.Auxiliary
        public abstract int id();
    
        public abstract String name();
    }

Using Integer in place of int also does not help
What am I doing wrong here ??

Thanks,
Bhargo

**Comment by elucash** [comment]
can you please try to use `@value.default` attribute to generate automatic value as shown in the second example of Id attribute: http://immutables.github.io/mongo.html#id-attribute
obviously it adds some verbosity, the easily generated values like ObjectId or random UUID are the best candidates to for this. but its also very clear and correspond how most of the mongodb drivers work (generating objectid before sending to db, if no _id given)

**Comment by bhargodevarya** [comment]
@elucash 

I have used these before and they work as per my expectations.
But what about the one that I have posted.
What are the the valid cases where I don't need the `@value.default` ??

The documentation seems, at least to me, unclear about this.

Thanks,
Bhargo

**Comment by gurpiarbassi** [comment]
I don't think you can assign null values by default. If you look a the generated code, you'll see precondition checks in place for nulls. If you want to be able to build that object and leave the id attribute as null, then use the @Nullable annotation

**Comment by bhargodevarya** [comment]
@gurpiarbassi 

I have seen at the generated code. Yes, the value cant be null.
But the point I am trying to make is, if it is supposed to not be null, then why mention something like this in the documentation.
If its only supposed to be used with `@value.Id` then the other example should be removed.
And if there is a valid use case, then what is it ?

Thanks,
Bhargo

**Comment by elucash** [comment]
Immutables are null hostile by default, if something can be null, it should be made explicitly marked `@Nullable` or better be `Optional`. In the context of MongoDB, ID should always be set on the client (yep, mongo driver can assign it for you, but still, unless I'm missing some newer MongoDB mechanisms), If you leave `int id` (annotated with `@Mongo.Id`) as `null`, then mongo driver will assign some generated `ObjectID` to `_id` field and you will get incompatible type error while trying to read `ObjectID` as `int`. Therefore you can use `org.immutables.mongo.types.Id`, together with its `Id.generate()` method and `@Value.Default` initializer to auto-create object ID. Or if you stick with `int` for `_id` you will have to provide some explicit or generate default value (via the same  `@Value.Default` initializer). If you want to just attach some `@Nullable Integer id` to your object in addition to Mongo's special `_id`, just remove `@Mongo.Id` from this field, so you will have both `_id: ObjectID` and `id: int` fields for different purposes.
