### ISSUE TITLE
Prefer new java.util.ArrayList<>() over com.google.common.collect.Lists.newArrayList() even if Guava is available on the classpath

### ISSUE THREAD

**Issue by vorburger** [immutables/immutables#749]
https://github.com/gaul/modernizer-maven-plugin suggestes that instead of `Lists.newArrayList()` as gen. e.g. here:

```java
    private void checkRequiredAttributes() throws IllegalStateException {
      if (initBits != 0) {
        throw new IllegalStateException(formatRequiredAttributesMessage());
      }
    }

    private String formatRequiredAttributesMessage() {
      List<String> attributes = Lists.newArrayList();
      if (!namePrefixIsSet()) attributes.add("namePrefix");
      if (!loggerIsSet()) attributes.add("logger");
      return "Cannot build ThreadFactoryProvider, some of required attributes are not set " + attributes;
    }
  }
```

it would be better to simply use `new ArrayList<>()` from `java.util`, see:

```
[INFO] --- modernizer-maven-plugin:1.6.0:modernizer (modernizer) @ infrautils-util ---
[ERROR] /home/vorburger/dev/ODL/git/infrautils/common/util/src/main/java/org/opendaylight/infrautils/utils/concurrent/ImmutableThreadFactoryProvider$Builder.java:375: Prefer java.util.ArrayList<>()
```

**Comment by elucash** [comment]
good suggestion, in fact, I already did some cleanups of these occurrences in favor of standard stuff,  but there are some. Limiting factor is that we have to care about Java 6 compatibility (including some on some Android): like if you on Java 6 you'd have to use stuff from Guava. For 2.6 the idea was not to fully break compatibility but put such Java 6 compatibility under (rather hidden) feature flag.
