### ISSUE TITLE
Non-String Values Interpreted Into Strings

### ISSUE THREAD

**Issue by eshrubs** [immutables/immutables#75]
I have run into a weird situation when using Immutables 1.0+.

Consider the following code:

```java
@Value.Immutable
@Json.Marshaled
public interface Item {
  String value();
}
```

`item.value()` will always consume json input regardless of type or null. For example:

```java
String valueInt = "{\"value\": 15 }";
Item intItem = Marshaling.fromJson(valueInt, Item.class);
// intItem.value() == "15"

String valueNull = "{\"value\": null}"; 
Item nullItem = Marshaling.fromJson(valueNull, Item.class);
// intItem.value() == "null"
```

This feels very wrong, especially in the null case. I have declared my value as non-optional type, so passing the a null json value should be considered a parsing error.
Is this the desired behaviour? Or should this be fixed?

Thanks in advance!

**Comment by elucash** [comment]
This is probably desired behavior to be able to read almost everything as string, but for `null` this makes more of a bug than help. Need to skip `null` values. I don't know if we should make it completely strict, thought. Thanks for reporting!

**Comment by freben** [comment]
I would personally argue that for a library like this, and in a strongly typed language reading strongly typed data, silent type coercion is surprising and undesirable. If there were a vote, I would vote for strictness :-) But if you have users that rely on this behavior, I understand that it might be hard to change suddenly (except when bumping the major version).

**Comment by elucash** [comment]
Partially this will be addressed by #80 with simplified jackson integration, where almost everything is delegated to _Jackson_. However, while `null` case will be handled properly,  _Jackson_ pretty much allows to read other primitive types as strings.
Overall  _Jackson_ is so "cool" that it doesn't require any serious code generation to be flexible and high performant. Current direction is to apply code generation techniques to _Gson_ support (#71), there was some measurable performance gains from the generated marshaling routines. To speed up _Gson_ even further, _Gson_ streaming could be implemented by  _Jackson_ streaming (see [JsonParserReader](https://github.com/immutables/immutables/blob/master/gson/src/org/immutables/gson/stream/JsonParserReader.java)).
So to speak, we will put strictness there, under existing configuration `JsonReader.isLenient()`.

**Comment by cocoviper** [comment]
Is there a way to force a Date to be serialized? Right now because the Non-string values are returned as string I get the following value in Json:
```Json
{
"id":92976.0,
"time":"Fri Feb 06 08:11:14 EST 2015"
}
```
The code in my class is: 
```Java
@Value.Immutable(visibility = Value.Immutable.ImplementationVisibility.PUBLIC)
@Value.Style(init = "set*", typeAbstract = "Abstract*",
        typeImmutable = "*", get = {"is*", "get*"}) @Json.Marshaled
abstract class AbstractTransaction {

    @Value.Default public Integer getId() {
        return 0;
    }

    @Value.Default public Date getTime() {
        return new Date();
    }
}
```

**Comment by elucash** [comment]
There are 2 ways how to serialize `Date` or any other objects currently:

_1_. Use `@Jackson.Mapped` on immutable object (along with `@JsonSerialize(as = Transaction.class)` if both abstract and immutable used). Then use Jackson's `ObjectMapper` to serialize and deserialize objects.

```java
ObjectMapper objectMapper = new ObjectMapper();
String json = objectMapper.writeValueAsString(value);
```

This will effectively delegate serialization to Jackson, which by default serialize `Date` to number (UTC value), but this could be overridden. You might also need to use `com.fasterxml.jackson.datatype:jackson-datatype-guava` artifact to support `Optional` or `Immutable-` collections.

```java
objectMapper.registerModule(new GuavaModule());
```

_2_. Other way to customize marshaling is using "marshaling routines". See documentation: [Custom Types](http://immutables.github.io/json.html#toc12) in JSON guide.

Note that `java.util.Date` is mutable and is probably a bad candidate to use with immutable objects.
_Immutables_ have immutable equivalent of UTC instant: `org.immutables.common.time.TimeInstant` which serialized to number in JSON.

Also, in upcoming 2.0 version JSON integration will be greatly simplified, being made less exotic for _Immutables_, especially when it comes to the custom types. We can't wait to release it along with proper documentation.

I can provide more examples if needed. Feel free to post questions or bug reports. Thanks!

**Comment by elucash** [comment]
As 2.0 is released and documentation updated (http://immutables.github.io/json.html) I could consider this issues is resolved in best efforts with some notes:
* With simplified Jackson integration almost all is delegated to Jackson, which still supports a lot of non-strict conversion.
* For Gson support there's ability to set lenient/strict modes. While for JAX-RS integration have strict mode enabled by default, there's caveat, some built-in Gson type adapters (like java.lang.Integer) actually are broken in strict mode.

My conclusion is that while `"null"` problem should be fixed, overall both Jackson and Gson rely on non-strict conversion in some cases, anyway.
