### ISSUE TITLE
Ship both a combined as well as split Annotations/APT Processor JARs

### ISSUE THREAD

**Issue by vorburger** [immutables/immutables#750]
Based on the discussion in https://github.com/uber/NullAway/issues/118, it seems it would be useful if Immutables could ship not just the current single JAR containing both the annotations one put in code using Immutables.org as well as the implementation of the APT processor (which in an ideal world really should not be on the classpath of the application using Immutables.org, only on the javac APT annotationProcessorPaths) as well as both of those in a separate artifact each.

If this is already available, then I do apologize - shout  and I would contribute a doc update to clarify it... :smile:

**Comment by elucash** [comment]
i believe we ship `value:annotations` (classifier) as annotation-only jar,  for the processor path I use the same combined `value` artifact. it's also possible to use `value-processor` as processor, but then it has to have its dependencies on the processor path (it's just unshaded jar artifact)

**Comment by tbroyer** [comment]
I confirm that `<classifier>annotations</classifier>` works (actually using it in Gradle, not Maven).

Also, wrt the original issue, putting `org.immutables:value` in both `<dependencies>` and `<annotationProcessorPaths>` should work too.

**Comment by Stephan202** [comment]
Can confirm @tbroyer's findings. Pasted a semi-complete Maven config @ https://github.com/immutables/immutables/issues/745#issuecomment-375952158.
