### ISSUE TITLE
wrong GsonTypeAdapters generated for class with @Value.Parameter

### ISSUE THREAD

**Issue by mnembrini** [immutables/immutables#754]
Hello,
Having an Immutable class with a @Value.Parameter makes the generated Gson.TypeAdapter wrong (bad serialization)
I have reduced this problem to this simple example:
File Cat.java
```java
import org.immutables.gson.Gson;
import org.immutables.value.Value;

@Gson.TypeAdapters
@Value.Immutable(builder = false)
public interface Cat {

    @Value.Parameter
    String getName();

}
```

File GsonTest.java
```
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.TypeAdapterFactory;
import org.junit.Test;

import java.util.ServiceLoader;

import static org.junit.Assert.assertEquals;

public class GsonTest {


    @Test
    public void correctAdapter() {

        GsonBuilder gsonBuilder = new GsonBuilder();

        for (TypeAdapterFactory factory : ServiceLoader.load(TypeAdapterFactory.class)) {
            gsonBuilder.registerTypeAdapterFactory(factory);
        }

        Gson gson = gsonBuilder.create();

        Cat cat = ImmutableCat.of("I am cat");
        String json = gson.toJson(cat);

        assertEquals("{\"name\":\"I am cat\"}", json);
    }

}
```

This test fails for me with 

```
org.junit.ComparisonFailure: 
Expected :{"name":"I am cat"}
Actual   :"I am cat"
```

The generated method 
```
    private void writeCat(JsonWriter out, Cat instance)
        throws IOException {
      out.value(instance.getName());
    }
```

is not using beginObject() and endObject().

If I switch the class back to using builders, the tests passes.

**Comment by mnembrini** [comment]
My build.gradle
```
plugins {
    // for annotation processing
    id "net.ltgt.apt" version "0.14"
}

group 'ch.aaap.intellij'
version '1.0-SNAPSHOT'

apply plugin: 'java'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.5'
}



dependencies {

    // immutable classes for domain objects
    // this will force gson 2.8 also for other dependencies
    compile 'org.immutables:gson:2.5.6'
    compileOnly "org.immutables:value:2.5.6"
    annotationProcessor "org.immutables:value:2.5.6"

    testCompile group: 'junit', name: 'junit', version: '4.12'
}

```

**Comment by elucash** [comment]
Thank you for reporting this. You've run into a "feature" described here: http://immutables.github.io/json.html#tuples-of-constructor-arguments . This feature is essential for implementing all sorts of transparent typed wrappers around plain types and tuples, but we recognize it structurally instead of having ad-hoc annotations or something like that.
If you remove `builder=false` (or switch it to `true`) you will get the expected result.

**Comment by mnembrini** [comment]
Ok, I see, thanks. 
Is there a reason to prefer not having adhoc annotation for this? 
I have to admit I skipped that part of the documentation, but it is very unexpected behaviour. I don't expect that disabling builders would affect the serialization. Could maybe something be added to the javadoc of the builder attribute? I will do it myself if it is something you would accept.
