### ISSUE TITLE
Add method to check if Builder has no missing attributes

### ISSUE THREAD

**Issue by dair-targ** [immutables/immutables#755]
It would be nice to have a method to check if `Immutable*.Builder.build()` would produce an `IllegalStateException`:
```
public final isBuildable() {
  return initBits != 0;
}
```

**Comment by elucash** [comment]
fixed, will be in next milestone (or release) or 2.6.0. The method will not be generated by default, only if naming template specified (the same as for "buildOrThrow")

```java
@Value.Style(canBuild="isBuildable")
```
and `builder.isBuildable()` with the appropriate check will be generated.

**Comment by dair-targ** [comment]
Thanks!
