### ISSUE TITLE
warning when a super interface is in a library

### ISSUE THREAD

**Issue by kkalmbach-rh** [immutables/immutables#757]
I have 2 source files Super and Sub
```
import javax.validation.constraints.Pattern;

public interface Super {
    @Pattern(regexp = "^[a-fA-F0-9]{1,64}$")
    String getFoo();
}
```

```
import org.immutables.value.Value;

import javax.validation.constraints.Pattern;

@Value.Immutable
public interface Sub extends Super {
    @Pattern(regexp = "^[a-fA-F0-9]{1,64}$")
    String getFoo();
}
```

I compile those no problem.
If I change the pattern in sub (or super) to:
```
    @Pattern(regexp = "^[a-fA-F0-9]{1,65}$")
```

Then recompile, I get the following warning:
```
Sub.java:6: warning: Generated 'Builder.from' method will not copy from attribute 'foo' because it has different return type in supertype (And we cannot handle generic specialization or covarian overrides yet). Sometimes it is possible to avoid this by providing abstract override method in this value object
public interface Sub extends Super {
       ^
1 warning
```

Which makes total sense.  No problems.

(Put the pattern back to match the super class and the warning goes away).

Onto my issue:
Now If I put Super into a jar file:
```
 jar cvf ../lib/test1.jar Super.class 
```

Then try to recompile Sub.java, I get the same warning, even though the return types (including the pattern) are the same.
```
javac -d classes -classpath "lib/*" Sub.java
Sub.java:6: warning: Generated 'Builder.from' method will not copy from attribute 'foo' because it has different return type in supertype (And we cannot handle generic specialization or covarian overrides yet). Sometimes it is possible to avoid this by providing abstract override method in this value object
public interface Sub extends Super {
       ^
1 warning
```

The only way to make this warning go away is to totally remove the pattern in Sub.
```
import org.immutables.value.Value;

import javax.validation.constraints.Pattern;

@Value.Immutable
public interface Sub extends Super {
    // @Pattern(regexp = "^[a-fA-F0-9]{1,65}$")
    String getFoo();
}
```

That removes the warning, but it's not what I want.

Putting Super into a jar file somehow is erasing the pattern from what immutables thinks is the return type.

Any help with this issue would be appreciated.

**Comment by elucash** [comment]
thank you for reporting this. Obviously, while we want to want to warn about incompatibility, considering annotation on type here is not very useful. I would qualify it as a bug which we hopefully can "fix" (Although BeanValidation 2.0's decision to switch to type annotations is, definitely, more far-reaching in breaking other tools' functionality than they probably thought it would).
