### ISSUE TITLE
Optional value builder method has incorrect javadoc reference.

### ISSUE THREAD

**Issue by k21** [immutables/immutables#76]
In https://github.com/immutables/immutables/commit/7e386ae217ca147739c4c76761e5dd909259a49d most javadoc references were changed to use `[sourceDocRef type v]` instead of `{@link [type.name]#[v.names.get]()}`.
One was missed https://github.com/immutables/immutables/commit/7e386ae217ca147739c4c76761e5dd909259a49d#diff-c353b3d5d486cfbadd53edfaf4e666b9L474 because it used a slightly different syntax.
This means that when using `@Value.Style` annotations to change the names of the getters it will refer to the getter by the attribute name instead of the method's name in the javadoc (for example `{@link Type#attribute}` instead of `{@link Type#getAttribute}`.

**Comment by elucash** [comment]
Thanks! Missed that one

**Comment by elucash** [comment]
Additional wrong javadoc references http://pastebin.com/kqwemdpR
Need to fix for the nested types also.

**Comment by elucash** [comment]
Fixes to javadoc reference generation was released in 1.1.1. Thanks again for the feedback!
