### ISSUE TITLE
Create an object without exposing the constructor of the child object

### ISSUE THREAD

**Issue by zhaohaifeng** [immutables/immutables#765]
This is my class,and I use version 2.5.6
```java
@Value.Style(visibility = Value.Style.ImplementationVisibility.PACKAGE, overshadowImplementation = true )
@Gson.TypeAdapters
@Value.Immutable
public abstract class FoobarValue {
    public abstract int foo();
    public abstract String bar();
    public abstract List<Person> getPersonList();
}
```
I need to create a FoobarValue object and add a Person at the same time, but I don't want to use ImmutablePerson outside.  Because Person has a lot of fields, it is still hoped to be built by the Builder, not a constructor or allParameters this form.

I hope to achieve this through a custom Person builder as [#227](https://github.com/immutables/immutables/issues/227) For example:
```java
public abstract class FoobarValue {
    public abstract int foo();
    public abstract String bar();
    public abstract List<Person> getPersonList();

    static class Builder extends ImmutableFoobarValue.Builder{
        public void addPerson(int id, String name, String a) {
            this.addPersonList(ImmutablePerson.builder().id(1).build());
        }
    }
}
```
But I found that ImmutableFoobarValue's builder is final and cannot extends,What should I do?

**Comment by elucash** [comment]
@zhaohaifeng I think you're doing everything right. When annotation processor will see the fact that `Builder extends ImmutableFoobarValue.Builder{`,  then the generated code will no longer have final modifier on `ImmutableFoobarValue.Builder`.  So if you just added extending builder, you need to recompile, and the problem will go away. If this is not working with a "clean" build/compile, please, create a minimal repro example with your build tool.

**Comment by zhaohaifeng** [comment]
Thank U, it works for me 👍 : )
