### ISSUE TITLE
Public Constructor generation should be referenced in the docs

### ISSUE THREAD

**Issue by bowbahdoe** [immutables/immutables#766]
Issue #231 added the ability to make an actual constructor instead of a static factory method. This doesn't seem to be advertised or given an example of the quick tour here https://immutables.github.io/immutable.html.

It is a pretty useful feature, since it lets me "hide" the fact that I am using immutables from library consumers for simple use cases, so I think it should be mentioned.

**Comment by elucash** [comment]
Thank you for pointing this out. I hope to carve some time to expand this and some other topics. Also, I would encourage people to also contribute to docs here [Repo: immutables/immutables.github.io, branch: src](https://github.com/immutables/immutables.github.io/tree/src) if there's desire.
