### ISSUE TITLE
Question: Override "from" method to implement a paper trail mechanism

### ISSUE THREAD

**Issue by minostro** [immutables/immutables#769]
I am trying to implement a paper trail mechanism where I can keep track of all the versions of a given object after it was "modified". The idea would be to save the "current" instance in an array of versions any time the method "from" is called. Let's assume I have a `CardNumber` immutable, and the following operations:

```java
@Target({ElementType.TYPE})
@Style(
    defaultAsDefault = true,
    typeBuilder = "*InternalBuilder",
    visibility = ImplementationVisibility.PACKAGE,
    builderVisibility = BuilderVisibility.PACKAGE
 )
public interface Card {
    UUID id();
    Integer moneyAvailable();

    class Builder extends CardInternalBuilder {};
}

Card cardFirst = Card.builder().id(UUID.randomUUID()).moneyAvailable(300).build();
Card cardSecond = Card.builder().from(cardFirst).moneyAvailable(cardFirst.moneyAvailable() - 100).build();

System.out.println(cardSecond.versions()); //print all the previous cards
```

And a straightforward to do this is to add an array of versions in the `Card` interface and override the `from` method. I learned that `from` method cannot be overridden, so I could define the `fromWithVersion` method that internally calls the `from` method:

```java
public interface Card {
    //previous attributes omitted    
    List<Card> versions();

    class Builder extends CardInternalBuilder {
       public Builder fromWithVersions(Card instance) {
          return this.from(instance).addVersions(instance);
       }
    };
}

...
Card cardSecond = Card.builder().fromWithVersions(cardFirst).moneyAvailable(cardFirst.moneyAvailable() - 100).build();

System.out.println(cardSecond.versions()); //print all the previous cards
```

I want to implement this mechanism to several classes (50 classes) and I would like to generalize the approach by defining a Version class. Unfortunately, I wasn't able to do it. I failed at knowing how to call the specific builders from the Version/Card builder. I would like to have something as follows:

```
public interface Version<T> {
   List<T> versions();

   class Builder extends VersionInternalBuilder {
      ???
    };   
}

public interface Card implements Version<Card> {
   class Builder extends Version.Builder {
      ???
    };
}
```

**Comment by elucash** [comment]
Definitely, this is not so straightforward to achieve given the desired result and limitations. Here's what I was able to come up with using `Optional<T> prevVersion()` and some default methods

```java
interface Version<T extends Version<T>> {
	Optional<T> previousVersion();

	@Value.Derived // Or @Value.Lazy
	default List<T> versions() {
		ImmutableList.Builder<T> versions = ImmutableList.builder();
		for (Optional<T> t = previousVersion(); t.isPresent(); t = t.get().previousVersion()) {
			versions.add(t.get());
		}
		return versions.build();// or maybe build().reverse(); ?
	}

	interface Builder<T, B extends Builder<T, B>> {
		default B fromWithVersion(T prev) {
			return from(prev).previousVersion(prev);
		}
		B from(T prev);
		B previousVersion(T prev);
	}
}

@Value.Immutable
public interface Card extends Version<Card> {
	class Builder extends ImmutableCard.Builder implements Version.Builder<Card, Builder> {
	}
}
```

I believe this can be also possible with just `List<T> versions` without `Optional<T> prevVersion`
Without _default_ methods this would be almost imposible if using _extending_ builder.

**Comment by minostro** [comment]
@elucash thanks for your quick response 🥇Your approach works like a charm! I have a couple of questions though :)

I ended up implementing `Version` as follows (numbers in parenthesis are important):

```java
//(1)
public interface Version<T extends Version<T>> { //(2)
    List<T> versions();

    interface Builder<T, B extends Builder<T, B>> { //(3)
        default B fromWithVersion(T instance) {
            return from(instance).addVersions(instance);
        }

        B from(T instance);
        B addVersions(T instance);
    }
}
```
As you mentioned in your previous comment there is no need to define `Optional<T> prevVersion` to implement the semantics I want. It was a good suggestion though. Questions:

- In line `(1)`, why is there no need to add any Immutables annotation? I added `@Value.immutable` by mistake and it took me a while to realize that you didn't add any annotation. I am kind of new using Immutables, so feel free to point me to the manual if necessary.

- In line `(2)`, there is no need to enforce `T` to be a subtype of `Version` right? this was only necessary because you were accessing `prevVersion`. I think that in my implementation, It would be fine to relax that restriction. Do you see any drawbacks on doing so?

- In line `(3)`, `B` has to extend from `Builder<T, B>` so the compiler let us use `from` and `addVersions` in the `fromWithVersion` default method, correct? `from` and `addVersions` will be implemented by the Immutables builder, but they need to be defined in this interface so we could use it in the `fromWithVersion`.

Thanks again for your help!

**Comment by minostro** [comment]
> Version<T> is a kind of "mixin" we use as part of our immutable object (i.e. Card) and all definitions Card value object inherits from Version are processed in the context of Card annotated by Value.Immutable. List<T> versions() is turned into List<Card> versions() by properly substituting type parameters etc. Such mixins are not required (nor it is desired) to be value objects themselves, they can just carry attributes and other definitions (such as Value.Check) which will be inherited by (and processed as part of) value object. The nested Builder in Version mean nothing special, this is just for grouping, convenience, it is not discovered in any special manner (as opposed to Card.Builder, which is). You can have as many such mixings or base interfaces for values or their builders as you would like as long they do not contain conflicting member definitions.

I see, this makes total sense to me. This interface definition is carrying extra implementation with it, and the Immutables library will resolve it when processing the value object.

> This is not really necessary. We can impose that Version<T extends Version<T>> to prevent some misuse or make it immediately apparent that self-type is expected, but it is not technically needed.

Cool, yeah it makes sense to me.

> For the builder, recursive generic parameter is crucial, I guess.

🥇
