### ISSUE TITLE
[Generics] Code generation is failing when parameters are like <K extends Comparable<K>>

### ISSUE THREAD

**Issue by Nhoutain** [immutables/immutables#779]
Hi everyone,

I'm using the 2.5.5 version.
I'm trying to generate code for this generic interface:
```
@Value.Immutable
public interface AnObject<K extends Comparable<K>> {
    K getMyInsideObject()
}
```
The doc say that generic are "fully supported". Is there any good reason why this kind of parameters (`<K extends Comparable<K>>`) doesn't work?

Thanks in advance for your response.

**Comment by elucash** [comment]
this should work (including 2.5.5), here's test: https://github.com/immutables/immutables/blob/master/value-fixture/src/org/immutables/fixture/generics/RecursiveGenerics.java 
Please check for accompanying or unrelated problems. If the problem persists, please provide some detailed information about java version/compiler used. etc

**Comment by Nhoutain** [comment]
My bad, in fact I'm using the 2.4.4 immutable version in this project by mistake. 
Updating at 2.5.5 fix the issue..

Sorry for this useless issues and the lost time

**Comment by elucash** [comment]
np, you can also upgrade to most recent 2.6.1
