### ISSUE TITLE
@InjectAnnotation cannot reference other immutable classes

### ISSUE THREAD

**Issue by bearcheese** [immutables/immutables#786]
Hi,

We are preparing a small project and I bumped into a problem with `@InjectAnnotation` feature, and I would like to ask for your help in this matter.
I understand that this feature is relatively new and experimental and that Immutables is not intended to be used with tools like Hibernate.

I have a model interface called `Product`, which uses `@InjectAnnotation` feature to inject various JPA annotations into the final immutable class, however it seems it cannot handle the situation when an annotation class parameter would reference another immutable class, as below it would do with `@InjectManyToOne` custom annotation:

```java
@InjectEntity
@Table(name = "product")
@Value.Immutable
@JsonSerialize(as = ImmutableProduct.class)
@JsonDeserialize(as = ImmutableProduct.class)
public interface Product {

    // ...
    
    @InjectManyToOne(targetEntity = ImmutableManufacturer.class)
    @InjectJoinColumn(name = "manufacturer_id", nullable = false)
    Manufacturer getManufacturer();
    
    // ...

}
```
Where `@InjectManyToOne` defined as:

```java
@InjectAnnotation(type = ManyToOne.class, target = FIELD, code = "([[*]])")
public @interface InjectManyToOne {
    Class targetEntity() default void.class;
}
```

Compiling the above will result an `"<error>"` parameter value as you can see in `@ManyToOne` annotation:
```java
@SuppressWarnings({"all"})
@Generated("org.immutables.processor.ProxyProcessor")
@org.immutables.value.Generated(from = "Product", generator = "Immutables")
@Table(name = "product")
@Entity
public final class ImmutableProduct implements Product {
    
    // ...
    
    @ManyToOne(targetEntity = "<error>")
    @JoinColumn(name = "manufacturer_id", nullable = false)
    private final Manufacturer manufacturer;
    
    // ...

}
```

The closest issue to this what I could find was #360, however this one is already closed and I'm using the latest (version 2.6.1) `org.immutables:value` and `org.immutables:annotate` artifacts.

I prepared a simplified version of our project, what you can find here, if it may help: https://github.com/bearcheese/shopping-demo/tree/hibernate-only

Executing `./mvnw clean install` should result in a compilation error due to thee above mentioned generated immutables class.

Additionally I would like to thank you your work with Immutables, I reckon it's a very useful library and it makes our life much more easier!

Thank you!

**Comment by elucash** [comment]
@bearcheese thank you for the kind words and for using our new experimental features!  Usage of not-yet generated types (like references to `ImmutableManufacturer.class`) during annotation processing was always a PITA. I'll see if for #360 we managed to fix this, so I can try to apply the same kind of crutch to annotation injection, so there are chances this can be fixed. If not, I'll try to find some workarounds or suggestion.

**Comment by marcphilipp** [comment]
I also just ran into this. Would it be complicated to fix?

**Comment by elucash** [comment]
should be fixed but possible for a limited amount of cases. I expect there isn't a universal solution for not-yet-generated classes in signatures and annotations, but some cases like these are working now in our tests

**Comment by marcphilipp** [comment]
Awesome, thanks a lot! 👍
