### ISSUE TITLE
Please release the annotation jar on it's own.

### ISSUE THREAD

**Issue by hsyed** [immutables/immutables#787]
in the land of bazel current dep solutions tools do not support classifiers (yet).  Currently the only viable option is to add the jar to a project's repo, or download the jar separately via http.

We exclude the main value annotations jar from the transitive classpath and without the annotations jar we get missing class  compiler warnings from other annotation processors and tools. Another downside of attached artefacts is that sources can't be naturally associated with them.

**Comment by elucash** [comment]
in version 2.7.1 we supply both `org.immutables:value:annotations` and `org.immutables:value-annotations`, which should be otherwise equivalent (and `Automatic-Module-Name: org.immutables.value.annotations` for both). It should be easier now for tools to resolve code and source jars. Thank you!
