### ISSUE TITLE
Multimap varargs builder methods are named inconsistently with List etc.

### ISSUE THREAD

**Issue by bgertzfield** [immutables/immutables#79]
The Facebook Buck team is super excited to have `Multimap` support in Immutables! (At least I am.)

I noticed the `put()` varargs method for a `Multimap<..> foo;` is named inconsistently with the `List` one:

    public final Builder addListFoo(ValueType... elements) { ... }
    public final Builder addAllListFoo(Iterable<ValueType> elements) { ... }

versus:

    public final Builder putAllMultimapFoo(KeyType key, ValueType... values) { ... }
    public final Builder putAllMultimapFoo(KeyType key, Iterable<ValueType> values) { ... }

I think the varargs variant should be named `putMultimapFoo(KeyType key, ValueType... values)` to be consistent with the `List` version that takes varargs.

**Comment by elucash** [comment]
Hi Ben, thanks! @augustotravillio did add `Multimap`, `Multiset` and Jdk collection support in a batch.
When we talked about builder methods we had a clear consensus to mimic what guava does in `Multimap` builder. On the other hand, list's `addListFoo(T... elements)` was made up for convenience. Hence the inconsistency.

If we fix this, there will be some inconsistency anyway. But I think we can go for convenience here and make it `putMultimapFoo(KeyType key, ValueType... values)`.

**Comment by bgertzfield** [comment]
Thanks! I think making it `putMultimapFoo(KeyType key, ValueType... values)` will be fine.

**Comment by elucash** [comment]
Fix for this was landed in maintenance release 1.1.3 currently on Central.

**Comment by elucash** [comment]
Released in 2.0
