### ISSUE TITLE
Allow to pass type T in constructor when using parameter Optional<T>

### ISSUE THREAD

**Issue by icule** [immutables/immutables#800]
Hello,

First of all, thanks for the library, it is really useful.

I'm currently working with the version 2.6.1, and I customized Immutables annotation to have a classic constructor

``` java
@Value.Style(
        get = {"is*", "get*"},
        init = "set*",
        of = "new",
        typeAbstract = {"*Definition"},
        typeImmutable = "*",
        visibility = Value.Style.ImplementationVisibility.PUBLIC,
        allParameters = true,
        jdkOnly = true,
        defaults = @Value.Immutable(copy = false, builder = false))
```

However, when I use Optional as a return type, I'm obliged to provide and Optional in the constructor because the class

``` java
interface Foo {
  Optional<Bar> getBar();
}
```

Will lead to the generation of this constructor

``` java
public Foo(Optional<? extends Bar> bar) {
  this.bar = bar.orElse(null);
}
```

What I would like to have is this constructor

``` java
public Foo(@Nullable Bar bar) {
  this.bar = bar;
}
```

Is there a way to generate such a constructor ?

**Comment by ThLeu** [comment]
This is a "feature" (more likely a bug) that I really miss.
The intended use of Optionals is as a return type and not as an input parameter, so the current implementation never made sense to me and is honestly kind of annoying to use.

I am using the factory methods style like "ImmutableObject.of()" so it should obviously also work there and not only for the constructor.

Please don't get me wrong, the library is a amazing and I am very thankful :-) this is basically the only thing (for now) that I don't like.

**Comment by ThLeu** [comment]
I added some comments to your last commit as I would argue that the flag usage is not correct.
