### ISSUE TITLE
How to suppress specific warning?

### ISSUE THREAD

**Issue by MartyIX** [immutables/immutables#803]
Hi,

I've encountered:

```
warning: Generated builder '.from' method will not copy from attribute '<X>' because it has different return type in supertype (And we cannot handle generic specialization or covariant overrides yet). Sometimes it is possible to avoid this by providing abstract override method in this value object
public interface Something extends SomeSuperType {
```
(https://github.com/immutables/immutables/blob/master/value-processor/src/org/immutables/value/processor/meta/FromSupertypesModel.java#L141)

I know there is a section about warning suppression: https://immutables.github.io/immutable.html#warnings but I still wonder whether I can suppress just this specific warning.

Does anyone know?

Thank you!

Regars,
Martin

**Comment by elucash** [comment]
Thank you for raising this! Unfortunately, there are no specific warning, I'll see if we can make those as individual warnings

**Comment by elucash** [comment]
some more detailed categories of warnings can be suppressed now in 2.7.1 so
`@SuppressWarnings("immutables")` disables all warning coming from immutables, but `@SuppressWarnings("immutables:from")` disables only warnings about `Builder.from` method. These categories are not very fine-grained though. Each warning now have them specified in front of a message in parentheses.
