### ISSUE TITLE
allow custom CodecProvider(s) for mongo adapter

### ISSUE THREAD

**Issue by asereda-gs** [immutables/immutables#807]
Hello,

Currently mongo repository [instantiates](https://github.com/immutables/immutables/blob/master/mongo/src/org/immutables/mongo/repository/Repositories.java#L88) internal bson codec provider which is based on [gson](https://github.com/google/gson). Since Mongo driver allows [pluggable](http://mongodb.github.io/mongo-java-driver/3.6/bson/codecs/) (de)serializers it would be nice to allow users to provide their own implementation (if needed). 

As example, separate codec can be easily written on the top of [bson4jackson](https://github.com/michel-kraemer/bson4jackson) library allowing clients to use jackson mapping to persist entities into mongo.

### Constraint (Bson Filter) Encoding
The only thing I'm unsure about is how to correctly encode mongo filters (aka [Constraint](https://github.com/immutables/immutables/blob/master/mongo/src/org/immutables/mongo/repository/internal/Constraints.java)) into bson format (see [find(Bson)](http://mongodb.github.io/mongo-java-driver/3.7/javadoc/com/mongodb/client/MongoCollection.html#find-org.bson.conversions.Bson-)). More specifically, how to allow different field naming strategies. Sometimes Fields / Methods can have different names at runtime and when serialized (persisted).  
#### Example
```java
// Query on Foo should contain secretName (not name)
interface Foo {
   @JsonProperty("secretName")
   String name();
}
```
Currently immutables is re-using [FieldNamingStrategy](https://google.github.io/gson/apidocs/com/google/gson/FieldNamingStrategy.html) from gson, but what if one leverages a different library ? Some solutions:
1. Injectable interface similar to `FieldNamingStrategy` (eg. `Function<Member, String>`) into `RepositorySetup`.
2. Special bson codec for `Constraint` (plus somehow save information about Field) ? 

Any other suggestions are welcome.

Would you consider such a contribution ?

**Comment by elucash** [comment]
Such a contribution would be welcome. While I adore `jackson-core`, I had many problems with `jackson-bind` as it over flexible (geared toward "free-form" pojoish beans) and a bit inconsistent at the edge cases, hence the choice of Gson as default API (as you can see we really skip actual Gson streaming code, just binding infrastructure). But as a story goes, this is more about enabling any kind of encoding, not specifically `jackson-bind` so yes, this should be beneficial.

Just as reminding to myself: this should somehow align with the idea of future generic JSON binding API/ custom-extensible DB repository generation.

**Comment by elucash** [comment]
We probably need custom `FieldNamingStrategy` interface (probably better than just `Function`) with the default implementations provided by Immutables, or adapters for corresponding Jackson/Gson classes/enums.

**Comment by elucash** [comment]
And something for `Constraints` obviously. It is interesting if we can adapt present constraints to the encoder as an object/map, or are we better of individually encoding constraint values, streaming the field names and operators ourselves?

**Comment by asereda-gs** [comment]
We don't have to address `Constraints` for this issue (maybe for #812). If `FieldNamingStrategy` is exposed that is sufficient (for now).

Constraints are currently encoded using visitor pattern on [ConsConstraint](https://github.com/immutables/immutables/blob/master/mongo/src/org/immutables/mongo/repository/internal/Constraints.java#L208). Serialization of `ConsConstraint.value` can be delegated to [Codec](http://mongodb.github.io/mongo-java-driver/3.8/bson/codecs/). What do you think ?

**Comment by elucash** [comment]
agree, it only makes sense to encode values using the same codec.

**Comment by asereda-gs** [comment]
Pls take a look at #817. 
It is just a first attempt (for feedback).
