### ISSUE TITLE
Remove transient from Derived fields

### ISSUE THREAD

**Issue by andreaseberhoefer** [immutables/immutables#808]
Hi,
I'm playing with @InjectAnnotation and JPA. It works good with hibernate, but I have a problem with Derived fields, because they are marked as `transient` in the code. I know this was introduced with #689. For me it is a problem, because hibernate ignores transient fields. 
Here is an example, what I want to do:

```
@InjectEntity
@Style(privateNoargConstructor = true)
@Immutable
abstract class MyEntity {
   @InjectId 
   public abstract long getID();

   @InjectColumn(name="VALUE")
   public abstract int getValue();
   
   // This should also be persisted, 
   // but since immutables generates a transient field for this,
   // hibernate ignores this value
   @Derived
   @InjectColumn(name="CALCULATED_VALUE")
   public int getCalculatedValue () {
       return getValue() + 42; 
   }
}
``` 

As a workaround I found out that the derived-field is not marked as `transient`, if MyEntity implements Serializable. Maybe you could make it only `transient`, if the class is not Serializable or make this configurable.

Thanks

**Comment by elucash** [comment]
here probably only feature flag may be added (to not break code for people who can accidentally depend on current "smart-pants" behavior wrt serialiable etc), thank you for reporting this!

**Comment by elucash** [comment]
new in 2.7.1 : `Style(transientDerivedFields = false)`  would disable default behavior, no transients will be put on derived fields.
Thank you!

**Comment by andreaseberhoefer** [comment]
Thank you!
