### ISSUE TITLE
Wrong JsonProperty annotation on boolean property

### ISSUE THREAD

**Issue by jurgc11** [immutables/immutables#811]
I've got a value object which looks like this:
```
@JsonDeserialize(as = ImmutableValueObject.class)
@Value.Immutable
public interface ValueObject {

    boolean isValid();
}
```
The generated ImmutableValueObject code contains this:

```
  @JsonProperty("isValid")
  @Override
  public boolean isValid() {
    return isValid;
  }
```

I would have expected that `@JsonProperty` annotation to have a value of `valid`, not `isValid`. Am I missing something or is that a bug?

I'm using Immutable 2.6.4 and Jackson 2.9.6.

Thanks

**Comment by jurgc11** [comment]
This seems to fix it, although I still don't understand why it's doing something so un-Java like: https://immutables.github.io/style.html#is-prefix-and-custom-getters

**Comment by elucash** [comment]
In addition, there's `Style(forceJacksonPropertyNames = false)` this will prevent generation of `@JsonProperty("you_name_it")`, so default Jackson rules will be used like default conventions or naming strategies.

As you've already read in https://immutables.github.io/style.html#is-prefix-and-custom-getters, we're not very keen to support JavaBeans conventions at least by default. Attribute names should be as they are, whether "isEmpty" or "empty" and map directly (where possible) to JSON fields avoiding arbitrary legacy conventions.

**Comment by pauldingemans** [comment]
@elucash As far as I see, no further action is needed on this issue. Would you mind closing the issue or otherwise propose/clarify what needs to be done before it can be closed?
