### ISSUE TITLE
Pattern matching criteria for Optional<String> fields

### ISSUE THREAD

**Issue by coreyjboyle** [immutables/immutables#813]
Hi

When using Immutables generated Repositories, only string fields have pattern matching criteria methods generated (*StartsWith, *Matches, *NotMatches).  We would like to have these methods generated even for Optional<String> fields.  Is this something that makes sense to add to Repositories.generator, or is there a different/better way?  I'm happy to contribute if this is the recommended approach.

Thank you
Corey

**Comment by coreyjboyle** [comment]
Went ahead and created a PR, #814, in case this is the recommended approach.

Thanks!

**Comment by elucash** [comment]
This is straightforward piece of functionality! Merged PR! Thank you!

**Comment by elucash** [comment]
released in 2.7.1 . Thank you!
