### ISSUE TITLE
Nullary `of()` method with `@Style(allParameters = true)`

### ISSUE THREAD

**Issue by Stephan202** [immutables/immutables#816]
Consider the following type definition:
```java
@Value.Immutable
@Value.Style(allParameters = true)
public interface Dummy {
    default String getType() {
        return "dummy";
    }
}
```

With this definition, the generated `ImmutableDummy` class will not have an `ImmutableDummy.of()` factory method; instead one must call `ImmutableDummy.builder().build()`. If another (non-`default`) property is added, then the `of` constructor _does_ become available.

Suggestion: make `of` unconditionally available when `allParameters = true`. This mirrors what Guava does for the production of empty data types (`ImmutableList.of()`, `ImmutableSet.of()`, etc.).

---
Some context about our use case for types of the above form: as part of a migration from an enum type to a collection of complex types we have defined a number of types such as the one above, all implementing a shared interface. During code review the use of `.builder().build()` was challenged, since throughout our codebase we're used to instantiating Immutables using the `of` factory method.

**Comment by elucash** [comment]
@Stephan202  thank you for reporting this! I kinda feel ok with justification for that, but I think that changes might not be necessary as we have a separate switch to enable auto-singleton when there are no attributes: `attributelessSingleton = true`. Semantically this might not be the quite the same as just constructing new instance (in this case even `.builder().build()` will return the same singleton) but this seems to be quite ok with immutable objects and similar to mentioned ImmutableList.of(), ImmutableSet.of(), etc. Please let me know if that can work for your case

**Comment by Stephan202** [comment]
@elucash I had completely forgotten about `@Style(attributelessSingleton = true)` and `@Value(singleton = true)`. Those work fine for our purposes. Thanks!

**Comment by hicksel** [comment]
Sorry for bringing this up again, but i have a use case where i need to generate many immutable objects that often times only have @Value.Derived attributes.
Having empty .of() factory methods would greatly clean up my Code.
