### ISSUE TITLE
SortedSet vs Set convenience methods not generated

### ISSUE THREAD

**Issue by frank-montyne** [immutables/immutables#820]
Hi,

I'm using a SortedSet in one of my immutable classes. When doing so the convenience methods to add elements to the sorted set are not generated. If I change the definition to Set then the convenience methods are generated. Is there any specific reason for this behavior oris this a bug?

Example:

With Set:

```java
@Gson.TypeAdapters
@Value.Immutable
@Serial.Version(value = 1)
public abstract class Message {
    public abstract @Nonnull Set<Parameter> parameters();
    ...
}
```

Ok: 

```java
    public final Builder addParameters(Parameter element)
    public final Builder addParameters(Parameter... elements)
    ...
   public final Builder parameters(SortedSet<Parameter> parameters)
```
are generated.

With SortedSet:

```java
@Gson.TypeAdapters
@Value.Immutable
@Serial.Version(value = 1)
public abstract class Message {
    public abstract @Nonnull SortedSet<Parameter> parameters();
    ...
}
```

Not Ok: 

```java
   public final Builder parameters(SortedSet<Parameter> parameters)
```
is generated, no convenience methods like above.

All help is appreciated!

Best regards,
Frank

**Comment by elucash** [comment]
Thank you for reporting this! This is briefly covered in [documentation section on collections](http://immutables.github.io/immutable.html#array-collection-and-map-attributes), but probably not stressed enough. Please add `@Value.NaturalOrder` (or `@Value.ReverseOrder`) to specify proper ordering for `[Sorted|Navigable][Set|Map]` collections, this will enable all convenience methods on builder etc.
If custom comparator is needed, then create immutable sorted set externally to builder, _Immutables_ will not help here (would be unnecessary API burden)

**Comment by frank-montyne** [comment]
Thanks for the fast reply! Works like a charm:)

**Comment by StephenOTT** [comment]
@elucash does @Value.NaturalOrder work with custom objects (other Immutable classes)? such as SortedSet<SomeImmutableInterface>

I am currently getting compile errors when adding NaturalOrder but errors are not clear.

Also how does the @Value.NaturalOrder work with a `Set`?

**Comment by elucash** [comment]
`@Value.NaturalOrder` and `@Value.ReverseOrder` are only for Sorted/NavigableSet, and relies on elements to be Comparable, otherwise, CCE will occur. Custom comparators and everything else — remove ordering annotations and construct things in DIY manner
