### ISSUE TITLE
How to specify toString() method on interface?

### ISSUE THREAD

**Issue by MartyIX** [immutables/immutables#825]
Hi,

Let's say I have the following interface:

```
// Define abstract value type
@Value.Immutable
public interface ValueObject {
  String name();
  List<Integer> counts();
  Optional<String> description();
}
```

Can I specify that I don't want `counts` to be taken into account in generated `toString()` method?

Best regards,
Martin

PS: I know I can convert the interface to an abstract class, but it collides with some of our custom-made  tooling that supposes that immutables are always interfaces.

**Comment by datval** [comment]
You can add `@Value.Redacted` annotation to counts() method.

**Comment by elucash** [comment]
@MartyIX thank you for asking this! @datval 's suggestion is the best way to handle your situation (`@Value.Redacted`). We're thinking of also adding general capability for interfaces to specify ("underwrite") equals / hashCode / toString as it is possible with abstract classes (maybe defining special static methods in interfaces), but we're not there yet (#739)

**Comment by MartyIX** [comment]
@datval @elucash Thank you guys!
