### ISSUE TITLE
Force to generate toString() method for abstract classes inheriting non-default implementation

### ISSUE THREAD

**Issue by datval** [immutables/immutables#826]
It seems Immutables skips to generate toString() method if it inherits non-default implementation from one of super classes. If you have abstract class extending RuntimeException it will not generate toString() as Throwables already have one.

```
@Value.Immutables
public abstract class MyRuntimeException extends RuntimeException {
    @Value.Default
    public abstract long timestamp();
    @Value.Redacted
    public abstract long secretTimestamp();
}
```

Desired result is:
```
MyRuntimeException e = ImmutableMyRuntimeException.builder().timestamp(111)
                                              .secretTimestamp(222).build();
assert e.toString().contains("111");
assert !e.toString().contains("222");
```

I guess it makes sense to still override `toString()` if abstract class has non-redacted field and doesn't provide its own implementation of the method.

My question is:
Is it possible to force immutables to generate `toString()` method in a case described above?

[StackOverflow question](https://stackoverflow.com/questions/52267965/force-java-immutables-to-generate-tostring-for-throwable-classes)

**Comment by elucash** [comment]
Thank you for the question! Answered on SO, also will post it here:
The trick is to declare abstract toString method signature in abstract value type.

@Value.Immutables
public abstract class MyRuntimeException extends RuntimeException {
    @Value.Default
    public abstract long timestamp();
    @Value.Redacted
    public abstract long secretTimestamp();
    @Override public abstract String toString(); //<-- forces toString impl
}

**Comment by datval** [comment]
Thanks @elucash!
