### ISSUE TITLE
org.immutables.value.Generated is not present in the shaded 2.7.1 value jar

### ISSUE THREAD

**Issue by ylexus** [immutables/immutables#833]
See title. And, silently, this annotation is not added to the generated classes. Workaround is to explicitly add value-annotations as a dependency to your project.

Looked at the jar here: https://search.maven.org/remotecontent?filepath=org/immutables/value/2.7.1/value-2.7.1.jar

**Comment by elucash** [comment]
thank you for reporting this! I've found out this is due to the single letter typo in maven plugin configuration.
