### ISSUE TITLE
inner Json classes are not annotated with org.immutables.value.Generated

### ISSUE THREAD

**Issue by ylexus** [immutables/immutables#834]
While immutable classes and builders are now conveniently annotated with org.immutables.value.Generated, inner "Json" classes are not, causing, in my case, jacoco coverage gaps. Workaround, if using jacoco, is to add "**/*$Json.class" as an rough exclude rule.

Are there any other inner classes that are generated under certain conditions that are possibly not annotated?

**Comment by Stephan202** [comment]
Yep, see #827.
