### ISSUE TITLE
Support Jackson JSON Serialization in Mongo Adapter

### ISSUE THREAD

**Issue by asereda-gs** [immutables/immutables#835]
After externalization of CodecRegistry in repository (see #807) it is possible to supply different serialization implementations for mongo adapter.

Since [jackson library](https://github.com/FasterXML/jackson) is extensively used in java projects, it would be nice to create special wrappers for [BsonReader](http://mongodb.github.io/mongo-java-driver/3.8/bson/readers-and-writers/) ([JsonParser](https://fasterxml.github.io/jackson-core/javadoc/2.8/com/fasterxml/jackson/core/JsonParser.html) for jackson) and BsonWriter([JsonGenerator](https://fasterxml.github.io/jackson-core/javadoc/2.8/com/fasterxml/jackson/core/JsonGenerator.html) for jackson) to allow POJOs to be encoded/decoded by jackson. 

This is similar to what has been done for Gson during mongo v3 migration (see #697)

**Comment by elucash** [comment]
only if there would be some help )

**Comment by asereda-gs** [comment]
Yes. I'll try to help. But #817 needs to be merged first :)

**Comment by asereda-gs** [comment]
Pls take a look at #850
