### ISSUE TITLE
Support MongoDB Async Driver

### ISSUE THREAD

**Issue by arouel** [immutables/immutables#836]
Do you have any plans to support [MongoDB Async Driver](http://mongodb.github.io/mongo-java-driver/3.8/driver-async/)?

**Comment by asereda-gs** [comment]
Maybe, if there is demand for it. 
Since most of Repository operations return [ListenableFuture](https://google.github.io/guava/releases/21.0/api/docs/com/google/common/util/concurrent/ListenableFuture.html) one can switch from sync to async mongo driver without affecting existing clients.

@before is sync driver a bottle-neck for you ?

**Comment by elucash** [comment]
I did investigation **long ago**, and most async mongo drivers actually had blocking IO underneath and backed by thread pool (except for one "commercial" driver and one OSS driver for Scala) , i.e. the same as we're doing in our repos with listenable futures. This poses a question if "MongoDB Async Driver" is "real async" driver as actually providing any benefits except for just futures/callbacks (like more efficient IO, more simultaneous streams)? Sorry, don't have a time to investigate right now.

**Comment by before** [comment]
I quickly reviewed the code and they are using either NIO2 or Netty (for SSL support) to communicate with a server. It looks like a full asynchronous implementation to me.

@asereda-gs it is not a bottleneck at this point, but I'm curious about the API impact when changing the underlying implementation to a non-blocking version at some point. Ideally, I would like to generate repositories that use the Async Driver and Vert.x [`Future`](https://vertx.io/docs/apidocs/io/vertx/core/Future.html) instances.

Would it make sense to consider an additional `mongo-vertx` module that renders repositories in the described way?

**Comment by asereda-gs** [comment]
I think there are multiple integrations which can be done with repositories: [rx2](https://github.com/ReactiveX/RxJava), [reactor](https://projectreactor.io/), [CompletionStage](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletionStage.html) etc. But do we have to support them all ? 

*Maybe* in future a "plugin system" like [Encodings](https://immutables.github.io/encoding.html) might be added to repositories (to allow customization). But right now, it is hard to chase all technologies.

**Comment by before** [comment]
@asereda-gs I agree that there are multiple integration scenarios. That's why I wanted to bring it to the table. I'm interested in a "plugin system" for _Immutables_.

How about building at least a `mongo` module with Async Driver and Java 8 `CompletableFuture`?

**Comment by asereda-gs** [comment]
Immutables has to remain compatible with Java 7 (because of Android platform). 
I will let @elucash comment on Java 8 and "repository extensions"

**Comment by before** [comment]
@elucash any opinions on that? I would like to help to create a more up-to-date Java 8 Mongo repository generator. Since the repository template etc. is part of the value-processor module, is there an alternative way to extend the processor with a custom/new layout?

**Comment by elucash** [comment]
As for free-form extensibility, separate annotation processor can be created, but then there will be a need to get the same analysis of the value types / compile type introspection, for this `value-processor` project classes may be used to construct/obtain instances of `ValueType` (and then value-processor with any other dependency like generator can be shaded into that additional processor). There's no fine grained template extensibility, sorry.
Having that said, I believe, if we left alone change of API for future/promises and leave current `FluentFuture<V> extends ListenableFuture<V> ` (where `FluentFuture` is ours and `ListenableFuture` from Guava), then all changes that are needed are in runtime code in `mongo` module, where we can change support implementation to configure and use async driver (or even make it default and only choice if it's mature enough). So far I see there's no need to change templates for this. As a starting point I would suggest looking at `Repositories` class containing large chunk of runtime support routines.
@before I would very appreciate if you can look into that and thank you for raising and moving this topic!

**Comment by asereda-gs** [comment]
Perhaps internally one can use [reactive-streams](http://www.reactive-streams.org/) API, or even [mongo-reactivestreams](https://mongodb.github.io/mongo-java-driver-reactivestreams/) (which is based on async driver). [Publisher](http://www.reactive-streams.org/reactive-streams-1.0.2-javadoc/org/reactivestreams/Publisher.html)  can then be converted to any reactive implementation (rx1+2, reactor,  different flavors of Futures). This will be a step forward towards "generic" repository.

**Comment by asereda-gs** [comment]
Immutables now has [Criteria API](https://immutables.github.io/criteria.html) which uses [mongo-reactivestreams](https://mongodb.github.io/mongo-java-driver-reactivestreams/) for Mongo backend.
