### ISSUE TITLE
Prehashed Immutable Annotation

### ISSUE THREAD

**Issue by iancaffey** [immutables/immutables#839]
Generating an immutable implementation of an annotation with `prehash = true` is currently broken in `v2.7.1`.

#### Example .java
```java
import org.immutables.value.Value;

@Value.Immutable(prehash = true)
public @interface Example {
    int value();
}
```

#### ImmutableExample.java
```java
...
  @Override
  public boolean equals(@Nullable Object another) {
    if (this == another) return true;
    return another instanceof Example
        && equalTo((Example) another);
  }

  private boolean equalTo(Example another) {
    if (hashCode != another.hashCode) return false; //error: cannot find symbol variable hashCode
    return value == another.value();
  }
...
```

[Immutables.generator#L2824](https://github.com/immutables/immutables/blob/master/value-processor/src/org/immutables/value/processor/Immutables.generator#L2824)

`[let equalToTypeRaw][if type.annotationType][type.typeAbstract.relativeRaw][else][type.typeImmutable.relativeRaw][type.generics.unknown][/if][/let]`

seems to be the direct cause of the bug since it uses the actual annotation type instead of the immutable type there.

#### Proposed Solution
The generator for equals could have a specific case for prehash in `equalTo` to keep the behavior consistent with previous revisions, that supports any implementation with equal attribute values, while fixing the error.

[L2865- L2867](https://github.com/immutables/immutables/blob/master/value-processor/src/org/immutables/value/processor/Immutables.generator#L2865-L2867)
```
    [if type.usePrehashed]
  if (hashCode != another.hashCode) return false;
    [/if]
```

could be changed to look something like:
```
    [if type.usePrehashed]
    [if type.annotationType]
  if (another instanceof [type.typeImmutable.relativeRaw] && hashCode != (([type.typeImmutable.relativeRaw]) another).hashCode) return false;
    [else]
  if (hashCode != another.hashCode) return false;
    [/if]
    [/if]
```

If everything looks good, I can open a PR with this fixed and tested.

Thanks,
Ian

**Comment by elucash** [comment]
@iancaffey thank you for reporting this! I think that fix is correct. (no type parameters/unchecked cast warnings to worry about etc). I've applied it and also added some other related refinements/fixes (additional error-prone errors appeared after the fix alone). Will be released in 2.7.2, hopefully very soon
