### ISSUE TITLE
Support JDK8 OptionalInt, OptionalDouble and OptionalLong

### ISSUE THREAD

**Issue by tbroyer** [immutables/immutables#85]
I see that JDK8 `java.util.Optional` is supported, but apparently not `OptionalInt`, `OptionalDouble` and `OptionalLong`.

Behavior would be the same as with `Optional<Integer>`, `Optional<Double>` or `Optional<Long>` (two _withers_ on the builder, one taking `int`, `double` or `long`, the other taking `OptionalInt`, `OptionalDouble` or `OptionalLong`)

**Comment by elucash** [comment]
Yes, that would be useful addition. Thanks for proposal!

**Comment by elucash** [comment]
Released in 2.0
