### ISSUE TITLE
Add isInitialized to immutable builders?

### ISSUE THREAD

**Issue by daicoden** [immutables/immutables#852]
Modifiables have an isInitialized method to make sure all required attributes have been set.

As an alternative to `@Check` could we expose isInitialized in the builder. The main reason @Check won't work is if you want to reference instance objects which are not part of the immutable, which can be accessible to the builder.

Use case looks something like this:

```
@Immutable
public class Example {
  Integer getValue();
  
  public static class Builder extends ImmutableExample.Builder {
    private final Validator validator;

    public Builder(Validator validator) {
      this.validator = validator
    }

    @Override public void build() {
      if (isInitialized) {
        validator.validate(this);
      }

      return super.build();
    }
  }
}
```

**Comment by elucash** [comment]
this may be already implemented IIRC, please look for similarly named style attribute where naming template has empty default value, setting it to non empty should produce the method (again IIRC)

**Comment by elucash** [comment]
`canBuild`

**Comment by daicoden** [comment]
thank you!!! `canBuild` indeed is it.
