### ISSUE TITLE
@SkipNulls without @Style(jdkOnly = true) does not report a warning

### ISSUE THREAD

**Issue by tonio-ramirez** [immutables/immutables#856]
When annotating a collection with `@AllowNulls`, a warning is generated if `@Style(jdkOnly = true)` is not used, indicating that Guava collection implementation does not allow nulls, etc.  But no such warning is generated when `@SkipNulls` is used, which is misleading, since attempting to add a `null` element to such a collection will fail.  Either the warning should be generated, or `null`s should be skipped, even when using Guava immutable collections.

**Comment by tonio-ramirez** [comment]
I'm not seeing that behavior, though.  With `@Style(jdkOnly = false)`, and Guava on the classpath, trying to add a `null` element to a collection results in an exception.

**Comment by elucash** [comment]
maybe I don't quite remember how it was actually implemented or there was a regression. Definitely, if you have `@SkipNulls` and they are not skipped, but exception is thrown, that should be at least a warning or even compilation error issued by processor.

**Comment by tonio-ramirez** [comment]
They're handled properly (i.e. skipped) with `@Style(jdkOnly = true)`, though.
