### ISSUE TITLE
When using @Mongo.Repository with Jackson, Gson warnings appear

### ISSUE THREAD

**Issue by clamothe** [immutables/immutables#859]
After configuring Immutable's mongo support to use Jackson, the following build warning still is shown:

`warning: (immutables) @Mongo.Repository types better have explicit @Gson.TypeAdapters annotation be placed on the class or enclosing package. It is also common to forget to generate type adapters for nested document classes, which will fallback to reflective Gson adapter otherwise.
`

I'm not sure how you would detect at build-time if the implementation is using the new Jackson Mongo support.

**Comment by elucash** [comment]
Probably, we need to remove this warning. We have a runtime check if we encounter reflective adapter for Gson to somehow mitigate something like this, i dunno
