### ISSUE TITLE
Nullness annotation prevents override of equals() method

### ISSUE THREAD

**Issue by bmhm** [immutables/immutables#865]
Hi,

I think the description can be kept short.

If I create an abstract class with this method:
```java
@Override
public boolean equals(final Object other) { … }
```

=> Everything works as expected, my implementation is used.

However, when I use this:
```java
@Override
public boolean equals(final @Nullable Object other) { … }
``` 
=>  Immutables will use its own implementation.

I'm using the checker framework. I really need to put that annotation into the signature.

Thanks!

**Comment by elucash** [comment]
Sure, thanks! I'll revise code comparing signatures (or smth like that)
