### ISSUE TITLE
Weak Interning should not use identity comparison in equals()

### ISSUE THREAD

**Issue by argibbs** [immutables/immutables#867]
# Problem Description

If interning is turned on, then the code for equals() looks like

```java
  public boolean equals(@Nullable Object another) {
    return this == another;
  }
```

This is fine for strong interning, but for weak interning it's incorrect. Assume you have an object like:

```java
@Value.Immutable(intern = true)
@Value.Style(weakInterning = true)
public abstract class Foo {
    public abstract String id();
}
```

If I create a value using id `"some-string"` then this is weakly interned. Subsequent calls will return the same instance, *unless the garbage collector intervenes*. At some point the garbage collector may decide to collect the entry from the weakly-keyed interner. After the GC runs, calls to create an `ImmutableFoo` using `"some-string"` will now return a different instance to before.

However, even though the GC has cleaned up the interner, it's still possible that some other part of the code is hanging on to the original instance of the ImmutableFoo. Thus it's possible to get two different instances of the ImmutableFoo class. They will have the same id, but `equals` will fail, because it's comparing by instance.

# Proposed Solution
Change the `equals` implementations to use the "non-interned" equality check, i.e. comparing all non-auxiliary members. This is only necessary for weak interning. Strong interning can continue to use identity checks.

For the example above, the equals method should instead look something like:
```java
  public boolean equals(@Nullable Object another) {
    if (this == another) return true;
    return another instanceof ImmutableFoo
        && equalTo((ImmutableFoo) another);
  }
```

**Comment by elucash** [comment]
Thank you for the detailed issue report! It is indeed a shortcoming, definitely have to be fixed

**Comment by argibbs** [comment]
You're welcome, and thanks for the fast turn around.
