### ISSUE TITLE
Should guava Optional<String> reference immutableCopyOf(String)?

### ISSUE THREAD

**Issue by cal101** [immutables/immutables#870]
Moin!
Many thanks for continuing the great work on immutables.org!

When I updated an older Java 7 project from 2.5.5 to 2.7.3 the compile failed because of missing 
immutableCopyOf methods for "String" and (guava) "Optional<String>" for an Optional<String>
property.

I expected the use of immutableCopyOf to be fragile but I wonder if 
it makes sense to call immutableCopyOf for String or Optional<String>?

Have fun,
    Cal

**Comment by elucash** [comment]
yep, we don't do much of detections of type inside `Optional` (technically we do some). Well, we can add a workaround to not generate `immutableCopyOf` such for such types, but not for a "String" specifically, but for something like "simple scalar type" or "known final type", I'll see what's is already there, maybe we can shove this in.

BTW, wrt safety and smells, I think that for such defaults some runtime logging or "tripwire" techniques can be used.

```java
public final class  Defaults {
  public static KnownOkType immutableCopyOf(KnownOkType ok) {
     // know to be exception, leave no-op
     return ok;
  }
  public static <T> T immutableCopyOf(T any) {
    // tripwire here or issue warning in log
    return any;
  }
}
```

**Comment by cal101** [comment]
If you consider it a workaround, please don't do it. 
It is not important enough for me to add hacks for this on the library side.

I consider immutableCopyOf kind of a hack itself and this is just another edge case.
The marriage of overloading and type erasure for container types is not a lucky one.
As soon as I used immutableCopyOf and had different lists it got ugly.
That is another motivation behind #871 to get more control. 


Instead of warnings I will just leave the any-Default out and let the compiler catch it as I did before.
If I have the choice I prefer static checks.

**Comment by cal101** [comment]
The tripwire technique used above works good enough. No need to keep the ticket open.
