### ISSUE TITLE
Generated methods do not inherit `throws SomeException` clause

### ISSUE THREAD

**Issue by RkShaRkz** [immutables/immutables#877]
My issue is that the generated *Value class does not inherit the superclass's `throws ...` part of the method declaration and I'm running into compile errors when using `throws`.

Example:
So, if I have a Immutable class such as this:

```
@Value.Immutable
@TupleWithBuilderImmutableStyle
public abstract class Wallet {
    public abstract Money balance();
    public abstract Map<String, Subscription> subscriptions();

   // some other irrelevant fields here

    @Value.Lazy
    public @Nullable Subscription getBaseSubscription() throws NoBaseSubscriptionException {
        for (Subscription subscription : subscriptions().values()) {
            if (subscription.basePlanId().equals(subscription.id())) {
                return subscription;
            }
        }
        throw new NoBaseSubscriptionException("No base subscription available");
    }
```

I get a following build-time error in the generated `WalletValue` class:
`Error:(141, 60) error: unreported exception NoBaseSubscriptionException; must be caught or declared to be thrown`

Looing into the generated class code, here's the generated code for this class:
```
@SuppressWarnings({"all"})
@Generated(from = "Wallet", generator = "Immutables")
public final class WalletValue extends Wallet {
  private final Money balance;
  private final Map<String, Subscription> subscriptions;

  @Override
  public Subscription getBaseSubscription() {
    if ((lazyInitBitmap & BASE_SUBSCRIPTION_LAZY_INIT_BIT) == 0) {
      synchronized (this) {
        if ((lazyInitBitmap & BASE_SUBSCRIPTION_LAZY_INIT_BIT) == 0) {
          this.baseSubscription = super.getBaseSubscription();
          lazyInitBitmap |= BASE_SUBSCRIPTION_LAZY_INIT_BIT;
        }
      }
    }
    return baseSubscription;
  }

// some other irrelevant fields here
}
```

I've also tried using this:
```
    @Value.Lazy
    @Value.Style(throwForNullPointer = NoBaseSubscriptionException.class)
    public @Nullable Subscription getBaseSubscription() throws NoBaseSubscriptionException {
        for (Subscription subscription : subscriptions().values()) {
            if (subscription.basePlanPurchaseKey().equals(subscription.id())) {
                return subscription;
            }
        }
        throw new NoBaseSubscriptionException("No base subscription available");
    }
```

But that requires my declared-exception to extend `RuntimeException` instead of regular `Exception`.

Is there a way to use the Immutables library with regular checked exceptions (and I missed something in the wiki) or is this feature simply lacking?

If it is possible and i just didn't RTFM good enough, would you please point me in the right direction and disregard this false issue?

I'm using version '2.6.3'

Thanks in advance and kind regards,
Shark

**Comment by StephenOTT** [comment]
Having this same issue.

```java
    @JsonIgnore
    @Value.Lazy
    default String toJsonString() throws JsonProcessingException {
        return StixDataFormats.getJsonMapper(true).writeValueAsString(this);
    }
```

and the generated code:

```java
  @Override
  public String toJsonString() {
    if ((lazyInitBitmap & TO_JSON_STRING_LAZY_INIT_BIT) == 0) {
      synchronized (this) {
        if ((lazyInitBitmap & TO_JSON_STRING_LAZY_INIT_BIT) == 0) {
          this.toJsonString = Objects.requireNonNull(ToolSdo.super.toJsonString(), "toJsonString");
          lazyInitBitmap |= TO_JSON_STRING_LAZY_INIT_BIT;
        }
      }
    }
    return toJsonString;
  }
```

Error:(1311, 80) java: unreported exception com.fasterxml.jackson.core.JsonProcessingException; must be caught or declared to be thrown

**Comment by elucash** [comment]
Thank you for reporting this. Here's related issue: #506
I think it's time to deal with the issue, so, for lazy methods throws clause will be simply propagated, for all other attributes it will be ignored + lengthy warning issued (there will be compilation error in the generated code most of the time)
