### ISSUE TITLE
Feature req: documentation annotation for noting required fields on a Builder

### ISSUE THREAD

**Issue by StephenOTT** [immutables/immutables#878]
Given that builders dont have IDE requirement field logic (could use Staged builders, but assume you dont want this so you are not forced in a specific order), it would be helpful to have a doc annotation that you could mark attributes as "builder required" with a extra text explanation, and this would be aggregated into the .builder() method, so someone can quickly review the docs in the IDE on .builder() to see what fields are "required"

**Comment by elucash** [comment]
this is a good idea, and this is similar to what we already have (or had at some point) in some of the generators) but not on the builder method. Should be relatively easy to add. As a variation: providing a code snippet in the generated javadoc.

**Comment by elucash** [comment]
<img width="859" alt="builder-javadoc" src="https://user-images.githubusercontent.com/1692611/50191309-2c438e00-02e2-11e9-854a-d84d242240b5.png">

^ Should be fine, right?

**Comment by StephenOTT** [comment]
@elucash what is the logic for determining "required"?

**Comment by elucash** [comment]
```java
  public boolean isMandatory() {
    return isGenerateAbstract
        && !isGenerateDefault
        && !isContainerType()
        && !isNullable()
        && !isEncoding()
        && !hasBuilderSwitcherDefault()
        && !(isPrimitive() && protoclass().styles().style().validationMethod() != ValidationMethod.SIMPLE);
  }
```

**Comment by StephenOTT** [comment]
@elucash how would a required field that is determined through a `@Value.Check` be captured with this?

**Comment by StephenOTT** [comment]
@elucash how about a additional annotation that can indicate it's a required field with a optional message/description prop that can be used to describe how / when it's required. ?

**Comment by elucash** [comment]
it's a good idea, but only in the context of potential/future extensible functionality like an improved version of "encodings" that we have (current encoding cannot be customized by annotations, only matching by attribute types). As for backing this in as built-in functionality, it has not very good power-to-weight ratio: whole new api annotation added with a benefit of generated Javadoc line and maybe exception message. The good enough way to handle it for now is, maybe, just specifying this in javadoc for the attribute. But I'm adding this kind of extensibility to the wishlist for Immutables3

**Comment by StephenOTT** [comment]
Would it change anything if It was a Value.style option where you provide a class which is the "required" class.
