### ISSUE TITLE
Immutable compares strings with '==' instead of '.equals' in with* methods when using @NotNull annotation (jetbrains)

### ISSUE THREAD

**Issue by inf0rm4tik3r** [immutables/immutables#879]
When not using an annotation on a string returning method, everything works fine.

Source:

    @Value.Immutable
    public interface Group {
        String getId();
        String getName();
    }

Generated withName method:

    public final ImmutableGroup withName(String value) {
        if (this.name.equals(value)) return this;
        String newValue = Objects.requireNonNull(value, "name");
        return new ImmutableGroup(this.id, newValue);
    }

When annotating the method with jetbrains' @NotNull annotation, the generated withName method no longer compares strings using the equals method, leading to a lot of reports in findbugs.

Source:

    @Value.Immutable
    public interface Group {
        @NotNull String getId();
        @NotNull String getName();
    }

Generated withName method:

    public final ImmutableGroup withName(java.lang.@NotNull String value) {
        if (this.name == value) return this;
        java.lang.@NotNull String newValue = Objects.requireNonNull(value, "name");
        return new ImmutableGroup(this.masterId, newValue);
    }

**Comment by elucash** [comment]
thank you for reporting the issue. there are some places which textually compare the type to "java.lang.String" which is no longer the case if type-use annotation added, we need to fix it with normal/reliable type identification as used in other places
