### ISSUE TITLE
Optional<T> uses T.toString instead of proper serializer

### ISSUE THREAD

**Issue by freben** [immutables/immutables#88]
I have a class

```java
@Value.Immutable
@Json.Marshaled
@Jackson.Mapped
public interface X {
  public Map<String, String> regularMap();
  public Optional<Map<String, String>> optionalMap();
}
```

I want it to serialize to

```json
{
  "regularMap": {"a": "b"},
  "optionalMap": {"a": "b"}
}
```

But it serializes as

```json
{
  "regularMap": {"a": "b"},
  "optionalMap": "{a=b}"
}
```

The reason that it's Optional is that I want to be able to leave out the optionalMap field completely when deserializing, and then get an Optional.absent() there. Is there another way of achieving these optional fields? It would be OK for it to be set to null as well.

**Comment by elucash** [comment]
Hi Fredrik, thank you for this report!
I hope that default behavior will suit your case, just using `java.util.Map` marshaler will omit field if the map is empty during serialization, then on deserialization you can use `Map.isEmpty`. However, if your goal is to distinguish absent field from explicit empty map `optionalMap: []`, then, probably, more involved solution might work, using wrapper immutable object.

```java
@Value.Immutable
@Json.Marshaled
@Jackson.Mapped
public interface X {
  public Map<String, String> regularMap();
  public Optional<Y> optionalMap();
}
@Value.Immutable(builder=false)
@Json.Marshaled
public interface Y {
   // builder= false and single constructor parameter make magic wrapping work
  @Value.Parameter
  Map<String, String> map();
}
...
        ImmutableX x = ImmutableX.builder()
                .build();

        System.out.println("1:" + Marshaling.toJson(x));

        x = ImmutableX.builder()
                .optionalMap(ImmutableY.of(ImmutableMap.of()))
                .build();

        System.out.println("2:" + Marshaling.toJson(x));

        x = ImmutableX.builder()
                .optionalMap(ImmutableY.of(ImmutableMap.of("a", "b")))
                .build();

        System.out.println("3:" + Marshaling.toJson(x));
```

Output will be
```js
1:{ }
2:{
  "optionalMap" : { }
}
3:{
  "optionalMap" : {
    "a" : "b"
  }
}
```
The same will work on deserialization.

Just as announcement: present in 1.x version of Immutables marshaling infrastructure will be very soon superseded with two JSON serialization options, hopefully, less exotic ones: #80 and #71. Immutables v2.0 is expected to be released month, and it's just around the corner.

**Comment by elucash** [comment]
I hope that proposed solutions was sufficient. In a meanwhile 2.0 was released, please see updated solution for JSON serialization at http://immutables.github.io/json.html
