### ISSUE TITLE
Possible to use JsonAnySetter with default Builder?

### ISSUE THREAD

**Issue by StephenOTT** [immutables/immutables#880]
I have a Map that I want to capture all of the unrecognized JSON properties in.

Typically this would be with something like 

```java
@JsonAnySetter
Map<String, Object> customProperties();
```

But this does not appear to work when using a setup stuch as 

```java
@Value.Immutable
@JsonSerialize(as = AttackPattern.class)
@JsonDeserialize(builder = AttackPattern.Builder.class)
@Value.Style(typeAbstract="*Sdo", typeImmutable="*", validationMethod = Value.Style.ValidationMethod.NONE, additionalJsonAnnotations = {JsonAnySetter.class})
public interface AttackPatternSdo extends DomainObject {

@JsonAnySetter
Map<String, Object> customProperties();

```

The annotation is passed into the class, but does capture the fields.

Any direction on the usage for this?

**Comment by StephenOTT** [comment]
Okay was able to figure this out.

So there is "magic" happening under the hood of Immutables which is not (i believe) documented.


So given 

```java
@Value.Immutable
@JsonSerialize(as = AttackPattern.class)
@JsonDeserialize(builder = AttackPattern.Builder.class)
@Value.Style(typeAbstract="*Sdo", typeImmutable="*", validationMethod = Value.Style.ValidationMethod.NONE, additionalJsonAnnotations = {JsonAnySetter.class})
public interface AttackPatternSdo extends DomainObject {

@JsonAnySetter
Map<String, Object> getCustomProperties();
 }

```

The "get" is used because I am also use Javax.Validation hence `Value.Style.ValidationMethod.NONE`.

BUT what is causing a issue here is the use of JsonAnySetter usage...

I had to change it to 

`additionalJsonAnnotations = {JsonAnySetter.class, JsonAnyGetter.class}`

and

```
...
@JsonAnyGetter
Map<String, Object> customProperties();
...

Then when it compiles, the Immutable class has the put methods generated with the `@JsonAnySetter`.

This might be specific to when using Interfaces rather than abstract classes? @elucash

**Comment by elucash** [comment]
JsonAnyGetter is supported (to generate corresponding JsonAnySetter) as a special case. AaddionalJsonAnnotation is not needed and would not work anyway for this case, accessor prefix (get) is irrelevant too IIRC

**Comment by StephenOTT** [comment]
@elucash i am using the get prefix because of https://github.com/immutables/immutables/issues/26#issuecomment-337653611,

**Comment by elucash** [comment]
that is for bean validation according to JSR303 spec (but I remember they promised to allow prefixless getters as a non-spec feature of HibernateValidator, dunno if this is released)
Anyway, this should not influence this feature, which may work with or without prefix

**Comment by StephenOTT** [comment]
But if you only provide @JsonAnySetter, then the AnyGetter is not generated.  In my case, I only needed the Setter, but it seems that you have to use the AnyGetter to allow Immutables to produce the proper code?

**Comment by elucash** [comment]
you would provide only any-getter on accessor (as abstract value type only define accesors, the rest is generated). The generated builder will contain any-setter method (or internal Json class if deserialise-as is used as opposed to deserialise-builder

**Comment by StephenOTT** [comment]
Right right.  Makes sense.  Thanks!
