### ISSUE TITLE
Inject Annotations in multiple possible locations?

### ISSUE THREAD

**Issue by StephenOTT** [immutables/immutables#885]
Consider a custom annotation that can be injected at the Class level and at the Method Level.

You might have something like: 
`@InjectAnnotation(target = InjectAnnotation.Where.ACCESSOR, code = "([[*]])", type = someAnn.class)`

but your custom annotation has the following config: `@Target( { ANNOTATION_TYPE, TYPE, FIELD, METHOD })`  

How can you configure the injection to support multiple possible placements?

**Comment by elucash** [comment]
`@InjectAnnotation(target)` is an array accepting multiple locations, is there a specific case which is not supported?

**Comment by StephenOTT** [comment]
@elucash Oh did not notice that!!  will test and report back

**Comment by StephenOTT** [comment]
@elucash thanks it works.  Part of the reason i missed it was there seems to be a issue with Intellij parsing the docs for the annotate module:

![screen shot 2018-12-20 at 10 55 40 am](https://user-images.githubusercontent.com/1994838/50295356-e4d61280-0445-11e9-9804-7c6d05fe785c.png)


![screen shot 2018-12-20 at 10 55 47 am](https://user-images.githubusercontent.com/1994838/50295364-e7d10300-0445-11e9-8c42-95dceddb057b.png)

**Comment by elucash** [comment]
@StephenOTT wdyt is there something wrong with javadoc markup on the annotation class/methods or just some random problem with IDEA?

**Comment by StephenOTT** [comment]
Closing and will open a new issue if I find reason for bad javadoc
