### ISSUE TITLE
Generated hashCode and equals methods are not safe for invalid instances deserialized by Jackson

### ISSUE THREAD

**Issue by matt-isaman** [immutables/immutables#915]
I am using Immutables for domain objects for a web service. Requests contain these domain objects and I use Jackson to deserialize them. Jackson happily deserializes nulls into fields that Immutables assumes will never be null. This becomes a problem when the default generated `hashCode()` or `equals()` are called as they're not safe to use in this case.

Example class:
```java
package scratch;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.Optional;
import org.immutables.value.Value.Immutable;
import org.immutables.value.Value.Style;

@Immutable
@Style(privateNoargConstructor = true) // (required by Jackson)
abstract class Foo {
    public abstract Optional<String> getOptS();
    public abstract String getS();

    public static void main(final String[] args) throws Exception {
        final var m = new ObjectMapper();
        final var f = m.readValue("{}", ImmutableFoo.class);
        System.out.println(f);
        System.out.println();
        System.out.println(f.hashCode());
        System.out.println();
        System.out.println(f.equals(ImmutableFoo.builder().s("s").build()));
    }
}
```
When run outputs this:
```
Foo{s=null}
Exception in thread "main" 
java.lang.NullPointerException
	at scratch.ImmutableFoo.hashCode(ImmutableFoo.java:107)
	at scratch.Foo.main(Foo.java:42)
```

The generated `hashCode()` and `equals()` are as follows:
```java
  @Override
  public boolean equals(Object another) {
    if (this == another) return true;
    return another instanceof ImmutableFoo
        && equalTo((ImmutableFoo) another);
  }

  private boolean equalTo(ImmutableFoo another) {
    return Objects.equals(optS, another.optS)
        && s.equals(another.s);
  }

  @Override
  public int hashCode() {
    int h = 5381;
    h += (h << 5) + Objects.hashCode(optS);
    h += (h << 5) + s.hashCode();
    return h;
  }
```

I think Immutables should generate methods that would work if things were unexpectedly null even in cases where it thinks everything won't be null. In my service I do a few things with the request objects, logging for one, before I call the `@Check` method to validate them. The methods above not being null safe has broken things for me and I have had to override the default implementations to work around this issue.

**Comment by elucash** [comment]
Hi, thank you for raising this. I'm quite reluctant to introduce unnecessary null-safety as it goes against fail-fast principle and also redundant code/bytecode for just a workaround. I believe you would not have any problems with Jackson if you use the approach described here: http://immutables.github.io/json.html#jackson which works for many users without the need for `privateNoargConstructor` hack.

**Comment by matt-isaman** [comment]
Fair points, I was unaware of the better way to do the Jackson integration thanks. That simplified things greatly and seems to have resolved my issue.

I guess the only thing that is slightly not ideal is that deeply invalid objects deserialized in this manner throw the jackson `InvalidDefinitionException` rather than the exception defined by `throwForInvalidImmutableState`. This is however an extremely minor issue and I assume it's not something that is simple (or perhaps possible) to "fix".

Rather than worrying about that I have just added the `InvalidDefinitionException` to the same exception handler as my custom `throwForInvalidImmutableState` exception. So client side everything should look consistent.

Thanks.
