### ISSUE TITLE
immutable: minimal java serialization support

### ISSUE THREAD

**Issue by elucash** [immutables/immutables#92]
At least some basic serialization support was requested during 2.0-rc evaluation

Currently,[for 2.0] we cannot add or change any of the APIs, but some opt-in change to the behavior would be ok.
Minimal support will consist of:

* Detecting if abstract value type implementing Serializable
* Copy serialVersionUID from abstract value type to immutable implementation type
* readResolve implementation to support singleton and interned instances

There was ideas to have additional support for serialization (backward and forward compatible serializations), but it seems nobody need it, especially having solid JSON serialization support.

**Comment by elucash** [comment]
Released in 2.0

**Comment by frostymarvelous** [comment]
From the docs, we need to implement `java.lang.Serializable` but this is not available on Android and we only have `java.io.Serializable`.

How can I get this to work on Android?
Thanks.

**Comment by elucash** [comment]
That's just an typo, it should be 'io', I'll review the docs. Thanks!

**Comment by frostymarvelous** [comment]
I noticed after I checked the commit.

Thanks.
