### ISSUE TITLE
Problem with values that have a sub-value in a different package

### ISSUE THREAD

**Issue by trask** [immutables/immutables#93]
I think I can repro in immutables value-fixture tests by moving SillySubstructure to a different package.

Then in the generated ImmutableSillyStructure, there is no package import statement for SillySubstructure, and compilation fails.

Let me know if you are unable to easily repro and I will work up a better test.

This is in Immutables 2.0.

Thanks,
Trask

**Comment by trask** [comment]
In my own code, this only seems to be a problem when I use ImmutableList<MySubStruct> in my Value class.  When I use List<MySubStruct> the import is added in the generated subclass and everything works.

**Comment by elucash** [comment]
Hi Trask, this one I was able to reproduce. Thanks! Investigating...

**Comment by elucash** [comment]
The problem is in import postprocessing.
To reproduce put referenced type in subpackage: import will be missing in generated code (thinking that subpackage == package)
Fixed in version 2.0.2 (released).
Please, could you check if it works for your cases?

**Comment by trask** [comment]
Thanks for quick turnaround.  It looks like I'm doing one other thing that is contributing to the issue.

I'm trying to use `@Value.Style(typeAbstract = "*Base", typeImmutable = "")`, with the idea of completely ignoring the *Base classes and exclusively using the (normally named) classes everywhere.

I was able to repro this in the updated value-fixture using:

```
public abstract class SillyStructure {
    ...
    public abstract List<ImmutableSillySubstructure> subs6();
    public abstract ImmutableSillySubstructure nest7();
    ....
}
```

Thanks,
Trask

**Comment by elucash** [comment]
That one is separate and really difficult case which expose all the bitterness of annotation processing, including subtle differences between Javac and Eclipse.
Investigating workarounds...
But without fix for this any usages of yet to be generated classes as attribute types would be compromised. I.e. currently it works only for types in the same package. The problem is that is considered unresolved, import `org.immutables.fixture.subpack.ImmutableSillySubstructure` is not taken in account of type is unresolved. Workaround could be somehow match import in source to the unresolvable type placeholder and generate code which takes this into account.

**Comment by trask** [comment]
Thanks for the explanation, I will stick with the default style for now (using normal named classes everywhere and using the Immutable* subclasses only when necessary).  It will be interesting to see what style(s) get adopted/used by others.  This is a very nice feature in 2.0.

**Comment by elucash** [comment]
Released in version 2.0.4, please try if it works. Thank you!

I've seen some other annotation processors try to delay processing of types which have yet-to-be-generated dependencies, but I suspect that delaying processing to later rounds will not work in all cases. What we did here to solve the issue:

* Relax type checks to allow unresolvable types to be handled nicely.
* Try to match to source class imports.
* If there are still some unresolved classes without class imports, then copy star-imports from source verbatim. (Copying all imports from the sources may preclude the need to resolve by class imports, but decided to not pollute each generated class if there's no real need for that)

In a course of action I had to reimplement type annotation support that you added way back. Updated implementation correctly handles that wacky qualified name syntax (like `com.pack.@Annotation SimpleName`) and type resolution described above. But was unpleasantly surprised to find out that javac does not provide type annotation for type arguments thought annotation processing API, i.e. `List<@Ann Integer>` will not work.

As for styles, I saw Facebook Buck team also want to use the "reverse" style with generated class to have nice simple name
https://github.com/facebook/buck/commit/7adbc045db87e7eb1af7d68ba3368c90b085f4d1
so this fix is real enabler for that.

**Comment by trask** [comment]
Excellent!  I was able to convert everything to the "reverse" style using 2.0.4. https://github.com/glowroot/glowroot/commit/072b54682c485a8296638b25119123ef65e1759f

**Comment by elucash** [comment]
Saw the commit, that is inspiring! thanks for sharing! I really hope that new features and fixes in 2.0 fits your needs nicely.

**Comment by trask** [comment]
I just realized that using "reverse" style simplifies necessary Json annotations.  https://github.com/glowroot/glowroot/commit/64a542bcece3bdbc193461491607498dbeed0da2

**Comment by trask** [comment]
The only thing I don't like about the "reverse" style so far is that when I ctrl+click through to methods on the immutable object, I end up in the subclass, when usually I'm wanting to end up in the base class.

**Comment by elucash** [comment]
yeah, Jackson support is enabled by either `JsonSerialize` or `JsonDeserialize` regardless of `as` attribute.

Navigation is definitely less pleasant if you use generated classes directly. I had an idea to write Eclipse plugins to handle rename attribute name refactoring on builders, maybe something could be done with navigation also. Just don't know when I will be able to get to this ))
