### ISSUE TITLE
Wrong code generation for Android with java 1.8 support

### ISSUE THREAD

**Issue by almozavr** [immutables/immutables#94]
On android, when using
```groovy
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
Immutables generator processor produces non 1.6-compatible sources, like `Boolean.hashcode(myValue)`, and it makes no choice but to use 1.7 java for android (no retrolambda, etc.)

**Comment by elucash** [comment]
Hi Aleksey, thank you for this report!
Currently, Immutables supports 2 set of APIs used in generated code.
1) jdk6+ APIs and Guava
2) jdk7 APIs
This way you can add Google Guava library to have code that uses only jdk6 APIs. Some related "fatness" of Guava library may require tools like ProGuard. Generated by Immutables classes may also benefit of some unused methods being removed to produce even smaller Android applications.
Please, let me know if it works for you.

**Comment by elucash** [comment]
Having Guava alternative, there's still problem with java 8 APIs. Java8 source version is checked only once in the place where hashCode is generated. I thought it was possible to add check for the classpath, to see presence of Java8 APIs, but high chances that during java8 compilation, java8 APIs would be also present even if masked by IDEs or not present in runtime.

Currently I'm adding following check for some android classes, to not use Java8 APIs during compilation at Java8 source level:
```
  [if classpath.isJava8 and (not (classpath.available 'android.R'))]
    [v.wrapperType].hashCode([v.name])
```
This will be released in neared patch.

**Comment by almozavr** [comment]
Thanks!

**Comment by elucash** [comment]
fix released in version 2.0.4, available on central. Please try if it works for your case. Thanks!

**Comment by almozavr** [comment]
Great, it works!

**Comment by tmtron** [comment]
I just had the same issue with `Long.hashCode()` and immutables 2.4.4.

In my case, I used it in a java-only module of an Android app. The fix was to add this compile-dependency to the java-module:

`compile "org.immutables:android-stub:2.4.4"`
