### ISSUE TITLE
Cannot selectively @JsonIgnore attributes either ONLY during serialization or deserialization

### ISSUE THREAD

**Issue by deepaks829** [immutables/immutables#969]
Related To: [Issue 503](https://github.com/immutables/immutables/issues/503)

I ran into a scenario where we would want to ignore an attribute selectively either during serialization/deserialization. Taking Jackson as an example this was achievable one of many ways. For example, annotating _only_ the getter with @JsonIgnore.

If we have a `UserDto` with a field like `password` then I think it's fair to expect this to be ignored during serialization and not deserialization. But annotating the accessor method with @JsoIgnore adds the annotation to both getter and setter which results in error described in [Issue 503](https://github.com/immutables/immutables/issues/503).

If there is a way around this (within Immutables) would be nice to add it to documentation.

Relevant StackOverflow question [here](https://stackoverflow.com/questions/55965304/selectively-jsonignore-immutables-accessor-methods-only-during-serialization-o).

**Comment by elucash** [comment]
As one of the comments on the SO suggested you can try to use `@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)`. Other than that there are no specific ways to do this. Sometimes this is a sign that maybe it is a good idea to split into two types: one for reading and another for writing to JSON (can use superinterface to share common attributes).

**Comment by deepaks829** [comment]
I had to use the suggestion from the comment except that I had to explicitly specify the value attribute of the property along with the Access attribute.

`@JsonProperty(value = "password", access = JsonProperty.Access.WRITE_ONLY)` solved the problem.
