### ISSUE TITLE
code generation not working in intellij idea

### ISSUE THREAD

**Issue by lburgazzoli** [immutables/immutables#977]
I have configured idea as documented on immutables website:

![image](https://user-images.githubusercontent.com/1868933/58037288-5f0dde80-7b2d-11e9-95cf-9a4c590bd455.png)

But when I rebuild the project, code generation does not happen:

![image](https://user-images.githubusercontent.com/1868933/58037311-6af9a080-7b2d-11e9-8cb7-d25e4411923b.png)

Running maven from command line does work. 

What can I check ?

**Comment by elucash** [comment]
Thank you for reporting this! I saw this but haven't got any chance to look into this in greater detail, my apologies for that. So I've tried the manual setup of annotation processors in IntelliJ and it seems to be working, however, any setup/project can be complex enough beyond my comprehension. I would recommend trying nail it down to the simplest possible projects on minimal value types, just to see if configured generated source folders are created and exposed as a generated source folders etc.

**Comment by lburgazzoli** [comment]
On a small project it is ok and the problem seems to be related to the use of errorprone in jetbrains idea: 

    https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003673859-Issue-with-annotation-processor

Sorry I forgot close the issue here.

**Comment by elucash** [comment]
Thank you for following up on this! so this ticket can be found by people facing similar issues
