### ISSUE TITLE
Wrong generation for @Nullable on Android

### ISSUE THREAD

**Issue by almozavr** [immutables/immutables#98]
```java
        @Value.Immutable
        public interface ValidationResult {
            enum ValidationStatus {
                SUCCESS, ERROR
            }
            ValidationStatus status();
            @Nullable Exception error();

        }
```

Gives this: ![](http://monosnap.com/image/FQDUIiY2cCZwwJ8NsLNODUIey50e2W.png)

**Comment by elucash** [comment]
I assume that it is `android.annotation.Nullable` which cannot target local variables. Didn't expect that, need to add check for target element type. Thanks for the report!

**Comment by elucash** [comment]
Please, try 2.0.6 release, this should be fixed.

**Comment by almozavr** [comment]
Confirm it, thanks!
